### ISSUE TITLE
SimulationModule logging not setup correctly

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#1000]
# Bug Report
`bypass_logging=True` does not correctly turn off logging for SimulationModule subclasses.

### Expected Behavior
SimulationModule logger should be shut off if `bypass_logging=True`

### Actual Behavior
Logging still occurs

**Comment by cjdsellers** [comment]
It appears that simulation modules are initializing their own `Logger` in the actor base class, as the current pattern in examples and tests has them being created before being passed in through `add_venue`.

So these need to be 're-wired' with a pattern similar to adding actors or strategies, at least to ensure that the same logger is being used (with the same config).

**Comment by cjdsellers** [comment]
Now fixed from 4eae94df37f0ec71a10db4c27c49cd42a8ab66f2.

Simulation modules are now properly registered which means they inherit the systems logger (and settings).
