### ISSUE TITLE
Unclean exit when running TradingNode in async main function

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#1004]
# Bug Report

We currently don't have a clean, working solution for running nautilus inside an `async main` function (like `examples/live/betfair.py`). Ideally users should be able to do this because they may need to make some async things (such as requests to get instruments before defining strategies) before starting a TradingNode. 

### Expected Behavior
TradingNode should exit cleanly when used within an async function.

### Actual Behavior
TradingNode either exits before full cleanup has occurred or hangs indefinitely.

### Steps to Reproduce the Problem

1. Run `examples/live/betfair.py`

**Comment by cjdsellers** [comment]
Now improved from 373fa29d23ed50b6f3be9db85d7703a3d7b52e69.

The `TradingNode` exposes the following methods: 
- `run()`
- `run_async()`
- `stop()`
- `stop_async()`

So the coroutine versions make the node easier to call within an `async` context.
