### ISSUE TITLE
`HttpClient` ignore my server proxy settings

### ISSUE THREAD

**Issue by gnemoug** [nautechsystems/nautilus_trader#1016]
# Bug Report

### Expected Behavior
I setup some http/https proxy in my server, I want `nautilus_trader` request data by the proxy

### Actual Behavior
When I use `BinanceFuturesMarketHttpAPI`, it seems just ignore the proxy, but if I use `wget` request the url, the proxy works!

### Specifications

- OS platform: ubuntu 20.04
- Python version: 3.10
- `nautilus_trader` version: 1.168.0

**Comment by cjdsellers** [comment]
Are you able to test this solution works for your use case? Then I could modify the code accordingly.

**Comment by cjdsellers** [comment]
Sure, so as you suggest, the `trust_env` param to `True` seems like what we want:

> **trust_env:**
> 
> Get proxies information from HTTP_PROXY / HTTPS_PROXY environment variables if the parameter is True (False by default).
> 
> Get proxy credentials from ~/.netrc file if present.

You're using one of these env vars, or the .netrc file I assume?

**Comment by cjdsellers** [comment]
That fix is now pushed to `develop` if you're able to pull, recompile and test?

**Comment by cjdsellers** [comment]
Awesome news! closing this as fixed then.
