### ISSUE TITLE
Use `process_files` process multiple files get read error

### ISSUE THREAD

**Issue by gnemoug** [nautechsystems/nautilus_trader#1018]
When `process_files` use many threads to handle files will get read error!
I think it maybe because when code rewrite_dataset, some file it writing by other thread. 

https://github.com/nautechsystems/nautilus_trader/blob/12801bec93142427dbe9eafa289d71ceb08a13d5/nautilus_trader/persistence/external/core.py#L370

The code before handle more files than it should process! But I don't figure out how to change that!

**Comment by cjdsellers** [comment]
Closing this as a stale issue as we're imminently about to refactor the entire catalog.
