### ISSUE TITLE
`nautilus_trader.model.objects.Quantity` QUANTITY_MAX not big enough!

### ISSUE THREAD

**Issue by gnemoug** [nautechsystems/nautilus_trader#1019]
# Bug Report

### Expected Behavior
Use `BarDataWrangler`  process trxusdt-swap ohlcv bar data get error!

### Actual Behavior
Error log:

> File "nautilus_trader/model/objects.pyx", line 114, in nautilus_trader.model.objects.Quantity.__init__
> ValueError: invalid `value` greater than `QUANTITY_MAX` 18_446_744_073.0, was 23_640_926_208.0

### Steps to Reproduce the Problem

1. request binance future trxusdt-swap 1d ohlcv data
2. use `wranglers`  to get bar objects

### Specifications

- OS platform: ubuntu 20.04
- Python version: 3.10
- `nautilus_trader` version: 1.168.0

**Comment by cjdsellers** [comment]
Unfortunately this is a design decision, that we represent all fractional values as fixed precision unsigned 64-bit integers internally, with up to 9 decimals of precision.

This means we can't represent values over about 18 billion from memory, which seems reasonable for a HFT platform as no value would be anywhere near this for an order quantity or price. Very large values we can represent using `decimal.Decimal` such as daily trading volumes (this is the approach for `BinanceBar`).

**Comment by cjdsellers** [comment]
To support this we could need a custom bar type using `decimal.Decimal` for the volume, which I'm assuming was the limitation here?
