### ISSUE TITLE
`BinanceSpotInstrumentProvider` load spot instruments got error

### ISSUE THREAD

**Issue by gnemoug** [nautechsystems/nautilus_trader#1020]
# Bug Report

### Expected Behavior
Use `BinanceSpotInstrumentProvider` load all currency_pairs.

### Actual Behavior
Some currency_pairs got parse warning, the log:

> 2023-02-21T08:45:29.728272314Z [WRN] TRADER-000.BinanceSpotInstrumentProvider: Unable to parse instrument SHIBUSDT, The 'maxQty' was out of range [0.0, 18_446_744_073.0], was 46_116_860_414.0.
> 2023-02-21T08:45:29.728344830Z [WRN] TRADER-000.BinanceSpotInstrumentProvider: Unable to parse instrument SHIBBUSD, The 'maxQty' was out of range [0.0, 18_446_744_073.0], was 46_116_860_414.0.
> 2023-02-21T08:45:29.728772992Z [WRN] TRADER-000.BinanceSpotInstrumentProvider: Unable to parse instrument SHIBEUR, The 'maxQty' was out of range [0.0, 18_446_744_073.0], was 46_116_860_414.0.
> 2023-02-21T08:45:29.728823516Z [WRN] TRADER-000.BinanceSpotInstrumentProvider: Unable to parse instrument SHIBRUB, The 'maxQty' was out of range [0.0, 18_446_744_073.0], was 46_116_860_414.0.
> 2023-02-21T08:45:29.731223819Z [WRN] TRADER-000.BinanceSpotInstrumentProvider: Unable to parse instrument SHIBBRL, The 'maxQty' was out of range [0.0, 18_446_744_073.0], was 46_116_860_414.0.
> 2023-02-21T08:45:29.731616359Z [WRN] TRADER-000.BinanceSpotInstrumentProvider: Unable to parse instrument SHIBTRY, The 'maxQty' was out of range [0.0, 18_446_744_073.0], was 46_116_860_414.0.

### Specifications

- OS platform:  ubuntu 20.04
- Python version: 3.10
- `nautilus_trader` version: 1.168.0

**Comment by cjdsellers** [comment]
As per the other issue thread, expected behavior for our current design using fixed precision integers.

**Comment by cjdsellers** [comment]
Just throwing out a suggestion, we might need to introduce a `BinanceBigBar` (or similar naming) to support these instruments with extreme values. Unfortunately the system wouldn't recognize it as a type of `Bar` though, and would be a custom data type.
