### ISSUE TITLE
External Bars with more than one type

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1049]
# Bug Report
Hi, further to report on discord, I believe this is bug 🙏

I see the `SimulatedExchange.process_bar` calls `OrderMatchingEngine.process_bar` which in turn creates the `TradeTick` or `QuoteTick` depending on PriceType. This doesn't cause any problem when there is only one `EXTERNAL` bar_type for the Instrument. However having more than one External bar_types causes unintended issues because of:

- The data received in any type of `Bar` is based on identical primary dataset `QuoteTick` or `TradeTick` except aggregated according to Bar Size, hence being converted to and processed as tick data multiple times.
- The way Bar is converted to Ticks is using all values of Bar i.e. OHLC are converted to tick at the time received. So having `1H` bar being received the Opening price which was `1H` prior, and when bar is processed, `OrderMatchingEngine` would match and takes the action whereas in reality that `Price` never existed at that moment. So this is fundamently wrong.

### Expected Behavior

- Unlike Wrangler to load data, `MatchingEngine` shouldn't process all OHLC values but just the `Close` price which will be upto date and same for all Bar size when the Bar is received. [Although in case still internal `BarBuilder` may mis-behave for the Volume/Size because that would treat it as seperate object and make double/triple the volume]
- I personally think `Bar` shouldn't be processed by `MatchingEngine` just like `INTERNAL` Bar.

### Steps to Reproduce the Problem

1. Backtest using External Bars of different size i.e `1M-LAST-EXTERNAL` and `1H-LAST-EXTERNAL`

**Comment by cjdsellers** [comment]
There are many users who only use bar data for backtesting, I'd say it would be a fundamental expectation for a backtest engine to handle this case.

The challenge with bar open is that it doesn't always correspond to the last bars close in bar data.

If we processed just the close it would make bars more compatible with tick data, but break backtests relying on bar only execution.

We used to have a config option `bar_execution` which would dictate whether bars are processed by the matching engine in backtests. I think it was removed to simplify config, but if we brought this settings back and you set to `False` then this would immediately solve your issue.

We could even make the setting more granular, so configuration on which bars are used for execution, or use the highest granularity bar for an instrument.

Thoughts?

**Comment by rsmb7z** [comment]
> There are many users who only use bar data for backtesting, I'd say it would be a fundamental expectation for a backtest engine to handle this case.

I am one of those as well because tick data is not that easy available and Yes this remains the expecation for sure. However the way it is now results in fancy profits/loss and any thing traded on these results would defintly result in real losses.

There is `QuoteTickWrangler` available for this case. However in user perspective and based on my journey, it is something not straight and easy accessible. I have been using custom method in Catalog i.e `bars_to_ticks(instrument_ids, bar_agg: Optional[str] = "1-MINUTE", **kwargs)`. Only thing which needs is converting those `1M` to Nautilus Parquet and then ticks can be created on the fly as not a major processing cost,
So my point is user chooses which Bar data to use for converstion or load the orignal ticks. If user loads ticks from multiple Bar sizes or messes, its the user who is causing unintended result in that case not the system's some built-in feature.

This issue is I have been noticing from few months but didn't had clue what's happening despite I was seeing some order filled in air (far away from the bar) when placed on graph. So system (I think) should avoid any assumption which contradict the core purpose i.e. using for profitable trading.

> We used to have a config option `bar_execution` which would dictate whether bars are processed by the matching engine in backtests. I think it was removed to simplify config, but if we brought this setting back and you set to `False` then this would immediately solve your issue.
> 
> We could even make the setting more granular, so configuration on which bars are used for execution, or use the highest granularity bar for an instrument.

I would be in favor of more simplicity. It wouldn't make sense at all to use 1H bar if there is lower bar available [which is high resolution to others] - so lowest bar size can be adopted. This assumption can be safely taken if there is no Tick data loaded at all. In nutshull, only take one set of highest resolution available.  I have fixed it with me so you can take your time.

**Comment by cjdsellers** [comment]
How are you currently solving the issue?

Determining the lowest bar size per instrument, per venue automatically during the data adding phase is not entirely trivial (although this would work). For the moment I've brought back the `bar_execution` option flag for the `BacktestVenueConfig` which is `True` by default to preserve current behavior.

So at least a user who is using both ticks and bars together can choose to turn off bar execution. It may even be a better idea to only process ticks, and rely on some upstream pre-processing to achieve this.

I also think the docs need updating to make it clearer how to handle backtests using tick and bar data together.

**Comment by rsmb7z** [comment]
Thanks for reinstanting the flag. I had removed the `process_bar` from matching_engine. Results are same now having `bar_execution=False` :thumbsup:

**Comment by cjdsellers** [comment]
I think I'll close this for now as we've established what the issue is, and reinstated the `bar_execution` config option.

Noted that documentation for setting up backtests needs to be improved.
