### ISSUE TITLE
Implement InstrumentClose catalog queries for the DataEngine

### ISSUE THREAD

**Issue by Troubladore** [nautechsystems/nautilus_trader#1052]
# Feature Request

Building on the request_xxxx() methods (e.g. request_bars), it would be helpful to be able to prime actors with historical "Instrument Close" data that represent the built-in Nautilus session close event for an instrument. This would seem to require two things:

1. Implementing an InstrumentCloseUpdate catalog query for the DataEngine to supplement the other event types
2. Loosen the typing for the on_data handler so it can handle lists as well as scalars. (e.g. on_data(data: Data) -> on_data(data: Any))

I realize option #2 would mean losing some type-safety in exchange for some flexibility, but given the start/end ranged nature of request_xxxx(), it could make sense.

**Comment by cjdsellers** [comment]
For 2. I've decided to go with this for now, which doesn't involve changing any of the method definitions.

```cython
    cpdef void _handle_data_response(self, DataResponse response):
        cdef Data data
        if isinstance(response.data, list):
            for data in response.data:
                self.handle_data(data)
        else:
            self.handle_data(response.data)
```

**Comment by cjdsellers** [comment]
`InstrumentClose` queries are now implemented for the catalog, and can be requested through the `DataEngine`. This is untested though as it involves loading this data into a catalog and writing a unit test - yet to be done.
