### ISSUE TITLE
Feeding pre-computed indicator (or similar) data into the strategy

### ISSUE THREAD

**Issue by tmorgan4** [nautechsystems/nautilus_trader#106]
I've been struggling with how to get pre-computed data (e.g. some other data source, expensive to compute indicator, etc.) fed into the strategy alongside the bar or tick data during a backtest and looking for any advice. When all prices are known ahead of time (i.e. backtest) it's often preferable to compute these indicators ahead of time. Or, maybe you have a news data feed that serves data at timestamps that don't necessarily coincide with tick or bar timestamps. 

The library is not currently set up to do this and feel it may be beneficial to others.

Ideas I've tried that both work but both seem hacky and don't fit the clean organization of the project:

1. Create an additional data dictionary in the BacktestDataClient alongside the existing _symbols, _price_volume, and _timestamps called _aux_features. During the initialization phase where data is added (e.g data.add_bars(), data.add_ticks(), etc.) an additional method is added called *.add_aux_features() to add any pre-computed data. Changes to various other classes must be made to keep these aux_features synced with the correct OHLCV timestamp.

2. Add these pre-computed features (called aux_features) to the DataCache when BacktestDataClient.setup() is called. The advantage here is that BacktestDataClient.setup() slices the full dataset between start:stop dates so the aux_features can be sliced between these same start:stop dates. The disadvantage is it's using the cache improperly as the normal OHLCV data is not added to the cache until after it is processed (i.e. no future prices exist in the cache). This works because the strategy has access to the cache and this provides a method to access pre-computed data by index inside a strategy at customizable intervals such as on_bar() or on_tick(). The index must be known so we must track the number of bars or ticks that have been seen by the strategy to retrieve the correct index.  

3. An indicator that handles this type of data and correctly feeds it according to the current timestamps seems best but indicators do not have access to any future data.
 
Can you think of a better way to implement this? I can continue on my own if this doesn't fit the broader scope of this awesome project.

**Comment by cjdsellers** [comment]
First off, thank you for your kind words.

I've setup something similar for expensive to compute ML models. I agree it makes sense when the outputs are known ahead of time - to cache them in some way so as not to slow down the backtest by re-computing.

You mentioned `"Or, maybe you have a news data feed that serves data at timestamps that don't necessarily coincide with tick or bar timestamps?"`

There actually is an `EconomicNewsEventFilter` in https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_trader/trading/filters.pyx. It can be queried in various ways. I'm not sure if this is what you were after? There used to be a more complex example strategy which would pause trading on news events, and then resume.

If that's not what you were trying to setup. I suppose what first has to be considered is - what is the source of the data? and how will it be delivered in live trading? In the case of an ML model, its generated within a strategy when the strategy passes it say the latest bar prices, and gets back a prediction, or a feature row to send into another model.

Or is this data generated external to a strategy, that could be subscribed to? This is the purpose of the `on_data` method, its an infinitely extendable point we can just keep adding data types to.

So it will help if you could be a little more specific about your use case, with an example, and we can move forward from there.

**Comment by cjdsellers** [comment]
Also to be considered is the internal data carried with the package, found at `nautilus_trader/_internal`

**Comment by tmorgan4** [comment]
Thanks for taking the time to review this. You're exactly correct that this would be used in a ML model and most likely would not work on live trading. A use-case that comes to mind is feeding many indicators and performing some type of feature selection algorithm to try and select some number of relevant yet uncorrelated features.

I've been through most of the code although it's changing quickly so I'm lagging a little behind the latest commits. I'll take a look at the suggested files to see if any of them look like they might work.

Appreciate your hard work!

**Comment by cjdsellers** [comment]
So the way I solved this was I created a class called `BlackBox`

Amongst other things you'd pass the name of your model (to joblib load from the .model file) and a flag `is_live`, this would be a class you instantiate inside the `TradingStrategy` `__init__` method. Once thats done the running strategy doesn't know whats happening under the hood of `BlackBox`, only that its passing back the predictions. For `is_live` its obviously calling the real thing, otherwise it was indexing a `pd.DataFrame` constructed from a CSV dump of predictions. It had nominal overhead.

One thing to be careful of is the consistency of inputs and outputs. So I'd do audits to check the prices/features going in exactly matched on the timestamps.

If you're calling this model at times other than the arrival of ticks or bars, then I'd suggest to use the `Clock` and setup a time alert or timer for the desired time. Its a pretty efficient class too.

**Comment by cjdsellers** [comment]
I think there is scope for an entire module dedicated to supporting algorithms and models. At present there's a large backlog of items as we move towards live trading, however some supporting classes and docs for this use case would be valuable.
