### ISSUE TITLE
ExecClient generate_order_status_report

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1061]
# Feature Request

There are may be more than one Orders to match this query results. Return accepts only one OrderStatusReport. Maybe allow list?

```
    async def generate_order_status_report(
        self,
        instrument_id: InstrumentId,
        client_order_id: Optional[ClientOrderId] = None,
        venue_order_id: Optional[VenueOrderId] = None,
    ) -> Optional[OrderStatusReport]:
```

**Comment by cjdsellers** [comment]
That method may be misleading because both of the order ID params are optional - however its actually an error if they're both `None`.

This method can be used for lists of order status reports:
```
    async def generate_order_status_reports(
        self,
        instrument_id: Optional[InstrumentId] = None,
        start: Optional[pd.Timestamp] = None,
        end: Optional[pd.Timestamp] = None,
        open_only: bool = False,
    ) -> list[OrderStatusReport]:
```

**Comment by rsmb7z** [comment]
Ah okay. In that case it will return only one. The later is implemented and works perfectly. I will close this as no action required.
