### ISSUE TITLE
Use "decimal-like" Price, Quantity, Money

### ISSUE THREAD

**Issue by micapumono** [nautechsystems/nautilus_trader#1067]
# Feature Request

It would be more ideal if Price Quantity and Money were to be stored as integers under the hood. E.g.

Price(value=63.21, precision=2)

and have it be stored under the hood as 
mem: int64=6321, precision=2

Then additions with Price(0.01) can look like
1 + 6321 rather than "shift the floating point number until the exponent is the same and then add the mantissa" or whatever whacky thing floating point does
Comparisons with Price(0.01) can look like
1 == 6321
Etc.

Indexing or hashing based on Price (let's say you want to aggregate orders by price) can look like

orders_by_price[price].append(order)

Mind you such a thing may surprisingly work right now due to python floating point magic but it doesn't feel like it would be reliable.

Along with this, some of these would be ideally signed as well, specifically Quantity but can do all of them.

**Comment by limx0** [comment]
https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_core/model/src/types/price.rs#L31
