### ISSUE TITLE
logging facility does not use a signed integer as time offset to UTC

### ISSUE THREAD

**Issue by martinsaip** [nautechsystems/nautilus_trader#1089]
# Bug Report

### Expected Behaviour
NautilusTrader consistently logging time in a timezone specified by user at all circumstances

### Actual Behaviour
When an order gets filled, inconsistent times are logged: I put 8 red cross marks around these incorrect hours - while the UTC time was 1:46:42 ("highlighted" by me using 8 check marks), NautilusTrader incorrectly assumed that it should use timezone of a machine it's running on.
Furthermore, instead of subtracting 5 hours from UTC as this machine's time is GMT-5, it instead added them, resulting in 1+5=6. The corresponding logs are below:
{"timestamp_ns":1682387202861111500,"level":"DEBUG","component":"ExecClient-InteractiveBrokers","msg":"_on_execution_detail O-20230425-001-000-1: Trade(contract=Stock(conId=320227571, symbol='QQQ', right='?', exchange='IBEOS', currency='USD', localSymbol='QQQ', tradingClass='NMS'), order=Order(orderId=3871, clientId=1, permId=368635839, action='BUY', totalQuantity=100.0, orderType='LMT', lmtPrice=315.45, auxPrice=0.0, tif='DAY', ocaType=3, orderRef='O-20230425-001-000-1', displaySize=2147483647, rule80A='0', openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='DU5562839', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=3871, status='Submitted', filled=0.0, remaining=100.0, avgFillPrice=0.0, permId=368635839, parentId=0, lastFillPrice=0.0, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[Fill(contract=Stock(conId=320227571, symbol='QQQ', right='?', exchange='IBEOS', currency='USD', localSymbol='QQQ', tradingClass='NMS'), execution=Execution(execId='0000e511.64470a33.01.01', time=datetime.datetime(2023, 4, 25, ❌❌❌❌❌❌❌❌6❌❌❌❌❌❌❌❌, 46, 42, tzinfo=datetime.timezone.utc), acctNumber='DU5562839', exchange='IBEOS', side='BOT', shares=100.0, price=315.45, permId=368635839, clientId=1, orderId=3871, liquidation=0, cumQty=100.0, avgPrice=315.45, orderRef='O-20230425-001-000-1', evRule='', evMultiplier=0.0, modelCode='', lastLiquidity=1), commissionReport=CommissionReport(execId='', commission=0.0, currency='', realizedPNL=0.0, yield_=0.0, yieldRedemptionDate=0), time=datetime.datetime(2023, 4, 25, ✔️✔️✔️✔️✔️✔️✔️✔️1✔️✔️✔️✔️✔️✔️✔️✔️, 46, 42, 859670, tzinfo=datetime.timezone.utc))], log=[TradeLogEntry(time=datetime.datetime(2023, 4, 25, 1, 30, 17, 207038, tzinfo=datetime.timezone.utc), status='Submitted', message='', errorCode=0), TradeLogEntry(time=datetime.datetime(2023, 4, 25, ✔️✔️✔️✔️✔️✔️✔️✔️1✔️✔️✔️✔️✔️✔️✔️✔️, 46, 42, 859670, tzinfo=datetime.timezone.utc), status='Submitted', message='Fill 100.0@315.45', errorCode=0)], advancedError='')"}{"timestamp_ns":1682387202865247800,"level":"DEBUG","component":"ExecClient-InteractiveBrokers","msg":"_on_order_update_event O-20230425-001-000-1: trade.orderStatus.status='Submitted'"}

{"timestamp_ns":1682387202865476200,"level":"DEBUG","component":"ExecClient-InteractiveBrokers","msg":"order submitted O-20230425-001-000-1: Trade(contract=Stock(conId=320227571, symbol='QQQ', right='?', exchange='IBEOS', currency='USD', localSymbol='QQQ', tradingClass='NMS'), order=Order(orderId=3871, clientId=1, permId=368635839, action='BUY', totalQuantity=100.0, orderType='LMT', lmtPrice=315.45, auxPrice=0.0, tif='DAY', ocaType=3, orderRef='O-20230425-001-000-1', displaySize=2147483647, rule80A='0', openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='DU5562839', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=3871, status='Submitted', filled=0.0, remaining=100.0, avgFillPrice=0.0, permId=368635839, parentId=0, lastFillPrice=0.0, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[Fill(contract=Stock(conId=320227571, symbol='QQQ', right='?', exchange='IBEOS', currency='USD', localSymbol='QQQ', tradingClass='NMS'), execution=Execution(execId='0000e511.64470a33.01.01', time=datetime.datetime(2023, 4, 25, ❌❌❌❌❌❌❌❌6❌❌❌❌❌❌❌❌, 46, 42, tzinfo=datetime.timezone.utc), acctNumber='DU5562839', exchange='IBEOS', side='BOT', shares=100.0, price=315.45, permId=368635839, clientId=1, orderId=3871, liquidation=0, cumQty=100.0, avgPrice=315.45, orderRef='O-20230425-001-000-1', evRule='', evMultiplier=0.0, modelCode='', lastLiquidity=1), commissionReport=CommissionReport(execId='', commission=0.0, currency='', realizedPNL=0.0, yield_=0.0, yieldRedemptionDate=0), time=datetime.datetime(2023, 4, 25, ✔️✔️✔️✔️✔️✔️✔️✔️1✔️✔️✔️✔️✔️✔️✔️✔️, 46, 42, 859670, tzinfo=datetime.timezone.utc))], log=[TradeLogEntry(time=datetime.datetime(2023, 4, 25, 1, 30, 17, 207038, tzinfo=datetime.timezone.utc), status='Submitted', message='', errorCode=0), TradeLogEntry(time=datetime.datetime(2023, 4, 25, ✔️✔️✔️✔️✔️✔️✔️✔️1✔️✔️✔️✔️✔️✔️✔️✔️, 46, 42, 859670, tzinfo=datetime.timezone.utc), status='Submitted', message='Fill 100.0@315.45', errorCode=0)], advancedError='')"}

{"timestamp_ns":1682387202865786500,"level":"DEBUG","component":"ExecClient-InteractiveBrokers","msg":"_on_order_update_event O-20230425-001-000-1: trade.orderStatus.status='Filled'"}

{"timestamp_ns":1682387202865994600,"level":"DEBUG","component":"ExecClient-InteractiveBrokers","msg":"order filled O-20230425-001-000-1: Trade(contract=Stock(conId=320227571, symbol='QQQ', right='?', exchange='IBEOS', currency='USD', localSymbol='QQQ', tradingClass='NMS'), order=Order(orderId=3871, clientId=1, permId=368635839, action='BUY', totalQuantity=100.0, orderType='LMT', lmtPrice=315.45, auxPrice=0.0, tif='DAY', ocaType=3, orderRef='O-20230425-001-000-1', displaySize=2147483647, rule80A='0', openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='DU5562839', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=3871, status='Filled', filled=100.0, remaining=0.0, avgFillPrice=315.45, permId=368635839, parentId=0, lastFillPrice=315.45, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[Fill(contract=Stock(conId=320227571, symbol='QQQ', right='?', exchange='IBEOS', currency='USD', localSymbol='QQQ', tradingClass='NMS'), execution=Execution(execId='0000e511.64470a33.01.01', time=datetime.datetime(2023, 4, 25, ❌❌❌❌❌❌❌❌6❌❌❌❌❌❌❌❌, 46, 42, tzinfo=datetime.timezone.utc), acctNumber='DU5562839', exchange='IBEOS', side='BOT', shares=100.0, price=315.45, permId=368635839, clientId=1, orderId=3871, liquidation=0, cumQty=100.0, avgPrice=315.45, orderRef='O-20230425-001-000-1', evRule='', evMultiplier=0.0, modelCode='', lastLiquidity=1), commissionReport=CommissionReport(execId='', commission=0.0, currency='', realizedPNL=0.0, yield_=0.0, yieldRedemptionDate=0), time=datetime.datetime(2023, 4, 25, ✔️✔️✔️✔️✔️✔️✔️✔️1✔️✔️✔️✔️✔️✔️✔️✔️, 46, 42, 859670, tzinfo=datetime.timezone.utc))], log=[TradeLogEntry(time=datetime.datetime(2023, 4, 25, 1, 30, 17, 207038, tzinfo=datetime.timezone.utc), status='Submitted', message='', errorCode=0), TradeLogEntry(time=datetime.datetime(2023, 4, 25, ✔️✔️✔️✔️✔️✔️✔️✔️1✔️✔️✔️✔️✔️✔️✔️✔️, 46, 42, 859670, tzinfo=datetime.timezone.utc), status='Submitted', message='Fill 100.0@315.45', errorCode=0), TradeLogEntry(time=datetime.datetime(2023, 4, 25, ✔️✔️✔️✔️✔️✔️✔️✔️1✔️✔️✔️✔️✔️✔️✔️✔️, 46, 42, 864642, tzinfo=datetime.timezone.utc), status='Filled', message='', errorCode=0)], advancedError='')"}{"timestamp_ns":1682387202866004800,"level":"WARNING","component":"ExecClient-InteractiveBrokers","msg":"fill should be handled in _on_execution_detail O-20230425-001-000-1"}

{"timestamp_ns":1682387202869919500,"level":"DEBUG","component":"ExecClient-InteractiveBrokers","msg":"_on_order_update_event O-20230425-001-000-1: trade.orderStatus.status='Filled'"}

### Specifications

- OS platform: independent
- Python version: 3.11.2
- `nautilus_trader` version: 1.171.0

**Comment by limx0** [comment]
HI @martinsaip,

These logs are coming from `ib_insync`, the underlying python client that Nautilus uses to connect to IB, and can safely be ignored.

You'll see the `"timestamp_ns":1682387202865994600` fields that nautilus uses are all UTC nanos. If you think we are parsing one of these incorrectly (ie, you are seeing incorrect `timestamp_ns`), please let us know. 

In the mean time I am going to close this issue.
