### ISSUE TITLE
Allow registering Strategy in runtime

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1095]
# Feature Request

In scenarios where it is not practical to subscribe many securities (particularly stocks) due to data lines limitation. I think allowing to register the Strategy during runtime while node is running would be useful approach, not sure if there would be any drawbacks or design issues. Following will be the usage scenario then:

1. An Actor, watching the Scan results internally from Adapter or External sources such as email or S3 etc, will spin the Strategy for those Instruments, if not running already.
2. Strategy will then subscribe the data and do actions as usual and can stop/dispose itself when not needed.

Although, in current scenario it can be achived by having single Strategy and configuring it to handle multiple Instruments however, keeping single instrument per Strategy keeps it very simple and less error prone.

**Comment by cjdsellers** [comment]
This feature is now completed (pending some docs examples).
https://docs.nautilustrader.io/develop/api_reference/trading.html#nautilus_trader.trading.controller.Controller
