### ISSUE TITLE
Properly model and handle errors in Rust components

### ISSUE THREAD

**Issue by twitu** [nautechsystems/nautilus_trader#1103]
A bunch of components have been ported to Rust and since they were quite experimental much of the error handling was ignored in favour of `unwrap` and `expect`. Now as the features are more stabilized and have been exposed it'll be better to handle errors properly so that appropriate messages can be shown in case of failure.

https://www.lpalmieri.com/posts/error-handling-rust/ is an excellent error modeling and handling guide that can be used as reference here.

**Comment by cjdsellers** [comment]
Closing this issue as we're generally moving in a better direction of returning `PyResult` types for pyo3 Python API boundaries by mapping out Rust errors to equivalent Python errors (exceptions).

We're also leveraging both `anyhow` and `thiserror` where it makes sense:
- `anyhow` to more concisely handle different `Result` types
- `thiserror` to more comprehensively express all of the possible errors for a particular domain

As a general philosophy we want to avoid Rust panics for the Python API, and favor propagating errors within the Rust code base where they may be either then recoverable, or mappable to Python errors.

As such we've seen a drastic reduction in the number of unwraps / expects, and clearer error messages - especially for the Python API.

Closing this for now, but lets use this issue to discuss further specifics related to the above if they come up. I'm also happy to hear anyones continued thoughts or any feedback/suggestions.

**Comment by twitu** [comment]
Modeling the error domain is useful in
* Reducing panics/unwraps in core logic
* Having consistent error messages
* Modeling failure cases and handling non-critical errors without panicing/exiting the system

Typically this is done by defining error enum for a particular domain where each variant represents a different failure condition. The `thiserror` crate helps by easily declaring error message templates for each variant. The error type from domain can be rolled up into a larger domain using From and Into traits. This technique is particularly useful when designing libraries where the application logic might handle different variants differently.

```rust
#[derive(thiserror::Error, Debug, PartialEq)]
pub enum InvalidBookOperation {
    #[error("Invalid book operation: cannot pre-process order for {0} book")]
    PreProcessOrder(BookType),
    #[error("Invalid book operation: cannot add order for {0} book")]
    Add(BookType),
    #[error("Invalid book operation: cannot update with tick for {0} book")]
    Update(BookType),
}
```

On the other hand, anyhow has very flexible error handling. It allows directly returning strings and contexts in errors which is more suitable for the application layer which might want to panic or log the error. In the current codebase, anyhow is used in the following crates appropriately.

* network (socket, tls, bubble up to python)
* model (correctness checks when initializing data model structs, mutex poisoning errors in venue and currency, bubble up to python)
* live (unnecessary imports)
* indicators (correctness check in a single file wma.rs, bubble up to python)
* data (all errors logged)
* cryptography (bubble up to python)
* core (correctness checks unwrapped to fail fast)
* cli (all errors logged)
* common (bubbled up to python)
* backtest (TODO: Not fully implemented
* analysis (TODO: Not fully implemented)
* adapters/tardis (data reading, replay errors bubbled up to python or unwrapped in test/example)
* adapters/databento (data loader errors, bubbled up to python)

However, for the below crates anyhow is being used to conveniently handle many errors that are being unwrapped. Since these libraries are more library like in logic and can have non-critical errors with many variants. They can be considered good candidates for stronger error domain modeling.

* infrastructure (stream errors, config errors, serialization errors, unwrapped)
* execution (bid errors, offset errors unwrapped in engine)
