### ISSUE TITLE
Bar and Tick Wranglers fail when using Pandas v2

### ISSUE THREAD

**Issue by rterbush** [nautechsystems/nautilus_trader#1137]
# Bug Report

### Expected Behavior
pyproject.toml suggests that pandas ^1.5.3 is supported. 
Should be able to run example backtests using pandas v2.x.x

### Actual Behavior
Example backtest will fail when using Pandas v2 with errors regarding tzinfo method unavilable. Imported data does not have a proper datetime64 dtype on index data.

### Steps to Reproduce the Problem

1. Run any example backtest that imports CSV data.

### Specifications

- OS platform: Linux amd64 and MacOS arm64
- Python version: 3.11.3
- `nautilus_trader` version: master and develop branches

PR #1136 has been submitted to fix this issue.

**Comment by cjdsellers** [comment]
Now closed from #1136
