### ISSUE TITLE
more exchange api development plans?

### ISSUE THREAD

**Issue by QuantQRI** [nautechsystems/nautilus_trader#1145]
# Feature Request
Are there any plans to add other exchange APIs to the development schedule?

OR

Specify some specifications about exchange API development to facilitate us to add more exchange api support for the current system. From the current point of view, it is more difficult to add more exchange api。

**Comment by cjdsellers** [comment]
Hi @QuantQRI 

Absolutely we have plans to add additional exchange adapters!

Right now there is a large effort on the core platform, and the refinements will help build adapters more efficiently. We recently ported our entire network layer to Rust (`HttpClient`, `WebSocketClient`, `SocketClient`). However, adapters will continue to be accessible from and built in Python.

There are also plans to improve the docs and provide a guide on how to implement an exchange adapter, its all on the near term roadmap, but difficult to give any concrete time frames at this stage.

I hope this helps to shed some more light.
