### ISSUE TITLE
Incorrect price reference in TickDataWrangler

### ISSUE THREAD

**Issue by tmorgan4** [nautechsystems/nautilus_trader#118]
I believe the first line of each code snippet contains a typo. Unless I'm misunderstanding all prices in lines #172 and #176 should be `df_ticks_o`.
 
https://github.com/nautechsystems/nautilus_trader/blob/0c410dd8b39e3d1cddafeb6c1240ac3efd035eba/nautilus_trader/data/wrangling.pyx#L172-L175
https://github.com/nautechsystems/nautilus_trader/blob/0c410dd8b39e3d1cddafeb6c1240ac3efd035eba/nautilus_trader/data/wrangling.pyx#L176-L179

**Comment by cjdsellers** [comment]
Excellent find! I just pushed a fix onto develop. Thank you
