### ISSUE TITLE
Consistent bug-free logging across Rust and Python components

### ISSUE THREAD

**Issue by twitu** [nautechsystems/nautilus_trader#1189]
Logging is an important tool in tracing the execution of the engine. It makes it possible to observe what is happening currently in the program, debugging logic issues and finally to observe if any component is failing or showing undesirable behavior. While doing all of this logging should affect the main execution path as little as possible.

Desired properties for logging -
* Writing is done in a separate thread
* Monotonic timestamps
* Supports writing to a file, stdout, and stderr
* Component level filtering for what level of log should be written

Current there are two logging styles being used in the project -
* `tracing` is the rust native logging/tracing library that uses a global subscriber to read, format and write events to stdout. This is being used in the network module in `websocket.rs` as it is pure rust and only exposed as a pyo3 module.
* `logging.rs` is a custom logging implementation in Rust that is made ffi-compatible and wrapped into a Cython object that can be passed around and called from Python. It uses thread channels to send log messages from the logger to a receiver thread running in the background.

Problems with [current setup](https://github.com/nautechsystems/nautilus_trader/blob/0981bc39f4939a54a1ed4034dd7ea20a732ce394/nautilus_core/common/src/logging.rs) -
* `logging.rs` has thread based channels but is used in async code. The sender end of the channel is not meant to be sent across threads but async code can place it on any thread. While there is no conclusive evidence, this is the likely reason the receiver end is not closed and the background thread is not being dropped causing a thread leak.
* `tracing` and `logging.rs` have different formattings for their log lines. They will have to be made consistent
  > 2023-06-16T12:49:47.171673409Z [INF] TESTER-001.TradingNode: loop.is_running=False

  custom logging formatting style
  > 2023-07-15T15:48:22.851336Z  INFO nautilus_trader: Received log (tracing line)

  default tracing formatting style
* monotonic timestamps is difficult to ensure across threads in async code

Proposed solution -

The `tracing` framework has different modular pieces that compose together to make a full logging solution. We will need to use parts of the `tracing-subscriber` and `tracing-appender` along with some custom implementation to get the desired behaviour.

1. Using the `set_global_default` method to set a global default dispatcher. This removes the need for setting up channels. The global dispatcher manages the listening to events and passing them to the subscriber.
2. A top level filtering layer that filters based on component - for e.g. only critical logs from the network module should be allowed
3. A per writer filtering layer - for e.g. only error and critical logs should be written to `stderr`
4. Non blocking writers[^1] for each of stdout, stderr, or file. We can reused this functionality from tracing_appender::non_blocking module[^2].
5. Non blocking writers creates a guard[^3] that must be held until the end of the program. When the guard is dropped the any remaining log lines are flushed to the writer. Since the main function is in Python. The guards will need to be wrapped as python objects (pyo3) and a reference held with the most long living object perhaps the kernel.
6. A custom formatting layer that formats rust and python log information consistently. Also since rust and python tracing calls will have different pieces of information like file and module name. Some of the information might need to be passed key values pairs (structured logging).

[^1]: https://github.com/tokio-rs/tracing/issues/971
[^2]: https://docs.rs/tracing-appender/latest/tracing_appender/non_blocking/index.html
[^3]: https://docs.rs/tracing-appender/latest/tracing_appender/non_blocking/struct.WorkerGuard.html

**Comment by twitu** [comment]
Core reasons for starting the port.
* Rust native logging for async (and sync)
* Fix thread leak issue with cython logger
* Unified logging for rust and python

Currently we have only covered the first point, using `tracing_subscriber` working for Rust logging. It has the additional benefits of providing file, stdout and stderr logging built in. Unifying logging for Rust and Python has presented new blockers and constraints.

* Mac (and possibly windows) don't have nano second resolution system time. The current implementation works because of a trick but it's not actually recording nano second resolution. Since `tracing_subscriber` uses the default SystemTime implementation which will not show nanos on Mac (and possibly windows). [^1] [^2].
* The nautilus engine has two modes - live and backtest. Both have different clocks. Live uses SystemTime while backtest has a non-live clock that's incremented by the engine. The logging framework needs to be able to switch between the two clocks.
* Since the non-live clock is actually a mutable value of time. It might not work directly with tracing_subscriber clock implementation. The clock might need to be put behind a mutex or passed as a separate key value pair. There are two downsides to the latter case -
  * the custom formatter will need to remove the default timestamp and use the key value pair timestamp
  * rust logging statements may not have access to the non-live clock so their timestamps will be inconsistent, but it will still be in the order of logging

[^1]: https://github.com/golang/go/issues/11222
[^2]: https://doc.rust-lang.org/std/time/struct.SystemTime.html#platform-specific-behavior

**Comment by twitu** [comment]
After some experimentation and discussion there's a different logging architecture to consider. Nautilus engine actually needs to different kinds of logging styles that need to be handled differently.

| Style | Component | Use case | Features |
| -- | -- | -- | -- |
| A1 | Single threaded engine - Rust core and Python wrapper | End user debugging trade execution | Nautilus formatting, colors, redirect to file, custom clock |
| A2 | Multi-threaded Python wrappers for rust peripherals | End user debugging for clients and adapters | Nautilus formatting, colors, redirect to file, component based filtering |
| B | Async rust peripherals for networking, database and file I/O | Dev debugging for peripheral internals | Vanilla formatting, module based filtering |

![shapes at 23-12-20 19 39 33](https://github.com/nautechsystems/nautilus_trader/assets/23196890/1968f993-9e0a-4fbd-a557-2539bc718297)

Logging style B needs to use `tracing` framework because it supports properly tracing async logic. Moreover, these components can benefit from the default formatting and module based filtering provided by the `FmtSubscriber`[^1] tracing implementation.

Logging style A does not require the complexity of tracing because it primarily needs to log sync code. In this case the `log` framework[^2] is a better choice -
* Simpler, flexible and well-suite for sync logic
* Uses global statics to allow for mpsc/mpmc channel-free logging. This will solve the thread leak issue with existing implementation

However, existing logging framework backend implementations[^3] will not work because nautilus logger -
* needs a custom clock
* custom formatting (partially supported by other frameworks)
* redirection to files in a separate thread (supported by flexi_logger)

It appears the best way is to repurpose the existing logger to implement the logging framework interface.

[^1]: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/struct.Subscriber.html
[^2]: https://docs.rs/log/latest/log/
[^3]: https://docs.rs/log/latest/log/#available-logging-implementations

**Comment by cjdsellers** [comment]
The logging thread leak is now fixed from https://github.com/nautechsystems/nautilus_trader/pull/1431 and we have a consistent logging interface in Rust provided by implementing `Log` from the `log` crate. Initialization of `tracing` was also improved.

Many thanks @twitu for all the hard work on this! :crab: 

Also, improved the performance of `AtomicTime` by removing the `Arc`s from its internal references and refined the setup of the core `ATOMIC_CLOCK` global statics.

Focus now shifts to additional refactors and performance benching + improvements https://github.com/nautechsystems/nautilus_trader/projects/4.
