### ISSUE TITLE
Trade ticks memory leak

### ISSUE THREAD

**Issue by Tzumx** [nautechsystems/nautilus_trader#1196]
# Bug Report
Hi. Thanks again for solving previous issues.
I know that you are working on memory consumption, so if this issue already was open and discussed - sorry and close it, please.

I've noticed some memory leak with binance trade ticks. I rarely use them (usually quote ticks) but when I subscribe to them it's starting to consume more memory with time. Up to 4 GB after a week. And if I comment subscribing for trade ticks - memory leak disappear. This situation was on all last versions (I've noticed on 1.174, 1.175, 1.176), but in 1.174 it was much less. On this picture I use 1.175 then switch to 1,174.
![Screenshot from 2023-08-07 19-08-27](https://github.com/nautechsystems/nautilus_trader/assets/91601062/efa5dbbd-d24d-4ed6-8e32-72fe2574c506)

### Expected Behavior
Stable memory consumption

### Actual Behavior
Memory consumption rise during all time trade ticks receive.

### Steps to Reproduce the Problem

1.Subscribe to binance trade ticks
2. Wait for a few hour/days

### Specifications

- OS platform: Ubuntu 22.04
- Python version: 3.11
- `nautilus_trader` version: 1.174 / 1.175 / 1.176

**Comment by cjdsellers** [comment]
Thanks again for the detailed report @Tzumx 

We'll investigate this soon!

**Comment by cjdsellers** [comment]
I did some initial investigations, including setting up [this](https://github.com/nautechsystems/nautilus_trader/blob/develop/tests/mem_leak_tests/tracemalloc_trade_ticks.py) tracemalloc test.

This test shows that after 1000 iterations of initializing a single trade tick, there is no memory leak. 
```
Run 999...
Memory allocated after run 1000: 0.0019207000732421875 MB
Max peak memory recorded: 0.0019207000732421875 MB
```

So I'm thinking it must be somewhere else in that path?

Are there any other differences with your strategy when it subscribes for trade ticks, any additional objects which may be getting initialized?

**Comment by cjdsellers** [comment]
Closing this for now, as nothing is tangibly actionable.

This issue will naturally resolve once we have entirely ported to Rust, please report if you have further findings!

**Comment by cjdsellers** [comment]
Hey @Tzumx 

Just to update you, I believe we've figured out what was causing the memory leak for `TradeTick`. See the below message from Discord today. This also wouldn't have shown up in the specific memory leak tests because the `trade_id` was always the same for each iteration.

> I think I've figured out why this happens, the trade tick trade_id is a Ustr, and the memory for these are stored in a global string cache and never freed. So when trade_ids go out of scope, the memory is essentially leaked which could explain the behavior you're seeing.
> 
> As an initial measure I've changed the implementation for the TradeId value to be like the UUID4, because we generally expect unique trade IDs, so its not actually a good candidate for Ustr anyway. Now we store a fixed array of bytes under the hood (37 which accommodates a 36 char uuid4 plus a null terminator), which can be represented as a C string.
> 
> I'll push to develop soon, and let me know if you see a behavior change. One limitiation this creates is there's now a max length on trade IDs, but I'm not aware of an integration currently where this would be a problem...
