### ISSUE TITLE
Permissive non copyleft license

### ISSUE THREAD

**Issue by sirinath** [nautechsystems/nautilus_trader#1197]
I am wondering if the license can move from the LGPL to a permissive license like MIT+AL2.0. In the Financial Services industry  use of non permissive license is problematics and cause fictions.

**Comment by cjdsellers** [comment]
Hi @sirinath 

Thanks for your question and interest in the project.

> The LGPL has had different versions, with the most recent being the LGPL version 3, often referred to as LGPLv3, which was released in June 2007. It's intended to offer a compromise between the strong copyleft of the GPL and the permissiveness of licenses like the MIT or BSD licenses.

My own understanding is that the LGPL v3 license allows you to freely use the open source code in proprietary code bases, such as for your own trading - or a trading firm. Whilst offering _some_ copyright protections for the original project, for instance if it was to be packaged up and distributed as a commercial product, it would have to abide by the original LGPL v3 license.

I acknowledge that a less permissive license than MIT+A2.0 can create unnecessary legal burdens, especially in the financial services industry.

Could you tell me more about your specific concerns, and individual use cases?

**Comment by sirinath** [comment]
Thanks for the quick response.

I am doing freelance / contract work. Using permissively licensed libraries and application is generally easier to get approved.

*GPL raises of questions and grey areas which even legal professionals intercept differently. So even it can be used in commercial products there is lot of caution and friction in doing it. There is always a possibility it might not get approved.

**Comment by cjdsellers** [comment]
I understand the concerns, and this certainly _can_ be the perception - even if the legal reality _may_ be different.

I'm not an expert in these matters, but my understanding is that if you were for instance writing proprietary code for clients which uses `nautilus_trader`, and they don't intend to further _release_ said code "under a license" - then there shouldn't be an issue.

If this was indeed the scenario and there were still concerns, then I think it would be a matter of perception, which is still a potential issue non-the-less.

I think at this stage, without a deeper analysis, I wouldn't see a need to change the license.

If it helps we also require all contributors to sign a standard CLA administered through [CLA assistant](https://cla-assistant.io/), with very reasonable and sensible protections going both ways, and notably simplifies the legalities for any downstream clients.

I hope this helps shed some light. I'll close this issue for now as I don't see an immediate actionable, but I'm also very willing to continue any discussions on this too.

**Comment by sirinath** [comment]
Another issue is if the code genets abandoned, they if a entity depends on this code they will have to maintain it, which will be a substantial commitment and investment. LGPL means that they will have to share the code of this fork. There will be reservations for this in such a case. Even commercial entities like Quantopian, QuantConnect used/use ASL2.0.

**Comment by cjdsellers** [comment]
The flip side of that viewpoint is that said entity gets to pick up and run with an enormous amount of already working and developed software, and also the cost savings involved for the years the entity was not having to contribute to maintaining the source code. So I suppose there are tradeoffs to be considered both ways there.

**Comment by sirinath** [comment]
But copyleft concerns can reduce adaptation to some degree.

Any way what is the additional benefits and protection that you seek from *GPL?

**Comment by rterbush** [comment]
Going to add my .02 here even though I am somewhat indifferent here.

I worked for many years on these topics and was involved in the creation of the Apache license. I was the first contact that many companies had to open source back in the late 90s. Sun Microsystems, Oracle to name a couple.

LGPL is very different from GPL but suffers from the perceptions of the GPL license. LGPL is quite permissive when compared to the GPL. Just takes the legal eagles to make the effort to fully understand the distinction. 

Less permissive licenses like the MIT or pure Berkley have their own risks that many companies don't consider and that is the risk regarding using code from the project that is possibly tainted by patent or other commercial copyright that makes its way into the codebase unknowingly. The Apache license specifically addresses this issue by requiring contributors to assert that they have the legal right to provide the code to the project with no legal encumbrance. So the folks pushing back about the LGPL should be just as careful about acceptance of this less restrictive licenses.

I think the point that @cjdsellers makes is a very good one. Risk comes in many shades of gray and the corporate types should be considering the risk reward in these discussions. Quite a bit of reward in taking a code base like this and applying it to your own business vs the true legal risk of adopting something with a funny license.
