### ISSUE TITLE
Indicators Rust port

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#1199]
This issue is to track the effort to port the existing indicators from `nautilus_trader/indicators` to Rust implementations defined in the crate under `nautilus_core/indicators`.

Example of the EMA indicator in Cython:
https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/indicators/average/ema.pyx

Example of the EMA indicator in Rust:
https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_core/indicators/src/ema.rs

Indicators must implement the `Indicator` trait, currently:
```rust
pub trait Indicator {
    fn name(&self) -> String;
    fn has_inputs(&self) -> bool;
    fn is_initialized(&self) -> bool;
    fn handle_quote_tick(&mut self, tick: &QuoteTick);
    fn handle_trade_tick(&mut self, tick: &TradeTick);
    fn handle_bar(&mut self, bar: &Bar);
    fn reset(&mut self);
}
```

Being mindful that eventually the system will have the capability of being all Rust end-to-end, a reasonable level of tests should be written which matches one-for-one with the Python counterparts.

Later when we can leverage the pyo3 interface, the Python tests can be abandoned in favor of the Rust tests.

**[Edit:] to reduce duplication and wasted work, we've decided to just write indicator tests in Rust, and not in Python additionally (which would just be testing the pyo3 boilerplate).**

**Comment by Pushkarm029** [comment]
> Example of the EMA indicator in Rust:
https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_core/indicators/src/ema.rs

This link is broken. Can you update it?

**Comment by Pushkarm029** [comment]
So, on researching a bit, I found out these complete indicators are not yet ported to nautilus_core:
- VariableIndexDynamicAverage `nautilus_trader/indicators/average/vidya.pyx`
- Donchian_Channel `nautilus_trader/indicators/donchian_channel.pyx`
- MovingAverageConvergenceDivergence `nautilus_trader/indicators/macd.pyx`

**Comment by cjdsellers** [comment]
Thank you for everyones efforts to help make this happen!

We'll need the rest of the port to be mostly completed before we're able to utilize these indicators generally.

There's also the need to do another QA sweep of the implementations, to check against the existing Python tests (importing from `nautilus_pyo3` instead of `indicators`).

Closing this task as initially completed though, good job team! 👏.
