### ISSUE TITLE
How to implement multi-instruments strategies like multi-factor stock selection

### ISSUE THREAD

**Issue by windblood** [nautechsystems/nautilus_trader#1204]
# Feature Request

on each event time, requests hundreds of stocks' data, do some calculation, and then submit some orders

**Comment by graceyangfan** [comment]
@windblood The  most simple  idea is to do all things in one strategy and use multi-thread or multi-process inside the strategy  to do calcultion and submit process,Another complex way is to maintain a distributed strategy,for example you can maturin a main Node for  collection data and data computing,and send submit orders to other Nodes(These Nodes only need for request data,computing and publish results into main Node and receive submit  command).I am not sure nautilus allows Node to Node 
communication,maybe @cjdsellers  can give you some suggestion!
