### ISSUE TITLE
Live Engine (on Binance) fails to restart due to Duplicate TradeId

### ISSUE THREAD

**Issue by doublier1** [nautechsystems/nautilus_trader#1205]
# Bug Report

When restarting the engine fails to start due to a Duplicate TradeId.

### Expected Behavior

Should handle duplicate trade_ids.

### Actual Behavior

Throws exception:
```
Exception: Duplicate TradeId('2355631'), existing PositionId('TOMOUSDT-PERP.BINANCE-BOTH') trade_ids=[TradeId('2355612'), TradeId('2355613'), TradeId('2355614'), TradeId('2355615'), TradeId('2355616'), TradeId('2355620'), TradeId('2355627'), TradeId('2355631')]
Traceback (most recent call last):
...
    node = TradingNode(config=config_node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautilus_trader/live/node.py", line 67, in __init__
    self.kernel = NautilusKernel(
                  ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautilus_trader/system/kernel.py", line 296, in __init__
    self.exec_engine.load_cache()
  File "nautilus_trader/execution/engine.pyx", line 571, in nautilus_trader.execution.engine.ExecutionEngine.load_cache
  File "nautilus_trader/execution/engine.pyx", line 583, in nautilus_trader.execution.engine.ExecutionEngine.load_cache
  File "nautilus_trader/cache/cache.pyx", line 326, in nautilus_trader.cache.cache.Cache.cache_positions
  File "nautilus_trader/infrastructure/cache.pyx", line 367, in nautilus_trader.infrastructure.cache.RedisCacheDatabase.load_positions
  File "nautilus_trader/infrastructure/cache.pyx", line 617, in nautilus_trader.infrastructure.cache.RedisCacheDatabase.load_position
RuntimeError: Duplicate TradeId('2355631'), existing PositionId('TOMOUSDT-PERP.BINANCE-BOTH') trade_ids=[TradeId('2355612'), TradeId('2355613'), TradeId('2355614'), TradeId('2355615'), TradeId('2355616'), TradeId('2355620'), TradeId('2355627'), TradeId('2355631')]
```

### Steps to Reproduce the Problem

(this was done on testnet)

1. Start Binance Engine
2. Do lots of trading
3. Restart Engine
(repeat until this occurs....)

### Specifications

- OS platform: Ubuntu 22.04
- Python version: 3.11
- `nautilus_trader` version: 1.176

**Comment by doublier1** [comment]
![image](https://github.com/nautechsystems/nautilus_trader/assets/137229291/51be1f3b-7d5d-4c24-bfd3-6c089ee127e1)

**Comment by cjdsellers** [comment]
Hi @doublier1

Thanks for all the information, which made getting to the bottom of all of this much more efficient.

So it looks like when loading a position from the cache this is being hit
```cython
        cdef:
            bytes event_bytes
            OrderFilled fill
        for event_bytes in events:
            event = self._serializer.deserialize(event_bytes)

            # Check event integrity
            if event in position._events:
                raise RuntimeError(f"Corrupt cache with duplicate event for position {event}")
            if event.trade_id in position._trade_ids:  # <---
                raise RuntimeError(
                    f"Duplicate {event.trade_id!r}, "
                    f"existing {position.id!r} trade_ids={position._trade_ids}",
                )

            position.apply(event)
```

It works on the assumption that each trade has a unique trade ID (which is normally the case), and thanks to recording the data we can see that a web UI order had the same trade ID assigned to two separate trades (for the same price).

So I'm not sure whether this is just a testnet thing, or a web UI thing, or the combination of both at this stage. 

To get around this you could comment the condition check yourself, or if we can confirm Binance make no guarantees about trade IDs then we could  add an option to relax the check (at the risk of dups and incorrect positions).

What are your thoughts?

**Comment by doublier1** [comment]
I've seen this problem multiple times now, I'm not 100% convinced it's a web UI thing, maybe I will need to dig through some logs further to find more examples...

Without knowing if this is specifically a testnet, web UI thing, or something that has changed internally in Binance, I would say the options are:

1) remove check
2) change check
- use a composite key of trade_id, instrument, side, qty, px?
- raise a warning and not an error
3) enable check optionally

Or some combination of the above...

My preference would probably be changing the check to use a composite key.

**Comment by cjdsellers** [comment]
Good points,

In light of this I've gone with the solution which will check for matching trade IDs and at that point will then additionally check a series of extra conditions -- basically as you suggested with the composite key only simpler.

```cython
    cdef void _check_duplicate_trade_id(self, OrderFilled fill):
        # Check all previous fills for matching trade ID and composite key 
        cdef:
            OrderFilled p_fill
        for p_fill in self._events:
            if fill.trade_id != p_fill.trade_id:
                continue
            if (
                fill.order_side == p_fill.order_side 
                and fill.last_px == p_fill.last_px 
                and fill.last_qty == p_fill.last_qty
            ):
                raise ValueError(f"Duplicate {fill.trade_id!r} in events {fill} {p_fill}")

```

So no additional overhead of assigning a key up front, and still linear growth iterating over all of these fills as more are applied to the position, as before.

Because of the additional condition checks, I've also dropped the duplicate trade ID error log in the `LiveExecutionEngine` to a warning.

Please let me know how this goes for you!

**Comment by cjdsellers** [comment]
Preemptively closing, pending any issues we can reopen.
