### ISSUE TITLE
Send TEXT data to the websocket connection

### ISSUE THREAD

**Issue by skc-j** [nautechsystems/nautilus_trader#1206]
Currently on send binary data to websocket connection is availlble.

Many websocket servers still accept text data in websocket. With such websockets, facing an issue because of difference in Frame masking (binary vs text). Due to this text messages being sent as binary from websocket client are getting ignored.

**Comment by cjdsellers** [comment]
Now merged into the codebase and released with 1.177.0, many thanks @twitu :pray:

**Comment by skc-j** [comment]
WebSocketClient.send_text(...) is working like charm. Thank you it's quick implementation and release.

I however seem to stumble into another issue while testing with different websockets. This time it is with inability to pass connection headers (such as "Origin", "Authorization", etc). 
Resulting in "Exception: Unable to make websocket connection because of error: HTTP error: 403 Forbidden"

Since this was not part of my original issue reported, I shall create a new enhancement request for the same.
Thank you.

**Comment by skc-j** [comment]
Created a new feature request # 1236 requesting for ability to pass connection headers in Websocket.connect().
