### ISSUE TITLE
Configuring order execution time for backtesting

### ISSUE THREAD

**Issue by dkharrat** [nautechsystems/nautilus_trader#1214]
When submitting a market order in a backtest, it seems that the order is executed immediately in the same bar at the `close` price. For more accurate backtesting results, it would be better to allow configuring this behavior, so that orders are executed on the next bar at the open or close price, which better is usually more realistic. I can see three possible modes one can configure:

1. Execute on current bar's close time
2. Execute on next bar's open time
3. Execute on next bar's close time

I didn't find a way to configure this behavior, but if there's a way to do it, please let me know.

**Comment by cjdsellers** [comment]
Hi @dkharrat 

We'd be hesitant to add support for this kind of bar specific execution modeling at this stage, given the scope of features currently in the pipeline, the port to Rust, and the fact that bar execution is considered secondary to tick / order book granularity data.

In the mean time there is a `LatencyModel` class which may interest you https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/backtest/models.pyx#L115 if you track the flow through the system of where this is added and used.
