### ISSUE TITLE
Value object API changes and use of decimal.Decimal

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#122]
**_Open for comments_**

Proposed changes as per commit 92d7a330be7f90943703d6c74ead1bc2596b8288
Added more `decimal.Decimal` type checks in commit 3354c039d42b31d00a8a4ed807c568e133e40337

### Background
There has been an ongoing challenge to create the best API possible for the domain value types in the framework, namely `Price`, `Quantity` and `Money`, which all inherit from a common base class wrapping a built-in `decimal.Decimal`.

There have been several iterations of this API, each improving on the last, often with feedback and advice from core contributors.

The goal is to provide;
- The most intuitive and flexible API possible
- Cython static typing where possible
- Allow arithmetic between `float` types and decimals
- The fastest possible performance

Previously the common base class was named `Decimal` and was also used as a first class object throughout the framework, often being used to represent anything with a fixed precision which wasn't a defined domain value type (as above).

### Considerations
Considering this for some time, I came to the conclusion that there was a mixing of concerns and concepts. The approach of using the base class to also represent other fixed precision concepts/types exposed it in a way that a user may find confusing, especially that it shared a name with the built-in `decimal.Decimal`.

To clarify this the name has been changed to `BaseDecimal`, with its use only intended as the parent class for the domain value types. The type in general provides in my opinion a better experience handling precision and rounding, and allows `float` to be used as operands in math ops.

If a user includes a `float` in a math op then the type of the returned result is a `float`. The thinking behind this is that a `float` has no precision specified and conversion to a decimal possibly implies a precision the user did not intend.

### API changes
This has allowed many redundant and uncesseary instantiations of `BaseDecimal` within framework methods and functions to be removed, with operations mainly on the `decimal.Decimal` type.

Following on from this all uses of `BaseDecimal` (where it wasn't being used as a base class as above, or in an operation with one of its subclasses) have been changed to `decimal.Decimal`.

The only down side I can see from this is that some typing information has been lost, as Cython cannot recognize `decimal.Decimal` as a C object, just a general `PyObject`.

To ensure static type safety remains some efficient `Condition.type(value, decimal.Decimal, "value")` checks have been added.

The returned type from math ops with a type other than `float` has been changed to a vanilla `decimal.Decimal` (changed from the `BaseDecimal`).

Performance has been ever so slightly improved on the backtest performance benchmark ~5.809 seconds vs ~5.960 seconds, although this was not the primary goal.

### Questions

- Does returning a `float` from a math op involving a `float` seem like expected and reasonable behavior?

- Does returning a  `decimal.Decimal` from all other valid math ops seem like expected and reasonable behavior?

- Should comparisons between `float` and `BaseDecimal` be considered invalid (raise an exception)? This is the currency behavour. Or should it be as per the built-in `decimal.Decimal` which allows it.
 
- Does raising a `TypeError` when the `BaseDecimal` constructor is passed a `float` value with no precision passed seem like expected and reasonable behavior?

- Are there any other areas for improvement regarding this API, or is there any feedback from users?

**Comment by mLewisLogic** [comment]
I'm in favor of this change overall. It gets us out of the business of maintaining something as generic as a Decimal implementation. Bummer that we lose some of the ability to cleanly specify type, but seems like a minor cost.

In general, if you're performing a binary operation and one of the operands has a weaker specification than the other, then the result should be limited by the weaker specification. In this case, a `float` is a weaker specification (due to imprecision) than a Decimal, so a binary op between a `float` and a `Decimal` should render a `float` to avoid casting surprises.

Seems like `Decimal() + float()` is going to work. How about `float() + Decimal()`? Might be tricky to get that working. Ultimately a simple fix, but may be an implementation-specific gotcha for users.

**Comment by mLewisLogic** [comment]
```
Does raising a TypeError when the BaseDecimal constructor is passed a float value with no precision passed seem like expected and reasonable behavior?
```

Probably fine either way. I could think of cases where you want to wrap it in Decimal just to combine with another prior to a round. In which case, specifying precision has no purpose. Could make things safer or more explicit though.

**Comment by cjdsellers** [comment]
> Bummer that we lose some of the ability to cleanly specify type, but seems like a minor cost.

There's still scope to add value types as appropriate if there's enough of them, I think there's not too much proliferation of checking for `decimal.Decimal` types throughout the codebase right now, but we'll keep an eye on it.

> In general, if you're performing a binary operation and one of the operands has a weaker specification than the other, then the result should be limited by the weaker specification. In this case, a `float` is a weaker specification (due to imprecision) than a Decimal, so a binary op between a `float` and a `Decimal` should render a `float` to avoid casting surprises.
> 

That's a good way of putting it, I agree this is the correct approach - so I'll leave as is.

> Seems like `Decimal() + float()` is going to work. How about `float() + Decimal()`? Might be tricky to get that working. Ultimately a simple fix, but may be an implementation-specific gotcha for users.

This actually works, and is tested for in the unit tests. For something like the below

```
def __add__(self, other)
```
The `self` and `other` param names are just standard conventions, the first argument is always the operand on the left of the expression even if that's not `self`, which is confusing I know. I noticed @scoder actually uses something more akin to `a, b` for the names. However, when I tried this I found PyCharm doesn't like it, so I just stick to `self, other`.

**Comment by cjdsellers** [comment]
> ```
> Does raising a TypeError when the BaseDecimal constructor is passed a float value with no precision passed seem like expected and reasonable behavior?
> ```
> 
> Probably fine either way. I could think of cases where you want to wrap it in Decimal just to combine with another prior to a round. In which case, specifying precision has no purpose. Could make things safer or more explicit though.

We'll keep this in mind if the scenario pops up regularly somewhere.
