### ISSUE TITLE
Stub test data model

### ISSUE THREAD

**Issue by filipmacek** [nautechsystems/nautilus_trader#1225]
Implement stub test data module for all the rust components. The idea is to have a reusable set of functions and fixtures with rust lib `rstest` that could be used across all rust codebase tests.

- replace `test` macro with `rstest`
- move everything related to creation of tests data in separate `stub` modules  that will be places behind a test feature flag
- refactor tests to use these stub modules

**Comment by cjdsellers** [comment]
@filipmacek has done a great job implementing this, now closing as this is an established pattern in the core Rust codebase :clap: :crab:
