### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by mLewisLogic** [nautechsystems/nautilus_trader#124]
Maybe it already works?
Adding this as an issue to remind us to enable it in CI and see how it goes.

**Comment by cjdsellers** [comment]
I noticed the PyPI badge added 3.9 a few days ago, almost as if we added the classifier for it.

I would expect everything is backwards compatible so I'll add it to the `python-version` list and see how it goes.

**Comment by cjdsellers** [comment]
Looks like it works 7faf02e8969a6f77a0a114b817453d609a8435fa

**Comment by cjdsellers** [comment]
Closing as the CI build is working with Python 3.9. We can reopen if a specific Python 3.9 issue comes up.
