### ISSUE TITLE
All Backtests in BacktestsNode fail if one Backtest Completely Fails

### ISSUE THREAD

**Issue by cavan-black** [nautechsystems/nautilus_trader#1280]
# Bug Report

### Expected Behavior
When running a number of backtests within a BacktestNode, if there is an error that occurs within one backtest, i.e. ValueError 'total' amount is negative (all capital has been lost) this backtest should be considered a finished backtest and the Node continues to run the other backtests.

### Actual Behavior
Instead, the entire BacktestNode terminates at that point and the program exits.

### Steps to Reproduce the Problem

1. Create multiple BacktestConfigs and add them to a BacktestNode (make sure at least one config has settings that will cause all of the capital in the account to be lost)
2. Run the BacktestNode

### Specifications

- OS platform: Windows 11
- Python version: 3.10
- `nautilus_trader` version: 1.178.0

**Comment by cjdsellers** [comment]
Hi @cavan-black 

Thanks for reporting.

These changes should prevent the entire node from falling over f79372c51ce378238922ecd630920cec80de8f4a. The expectation though is that any `AccountError` type is caught and handled inside the `BacktestEngine` and this should naturally end the backtest and still provide some results.

Please let me know if you actually hit that catch-all `Exception` handler in the node, and see any account related exceptions printed to stdout from it. If you could copy paste the stack trace, it would be most helpful :pray: .

Many thanks!
