### ISSUE TITLE
Clock condition check

### ISSUE THREAD

**Issue by ghill2** [nautechsystems/nautilus_trader#1285]
In the clock.advance_time_c method this condition is checked:

```Condition.true(to_time_ns >= test_clock_timestamp_ns(&self._mem), "to_time_ns was < time_ns (not monotonic)")```

The merged data stream could have two sequential data points that have identical timestamps, for example a MINUTE and DAILY bar. This situation is not erroneous therefore the condition should be changed to ```to_time_ns < test_clock_timestamp_ns```

**Comment by cjdsellers** [comment]
Hi @ghill2 

Thanks for looking over the code here.

I agree with your reasoning here, but the current condition check is equivalent to your suggestion (its checking the predicate is `True`) - so I think this is fine?

**Comment by ghill2** [comment]
Absolutely, I completely missed that
