### ISSUE TITLE
Partial fills missing from orders and fills report

### ISSUE THREAD

**Issue by r3k4mn14r** [nautechsystems/nautilus_trader#1286]
# Bug Report

### Expected Behavior
`generate_order_fills_report()` should return all the orders filled (full or partial fills).

### Actual Behavior
Currently the report returns all orders that have `status == OrderStatus.FILLED`. This omits all partially filled orders that have a status other than fully filled. For instances an order with `status == OrderStatus.CANCELED` that was partially filled before being canceled.

### Steps to Reproduce the Problem

1. Generate a scenario where an order gets partially filled and subsequently closed.
2. Generate the order and fills report

### Specifications

- OS platform: Linux
- Python version: 3.11
- `nautilus_trader` version: 1.178.0

My suggestion would be to filter the orders for `filled_qty > 0` instead of by order status. I am happy to submit a pull request once I get confirmation that the behavior I am seeking is what is actually expected.

**Comment by cjdsellers** [comment]
Closed from bf30479e486eac6727f1474490ba477b982e2ef8.

Many thanks @r3k4mn14r !
