### ISSUE TITLE
Fills report

### ISSUE THREAD

**Issue by r3k4mn14r** [nautechsystems/nautilus_trader#1287]
# Feature Request

A report in the spirit of to the orders and fills report that does not aggregate the fills at the parent order level. Specifically every individual `OrderFilled` event should have a line entry in that report.

I am happy to submit a PR if you want the feature.

**Comment by cjdsellers** [comment]
Now closed from 8232c5ed3ff4ff90782e3ccee3a9b4e3d338c147.

Many thanks for the contribution!
