### ISSUE TITLE
Unable to fetch historical crypto bars from Interactive Brokers

### ISSUE THREAD

**Issue by benjaminsingleton** [nautechsystems/nautilus_trader#1296]
# Bug Report

### Expected Behavior
Successfully download historical Crypto bars from Interactive Brokers with bar price type "LAST", such as `"BTC/USD.PAXOS-1-HOUR-LAST-EXTERNAL"`

### Actual Behavior

Download fails and logs say:

```
Expected what to show is AGGTRADES, please use that instead of TRADES.
```

Per the [IB docs](https://interactivebrokers.github.io/tws-api/historical_bars.html#hd_what_to_show): `AGGTRADES data should only be used with Crypto contracts.`

So `PriceType.LAST: "TRADES"` from [here](https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_trader/adapters/interactive_brokers/parsing/data.py#L50) isn't actually correct if the `contract.secType == "CRYPTO"`.

Wherever `whatToShow=what_to_show[bar_type.spec.price_type]` appears, there might need to be a conditional to check if Crypto and return `AGGTRADES` instead of `TRADES`.

### Steps to Reproduce the Problem

Attempt to fetch historical bars for `"BTC/USD.PAXOS-1-HOUR-LAST-EXTERNAL"` using the example script:
- https://github.com/nautechsystems/nautilus_trader/blob/master/examples/live/interactive_brokers/historic_download.py

### Specifications

- OS platform: macOS 13.0
- Python version: 3.10
- `nautilus_trader` version: 1.179.0

**Comment by cjdsellers** [comment]
Closed from #1302.
