### ISSUE TITLE
Add imports to Python snippets in documentation

### ISSUE THREAD

**Issue by benjaminsingleton** [nautechsystems/nautilus_trader#1297]
# Feature Request

The documentation would be more helpful if it consistently included imports when referencing specific objects in Python code snippets. Because imports are often not included, you can't simply copy-paste code snippets into your project. Instead, it requires some digging to understand where exactly the objects come from. The documentation is currently inconsistent because imports are included in some instances ([example](https://docs.nautilustrader.io/concepts/instruments.html#finding-instruments)), particularly when the snippet is longer.

To provide one example to illustrate, the data catalog ([docs](https://docs.nautilustrader.io/concepts/data.html#initializing)) includes a reference to `ParquetDataCatalog` but nowhere on the page does it show `from nautilus_trader.persistence.catalog import ParquetDataCatalog`. This makes it hard to get started with the catalog as it requires another step to look up the import in the codebase or elsewhere in the docs.

In this example, I'd recommend changing the snippet to the code below, which now works when copy-pasting into your project:

```python
import os
from nautilus_trader.persistence.catalog import ParquetDataCatalog


CATALOG_PATH = os.getcwd() + "/catalog"

# Create a new catalog instance
catalog = ParquetDataCatalog(CATALOG_PATH)
```

I'm happy to make this simple contribution throughout the docs, which I think will help people who are trying to get started with nautilus-trader.

**Comment by cjdsellers** [comment]
Hi @benjaminsingleton 

Thanks so much for this contribution!

I agree with your points - that this is a better style for the documentation. Particularly that imports from Cython don't work due to a lack of `.pyi` Python type stubs, so at least the docs now make it clearer how to import the different types.

Closing this as about to merge your PR :pray:
