### ISSUE TITLE
Add option to send custom ping message in Websocket client

### ISSUE THREAD

**Issue by filipmacek** [nautechsystems/nautilus_trader#1306]
# Feature Request

Currently, for `WebscocketConfig` we can only specify `heartbeat` parameter which represents seconds between executions of hearbeat task. Right new this heartbeat task sends `Ping` message with an empty payload. 
Add an option to send custom data(string message) in the heartbeat task.
We need to use it for custom websocket server that are defining heartbeat messages with other params in payload like Bybit here https://bybit-exchange.github.io/docs/v5/ws/connect

**Comment by twitu** [comment]
Currently websocket configuration stores an optional period for heartbeating. The heartbeat itself sends the a blank ping to the server.

```
pub struct WebSocketConfig {
    ...
    heartbeat: Option<u64>,
}

    pub fn spawn_heartbeat_task(
        heartbeat: Option<u64>,
        writer: SharedMessageWriter,
    ) -> Option<task::JoinHandle<()>> {
                    ...
                    match guard.send(Message::Ping(vec![])).await {
```

We want to make the heartbeat message configurable. So heartbeat can take an optional string message. If the optional message is None, it sends a ping, but if there is a string message does it exist it sends a Message::Text.
