### ISSUE TITLE
Constant reconnections to websockets

### ISSUE THREAD

**Issue by Tzumx** [nautechsystems/nautilus_trader#1339]
# Bug Report
Sometimes (usually after days of clear work) constant reconnections to websockets appears. After restarting works fine again for a couple of days.

### Expected Behavior
Stable connection to websockets, and successful reconnection in case it need.

### Actual Behavior
Constant reconnections to binance websocket.
<details> 
  <summary>Logs samples.</summary>
<pre><code>
INFO 2023-11-10T00:59:54.329472114Z [DBG] TRADER-001.ExecEngine: Checking in-flight orders status...
INFO 2023-11-10T00:59:54.329482433Z [DBG] TRADER-001.ExecEngine: Found 0 orders in-flight.
INFO 2023-11-10T00:59:55.404448765Z [WRN] TRADER-001.BinanceWebSocketClient: Reconnected to wss://fstream.binance.com.
INFO 2023-11-10T00:59:56.331682118Z [DBG] TRADER-001.BinanceWebSocketClient: SENDING: {'method': 'SUBSCRIBE', 'params': ['adausdt@trade', 'bchusdt@trade', 'bnbusdt@trade', 'btcusdt@trade', 'dydxusdt@trade', 'ethusdt@trade', 'solusdt@trade', 'xrpusdt@trade', 'adausdt@bookTicker', 'aliceusdt@bookTicker', 'avaxusdt@bookTicker', 'axsusdt@bookTicker', 'balusdt@bookTicker', 'bchusdt@bookTicker', 'bnbusdt@bookTicker', 'btcusdt@bookTicker', 'c98usdt@bookTicker', 'crvusdt@bookTicker', 'dentusdt@bookTicker', 'dydxusdt@bookTicker', 'etcusdt@bookTicker', 'ethusdt@bookTicker', 'filusdt@bookTicker', 'ftmusdt@bookTicker', 'ksmusdt@bookTicker', 'linkusdt@bookTicker', 'lrcusdt@bookTicker', 'maticusdt@bookTicker', 'nearusdt@bookTicker', 'roseusdt@bookTicker', 'rsrusdt@bookTicker', 'runeusdt@bookTicker', 'sandusdt@bookTicker', 'solusdt@bookTicker', 'xrpusdt@bookTicker', 'zecusdt@bookTicker'], 'id': 4578}
INFO 2023-11-10T00:59:56.331703388Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to adausdt@trade.
INFO 2023-11-10T00:59:56.331729126Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to bchusdt@trade.
INFO 2023-11-10T00:59:56.331744335Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to bnbusdt@trade.
INFO 2023-11-10T00:59:56.331748753Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to btcusdt@trade.
INFO 2023-11-10T00:59:56.331757400Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to dydxusdt@trade.
INFO 2023-11-10T00:59:56.331763211Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to ethusdt@trade.
INFO 2023-11-10T00:59:56.331780343Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to solusdt@trade.
INFO 2023-11-10T00:59:56.331801863Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to xrpusdt@trade.
INFO 2023-11-10T00:59:56.331817763Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to adausdt@bookTicker.
INFO 2023-11-10T00:59:56.331830848Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to aliceusdt@bookTicker.
INFO 2023-11-10T00:59:56.331862217Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to avaxusdt@bookTicker.
INFO 2023-11-10T00:59:56.331891593Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to axsusdt@bookTicker.
INFO 2023-11-10T00:59:56.331895931Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to balusdt@bookTicker.
ERROR 2023-11-10T00:59:56.331909977Z  Future exception was never retrieved
ERROR 2023-11-10T00:59:56.331913073Z  future: <Future finished exception=RuntimeError('WebSocket protocol error: Sending after closing is not allowed')>
ERROR 2023-11-10T00:59:56.331916580Z  RuntimeError: WebSocket protocol error: Sending after closing is not allowed
INFO 2023-11-10T00:59:56.331925547Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to bchusdt@bookTicker.
INFO 2023-11-10T00:59:56.331928562Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to bnbusdt@bookTicker.
INFO 2023-11-10T00:59:56.331945535Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to btcusdt@bookTicker.
INFO 2023-11-10T00:59:56.331960413Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to c98usdt@bookTicker.
INFO 2023-11-10T00:59:56.331976673Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to crvusdt@bookTicker.
INFO 2023-11-10T00:59:56.331992032Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to dentusdt@bookTicker.
INFO 2023-11-10T00:59:56.332007301Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to dydxusdt@bookTicker.
INFO 2023-11-10T00:59:56.332022680Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to etcusdt@bookTicker.
INFO 2023-11-10T00:59:56.332040904Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to ethusdt@bookTicker.
INFO 2023-11-10T00:59:56.332056103Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to filusdt@bookTicker.
INFO 2023-11-10T00:59:56.332075029Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to ftmusdt@bookTicker.
INFO 2023-11-10T00:59:56.332084567Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to ksmusdt@bookTicker.
INFO 2023-11-10T00:59:56.332105767Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to linkusdt@bookTicker.
INFO 2023-11-10T00:59:56.332122518Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to lrcusdt@bookTicker.
INFO 2023-11-10T00:59:56.332139280Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to maticusdt@bookTicker.
INFO 2023-11-10T00:59:56.332155942Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to nearusdt@bookTicker.
INFO 2023-11-10T00:59:56.332170609Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to roseusdt@bookTicker.
INFO 2023-11-10T00:59:56.332186659Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to rsrusdt@bookTicker.
INFO 2023-11-10T00:59:56.332204443Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to runeusdt@bookTicker.
INFO 2023-11-10T00:59:56.332220704Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to sandusdt@bookTicker.
INFO 2023-11-10T00:59:56.332238026Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to solusdt@bookTicker.
INFO 2023-11-10T00:59:56.332253245Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to xrpusdt@bookTicker.
INFO 2023-11-10T00:59:56.332281989Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to zecusdt@bookTicker.
INFO 2023-11-10T00:59:56.332305444Z [DBG] TRADER-001.ExecEngine: Checking in-flight orders status...
INFO 2023-11-10T00:59:56.332326924Z [DBG] TRADER-001.ExecEngine: Found 0 orders in-flight.
INFO 2023-11-10T00:59:57.671008090Z [WRN] TRADER-001.BinanceWebSocketClient: Reconnected to wss://fstream.binance.com.
INFO 2023-11-10T00:59:57.891581572Z [DBG] TRADER-001.BinanceWebSocketClient: SENDING: {'method': 'SUBSCRIBE', 'params': ['adausdt@trade', 'bchusdt@trade', 'bnbusdt@trade', 'btcusdt@trade', 'dydxusdt@trade', 'ethusdt@trade', 'solusdt@trade', 'xrpusdt@trade', 'adausdt@bookTicker', 'aliceusdt@bookTicker', 'avaxusdt@bookTicker', 'axsusdt@bookTicker', 'balusdt@bookTicker', 'bchusdt@bookTicker', 'bnbusdt@bookTicker', 'btcusdt@bookTicker', 'c98usdt@bookTicker', 'crvusdt@bookTicker', 'dentusdt@bookTicker', 'dydxusdt@bookTicker', 'etcusdt@bookTicker', 'ethusdt@bookTicker', 'filusdt@bookTicker', 'ftmusdt@bookTicker', 'ksmusdt@bookTicker', 'linkusdt@bookTicker', 'lrcusdt@bookTicker', 'maticusdt@bookTicker', 'nearusdt@bookTicker', 'roseusdt@bookTicker', 'rsrusdt@bookTicker', 'runeusdt@bookTicker', 'sandusdt@bookTicker', 'solusdt@bookTicker', 'xrpusdt@bookTicker', 'zecusdt@bookTicker'], 'id': 4579}
INFO 2023-11-10T00:59:57.891601540Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to adausdt@trade.
INFO 2023-11-10T00:59:57.891618492Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to bchusdt@trade.
INFO 2023-11-10T00:59:57.891630705Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to bnbusdt@trade.
INFO 2023-11-10T00:59:57.891635815Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to btcusdt@trade.
INFO 2023-11-10T00:59:57.891656434Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to dydxusdt@trade.
INFO 2023-11-10T00:59:57.891676161Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to ethusdt@trade.
INFO 2023-11-10T00:59:57.891695447Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to solusdt@trade.
INFO 2023-11-10T00:59:57.891705166Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to xrpusdt@trade.
INFO 2023-11-10T00:59:57.891712369Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to adausdt@bookTicker.
INFO 2023-11-10T00:59:57.891715335Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to aliceusdt@bookTicker.
INFO 2023-11-10T00:59:57.891720955Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to avaxusdt@bookTicker.
INFO 2023-11-10T00:59:57.891730463Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to axsusdt@bookTicker.
INFO 2023-11-10T00:59:57.891749910Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to balusdt@bookTicker.
INFO 2023-11-10T00:59:57.891756382Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to bchusdt@bookTicker.
INFO 2023-11-10T00:59:57.891772162Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to bnbusdt@bookTicker.
INFO 2023-11-10T00:59:57.891794204Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to btcusdt@bookTicker.
INFO 2023-11-10T00:59:57.891804092Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to c98usdt@bookTicker.
INFO 2023-11-10T00:59:57.891809803Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to crvusdt@bookTicker.
INFO 2023-11-10T00:59:57.891818159Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to dentusdt@bookTicker.
INFO 2023-11-10T00:59:57.891824811Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to dydxusdt@bookTicker.
INFO 2023-11-10T00:59:57.891834950Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to etcusdt@bookTicker.
INFO 2023-11-10T00:59:57.891845611Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to ethusdt@bookTicker.
INFO 2023-11-10T00:59:57.891855259Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to filusdt@bookTicker.
INFO 2023-11-10T00:59:57.891865588Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to ftmusdt@bookTicker.
INFO 2023-11-10T00:59:57.891874345Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to ksmusdt@bookTicker.
INFO 2023-11-10T00:59:57.891884664Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to linkusdt@bookTicker.
INFO 2023-11-10T00:59:57.891902718Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to lrcusdt@bookTicker.
INFO 2023-11-10T00:59:57.891918668Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to maticusdt@bookTicker.
INFO 2023-11-10T00:59:57.891924980Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to nearusdt@bookTicker.
INFO 2023-11-10T00:59:57.891929920Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to roseusdt@bookTicker.
INFO 2023-11-10T00:59:57.891946020Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to rsrusdt@bookTicker.
INFO 2023-11-10T00:59:57.891951751Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to runeusdt@bookTicker.
INFO 2023-11-10T00:59:57.891966328Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to sandusdt@bookTicker.
INFO 2023-11-10T00:59:57.891971749Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to solusdt@bookTicker.
INFO 2023-11-10T00:59:57.891986707Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to xrpusdt@bookTicker.
INFO 2023-11-10T00:59:57.891992197Z [INF] TRADER-001.BinanceWebSocketClient: Subscribed to zecusdt@bookTicker.
INFO 2023-11-10T00:59:58.331617689Z [DBG] TRADER-001.ExecEngine: Checking in-flight orders status...
INFO 2023-11-10T00:59:58.331635382Z [DBG] TRADER-001.ExecEngine: Found 0 orders in-flight.
INFO 2023-11-10T00:59:59.967199850Z [WRN] TRADER-001.BinanceWebSocketClient: Reconnected to wss://fstream.binance.com.
</pre></code>
</details>

### Steps to Reproduce the Problem

1. Run strategy
2. Wait for a few days (?week?)
3. Get the problem

### Specifications

- OS platform: Ubuntu 22.04
- Python version: 3.10
- `nautilus_trader` version: 1.180

I [saw in discord](https://discord.com/channels/924497682343550976/954875368261693511/1163725379266170890) you observed some noncorrect behavior with websockets already and solved it. I'll very appreciate if you share any ideas why we have such case.

**Comment by cjdsellers** [comment]
Hi @Tzumx 

Thanks for the issue report and for providing the logs. 

The reconnect logic was fixed and hasn't changed since 1.179.0, although some new features have gone in since so I'll have to double check there hasn't been any kind of cross interaction. It's a strange one though because for the most part reconnects must be working for you, as Binance will disconnect you every ~24 hours.

**Comment by Tzumx** [comment]
Hi. We are still trying to resolve this issue. The problem is that the case appears very rarely.
Now checking it from the side of ip limitation (as we run a few instances on the same ip):
either [300 connections per attempt every 5 minutes](https://developers.binance.com/docs/binance-trading-api/websocket_api#connection-limits)
or [6000 weight limit](https://developers.binance.com/docs/binance-trading-api/websocket_api#ip-limits)

**Comment by cjdsellers** [comment]
Thanks for the update @Tzumx

We've only implemented rate limiting for the HTTP client if that helps, so it does seem like one of these limits are being hit. You might need to run your trading across multiple accounts?

It's starting to look to me like there isn't actually a bug here, but we(I) should more clearly document the current limitations of the platform?

**Comment by cjdsellers** [comment]
I'm closing this, as I don't believe its a platform bug, but a rate limit exceedance.

Please keep me updated though when you can, and once we confirm the issue I can add some better documentation and potentially some work arounds or improvements if that's possible.
