### ISSUE TITLE
I found a bug of submit_order_list function.

### ISSUE THREAD

**Issue by Hao0oo** [nautechsystems/nautilus_trader#1348]
# Bug Report

### Expected Behavior
I post a order_list, and each targets should be matched with their own market price
### Actual Behavior
the targets have been matched with market price of the first target of the order_list

### Steps to Reproduce the Problem

1. subscribe 3 targets, for example: a, b, c
2.create a order_list by order_factory.create_list, for example: buy 1 a, sell 1 b, and buy 1 c,
3.post the order_list by submit_order_list
I suppose a will fill with a.best_ask, b - b.best_bid, c - c.best_ask
but actually, a filled with a.best_ask, is right, b and c filled with a.best_bid and a.best_ask as well, is wrong. 

### Specifications

- OS platform: win64
- Python version: 3.9
- `nautilus_trader` version: 1.179.0

**Comment by cjdsellers** [comment]
Hi @Hao0oo 

Thanks for your report here.

Does it help to know that currently any user trading activity does not affect size available in the book at any level? i.e. available size will not reduce. We're looking at improving the realism of fill dynamics around this in the future, but currently the data just acts as immutable order book state.

**Comment by cjdsellers** [comment]
Closing this for now as I don't believe the system is behaving out of spec, or otherwise if you could please provide more details or logs that would be helpful, many thanks :pray:
