### ISSUE TITLE
Incorrect ts_event and ts_init in historic Interactive Brokers daily bars

### ISSUE THREAD

**Issue by benjaminsingleton** [nautechsystems/nautilus_trader#1353]
# Bug Report

### Expected Behavior
I expect `ts_init` and `ts_event` to reflect accurate unix nanoseconds for daily bars.

### Actual Behavior
Daily bars retrieved using the `HistoricInteractiveBrokersClient` have timestamps that look like: `20231116000000000`.

Full example: `Bar(SPY.ARCA-1-DAY-LAST-EXTERNAL,449.22,450.56,448.12,450.23,48072316,20231116000000000)`

Per the [IB Docs](https://interactivebrokers.github.io/tws-api/historical_bars.html): "formatDate, The format in which the incoming bars' date should be presented. Note that for day bars, only yyyyMMdd format is available."

### Steps to Reproduce the Problem

```
import asyncio
import datetime

from nautilus_trader.adapters.interactive_brokers.historic import HistoricInteractiveBrokersClient

async def main():
    client = HistoricInteractiveBrokersClient(port=4002, client_id=5)
    await client._connect()
    await asyncio.sleep(2)

    bars = await client.request_bars(
        bar_specifications=["1-DAY-LAST"],
        end_date_time=datetime.datetime(2023, 11, 17),
        duration="1 D",
        tz_name="America/New_York",
        instrument_ids=["SPY.ARCA"],
    )
    print(bars)


if __name__ == "__main__":
    asyncio.run(main())
```

### Specifications

- OS platform: Ventura 13.0
- Python version: 3.10.13
- `nautilus_trader` version: 1.180

**Comment by cjdsellers** [comment]
Now closed from https://github.com/nautechsystems/nautilus_trader/pull/1354.

Many thanks for the fix @benjaminsingleton :pray:
