### ISSUE TITLE
Simplify msgspec encoding/decoding for NautilusConfig objects

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1392]
# Feature Request

**Goal:** Implement direct encoding/decoding of NautilusConfig objects (including Identifiers) in Msgspec. This will eliminate the need for converting objects to strings in Strategy/Actor, streamlining our process.

**Issue:** Currently, NautilusConfig objects require conversion to strings before processing, which is inefficient and error-prone.

**Solution:** Adapt Msgspec to handle NautilusConfig objects natively. I've made a preliminary implementation [here](https://github.com/nautechsystems/nautilus_trader/commit/4800b7d77609aba0c01a78f444b0995a8f8c4052), but it needs refinement, particularly in the placement of hooks and overall cleanliness.

**Benefit:** This change will simplify data handling, improve efficiency, and reduce errors in our system.

**Comment by cjdsellers** [comment]
I agree, this is a good idea. 

The only reason we use primitives such as bare strings was to accommodate serialization, and with these hooks which `msgspec` provide, we can more strongly type the config - and still be able to serialize.

Currently being worked on https://github.com/nautechsystems/nautilus_trader/tree/msgspec-config.

**Comment by cjdsellers** [comment]
Now implemented from #1406. Thanks for the assistance @rsmb7z :pray:
