### ISSUE TITLE
ParquetDataCatalog: circular import in `nautilus_trader.config.common`

### ISSUE THREAD

**Issue by kivo360** [nautechsystems/nautilus_trader#1404]
# Bug Report

### Expected Behavior
I was just trying to follow the getting started tutorial. I tried to import the parquet data catalog `ParquetDataCatalog` from `nautilus_trader.persistence.catalog`.  

```py
from nautilus_trader.persistence.catalog import ParquetDataCatalog
```

With the hope that I could get tick information to backtest on. 
```py
catalog = ParquetDataCatalog("./catalog")
catalog.instruments()
```

### Actual Behavior
That raised a circular import error:
```sh
from nautilus_trader.config.backtest import BacktestDataConfig
  File "/Users/Kevin.Hill/Library/Caches/pypoetry/virtualenvs/curvature-BSPcu68l-py3.11/lib/python3.11/site-packages/nautilus_trader/config/backtest.py", line 27, in <module>
    from nautilus_trader.config.common import DataEngineConfig
  File "/Users/Kevin.Hill/Library/Caches/pypoetry/virtualenvs/curvature-BSPcu68l-py3.11/lib/python3.11/site-packages/nautilus_trader/config/common.py", line 27, in <module>
    from nautilus_trader.persistence.catalog.parquet import ParquetDataCatalog
ImportError: cannot import name 'ParquetDataCatalog' from partially initialized module 'nautilus_trader.persistence.catalog.parquet' (most likely due to a circular import) (/Users/Kevin.Hill/Library/Caches/pypoetry/virtualenvs/curvature-BSPcu68l-py3.11/lib/python3.11/site-packages/nautilus_trader/persistence/catalog/parquet.py)
```
The only import that worked was the following:
```py
from nautilus_trader.config.common import ParquetDataCatalog
```

### Steps to Reproduce the Problem

1. Just import the most recent library

### Specifications

- OS platform: macos darwin m1
- Python version: 3.11.6
- `nautilus_trader` version: 1.181.0

**Comment by cjdsellers** [comment]
Hi @kivo360

Thanks for the report.

This has actually been fixed on `develop` branch, so I'll close this for now. We'll also make some further improvements by shifting some of this more complex logic away from config objects and into their respective components.

We're currently working on the Bybit adapter and so the next release may be held up for a couple of weeks on that unfortunately.
