### ISSUE TITLE
issue with nautilus-ibapi? fixed by installing most recent IBApi version manually 

### ISSUE THREAD

**Issue by gminorcoles** [nautechsystems/nautilus_trader#1413]
a few days ago testing the IB connection inside nautilus worked. today it did not work, I got a connection refused error. after some trial and error trying to connect to TWS api outside of nautilus, I got it  to work by uninstalling nautilus-ibapi and manually installing the most recent (v 10.9.2) ibapi. 

I am new to IB and to nautilus but I guess that this is due to the current version of ibapi being very recent - Dec 13 2023 if I am not mistaken? maybe they refuse the connection to an out of date api client? 

perhaps its time to update your pip package.

**Comment by cjdsellers** [comment]
Hi @gminorcoles 

Indeed there was a new version waiting to be merged, that's been released to PyPI now. It's curious that their API fails on a version bump though, there might be something we can do to mitigate this in the future.

I'll update the dependency on `develop` branch later today.

**Comment by gminorcoles** [comment]
thanks I think nautilus is cool
