### ISSUE TITLE
Enhancement for BacktestEngine in Event-Driven Strategies

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1418]
# Feature Request

## Overview
I've observed distinct behavior differences between live trading and backtesting across two scenarios. Community insights or advice for similar situations would be invaluable.

### Scenario 1: Serial Execution
```scss
├─ Description: Strategy logic operates serially.
├─ Process:
│ ├─ on_bar:
│ │ ├─ Executes signal logic (variable execution time).
│ │ ├─ Determines position size and other parameters.
│ │ └─ Places BUY/SELL orders.
└─ Behavior: Consistent in both live and backtest environments.
```

### Scenario 2: Event-Driven Execution
```scss
├─ Description: Strategy logic is event-driven, differing from Scenario 1 in signal handling.
├─ Process:
│ ├─ Actor:
│ │ ├─ on_bar: Executes signal logic and publishes BUY/SELL signals.
│ ├─ Strategy:
│ │ ├─ on_event: Responds to signals for order placement.
├─ Behavior:
├─ Live Runs: Operates as expected with natural bar delays.
└─ Backtest: Executes continuously without pausing.
```

## Problem
In Scenario 2, as well as when an Executor is used within the same Strategy, we encounter a notable complexity. The BacktestEngine continues to run without pausing for the executor's completion, causing unending execution. While switching to Scenario 1 resolves this issue effectively in both backtest and live runs, it brings its own set of challenges. Notably, it can lead to blocking and potential delays in the main loop. This problem is particularly acute when multiple instruments are being handled on a single node, exacerbating the delays.

## Proposed Solution
I propose a modification to the BacktestEngine for better support of event-driven strategies and executors. The key change involves introducing events that control the TestClock's progression. Rather than advancing to the next data timestamp, the TestClock would operate in real-time intervals during active requests. These events, each with a unique UUID, allow for locking or releasing states as needed. The BacktestEngine would track these events, synchronizing the TestClock with real-time during active requests and reverting to its standard behavior otherwise.

**Example Use Case:** In scenarios where a strategy or actor triggers a process within an Executor or another Actor, an event would lock the TestClock at the initiation (backtest time X) and release it upon completion (backtest time Y). For instance, if a process takes 30 seconds, the TestClock mirrors this duration in real-time, ensuring all data (ticks/bars) within this window are processed accordingly by the BacktestEngine.

These events, generated as needed within the Strategy/Actor, would be automatically disregarded in live environments due to no consumer presence.

This enhancement aims to maintain unaffected live operations, enabling a unified and seamless strategy application across both live and backtesting environments, eliminating the need for separate workarounds.

**Comment by cjdsellers** [comment]
Hi @rsmb7z 

So I'm understanding this correctly, the challenge is that for real-time operations there would be some natural "delay" in executing a `func` which is passed to `run_in_executor`, where as for backtesting it simply calls the function immediately - which may then trigger other events on the same timestamp (potentially causing a feedback loop)?

This actually has some similarities to simulating compute time of model predict calls. What we want to avoid is any code in the strategy which is specific to backtesting - we want to hide that underneath classes or functions like black boxes. Could this just be handled under the hood of whatever function you're calling, i.e. where an event could be raised when the function has completed, and you could ensure a different "mode" for backtesting and live (no delay)?

I agree that it would be nice to come up with a solution which is first class in the platform, at the same time I think this would be a QoL feature, and all the tools currently exist to "work around" this - which is what I understand you're proposing here?

**Comment by rsmb7z** [comment]
> So I'm understanding this correctly, the challenge is that for real-time operations there would be some natural "delay" in executing a `func` which is passed to `run_in_executor`, where as for backtesting it simply calls the function immediately - which may then trigger other events on the same timestamp (potentially causing a feedback loop)?

The natural delay is there in both cases however what happens during backtest, BacktestEngine data loop would continue based on next available data timestamp. So assuming the `func` took 5 seconds, backtest TestClock may have jumpted to an hour forward.
So the expectation is not to modify the behavior anything else other than the BacktestEngine loop which moves/jumps the TestClock to next available data timestamp.


> This actually has some similarities to simulating compute time of model predict calls. What we want to avoid is any code in the strategy which is specific to backtesting - we want to hide that underneath classes or functions like black boxes. Could this just be handled under the hood of whatever function you're calling, i.e. where an event could be raised when the function has completed, and you could ensure a different "mode" for backtesting and live (no delay)?
This feature indeed solves this problem and while at the moment workaround is to either do predictions seperately, add the delay fraction to timestamp and then include these signals as backtest data which infact is not inline with same code for backtest/live play. However if we resolve this, not only it wouldn't require any work-arounds but also each prediction would land at exact time it would be in case of live.

I am not in favor of setting the run mode at global level during backtest, because we don't it to slow down (in sync with real intervals) only when needed. Otherwise it would be dead slow where strategy is for 5M and it would be taking actually 5M. But the case I suggested is it will would the 5M at backtest speed (current behavior) and slow down when `func` is called.

As you suggest for `run_in_executor` can making the tracking call to `BacktestEngine` under the hood is good idea.



> I agree that it would be nice to come up with a solution which is first class in the platform, at the same time I think this would be a QoL feature, and all the tools currently exist to "work around" this - which is what I understand you're proposing here?

I believe the ML closely linked with platform, there will be most users using the ML than not and having the built-in solution for this makes it essential.

**Comment by rsmb7z** [comment]
> This actually has some similarities to simulating compute time of model predict calls. What we want to avoid is any code in the strategy which is specific to backtesting - we want to hide that underneath classes or functions like black boxes. Could this just be handled under the hood of whatever function you're calling, i.e. where an event could be raised when the function has completed, and you could ensure a different "mode" for backtesting and live (no delay)?

After further investigation, it has come to light that the Executor is not initialized during the backtesting phase. This means that all operations are executed within the same process, effectively making it blocking. This behavior addresses the concern raised. It's important to note that the Executor is utilized during live operations as expected. Given this clarification, no additional action is deemed necessary. Thus, I am closing this issue.
