### ISSUE TITLE
Upgrade hyper dependency to 1.1.0

### ISSUE THREAD

**Issue by twitu** [nautechsystems/nautilus_trader#1421]
# Feature Request

Hyper has finally stabilized with a major version release. Nautilus uses hyper in the `nautilus-network` module and this needs to be upgraded to the latest `1.1.0` version. However the hyper upgrade breaks some of its public apis and parts of nautilus logic that rely on it need to be updated.

https://hyper.rs/guides/1/upgrading/
https://github.com/hyperium/hyper/releases

**Comment by cjdsellers** [comment]
Now completed from #1429.

Many thanks again @ayush-sb and @twitu :pray:
