### ISSUE TITLE
Are there any tutorials for stock

### ISSUE THREAD

**Issue by xiadingZ** [nautechsystems/nautilus_trader#1427]
# Feature Request

Provide a detailed description of your proposal, with some examples.

Now, the examples are for binance and forex. Are there any exmaples for stocks, such as load 'AAPL' stocks's bar and ticks data from disk/online, and use a simple strategy to backtest?

**Comment by cjdsellers** [comment]
Hey @xiadingZ 

Thanks for your interest, actually more examples are being worked on right now which will include other asset classes such as equities (including bar data), and instrument classes such as options.
