### ISSUE TITLE
KeyError in Binance Spot Instrument Provider

### ISSUE THREAD

**Issue by doublier1** [nautechsystems/nautilus_trader#1428]
# Bug Report

In the file: `adapters/binance/spot/providers.py` function call `load_all_async` fails on the call to `fee=fees_dict.get(symbol_info.symbol),` as the `fees_dict` is empty for `testnet=True`

```
    async def load_all_async(self, filters: dict | None = None) -> None:
        filters_str = "..." if not filters else f" with filters {filters}..."
        self._log.info(f"Loading all instruments{filters_str}")

        try:
            # Get current commission rates
            if not self._is_testnet:
                response = await self._http_wallet.query_spot_trade_fees()
                fees_dict: dict[str, BinanceSpotTradeFee] = {fee.symbol: fee for fee in response}
            else:
                self._log.warning(
                    "Currently not requesting actual trade fees for the SPOT testnet. "
                    "All instruments will have zero fees.",
                )
                fees_dict = {}
        except BinanceClientError as e:
            self._log.error(
                "Cannot load instruments: API key authentication failed "
                f"(this is needed to fetch the applicable account fee tier). {e.message}",
            )
            return

        # Get exchange info for all assets
        exchange_info = await self._http_market.query_spot_exchange_info()
        for symbol_info in exchange_info.symbols:
            self._parse_instrument(
                symbol_info=symbol_info,
                fee=fees_dict.get(symbol_info.symbol), <<<<-------- Fails on this line
                ts_event=millis_to_nanos(exchange_info.serverTime),
            )
```

This seems to happen only when you try and filter down the providerconfig to only instruments you care about:

```
                # instrument_provider=InstrumentProviderConfig(load_all=False, load_ids=frozenset(traded_instruments)),
                instrument_provider=InstrumentProviderConfig(load_all=True),
```

load_all works fine, but when filtering with set of load_ids the action fails.

### Expected Behavior

Binance Spot engine, Live, testnet=True should allow you to filter to only instruments that are required for trading.

### Actual Behavior

`2023-12-28T18:37:37.461203001Z [ERR] A23R-spot-001.DataClient-BINANCE: Error on `_connect`: KeyError('ETHUSDT')`

### Steps to Reproduce the Problem

1. Run the SPOT example with:
```
instrument_provider=InstrumentProviderConfig(load_all=False, load_ids=frozenset(traded_instruments)),
```

### Specifications

- OS platform: MacOS
- Python version: 3.11
- `nautilus_trader` version: 1.183.0

**Comment by cjdsellers** [comment]
Hey @doublier1 

Thanks for the report.

For some reason we were only using the safe lookup `fees_dict.get(...)` when loading all instruments, and not when loading individual or a subset.

Just pushed a fix to `develop` branch.
