### ISSUE TITLE
Catalog.query() leaks memory for QuoteTicks and TradeTicks

### ISSUE THREAD

**Issue by davidsblom** [nautechsystems/nautilus_trader#1430]
# Bug Report

### Expected Behavior
My use case is to run multiple backtests in a sequence by using catalog.query() directly. The aim is to use different time chunks for every back test. The expected behavior is no memory usage increase for every backtest. 

### Actual Behavior
When calling query_rust() repeatedly, the memory usage increases quickly. At some point the process needs to be killed. 

### Steps to Reproduce the Problem

1. Repeatedly call catalog.query(data_cls=QuoteTick, instrument_ids=[instrument.id.value], start=strt_time, end=end_time)
2.
3.

The workaround is to use query_pyarrow which doesn't have a memory leak. The returned objects need to be converted to the appropriate Nautilus objects though. 

### Specifications

- OS platform:
- Python version:
- `nautilus_trader` version:

**Comment by davidsblom** [comment]
Confirmed by 'ants_are_everywhere'

**Comment by cjdsellers** [comment]
Should now be fixed from https://github.com/nautechsystems/nautilus_trader/pull/1453

Many thanks @twitu :pray:

**Comment by davidsblom** [comment]
Amazing! Thank you!
