### ISSUE TITLE
Logging V2 - optimizations and performance profiling

### ISSUE THREAD

**Issue by twitu** [nautechsystems/nautilus_trader#1435]
# Feature Request

The first draft of logging implementation in #1431 implements the log framework for a custom nautilus logger. While functionally complete, it still needs a few changes and tests.

1. Performance benchmark. Since logging is used everywhere measure perf change between old and new logging will be critical
    * Logging specific benchmark - log million or so calls with some randomness in input and measure time taken. Log only to stderr to minimize effect of buffers and io on time
    * Full backtest - Measure time difference for any full backtest with both loggers
2. Refactor the logging.rs logic into separate writers for stdout, stderr and file. Which will make it easier to filter messages and extend with more writers if needed. `LogWriter`[^1] trait from `flexi_logger` is a good reference for the kind of features we want from a writer.

[^1]: https://docs.rs/flexi_logger/latest/flexi_logger/writers/trait.LogWriter.html

**Comment by cjdsellers** [comment]
The improved writers have now landed, many thanks @twitu and @ayush-sb :pray: 

A related issue is https://github.com/nautechsystems/nautilus_trader/issues/1461, however closing this issue for now as completed.
