### ISSUE TITLE
ParquetDataCatalog write_data takes a very long time

### ISSUE THREAD

**Issue by 0x0scion** [nautechsystems/nautilus_trader#1443]
# Bug Report

### Expected Behavior
I'm trying to run the quick_start example locally
When preparing example data from `nautilus_data` for the `quick_start` example, the docs state it should take 1-2 minutes

### Actual Behavior
The process takes over 1 hour when running locally
This is the time-consuming step:
`catalog.write_data(ticks)`
https://github.com/nautechsystems/nautilus_data/blob/40f9138c875b53b306117cfab2ac059e1b9ddd63/nautilus_data/hist_data_to_catalog.py#L37

When running the `quick_start` example via the jupyter notebook from the docker container seems to work right away... But I'm not totally sure what its doing under the hood

### Steps to Reproduce the Problem

1. git clone https://github.com/nautechsystems/nautilus_data.git
2. cd nautilus_data
3. poetry install
4. poetry run python -m nautilus_data.hist_data_to_catalog

### Specifications

- OS platform: macOS 13.6.1
- Python version: 3.11.6
- `nautilus_trader` version: 1.182.0 and 1.183.0

**Comment by cjdsellers** [comment]
Hi @0x0scion

Thanks for the report on this, its actually been solved on `develop` and `nightly` branches and will make it out in the next release which kicks off later today.

The `nautilus_data` repo is also currently pinned on an older version which had this issue, so that'll be changing too.
