### ISSUE TITLE
Logger Output Not Printing to Console After Commit 120bc0e

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1450]
# Bug Report

### Expected Behavior
Following code used to print the output logs to console however since https://github.com/nautechsystems/nautilus_trader/commit/120bc0e76a6eeafb72ff26f857169c0c0f09aeed it is no longer working.

```python
from nautilus_trader.common.logging import LoggerAdapter
from nautilus_trader.common.logging import Logger
from nautilus_trader.common.clock import LiveClock
logger = Logger(clock=LiveClock())
log = LoggerAdapter(
 component_name="TEST-0",
 logger=logger,
)
log.error("This should print the error.")
log.warning("This should print the warning.")
log.info("This should print the info.")
```

### Actual Behavior
Logs are not printed to console.

### Steps to Reproduce the Problem
Simply excute the above code which doesn't result in any error but also doesn't print any logs to console.

### Specifications

- OS platform: Windows
- Python version: 3.11.6
- `nautilus_trader` version: develop latest

**Comment by rsmb7z** [comment]
Noticed odd thing though, when you run the backtest first and execute above code in same console, output works as expected but doesn't when excuted in new console.

**Comment by rsmb7z** [comment]
@cjdsellers it worked by using `init_logging` as you suggested. This issue may be closed.

**Comment by cjdsellers** [comment]
Hi @rsmb7z 

This is now repaired on `develop` branch. 

It's now possible to use a logger in isolation of the `NautilusKernel`, and the lower level Rust logging system will be initialized as you would expect.

You also don't need to pass a live clock anymore if you simply want a basic logger, this will work as you would expect:
```python
logger = Logger()
```
