### ISSUE TITLE
StreamingFeatherWriter doesn't honour include_types filter

### ISSUE THREAD

**Issue by doublier1** [nautechsystems/nautilus_trader#1458]
# Bug Report

We have setup a `StreamingFeatherWriter` to log out a bit of generic data that we use for debugging.

```
        streaming_config = StreamingConfig(catalog_path=config['output_path'],
                                           fs_protocol=config['output_type'],
                                           include_types=['StrategyStatus'])
        print(f'Logging output to: [{streaming_config.catalog_path}]')
```

When we run this `OrderbookDeltas` objects are also written.

### Expected Behavior

Only `StrategyStatus` messages should be written.

### Actual Behavior

`OrderbookDeltas` are written. The code path followed in the writer seems to treat instrument writers without considering the include_types.

### Steps to Reproduce the Problem

1. Register a StreamingConfig as shown above
2. Run e.g. a Binance live engine 

### Specifications

- OS platform: Linux
- Python version: 3.11.6
- `nautilus_trader` version: 1.182.0

**Comment by cjdsellers** [comment]
Thanks for the report @doublier1 

This is now fixed from b09602a48b45eeb62dbf3506100fbbc2ffb32ebb.
