### ISSUE TITLE
Flush logging when terminating process to avoid truncating logs

### ISSUE THREAD

**Issue by twitu** [nautechsystems/nautilus_trader#1461]
# Feature Request

The current logging setup does not explicitly flush the logging setup when the process ends. This can cause the last few log lines to be truncated.

This can be solved using a guard pattern. A guard is created when the logging is initialized. This is typical done at the top level at the beginning of the application. The drop function for the guard flushes the logging setup and cleans up resources like threads by joining on them.

Since nautilus engine starts it's control flow in python. The guard must also derive `#[pyclass]`. And it's usage will look something like this.

```python
import nautilus.... logging

def main():
    guard = logger_init()
    # run engine
    return # guard is dropped here
```

**Comment by cjdsellers** [comment]
Now completed https://github.com/nautechsystems/nautilus_trader/commit/4bdf54b1418aefc83845f0863def77d5d4c797f2.
