### ISSUE TITLE
Support for multiple trading nodes on IB client

### ISSUE THREAD

**Issue by pcgm-team** [nautechsystems/nautilus_trader#1464]
When you run multiple trading nodes, it gives the error:
```
[ERROR] TESTER-001.InteractiveBrokersClient-001: Unable to connect to 127.0.0.1:4002 w/ id:1
[ERROR] TESTER-001.InteractiveBrokersClient-001: Error 504 req_id=1: Not connected
```

The IB client uses a default contract to verify the connection. However, I think when both try to subscribe to this, it fails. 
If I'm right, this should be an easy fix just by adding a field allowing the user to change the default 'test contract' on one of the nodes to something else other than EUR.CHF on IDEALPRO (ie SPY or something).

**Comment by pcgm-team** [comment]
@rsmb7z

**Comment by rsmb7z** [comment]
Hi @pcgm-team 
What you need is to configure unique int value for `ibg_client_id` for each seperate Node i.e. 1, 2, 3 etc.

https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_trader/adapters/interactive_brokers/config.py#L183
https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_trader/adapters/interactive_brokers/config.py#L154

I am closing this as no further action is required.

**Comment by pcgm-team** [comment]
That allows it to run. 

But in that case, is there a way I can access the net exposures of positions across different trading nodes? I thought that external_order_claims might allow this, but the net exposure on the new node is always zero.
