### ISSUE TITLE
Refactor/Upgrade vendored `tokio-tungstenite` logic

### ISSUE THREAD

**Issue by twitu** [nautechsystems/nautilus_trader#1473]
# Feature Request

Websocket and TCP connections use logic from vendored `tokio-tungstenite` crate. The `tokio-tungstenite` crate is not used as a dependency because some minor modifications were needed to use it with nautilus[^1]. However, it appears `tokio-tungstenite` does not receive updates frequently.

1. Refactor websocket logic to use latest `tokio-rs`, `fastwebsockets` or other websocket library
2. Refactor tls connection handling logic. Ideally the same logic can be used to encrypt both TCP connections and websocket connections. Connection with and without tls should be supported
3. Currently nautilus is enabling features that use rusttls with native roots. All other optional logic can be removed
4. Clients in websocket.rs and socket.rs should ideally stay unchanged

[^1]: https://github.com/nautechsystems/nautilus_trader/issues/1098#issuecomment-1598206852

**Comment by par4m** [comment]
I'll be taking up the task of implementing this feature.

**Comment by twitu** [comment]
Closed by  af52b9d. Tokio tungstenite has been removed.
