### ISSUE TITLE
Always 100ms lag to match time, it is not good for users what to get the snapshot asap, even the snapshot ts_event has some interval

### ISSUE THREAD

**Issue by x-zho14** [nautechsystems/nautilus_trader#1477]
`
        self.subscribe_order_book_snapshots(
            self.instrument_id,
            depth=20,
        ) 

    def on_order_book(self, order_book: OrderBook) -> None:
        self.log.info(repr(order_book))
        print(pd.to_datetime(order_book.ts_event, unit="ns"))
        print(pd.to_datetime(order_book.ts_init, unit="ns"))
        print(pd.to_datetime(time.time(), unit="s"))
`

> 
> 2024-01-30T01:48:51.900841968Z [INFO] BTCUSDTMM-60.MarketMaker: OrderBook L2_MBP
> instrument: BTCUSDT-PERP.BINANCE
> sequence: 0
> ts_last: 1706579331830000128
> count: 1394
> ╭─────────┬──────────┬─────────╮
> │ bids    │ price    │ asks    │
> ├─────────┼──────────┼─────────┤
> │         │ 43402.30 │ [0.003] │
> │         │ 43401.50 │ [0.035] │
> │         │ 43401.40 │ [4.848] │
> │ [5.974] │ 43401.30 │         │
> │ [0.055] │ 43401.20 │         │
> │ [3.006] │ 43401.00 │         │
> ╰─────────┴──────────┴─────────╯
> 2024-01-30 01:48:51.830000128
> 2024-01-30 01:48:51.830000128
> 2024-01-30 01:48:51.901327610
> 2024-01-30T01:48:52.000653010Z [INFO] BTCUSDTMM-60.MarketMaker: OrderBook L2_MBP
> instrument: BTCUSDT-PERP.BINANCE
> sequence: 0
> ts_last: 1706579331902000128
> count: 1435
> ╭─────────┬──────────┬─────────╮
> │ bids    │ price    │ asks    │
> ├─────────┼──────────┼─────────┤
> │         │ 43402.30 │ [0.003] │
> │         │ 43401.50 │ [0.035] │
> │         │ 43401.40 │ [4.668] │
> │ [5.974] │ 43401.30 │         │
> │ [0.055] │ 43401.20 │         │
> │ [3.006] │ 43401.00 │         │
> ╰─────────┴──────────┴─────────╯
> 2024-01-30 01:48:51.902000128
> 2024-01-30 01:48:51.902000128
> 2024-01-30 01:48:52.001138687
> 2024-01-30T01:48:52.100268626Z [INFO] BTCUSDTMM-60.MarketMaker: OrderBook L2_MBP
> instrument: BTCUSDT-PERP.BINANCE
> sequence: 0
> ts_last: 1706579332063000064
> count: 1476
> ╭─────────┬──────────┬─────────╮
> │ bids    │ price    │ asks    │
> ├─────────┼──────────┼─────────┤
> │         │ 43401.60 │ [0.060] │
> │         │ 43401.50 │ [0.035] │
> │         │ 43401.40 │ [4.607] │
> │ [5.977] │ 43401.30 │         │
> │ [0.055] │ 43401.20 │         │
> │ [3.006] │ 43401.00 │         │
> ╰─────────┴──────────┴─────────╯
> 2024-01-30 01:48:52.063000064
> 2024-01-30 01:48:52.063000064
> 2024-01-30 01:48:52.100769520
> 2024-01-30T01:48:52.200427453Z [INFO] BTCUSDTMM-60.MarketMaker: OrderBook L2_MBP
> instrument: BTCUSDT-PERP.BINANCE
> sequence: 0
> ts_last: 1706579332152000000
> count: 1517
> ╭─────────┬──────────┬─────────╮
> │ bids    │ price    │ asks    │
> ├─────────┼──────────┼─────────┤
> │         │ 43401.60 │ [0.060] │
> │         │ 43401.50 │ [0.035] │
> │         │ 43401.40 │ [4.670] │
> │ [5.977] │ 43401.30 │         │
> │ [0.055] │ 43401.20 │         │
> │ [3.006] │ 43401.00 │         │
> ╰─────────┴──────────┴─────────╯
> 2024-01-30 01:48:52.152000
> 2024-01-30 01:48:52.152000
> 2024-01-30 01:48:52.200909138
> 2024-01-30T01:48:52.300774439Z [INFO] BTCUSDTMM-60.MarketMaker: OrderBook L2_MBP
> instrument: BTCUSDT-PERP.BINANCE
> sequence: 0
> ts_last: 1706579332272999936
> count: 1599
> ╭─────────┬──────────┬─────────╮
> │ bids    │ price    │ asks    │
> ├─────────┼──────────┼─────────┤
> │         │ 43401.60 │ [0.060] │
> │         │ 43401.50 │ [0.035] │
> │         │ 43401.40 │ [4.770] │
> │ [5.870] │ 43401.30 │         │
> │ [0.055] │ 43401.20 │         │
> │ [3.006] │ 43401.00 │         │
> ╰─────────┴──────────┴─────────╯
> 2024-01-30 01:48:52.272999936
> 2024-01-30 01:48:52.272999936
> 2024-01-30 01:48:52.301270008
> 2024-01-30T01:48:52.401044730Z [INFO] BTCUSDTMM-60.MarketMaker: OrderBook L2_MBP
> instrument: BTCUSDT-PERP.BINANCE
> sequence: 0
> ts_last: 1706579332327000064
> count: 1640
> ╭─────────┬──────────┬─────────╮
> │ bids    │ price    │ asks    │
> ├─────────┼──────────┼─────────┤
> │         │ 43401.60 │ [0.060] │
> │         │ 43401.50 │ [0.035] │
> │         │ 43401.40 │ [4.843] │
> │ [5.869] │ 43401.30 │         │
> │ [0.055] │ 43401.20 │         │
> │ [3.006] │ 43401.00 │         │
> ╰─────────┴──────────┴─────────╯
> 2024-01-30 01:48:52.327000064
> 2024-01-30 01:48:52.327000064
> 2024-01-30 01:48:52.401601791
> 2024-01-30T01:48:52.501046183Z [INFO] BTCUSDTMM-60.MarketMaker: OrderBook L2_MBP
> instrument: BTCUSDT-PERP.BINANCE
> sequence: 0
> ts_last: 1706579332404999936
> count: 1681
> ╭─────────┬──────────┬─────────╮
> │ bids    │ price    │ asks    │
> ├─────────┼──────────┼─────────┤
> │         │ 43401.60 │ [0.060] │
> │         │ 43401.50 │ [0.035] │
> │         │ 43401.40 │ [4.843] │
> │ [5.921] │ 43401.30 │         │
> │ [0.055] │ 43401.20 │         │
> │ [3.006] │ 43401.00 │         │
> ╰─────────┴──────────┴─────────╯
> 2024-01-30 01:48:52.404999936
> 2024-01-30 01:48:52.404999936
> 2024-01-30 01:48:52.501544714

Hi, Developers,

I observe that, there is always 100ms lag to match time, it is not good for users what to get the snapshot asap, even the snapshot ts_event has some interval. We want the time to catch such snapshot is as close as the ts_event as possible, not to match the local 100ms interval.

Thanks

**Comment by cjdsellers** [comment]
Hi @x-zho14

So it seems like what you're after here is `subscribe_order_book_deltas`, which will update the book every time data is received (this is also what `subscribe_order_book_snapshots` does - it only sends the book to the subscriber on a defined interval). 

So after you `subscribe_order_book_deltas`, you could then setup your strategy `on_order_book_delta` to fetch the book from the cache on every update.

The snapshots use case is a little different, this is specifically for users who _aren't_ interested in every update/delta, but would like a snapshot of the book every n milliseconds.

I also checked the Binance adapter, and it seems we're correctly using the maximum 100ms for spot, and 0ms (unthrottled) for futures.

So give `subscribe_orderbook_deltas` a go and see if this one meets your needs.

Hope this helps and let me know if you have any issues with it!
