### ISSUE TITLE
Allow _get_last_price() to use bars if quote ticks are not subscribed

### ISSUE THREAD

**Issue by pcgm-team** [nautechsystems/nautilus_trader#1480]
Quote tick subscriptions are not always necessary (or available) yet features such as net exposures and unrealized_pnl depend on either quote or trade tick subscriptions to function.

This should be changed to use the most recent bar price in the event that no quote ticks are subscribed.

**Comment by cjdsellers** [comment]
Many thanks @rsmb7z :pray:.
