### ISSUE TITLE
RiskEngine -> Order Denied: CUM_NOTIONAL incorrect calculation

### ISSUE THREAD

**Issue by AnthonyVince** [nautechsystems/nautilus_trader#1507]
# Bug Report
When trading Binance spot in Live production the Risk engine denies orders that should be allowed based on the account state. 
In the attached example we are trading ADA/USDT which has a price of 0.6109 USDT.
Order_size is 440 ADA
free_balance is 440 ADA (therefore we can sell 440 ADA)
Notional value should be 440 x 0.6109 = 268.796 USDT
The Risk engine is calculating cum_notional as 720.24881323 ADA.
That appears to be dividing rather than multiplying 440 / 0.6109 = 720.24881323

The instruments are not setup as inverse, they are standard cash instruments.
LiveRiskEngineConfig is:

        risk_engine=LiveRiskEngineConfig(
            max_order_submit_rate='60/00:00:10',  # As per Binance announcement 2023-11-21 (100 was the limit, use 60 to be safe)
            max_order_modify_rate='500/00:00:01',  # Modifies not supported in Spot market
            max_notional_per_order={},
            debug=True if config["log_level"] in DEBUG_VALUES else False
        ),

### Expected Behaviour
The order should not be denied.

### Actual Behaviour
Order is denied.

### Steps to Reproduce the Problem

Run a strategy on Binance Spot Live or Testnet where the order size is close to the free balance on the account.
<img width="2305" alt="Screenshot 2024-02-20 at 18 01 36" src="https://github.com/nautechsystems/nautilus_trader/assets/137524768/c045b71e-6c42-4f9b-afe1-1694692ab10d">
<img width="2305" alt="Screenshot 2024-02-20 at 18 01 36" src="https://github.com/nautechsystems/nautilus_trader/assets/137524768/044dc676-6952-48ff-be62-1e6cb227e23b">

### Specifications

- OS platform: Mac
- Python version: 3.11.5
- `nautilus_trader` version: latest develop

**Comment by cjdsellers** [comment]
Working on this, so far I've setup a risk engine unit test which reproduces the error:
```
2024-02-21T11:17:09.260984135Z [ERROR] TRADER-000.RiskEngine: SubmitOrder for O-19700101-0000-000-None-1 DENIED: CUM_NOTIONAL_EXCEEDS_FREE_BALANCE: free=440.000000 ADA, cum_notional=720.248813 ADA.
```
