### ISSUE TITLE
Address of file to download for downloading data to change for quickstart

### ISSUE THREAD

**Issue by faysou** [nautechsystems/nautilus_trader#1509]
# Bug Report

### Expected Behavior
On this page [quickstart](https://docs.nautilustrader.io/getting_started/quickstart.html) the download of a script for downloading data should work but it doesn't:
curl https://raw.githubusercontent.com/nautechsystems/nautilus_data/main/scripts/hist_data_to_catalog.py

Downloading this file works instead https://raw.githubusercontent.com/nautechsystems/nautilus_data/main/nautilus_data/hist_data_to_catalog.py

Also when executing the script after downloading it I get this error (note that I'm not using a docker image, I just pip installed nautilus inside my current anaconda environment):
>>> from nautilus_data.util import CATALOG_DIR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nautilus_data'

**Comment by cjdsellers** [comment]
Thanks @faysou

The path in the quickstart guide has been updated (and will be reflected once we release), and the script has also been fixed.
