### ISSUE TITLE
Restore subscriptions after IB client reconnects

### ISSUE THREAD

**Issue by benjaminsingleton** [nautechsystems/nautilus_trader#1533]
# Bug Report

### Expected Behavior

Following a connectivity disruption, the InteractiveBrokersClient does not restore all functionality, such as resubscribing to bar data.

### Actual Behavior

> After NT reestablishes the connection, it stops receiving any bar data from IB.
> \- d2b, Discord

### Steps to Reproduce the Problem

1. Start paper trading IBKR
2. Kill the IB Gateway / TWS
3. Restart IB Gateway / TWS
4. Notice that functionality is not fully restored

### Specifications

- OS platform: Mac OS 14.3.1
- Python version: 3.10
- `nautilus_trader` version: 1.189

**Comment by cjdsellers** [comment]
Closing as I believe this was addressed @benjaminsingleton ?
