### ISSUE TITLE
Improving the tests for IBKR 

### ISSUE THREAD

**Issue by andrewcz** [nautechsystems/nautilus_trader#1535]
First project contribution- improve the tests for IBKR for the project. This includes but not limited to-
- Test reconnection 
- Test order submission
- Test price retrieval 

happy for this to be edited and suggestions made
Cheers

**Comment by cjdsellers** [comment]
Sounds good to me, let us know here or on discord if you have any questions!

**Comment by cjdsellers** [comment]
Hi @andrewcz

How are things going with the above?

**Comment by andrewcz** [comment]
Hi @cjdsellers I come back to this tomorrow.

**Comment by Troubladore** [comment]
@andrewcz - I was thinking about adding some IBKR tests as well, but I don't want to re-cover any cases you've already implemented. Are there any cases you'd like help with?
