### ISSUE TITLE
Missing documentation on using without docker

### ISSUE THREAD

**Issue by edgimar** [nautechsystems/nautilus_trader#1549]
# Feature Request

Currently there is documentation at https://docs.nautilustrader.io/getting_started/quickstart.html that explains how to get started with docker, but there is nothing that explains what to do if you have installed directly using poetry / cargo.  At the minimum it would be helpful to include step-by-step instructions that show (after building / installing using `make`) how to start a jupyterlab instance that has `nautilus_trader` in the python path.  In particular I'm using MacOS, having used port to install poetry.  Maybe this is more straightforward on other platforms?

**Comment by cjdsellers** [comment]
Hi @edgimar

This should actually be relatively straight forward, you just have to ensure the `nautilus_trader` package is installed in the Python environment you're running the jupyter notebook in. There are many examples already in the documentation which assume you're running on "bare metal" outside a docker container.

Closing this for now, as you can expect more examples to land very soon - which won't assume running inside docker.
