### ISSUE TITLE
Performance regression between 1.88.0 and 1.89.0

### ISSUE THREAD

**Issue by dkharrat** [nautechsystems/nautilus_trader#1574]
# Bug Report
I recently upgraded from 1.88.0 to the latest version of Nautilus of 1.90.0, but noticed that backtests run significantly slower. My backtest used to run in ~9 secs (going over 2-years of 1-min bars), but with the latest version, it now runs in ~33 secs. I tried different version of Nautilus and noticed that the 1.89.0 is where the performance regression was introduced. I tried the develop branch and it seems to happen there as well.

### Specifications

- OS platform: Ubuntu
- Python version: 3.11
- `nautilus_trader` version: 1.89.0

**Comment by cjdsellers** [comment]
Hi @dkharrat

I can't see anything obvious so far, did you start using the `use_pyo3` logging option by any chance?

I generally run some of the example backtests periodically and can't see any significant performance change, I wonder if this might be specific to bars in some way?

**Comment by cjdsellers** [comment]
Hey @dkharrat

Thanks for going through this and providing the extra information. There's a chance this could have something to do with a change to how the message bus processes published messages (including bars), but I'll have to test.

**Comment by cjdsellers** [comment]
So after a lengthy investigation this was tracked down to a subtle edge case with the `MessageBus` topic resolving.

## The issue
A [bug was fixed](https://github.com/nautechsystems/nautilus_trader/commit/f826a3cc0c82ee587485b32a8ccbec2b154e9926) for the 1.189.0 release whereby it became possible to subscribe to topics which previously had messages published with no subscribers.

This change caused a performance regression where messages being published without any subscribers would always go through an expensive resolving operation.

## The fix
Now fixed from d28da7636bcd8730e7c8a7f0d535f7e01dd0624a with a simple boolean flag.

Whenever `subscribe` or `unsubscribe` is called on the bus, its put back into an "unresolved" state until the next message is published with has no subscribers. There is still an edge case existing where multiple of these "no subscriber topics" could need resolving (and only the first one will resolve), however this at least fixes the most common use case and performance regression.

Let me know if this fix works for you when you get a chance.
