### ISSUE TITLE
Creating strategy with data sources from both binance spot and binance futures do not work

### ISSUE THREAD

**Issue by dimitar-petrov** [nautechsystems/nautilus_trader#1583]
# Bug Report

### Expected Behavior
Creating a strategy that trades simultaneously on binance trades and futures should be supported.

Here are the two data clients.
```py
{'BINANCE_FUTURES': BinanceDataClientConfig(handle_revised_bars=False, instrument_provider=InstrumentProviderConfig(load_all=False, load_ids=frozenset({'BTCUSDT-PERP.BINANCE'}), filters=None, filter_callable=None, log_warnings=True), routing=RoutingConfig(default=False, venues=None), api_key='****', api_secret='****', account_type=<BinanceAccountType.USDT_FUTURE: 'USDT_FUTURE'>, base_url_http=None, base_url_ws=None, us=False, testnet=False, use_agg_trade_ticks=False),
 'BINANCE_SPOT': BinanceDataClientConfig(handle_revised_bars=False, instrument_provider=InstrumentProviderConfig(load_all=False, load_ids=frozenset({'BTCUSDT.BINANCE'}), filters=None, filter_callable=None, log_warnings=True), routing=RoutingConfig(default=False, venues=None), api_key='****', api_secret='****', account_type=<BinanceAccountType.SPOT: 'SPOT'>, base_url_http=None, base_url_ws=None, us=False, testnet=False, use_agg_trade_ticks=False)}
```

### Actual Behavior.

We are getting the following error check.
```
  self._data_engine.register_client(client)
  File "nautilus_trader/data/engine.pyx", line 246, in nautilus_trader.data.engine.DataEngine.register_client
  File "nautilus_trader/data/engine.pyx", line 262, in nautilus_trader.data.engine.DataEngine.register_client
  File "nautilus_trader/core/correctness.pyx", line 505, in nautilus_trader.core.correctness.Condition.not_in
KeyError: "The 'client' BINANCE was already contained in the '_clients' collection"
```

Reason is that clientId for both binance futures and binance spot is hardcoded as follows

./nautilus_trader/nautilus_trader/adapters/binance/spot/data.py

```py
class BinanceCommonDataClient(LiveMarketDataClient):
    def __init__(
        self,
        loop: asyncio.AbstractEventLoop,
        client: BinanceHttpClient,
        market: BinanceMarketHttpAPI,
        enum_parser: BinanceEnumParser,
        msgbus: MessageBus,
        cache: Cache,
        clock: LiveClock,
        instrument_provider: InstrumentProvider,
        account_type: BinanceAccountType,
        base_url_ws: str,
        config: BinanceDataClientConfig,
    ) -> None:
        super().__init__(
            loop=loop,
            client_id=ClientId(BINANCE_VENUE.value),  # Same CliendId is created and latter the check does not pass
            venue=BINANCE_VENUE,
            msgbus=msgbus,
            cache=cache,
            clock=clock,
            instrument_provider=instrument_provider,
        )
```

Also get_cached_binance_http_client is using key and secret as caching mechanism which leads to issues in case both spot and futures in binance have the same key, which is the case of subaccounts.
./nautilus_trader/nautilus_trader/adapters/binance/factories.py
```py
    client_key: str = "|".join((key, secret))
```
This can be mitigated as follows if it is not breaking something else
```py
    client_key: str = "|".join((str(account_type), key, secret))

```

### Steps to Reproduce the Problem
Create a tradingnode with both binance spot and futures data set.

### Specifications

- OS platform: linux
- Python version: 3.10
- `nautilus_trader` version: 1.190

**Comment by cjdsellers** [comment]
Hi @dimitar-petrov 

Thanks for bringing this to my attention, it should now be fixed from 6f9686565e05360b262b40e39c0f3b0469508291 on `develop` branch.

I was able to run two Binance data clients, and two Binance execution clients. Let me know how you go when you get a chance.

**Comment by cjdsellers** [comment]
Hi @dimitar-petrov

Yes, this is known and currently the intent is that you would add your two client sets for SPOT and FUTURES, then use the `client_id` param for commands to specifically route to those clients, e.g.
```
client_id=ClientId("BINANCE_PERP")
```

```
    cpdef void subscribe_quote_ticks(self, InstrumentId instrument_id, ClientId client_id=*)

```

**Comment by dimitar-petrov** [comment]
@cjdsellers, thanks for the clarification.

I did not notice that client_id was added to the subscribe methods.

**Comment by cjdsellers** [comment]
Yes, `client_id` has actually been in the API a long time as well. :+1:
