### ISSUE TITLE
BinanceBar ts_event not consistent

### ISSUE THREAD

**Issue by OnlyC** [nautechsystems/nautilus_trader#1591]
# Bug Report
`BinanceBar` from historical request use `open_time` as `ts_event` , websocket stream using `close_time (T)`

![image](https://github.com/nautechsystems/nautilus_trader/assets/1250580/d7fb4974-7b12-4de1-ad94-f8f9e7abc160)
![image](https://github.com/nautechsystems/nautilus_trader/assets/1250580/9c6e8098-ad9f-44b0-86d2-857830f15931)

### Expected Behavior
Use `open_time (t)` in websocket stream parse or use `time_bars_timestamp_on_close` option from `LiveDataEngineConfig`

### Specifications
- `nautilus_trader` version: 1.190.0

**Comment by cjdsellers** [comment]
Hi @OnlyC

Thanks for the report!

I think using the `close_time` is best, so have aligned the historical kline parsing to this in 882ce3c7b7763bd0c200d7ebda83e548190f1c24.
