### ISSUE TITLE
Add CFD and Commodity support for Interactive Brokers 

### ISSUE THREAD

**Issue by DracheShiki** [nautechsystems/nautilus_trader#1605]
# Feature Request

add CFD and Commodity support for Interactivebrokers.

Done with it:)
Tested with "XAUUSD.IBCMDTY", "XAUUSD.IBCFD", "IBUS30.IBCFD", "TSLA.IBCFD", "EUD/USD.IBCFD" by live trading and historical data downloading.
fix the small bug of strict symbology. "NVDAn=CFD.IBCFD" works now.
a doc that "IBCFD" and "IBCMDTY" used as venue (mapping to "SMART") might be updated.
Although it works with no bugs as far as i tested it, the cfd.pyx and commodity.pyx may need to be refined.

**Comment by cjdsellers** [comment]
Now implemented with #1604, many thanks @DracheShiki :pray:.
