### ISSUE TITLE
Incorrect import for OrderBookImbalance example strategy

### ISSUE THREAD

**Issue by lufengkuang** [nautechsystems/nautilus_trader#1651]
# Bug Report
one of the examples doesn't work
examples/live/binance/binance_futures_testnet_orderbook_imbalance.py

### Expected Behavior
Add here...

### Actual Behavior

the error message reads as follow:

Traceback (most recent call last):
  File "F:\quant\ntrader\test.py", line 103, in <module>
    strategy = OrderBookImbalance(config=strat_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\office\.conda\envs\ntrader\Lib\site-packages\nautilus_trader\examples\strategies\orderbook_imbalance_rust.py", line 116, in __init__
    self.book = nautilus_pyo3.OrderBook(self.book_type, pyo3_instrument_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'book_type': 'BookType' object cannot be converted to 'BookType'

### Steps to Reproduce the Problem

1.  pip install -U nautilus_trader
2.  fill in my own testnet api key and secret in binance_futures_testnet_orderbook_imbalance.py
3. run the py file

### Specifications

- OS platform: windows 10
- Python version: 3.11
- `nautilus_trader` version:  1.192.0

**Comment by cjdsellers** [comment]
Hi @lufengkuang

Thanks for the report on this.

I've now fixed the import on `develop` branch.
