### ISSUE TITLE
Multi-currency support for SANDBOX mode

### ISSUE THREAD

**Issue by VeraLyu** [nautechsystems/nautilus_trader#1671]
# Feature Request

For use cases of cross currencies arbitrage  we need our account to support multi base currencies, we can do this in live mode, but for SANDBOX mode we just support set single currency for now.

**Comment by cjdsellers** [comment]
This is now supported on `develop` branch https://github.com/nautechsystems/nautilus_trader/commit/54d05103b79c2859a5b8efe1847627fee1a716fc.

**Comment by willjay97** [comment]
@VeraLyu Hello, I'm a newer about NautilusTrader. I'm finding out how to subscribe to multi-currency market data in a strategy, would you mind sharing an example code about this? Thank you.
