### ISSUE TITLE
Documentation site navigation menu cuts off on left edge at certain zoom resolutions

### ISSUE THREAD

**Issue by Troubladore** [nautechsystems/nautilus_trader#1723]
# Bug Report
When I open [the Nautilus documentation site](https://nautilustrader.io/docs/) on a Windows or Ubuntu machine, the left edge of the left-hand menu is cut off at some magnification levels in the browsers I tested.

### Expected Behavior
You can see the full text of the left-hand navigation menu.

### Actual Behavior
The left edge of the menu is cut off from view (see attached screenshot).

![image](https://github.com/nautechsystems/nautilus_trader/assets/8116429/bc5863a6-a68f-4984-8480-0c28fbfbe7c9)

### Steps to Reproduce the Problem

1. On a Windows 11 or Ubuntu 22.04 machine...
2. Open Firefox, Brave, Chrome, or Edge
3. Maximize the browser window on one monitor
4. Navigate to https://nautilustrader.io/docs/
5. Increment the display zoom from 60% to 150%, watching the left-hand menu.
6. At some point, the left edge of the menu should shift out of view.
7. Verify that the menu is visible when changing the zoom scaling to some other value.

### Specifications

- OS platform: Windows 11, Ubuntu 22.04
- Browsers: Firefox, Brave, Chrome, or Edge
- `nautilus_trader` version: Live documentation site

**Comment by cjdsellers** [comment]
Thanks for the report @Troubladore, we'll look into addressing this soon!

**Comment by Troubladore** [comment]
Confirmed fixed for all prior test cases - thank you @cjdsellers
