### ISSUE TITLE
Mutliplier not imported from databento definition file for FuturesContract and OptionsContract

### ISSUE THREAD

**Issue by faysou** [nautechsystems/nautilus_trader#1757]
# Bug Report

### Expected Behavior
The futures multiplier in a nautilus FuturesContract or OptionsContract should be correctly imported from a databento defintion file.

### Actual Behavior
It is set to 1.

### Steps to Reproduce the Problem

1. Load and save definition of a contract from databento (use 'ESM4 P5230' for a test option symbol)

```
import databento as db

client = db.Historical()
definition_file = 'test.dbn.zst'

definition = client.timeseries.get_range(
        dataset='GLBX.MDP3',
        schema='definition',
        symbols=['ESM4'],
        start='2024-05-09',
        end='2024-05-10',
        path=definition_file
    )

list(definition)
```

`[InstrumentDefMsg { ..., unit_of_measure_qty: 50.000000000, ...}]`

2. Load the saved file with Nautilus

```
from nautilus_trader.adapters.databento.loaders import DatabentoDataLoader

loader = DatabentoDataLoader()
future_defintion = loader.from_dbn_file(path=definition_file)

future_defintion
```

`[FuturesContract(..., multiplier=1, ...)]`

### Specifications

- OS platform: macos
- Python version: 3.11
- `nautilus_trader` version: latest develop commit

**Comment by cjdsellers** [comment]
Hi @faysou

I'm not sure if the `unit_of_measure_qty` is what we want in all cases, but this should now be returning what you expect for ES 7abdbad022acf60782b1bd274dd67328a54820a1.

**Comment by faysou** [comment]
Thanks @cjdsellers
