### ISSUE TITLE
Parquet loader support ? 

### ISSUE THREAD

**Issue by ian-wazowski** [nautechsystems/nautilus_trader#177]
I'd like to recommand default store of tick data as a [parquet](https://parquet.apache.org/) not csv.

In a nutshell, parquet is a highly well-designed file type for handling time series data-sets such as large tick data. Pandas supports very well operation without any boilerplate code like pd.read_csv().

The main reason I use this is because it can do compression. You can compress a bitcoin trade tick for a day to around 30mb (200mb when uncompressed, You can learn more by looking at the sample data posted on PR.)

I used parquet mainly by previous HFT firm and it worked fine without any problems. so I also recommanded to use this in the nautilus_trader project.

**Comment by cjdsellers** [comment]
Lets support parquet, it looks valuable.

I suppose we just need a `ParquetTradeDataLoader` and `ParquetQuoteDataLoader` for now. If you're able to provide those with some sample data in the `test_kit.data` folder with tests then I'm happy to include that.

I think for ease of development and familiarity right now, it'll be a good idea to stick to CSV sample data in general though?

**Comment by ian-wazowski** [comment]
> I think for ease of development and familiarity right now, it'll be a good idea to stick to CSV sample data in general though?
Of course, (I love csv.) I just wanted to emphasize that the sample data is getting large that downloading the repository is slow. By compressing it with parquet, I thought I could reduce the total size of the repository.

**Comment by cjdsellers** [comment]
I agree the repo with the sampl data is getting fairly bulky.

**Comment by jpmediadev** [comment]
> Actually the only reason the rest of the data isn't compressed is due to CI failing issues with pandas which I couldn't get a fix for quickly.

several times tried to upload gz csv -  files were broken

**Comment by cjdsellers** [comment]
Yes, its a strange error on the gzips.

**Comment by cjdsellers** [comment]
pyarrow dependency fixed and merged.
