### ISSUE TITLE
Small mistake in Cache.get function documentation

### ISSUE THREAD

**Issue by faysou** [nautechsystems/nautilus_trader#1772]
# Bug Report

### Expected Behavior
The get function for the cache class has the same documentation as add, this should be corrected.
https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/cache/cache.pyx#L2005

**Comment by cjdsellers** [comment]
Thanks for the report @faysou

Now fixed 649a096207f375bd285975c2f07cc74d2f25bd87.
