### ISSUE TITLE
writing backtest with rust?

### ISSUE THREAD

**Issue by naijim** [nautechsystems/nautilus_trader#1784]
I check the example dir. It seems that I have to write backtest with python. Is it any plan to offer rust backtest example.
Just like Polars having python & rust interface.

**Comment by cjdsellers** [comment]
Hi @naijim

Thanks for your interest!

Exactly, the intent is to eventually achieve a polars type interface where there are both fully supported Python and Rust APIs. At this point the Rust port is still ongoing and does not yet have any interface for writing strategies and actors.

I'll close this for now as we're still a way off this being achieved, but we're working hard on achieving this goal.
