### ISSUE TITLE
Enhancement to documentation for make install-cli

### ISSUE THREAD

**Issue by faysou** [nautechsystems/nautilus_trader#1787]
The nautilus cli doesn't run if the path to libpython is not set for the linker used by rust.

Under macos I got this error:
```
dyld[92351]: Library not loaded: @rpath/libpython3.12.dylib
  Referenced from: <290892CB-FDE9-30C3-9AA9-6213CB60CB32> /Users/ata/.cargo/bin/nautilus
  Reason: tried: '/Users/ata/.gvm/pkgsets/go1.22.5/global/overlay/lib/libpython3.12.dylib' (no such file)
```

Using this for example fixed it for me:
```
export DYLD_LIBRARY_PATH=~/miniconda3/envs/nautilus/lib  
make install-cli
```

Making users aware of this in the documentation could save them some time to avoid this issue.

I'm using the latest develop version under macos.

**Comment by cjdsellers** [comment]
Hi @faysou

Thanks for the report here.

One factor at play here is the conda environment. This isn't the first or only issue compiling from source using conda, although likely the only one you've run into?

**Comment by cjdsellers** [comment]
Closing this for now as conda isn't officially supported.
