### ISSUE TITLE
Main Backtest loop perfomance

### ISSUE THREAD

**Issue by jpmediadev** [nautechsystems/nautilus_trader#179]
The reset() method in BacktestDataProducer hints that running a backtest with the same data can be repeated
I have not found any trace of its use on the system, but the idea is good

maybe it makes sense to cache the results of the first launch so as not to create QuoteTick, TradeTick every next  time

the difference is approximately as follows:

~2M trades & quotes  just iteration without time for preparation: 

 7.48 sec VS  0.67 sec (if cached and stored in SortedDict)

How valuable is it?

**Comment by ian-wazowski** [comment]
Interesting...

**Comment by jpmediadev** [comment]
2 years of ticks & trades will not fit in memory, especially if you need to generate features from them )

before changing this, need to understand how much it is relative to the whole backtest process

**Comment by ian-wazowski** [comment]
> 2 years of ticks & trades will not fit in memory, especially if you need to generate features from them )
> 
> before changing this, need to understand how much it is relative to the whole backtest process

You are right, It taskes 67GB for BTCUSDT(Binance, Trade/Quotes Ticks) 2019-03-30 ~ now.

And so I thinking of implementing yield(chunk) based data producer to perform long-term back-testing. 

I look forward to your work :)

**Comment by jpmediadev** [comment]
@ian-wazowski ,
how are you planning to do backtest - calculation of indicators and features inside the nautilus_trader or nautilus just for backtesting previously calculated features and signals ?

**Comment by ian-wazowski** [comment]
> @ian-wazowski ,
> how are you planning to do backtest - calculation of indicators and features inside the nautilus_trader or nautilus just for backtesting previously calculated features and signals ?

Currently, I re-calculate every indicators and features when one back-testing is done. 

I am finding way to avoid a such overhead...

**Comment by cjdsellers** [comment]
> The reset() method in BacktestDataProducer hints that running a backtest with the same data can be repeated
> I have not found any trace of its use on the system, but the idea is good
> 
> maybe it makes sense to cache the results of the first launch so as not to create QuoteTick, TradeTick every next time
> 
> the difference is approximately as follows:
> 
> ~2M trades & quotes just iteration without time for preparation:
> 
> 7.48 sec VS 0.67 sec (if cached and stored in SortedDict)
> 
> How valuable is it?

That's exactly the intended behavior.

**Comment by cjdsellers** [comment]
> > @ian-wazowski ,
> > how are you planning to do backtest - calculation of indicators and features inside the nautilus_trader or nautilus just for backtesting previously calculated features and signals ?
> 
> @jpmediadev
> Currently, I re-calculate every indicators and features when one back-testing is done. (with pre-trained Model)
> 
> I am finding way to avoid a such overhead without changing the structure of the nautilus_trader.

I've found the best way to handle this use case is inside the strategy itself. As not every strategy would require that functionality. This has been briefly discussed here #106.

**Comment by cjdsellers** [comment]
> > 2 years of ticks & trades will not fit in memory, especially if you need to generate features from them )
> > before changing this, need to understand how much it is relative to the whole backtest process
> 
> You are right, It taskes 67GB for BTCUSDT(Binance, Trade/Quotes Ticks) 2019-03-30 ~ now.
> 
> And so I thinking of implementing yield(chunk) based data producer to perform long-term back-testing.
> 
> I look forward to your work :)

This is something I've had in the back of my mind but lacked the bandwidth to implement.

**Comment by ian-wazowski** [comment]
> > > @ian-wazowski ,
> > > how are you planning to do backtest - calculation of indicators and features inside the nautilus_trader or nautilus just for backtesting previously calculated features and signals ?
> > 
> > 
> > @jpmediadev
> > Currently, I re-calculate every indicators and features when one back-testing is done. (with pre-trained Model)
> > I am finding way to avoid a such overhead without changing the structure of the nautilus_trader.
> 
> I've found the best way to handle this use case is inside the strategy itself. As not every strategy would require that functionality. This has been briefly discussed here #106.

Thanks

**Comment by ian-wazowski** [comment]
> > > 2 years of ticks & trades will not fit in memory, especially if you need to generate features from them )
> > > before changing this, need to understand how much it is relative to the whole backtest process
> > 
> > 
> > You are right, It taskes 67GB for BTCUSDT(Binance, Trade/Quotes Ticks) 2019-03-30 ~ now.
> > And so I thinking of implementing yield(chunk) based data producer to perform long-term back-testing.
> > I look forward to your work :)
> 
> This is something I've had in the back of my mind but lacked the bandwidth to implement.

I will go for it in this week.

**Comment by jpmediadev** [comment]
Done https://github.com/nautechsystems/nautilus_trader/pull/181

**Comment by cjdsellers** [comment]
Excellent work!

**Comment by cjdsellers** [comment]
I'm just tidying some things up for it.

While I remember, is it possible to add some parquet format bar data with a test for that?

**Comment by cjdsellers** [comment]
I did uncover a slight bug but not with the system. The example strategies weren't resetting indicators `on_reset` which resulted in slightly different runs.

Thats also fixed now.

**Comment by jpmediadev** [comment]
great,  waiting for the new version and preparing tests..

**Comment by cjdsellers** [comment]
For the performance it depends on how computationally heavy the strategy is, and how many events its producing per iteration. For a really busy strategy there isn't much performance gain, for other strategies where a larger amount of market data is passing through there's good performance increases. More than twice as fast on a few examples I ran.

Pushing very soon.

**Comment by ian-wazowski** [comment]
Great Work!

**Comment by jpmediadev** [comment]
I see the main usercase is optimization of parameters for a previously calculated strategy (Blackbox), also critically fast environment for RL models

**Comment by cjdsellers** [comment]
I think there's still some room for improvement too.

I'll write a short description of how to do performance profiling in the developer guide.

**Comment by ian-wazowski** [comment]
CachedProducer use memory twice.

use_cached_ticks=True => 80% memory Usage
![bandicam 2021-01-14 15-54-57-161](https://user-images.githubusercontent.com/76048528/104555719-af7e6c00-5681-11eb-8a04-6ee8a7258005.jpg)

use_cached_tick=False => 50% memory Usage
![bandicam 2021-01-14 15-54-16-330](https://user-images.githubusercontent.com/76048528/104555824-d9379300-5681-11eb-8ad0-6d769345f8c0.jpg)

I think `self._producer.clear()` is not actually release memory.
you should be add `self._producer.reset()` too.

```Python
cdef void _create_tick_cache(self) except *:
    self._log.info(f"Pre-caching ticks...")
    self._producer.setup(self.min_timestamp, self.max_timestamp)

    timing_start_total = time.time()

    cdef Tick tick
    while self._producer.has_tick_data:
        tick = self._producer.next_tick()
        self._tick_cache.append(tick)
        self._ts_cache.append(tick.timestamp.timestamp())

    processing_time = round((time.time() - timing_start_total), 2)
    self._log.info(f"Pre-cached {len(self._tick_cache):,} "
                   f"total tick rows in {processing_time}s.")

    self._producer.clear()
    gc.collect()  # Removes redundant processing artifacts
```

**Comment by cjdsellers** [comment]
Did you find adding `self._producer.reset()` releases the memory?

I think there we're trying to release those pandas dataframes as they're already been used to pre-process and then cache the ticks.

**Comment by jpmediadev** [comment]
> Did you find adding self._producer.reset() releases the memory?
Sure, forgot add...

```
Cache without reset: 

2021-01-14T10:30:03.530Z [INF] BacktestEngine: =================================================================
2021-01-14T10:30:03.530Z [INF] BacktestEngine:  MEMORY USAGE
2021-01-14T10:30:03.530Z [INF] BacktestEngine: =================================================================
2021-01-14T10:30:03.530Z [INF] BacktestEngine: RAM-Total: 68,719 MB
2021-01-14T10:30:03.530Z [INF] BacktestEngine: RAM-Used:  37,375 MB (56.2%)
2021-01-14T10:30:03.530Z [INF] BacktestEngine: RAM-Avail: 30,105 MB (43.8%)
2021-01-14T10:30:04.386Z [INF] BacktestEngine: Data size: 667.89 MB


No cache:
2021-01-14T10:31:31.166Z [INF] BacktestEngine: RAM-Total: 68,719 MB
2021-01-14T10:31:31.166Z [INF] BacktestEngine: RAM-Used:  35,451 MB (53.4%)
2021-01-14T10:31:31.166Z [INF] BacktestEngine: RAM-Avail: 32,030 MB (46.6%)
2021-01-14T10:31:31.893Z [INF] BacktestEngine: Data size: 667.89 MB



Cache with reset:
2021-01-14T10:34:28.575Z [INF] BacktestEngine: RAM-Total: 68,719 MB
2021-01-14T10:34:28.575Z [INF] BacktestEngine: RAM-Used:  35,619 MB (53.6%)
2021-01-14T10:34:28.575Z [INF] BacktestEngine: RAM-Avail: 31,862 MB (46.4%)
2021-01-14T10:34:29.321Z [INF] BacktestEngine: Data size: 667.89 MB
```

**Comment by cjdsellers** [comment]
It could depend on the moment those measurements were taken too...

**Comment by cjdsellers** [comment]
Ah didn't see your PR, just pushed alot of changes. Hopefully you don't have to rebase - I don't think I touched the `data_producer` stuff.

**Comment by jpmediadev** [comment]
> It could depend on the moment those measurements were taken too...

No, i just do `git reset --hard upstream/develop`
and finally everything became cleaner

**Comment by jpmediadev** [comment]
> Ah didn't see your PR, just pushed alot of changes. Hopefully you don't have to rebase - I don't think I touched the data_producer stuff.

No, i just do `git reset --hard upstream/develop`
and finally everything became cleaner

**Comment by cjdsellers** [comment]
It's taking up quite a lot of memory all of those objects...

If these checks pass it'll make the 1.96.2 release haha

**Comment by jpmediadev** [comment]
i tried to free completely self._producer  after all calcs,  get_size_of()  shows that there is still enough memory left , but i get error, I don't understand how to do it

**Comment by ian-wazowski** [comment]
I think issue has fixed. It works well intended.

**Comment by jpmediadev** [comment]
ok, close
