### ISSUE TITLE
ValueError: currency != other.currency

### ISSUE THREAD

**Issue by dpmabo** [nautechsystems/nautilus_trader#1805]
# Bug Report
When pnl currency is different from commission currency and commission is 0, Assert is raised.

```python
# In file "nautilus_trader/accounting/manager.pyx", line 520
currency = pnl.currency
if commission.currency != currency and commission._mem.raw != 0:
    ...
else:
    pnl = pnl.sub(commission)
```

**Possible reason:**
In the if statement is true when the  pnl and commission have the same currency ,  and the value of commission is not 0. However, the else statement on line 538 will throw an exception when  the  pnl and commission don't have the same currency , but this line can be reached when the  pnl and commission don't have the same currency , while the value of commission is 0.

### Expected Behavior
No assert.

### Actual Behavior
Assert is raised.

### Steps to Reproduce the Problem
Make  the pnl currency different from commission  currency

### Specifications

- OS platform: Ubuntu 22.04
- Python version: 3.11
- `nautilus_trader` version: 1.196

**Comment by cjdsellers** [comment]
Hi @dpmabo

Thanks for the report and this is now fixed from e05585ca2d9f4d5325eba14ecf0d7dd1d4a7f660.

I simplified and consolidated the logic, so your edge case shouldn't occur anymore (let me know how it goes).

I also uncovered two other bugs:
- Commissions would be applied for every PnL where its currency didn't equal the commission currency
- The calculation would end early if any PnL was zero (such as post commission)
