### ISSUE TITLE
typo in persistence/BarDataWranglerV2

### ISSUE THREAD

**Issue by anegrean** [nautechsystems/nautilus_trader#1825]
# Bug Report

### Expected Behavior

in file nautilus_trader/persistence/wranglers_v2.py class BarDataWranglerV2, def from_pandas function, line 478, should read:
df["close"] = (df["close"] * 1e9).astype(pd.Int64Dtype())

### Actual Behavior
the line currently reads:
df["clow"] = (df["close"] * 1e9).astype(pd.Int64Dtype())

- `nautilus_trader` version: 1.198.0, development branch

**Comment by cjdsellers** [comment]
Hi @anegrean

Thanks for the report! now fixed from 031de7a3c04b924aa48ee2565eb6c1aa79043265.
