### ISSUE TITLE
core dump when running pytest and initializing CachePostgresAdapter

### ISSUE THREAD

**Issue by anegrean** [nautechsystems/nautilus_trader#1829]
# Bug Report

### Expected Behavior
When I run pytest in the nautilus_trader/tests, all tests should pass.

### Actual Behavior
I get core dump when running test integration_tests/infrastructure/test_cache_database_postgres.py

Current thread 0x00007a39f025d740 (most recent call first):
  File ".. nautilus_trader/nautilus_trader/cache/postgres/adapter.py", line 53 in __init__
  File ".. nautilus_trader/tests/integration_tests/infrastructure/test_cache_database_postgres.py", line 74 in setup

### Steps to Reproduce the Problem
compiled files running command in nautilus_trader folder:
poetry run python build.py

run pytest in nautilus_trader/tests

I further isolated the problem by running these commands in a clean python kernel:

```python
from nautilus_trader.cache.postgres.adapter import CachePostgresAdapter
import os
# set envs
os.environ["POSTGRES_HOST"] = "localhost"
os.environ["POSTGRES_PORT"] = "5432"
os.environ["POSTGRES_USERNAME"] = "nautilus"
os.environ["POSTGRES_PASSWORD"] = "pass"
os.environ["POSTGRES_DATABASE"] = "nautilus"
database: CachePostgresAdapter = CachePostgresAdapter()
```

thread '<unnamed>' panicked at infrastructure/src/sql/pg.rs:129:44:
called `Result::unwrap()` on an `Err` value: PoolTimedOut
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

### Specifications
System: Linux x86_64, Ubuntu 22.04.4 LTS
Clang:  14.0.0-1ubuntu1.1
Rust:   1.80.0 (051478957 2024-07-21)
Python: 3.10.13
Cython: 3.0.10
NumPy:  1.26.4

Both the latest master commit c760fb0 and develop 198dd9029 commits fail.

**Comment by filipmacek** [comment]
Hi @anegrean, thanks for reporting this. We don't have any problems with running Postgres and executing these tests on both Mac and Linux dev machines, and they are also run on Linux machines in GitHub actions.
What is your Postgres server setup, is it run locally or from docker?
 We have officially supported [docker-compose](https://github.com/nautechsystems/nautilus_trader/blob/develop/.docker/docker-compose.yml) that works well for us. 
Connection timeout errors are mostly related to network or configuration issues. 
I would also try to connect to postgres with `psql` cli tool.
And we have `nautilus` cli which bootstraps postgres schema for you, more about it here https://nautilustrader.io/docs/latest/developer_guide/environment_setup/#nautilus-cli-developer-guide

**Comment by cjdsellers** [comment]
Thanks @filipmacek

Closing this for now preempting a config or infra setup issue.
