### ISSUE TITLE
Add time_in_force parameters for bracketing stop-loss and take-profit orders

### ISSUE THREAD

**Issue by marcodambros** [nautechsystems/nautilus_trader#1838]
# Feature Request

At the moment, when you create a bracket order, the TP and SL "sub-orders" have a time_in_force GTC.
With this feature, I propose to add two parameters to the bracket order creation (https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/common/factories.pyx#L1096): 
- tp_time_in_force
- sl_time_in_force

Looking at the code, it seems that this change entails propagating the given parameters when creating the tp and sl orders (for example here: https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/common/factories.pyx#L1325).

**Comment by cjdsellers** [comment]
Hi @marcodambros

Thanks for your thoughts.

I'm interested to know what your use case is? The idea behind the default GTC time in force for TP and SL bracketing orders was that you'd probably not want these orders to expire or partially fill if you have open exposure.

**Comment by marcodambros** [comment]
Hi @cjdsellers,

thanks for your feedback. I totally agree that most of the time you do not want order to expire or be partially filled if you have open exposure, and in fact with this issue I propose this to be the default behaviour.
However, you might want to implement strategies where you want your TP or SL to happen at ATO or ATC. Once could also implement this behaviour manually in the strategy, but with the bracket order it would be much simpler.
Also the code change seems to be minimal.

Thanks and take care,
Marco

**Comment by cjdsellers** [comment]
Hi @marcodambros

Makes sense, I agree that the change _should_ be relatively small too - just a couple of optional time in force params.
There's also another small change coming up for the `OrderFactory` with #1884, so I should be able to handle this at the same time.

**Comment by cjdsellers** [comment]
Hey @marcodambros

Now added from commit 8ac2fe1d6cfb5a3c265c532c1ca469e54ffc4bae on `develop` branch, and will be available in the next release.
