### ISSUE TITLE
Add PrevNDayHigh and PrevNDayLow indicators 

### ISSUE THREAD

**Issue by mylesgamez** [nautechsystems/nautilus_trader#1871]
I'm working on improving our trading strategies that use Nautilus. We've identified a need for PrevNDayHigh and PrevNDayLow indicators which are currently not present in Nautilus core.

Would you be open to adding these indicators? If so, any specific requirements or guidelines in mind? 

I'm prepared to contribute towards this if it aligns, look forward to your thoughts and any guidance you can provide.

**Comment by cjdsellers** [comment]
Hey @mylesgamez

Could you provide an example of such an indicator?

If you’re simply looking for the previous N high/low from a series of bars, that’s a straightforward calculation that doesn’t require persisting any previous state, aside from the bars themselves.

**Comment by faysou** [comment]
You could subscribe to a composite bar like this, maybe this would solve your problem:

"BTCUSDT-PERP.BINANCE-5-DAY-LAST-INTERNAL@BTCUSDT-PERP.BINANCE-1-MINUTE-LAST-EXTERNAL"
