### ISSUE TITLE
Cannot access strategy object after running high-level API node

### ISSUE THREAD

**Issue by anegrean** [nautechsystems/nautilus_trader#1878]
# Bug Report

To access post strategy stats calculated after each run, need to access strategy object configured by high level node API.

### Expected Behavior

node = BacktestNode(configs=[bt_run_cfg])

bt_results: list[BacktestResult] = node.run()

bt_engine: BacktestEngine = node.get_engine(bt_run_cfg.id)

strategy = bt_engine.trader.strategies()[0]

.strategies() should return strategy objects after node run.

### Actual Behavior

.strategies() returns empty list

### Steps to Reproduce the Problem

run this code: https://gist.github.com/anegrean/79e63be8451f188c72c09b09e785904a
 
### Specifications

- OS platform: Ubuntu Linux 22.04 LTS
- Python version: 3.10
- `nautilus_trader` version: 1.198.0 development branch

**Comment by cjdsellers** [comment]
Hi @anegrean

This can now be accommodated by using the new `dispose_on_completion` config setting for `BacktestRunConfig`. For your use case, set this to `False` (the default is `True` to maintain the current behavior).

Now available on `develop` branch from commit b446e39b3f587976e40c588e1b41af4da5fb6d40, and will make it into the next release.

**Comment by anegrean** [comment]
This is a great feature addition, thank you!
