### ISSUE TITLE
Change vendored tokio-tungstenite for raw socket

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#1902]
We are currently vendoring a version of `tokio-tungstenite` within our codebase to access certain TLS functionalities that are privately scoped within the library. This approach is suboptimal as it diverges from the official release, leading to maintenance challenges and security vulnerabilities (TLS dependencies are starting to fall behind).

We should switch the socket dependency to the official `tokio-tungstenite` crate from crates.io, then replace the current TLS implementation with an available alternative, such as `tokio-rustls` or a similar.

First step to investigate this is to change the dependency in the `network` crate `Cargo.toml` to the following:
```
tokio-tungstenite = { version = "0.23.1", features = ["rustls-tls-native-roots"] }
```

You'll then immediately run into this issue (which is why we vendor):
```
error[E0603]: module `tls` is private
  --> network/src/socket.rs:36:5
   |
36 |     tls::tcp_tls,
   |     ^^^ private module
```

This change will reduce the burden of maintaining the custom implementation, and enhance security by relying on official up-to-date crates.

**Comment by VioletSakura-7** [comment]
Do I need to abandon and delete the customized tokio-tungstenite module in the restored directory?

**Comment by cjdsellers** [comment]
Hi @VioletSakura-7

Yes, that vendored dir could be removed once we depend on the official `tokio-tungstenite` crate. There may also be a solution using a different crate as well, but we found some good TLS pieces in there (just private modules we can't depend on without vendoring in all of the code, unfortunate for our use case - but probably the correct design on their part).

**Comment by VioletSakura-7** [comment]
After studying Porting network layer to Rust #1098 and Public encryption module or separate crate for encrypting TcpStream #285, I thought it would be a good idea to separate mod encryption from the tls module in tokio::tungstenite and keep the original socket.rs file unchanged to minimize modifications. I created a new tls.rs file that uses the logic of original tcp_tls function , as follows

```rust
//! Connection helper.
use tokio::io::{AsyncRead, AsyncWrite};


// use tokio_tungstenite::{
//     tungstenite::{
//         client::uri_mode, error::Error, handshake::client::Response, protocol::WebSocketConfig,
//     },
//     MaybeTlsStream,
// };
use tokio_tungstenite::{
    tungstenite::{
        client::IntoClientRequest, 
        stream::Mode,
        handshake::client::{Request, Response},
        Error, 
    },
    MaybeTlsStream,
};

/// A connector that can be used when establishing connections, allowing to control whether
/// `native-tls` or `rustls` is used to create a TLS connection. Or TLS can be disabled with the
/// `Plain` variant.
#[non_exhaustive]
#[derive(Clone)]
pub enum Connector {
   ...
}

mod encryption {
    #[cfg(feature = "native-tls")]
    pub mod native_tls {
        use native_tls_crate::TlsConnector;
        use tokio_native_tls::TlsConnector as TokioTlsConnector;

        use tokio::io::{AsyncRead, AsyncWrite};

        use tokio_tungstenite::tungstenite::{error::TlsError, stream::Mode, Error};

        use tokio_tungstenite::MaybeTlsStream;

        pub async fn wrap_stream<S>(...){
			...
		}
    }

    #[cfg(feature = "__rustls-tls")]
    pub mod rustls {
        pub use rustls::ClientConfig;
        use rustls::RootCertStore;
        use rustls_pki_types::ServerName;
        use tokio_rustls::TlsConnector as TokioTlsConnector;

        use std::{convert::TryFrom, sync::Arc};
        use tokio::io::{AsyncRead, AsyncWrite};

        use tokio_tungstenite::tungstenite::{error::TlsError, stream::Mode, Error};

        use tokio_tungstenite::MaybeTlsStream;

        pub async fn wrap_stream<S>(...){
			...
		}
    }

    pub mod plain {
        use tokio::io::{AsyncRead, AsyncWrite};

        use tokio_tungstenite::tungstenite::{
            error::{Error, UrlError},
            stream::Mode,
        };

        use tokio_tungstenite::MaybeTlsStream;

        pub async fn wrap_stream<S>(socket: S, mode: Mode) -> Result<MaybeTlsStream<S>, Error>
        where
            S: 'static + AsyncRead + AsyncWrite + Send + Unpin,
        {
            match mode {
                Mode::Plain => Ok(MaybeTlsStream::Plain(socket)),
                Mode::Tls => Err(Error::Url(UrlError::TlsFeatureNotEnabled)),
            }
        }
    }
}

pub async fn tcp_tls<S>(
    request: &Request,
    mode: Mode,
    stream: S,
    connector: Option<Connector>,
) -> Result<MaybeTlsStream<S>, Error>
where
    S: 'static + AsyncRead + AsyncWrite + Send + Unpin,
    MaybeTlsStream<S>: Unpin,
{
    #[cfg(any(feature = "native-tls", feature = "__rustls-tls"))]
    let domain = crate::domain(request)?;

    match connector {
        Some(conn) => match conn {
            #[cfg(feature = "native-tls")]
            Connector::NativeTls(conn) => {
                self::encryption::native_tls::wrap_stream(stream, domain, mode, Some(conn)).await
            }
            #[cfg(feature = "__rustls-tls")]
            Connector::Rustls(conn) => {
                self::encryption::rustls::wrap_stream(stream, domain, mode, Some(conn)).await
            }
            Connector::Plain => self::encryption::plain::wrap_stream(stream, mode).await,
        },
        None => {
            #[cfg(feature = "native-tls")]
            {
                self::encryption::native_tls::wrap_stream(stream, domain, mode, None).await
            }
            #[cfg(all(feature = "__rustls-tls", not(feature = "native-tls")))]
            {
                self::encryption::rustls::wrap_stream(stream, domain, mode, None).await
            }
            #[cfg(not(any(feature = "native-tls", feature = "__rustls-tls")))]
            {
                self::encryption::plain::wrap_stream(stream, mode).await
            }
        }
    }
}



```

​	This allows us to wrap TCP streams with tls in socket.rs using custom logic that is exactly the same as in tokio::tungstenite, while other modules such as http and websocket rely on official libraries. So I added the dependency of the official tokio::tungstenite library 0.23.1 

```
tokio-tungstenite = { version = "0.23.1", features = ["rustls-tls-native-roots"] }
```

and deleted the original custom network/tokio-tungstenite package and tried cargo test and succeeded.
<img width="928" alt="截屏2024-09-07 20 47 52" src="https://github.com/user-attachments/assets/7e5ed999-2ec6-4478-940c-6d5a12a2db1d">

**Comment by cjdsellers** [comment]
Hi @VioletSakura-7

Thanks so much for digging into that!

I think it's a nice solution to use a separate `tls.rs` module which mirrors the `tokio-tungstenite` approach. I had to add a couple of their own dependencies too such as `rustls` and `tokio-rustls` (these were being pulled in as transitive dependencies already anyway), but your post made this process seamless.

Now completed from commit af52b9df6e2fc8e3c333a8ede416bfac997f8ca6 on `develop` branch, and credited you in the release notes :pray:.
