### ISSUE TITLE
Multiplier parameter for CryptoPerpetual

### ISSUE THREAD

**Issue by miller-moore** [nautechsystems/nautilus_trader#1912]
# Feature Request

This is a feature request to add `Quantity multiplier` as a parameter to ``CryptoPerpetual``, defaulting to 1 (which is currently hardcoded in its construction). OKX is an example of a venue whose perp contracts vary in the amount of base currency each contract represents (e.g., BTC-USDT-SWAP is worth 0.01 BTC per perp contract).

**Comment by cjdsellers** [comment]
Hey @miller-moore 

Good suggestion, I also standardized a couple of other things along the way.

Now added from commit 73df6b411af2a2f558544dd8b50d5369c9dd144b on `develop` branch - and will be in the next release.
