### ISSUE TITLE
Binance extras likely missing 'pynacl'

### ISSUE THREAD

**Issue by TradingMax** [nautechsystems/nautilus_trader#1917]
# Bug Report

### Expected Behavior
Able to use 
..\nautilus_trader\adapters\binance\http\client.py
when installing with binance extra

### Actual Behavior
Error `ModuleNotFoundError: No module named 'nacl'`

### Steps to Reproduce the Problem

1. Install `pip install nautilus_trader[binance]`
2. run `import nautilus_trader.adapters.binance.http.client`

Likely missing pynacl from extras in pyproject.toml
probably need - `binance = ["pycryptodome", "pynacl"]`

### Specifications

- OS platform: Windows
- Python version: 3.12
- `nautilus_trader` version: 1.200.0

**Comment by cjdsellers** [comment]
Hi @TradingMax

Thanks for the report!

This has now been addressed from commit 811c9eec1c20f244153e67e4152a7ac2176d8dcb on `develop` branch. We’ve moved the cryptographic signing to Rust, removing the Python dependencies related to Binance.

This will make it out into the next release, which will be very soon.
