### ISSUE TITLE
Add OKX Support

### ISSUE THREAD

**Issue by Crypto7816** [nautechsystems/nautilus_trader#1932]
# Feature Request

Hi, team

Great project! I'm planning to add support for the OKX exchange. I have experience integrating with OKX, and I've already connected their websocket in my own project. I'm curious if you guys are planning to support OKX as well. Can I contribute?

Best,

River

**Comment by Crypto7816** [comment]
I am currently developing an OKX WebSocket client, which I plan to divide into two parts: private and public, similar to Bybit.

Public link: [public ws](https://www.okx.com/docs-v5/en/#order-book-trading-market-data-ws-order-book-channel)  
Private account link: [private account ws](https://www.okx.com/docs-v5/en/#trading-account-websocket)  
Private order update link: [private order ws](https://www.okx.com/docs-v5/en/#order-book-trading-trade-ws-order-channel)  

For the public link, I will implement:

```
async def subscribe_order_book(self, symbol: str, channel: int) -> None:
async def subscribe_trades()
async def subscribe_candlestickers(self, symbol: str, interval: str) -> None: # or we can call it klines 
async def subscribe_tickers(self, symbol: str) -> None:
```

For the private link, I will implement:

```
async def subscribe_account_update()
async def subscribe_position_update()
async def subscribe_orders_update()
```

Is it reasonable to implement these methods? I would appreciate your advice.

**Comment by vec715** [comment]
hi, any news on this? thanks @Crypto7816 for your idea and work on this area, but looks like we didnt get any feedback from maintainers?

**Comment by cjdsellers** [comment]
Hi @vec715

The initial OKX adapter has actually landed on `develop` branch.

There was also a conversation in the discord server and a dedicated `#okx` channel there, but I should have followed up and closed this issue.
