### ISSUE TITLE
Bar subscription broken upon reconnection with Interactive Brokers

### ISSUE THREAD

**Issue by FGU1** [nautechsystems/nautilus_trader#1933]
# Bug Report
Connected to IB, and subscribing to bar : if the TWS / GW restart (nightly auto restart or manual) NT reconnect but bar subscription is broken. 

### Expected Behavior
bar subscription not broken by a TWS/GW restart

### Actual Behavior
bar subscription is broken by a TWS/GW restart. 
Latest release tested with : pip install "nautilus_trader[ib]"
See attached logs

### Steps to Reproduce the Problem

1.  pip install "nautilus_trader[ib]" then use examples/live/interactive_brokers/connect_with_tws.py and modify it to subscribe to bar only or use attached file.
2. Connect to TWS or GW
3. Wait for nightly restart or restart manually (in TWS, this can be done with file/restart)

### Specifications

- OS platform: Debian 12
- Python version: 3.11.2
- `nautilus_trader` version: 
     nautilus-ibapi==10.19.4
     nautilus-trader==1.201.0

[bars_restart.log](https://github.com/user-attachments/files/16991657/bars_restart.log)

[example_IB_live_data_bars.py.txt](https://github.com/user-attachments/files/16991875/example_IB_live_data_bars.py.txt)

**Comment by rsmb7z** [comment]
Hi @FGU1,
Fix has been merged, closing this issue.
