### ISSUE TITLE
 Improve StreamingFeatherWriter to support file rotation and better time management

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#1945]
## Issue Description
The current `StreamingFeatherWriter` class lacks file rotation functionality, which may lead to oversized files during long-running operations or high data volume scenarios. Additionally, there's room for improvement in time management and file naming.

## Suggested Improvements
1. Implement file rotation functionality, supporting rotation based on size, time interval, and scheduled dates.
2. Use a `Clock` object for time management to improve flexibility and testability.
3. Add timestamps to filenames for better organization and identification.
4. Track file sizes and creation times to support rotation functionality and provide more information.
5. Add methods to query current file information and next rotation time.

## Expected Benefits
- Better file management, avoiding oversized single files.
- Improved system reliability and performance.
- More flexible time handling, facilitating testing and simulation of different time zones.
- Better file organization and information query capabilities.

## Related Files
- `nautilus_trader/persistence/writer.py`

**Comment by cjdsellers** [comment]
Implemented in #1954, many thanks @graceyangfan!
