### ISSUE TITLE
logging configuration bug

### ISSUE THREAD

**Issue by xt2014** [nautechsystems/nautilus_trader#1955]
In version v1.197, the logging configuration is not effective. Whether modifying the log_level or configuring log_level_file, the configuration for log_level_file does not generate a file, and even after changing the log_level, it still remains at the default log_level.

**Comment by cjdsellers** [comment]
Hi @xt2014

Thanks for the report.

Closing this as its a known and repaired bug. Latest release is v1.201.0.

**Comment by xt2014** [comment]
That's so unfortunate，upgrading to versions above 1.198 causes bugs due to numpy 2.0, and this issue still hasn't been resolved. But version 1.197 also has bugs. I can't upgrade, nor can I stay with the current version

**Comment by cjdsellers** [comment]
Hi @xt2014

I understand, which Python package or environment are you using where numpy 2.x causes an issue?

**Comment by cjdsellers** [comment]
We may have uncovered a new bug here, could you try setting `use_pyo3` to `False` in the `LoggingConfig`, and see if a log file is produced?

**Comment by xt2014** [comment]
I found that after upgrading to v1.201, when I wanted to check the numpy issue by setting log_level to debug, I was surprised to discover that, just like in v1.197, log_level is ineffective and the log_file cannot be generated

**Comment by xt2014** [comment]
> We may have uncovered a new bug here, could you try setting `use_pyo3` to `False` in the `LoggingConfig`, and see if a log file is produced?我们可能在这里发现了一个新的错误，您可以尝试在`LoggingConfig`中将`use_pyo3`设置为`False` ，看看是否生成日志文件？
> 
> [edit]: Definitely a bug is confirmed here, which is when `use_pyo3` is set, we weren't passing through the `level_file` to the `init_logging` function. Will be fixed on `develop` branch soon and make it into the next release. I'll credit you with the report in the release notes.[编辑]：这里肯定确认了一个错误，即当设置`use_pyo3`时，我们没有将`level_file`传递给`init_logging`函数。很快就会在`develop`分支上修复并进入下一个版本。我会将发行说明中的​​报告归功于您。
> 
> In the mean, time setting `use_pyo3` to `False` may fix this issue for you.也就是说，将`use_pyo3`设置为`False`可能会为您解决此问题。



> We may have uncovered a new bug here, could you try setting `use_pyo3` to `False` in the `LoggingConfig`, and see if a log file is produced?
> 
> [edit]: Definitely a bug is confirmed here, which is when `use_pyo3` is set, we weren't passing through the `level_file` to the `init_logging` function. Will be fixed on `develop` branch soon and make it into the next release. I'll credit you with the report in the release notes.
> 
> In the mean, time setting `use_pyo3` to `False` may fix this issue for you.

i found that the init value is false，and i has not set it

**Comment by xt2014** [comment]
I found the reason. I registered a logger using logger = init_logging() before configuring BacktestEngineConfig

**Comment by xt2014** [comment]
when "from nautilus_trader.indicators.ta_lib.manager import TALibIndicatorManager, TAFunctionWrapper",numpy 2.x causes an issue

**Comment by cjdsellers** [comment]
Others have also run into numpy compatibility issues. We've now relaxed the numpy version requirement to `>=1.26.4` on `develop` branch and for the next release.
