### ISSUE TITLE
time_bars_interval_type in DataEngineConfig doesn't work

### ISSUE THREAD

**Issue by DeevsDeevs** [nautechsystems/nautilus_trader#1979]
# Bug Report

### Expected Behavior
Determines the type of interval used for time aggregation.
        - 'left-open': start time is excluded and end time is included (default).
        - 'right-open': start time is included and end time is excluded.
if value is invalid -> throw error

### Actual Behavior
If invalid value is passed, nothing happens
If right-open is passed, still nothing happens
=> time_bars_interval_type doesn't affect anything, because TimeBarAggregator doesn't receive it

### Steps to Reproduce the Problem

1. download [this](https://data.binance.vision/data/futures/um/daily/klines/ETHUSDT/5m/ETHUSDT-5m-2024-09-01.zip) binance data 
2. convert it and add to nautilus
```python
bar_spec = BarSpecification(
    step=5,
    aggregation=BarAggregation.MINUTE,
    price_type=PriceType.LAST,
)
bar_type = BarType(
    instrument_id=instrument.id,
    bar_spec=bar_spec,
    aggregation_source=AggregationSource.EXTERNAL,
)
bar_wrangler = BarDataWrangler(instrument=instrument, bar_type=bar_type)
bars_df = pd.read_feather(file_path)
bars_df['timestamp'] = pd.to_datetime(bars_df['close_time'], unit='ms')
bars_df.set_index('timestamp', inplace=True)
bars_df.sort_index(inplace=True)
bars_df['volume'] = bars_df['quote_volume']
bars = bar_wrangler.process(
    data=bars_df[["open", "high", "low", "close", "volume"]],
    default_volume = 0,
)
```
3. run backtest with this config
```python
engine_config = BacktestEngineConfig(
    trader_id=TraderId("BACKTESTER-001"),
    logging=LoggingConfig(log_level="INFO"),
    strategies=[
        ImportableStrategyConfig(
            strategy_path="strategy.strategy:MidfreqDailyStrategy",
            config_path="strategy.strategy:MidfreqDailyStrategyConfig",
            config={
                "instruments_ids": instruments_ids,
            },
        )
    ],
    data_engine=DataEngineConfig(
        time_bars_timestamp_on_close = True,
        time_bars_interval_type = "right-open",
        debug=True
    )
)

run_config = BacktestRunConfig(
    engine=engine_config,
    venues=venue_configs,
    data=data_configs,
)
```
4. add bar log on_bar
expected:
get first bar at 2024-09-01T00:04:59.999000000 with ts_event of 2024-09-01T00:00:00

actual:
nothing changed with any value of time_bars_interval_type

### Specifications

- Python version: 3.12
- `nautilus_trader` version: 1.203

**Comment by DeevsDeevs** [comment]
So as i can see `time_bars_interval_type` is only used if aggregation_source is INTERNAL

In this case i have a question: how to achieve in backtesting with EXTERNAL data this kind of behaviour?

And same question for request_bars

(so maybe it's not a bug yet)

**Comment by cjdsellers** [comment]
Hi @DeevsDeevs

Thanks for your feedback.

You're correct in that this configuration applies to how bars are internally aggregated. I'm not sure it makes sense for externally aggregated bars - as by definition, they are already aggregated. So modifying the interval timestamps wouldn't be valid because the prices may not be correct and we've already lost that information during the aggregation.

Your best bet is to provide the backtest with trades, and then use internal aggregation and configure `DataEngineConfig` per your desired interval type.

I hope that helps!
