### ISSUE TITLE
Websocket Rust client keeps sending ping messages after connection is closed

### ISSUE THREAD

**Issue by davidsblom** [nautechsystems/nautilus_trader#1980]
# Bug Report

### Expected Behavior
The websocket automatically reconnects or the heartbeat task is canceled. The dYdX client has called the `disconnect()` method, but the heart beat task keeps running in the background.

### Actual Behavior
The websocket is closed by the venue:
```
nautilus_network::websocket: Received error message - terminating: WebSocket protocol error: Connection reset without closing handshake
```
The heartbeat task keeps sending ping messages which continuously fails. This is the first error message.
```
[1m2024-10-02T22:20:15.323098159Z[0m [ERROR] FIREHOSE-SPOT-001.nautilus_network::websocket: Error sending ping: Trying to work with closed connection
```
Somewhat later, the logs contain the same error message multiple times (at every ping interval)
```
1m2024-10-02T22:20:45.832380494Z[0m [ERROR] FIREHOSE-SPOT-001.nautilus_network::websocket: Error sending ping: WebSocket protocol error: Sending after closing is not allowed
```

The dYdX websocket client detects that ping messages are not being received anymore, and goes through a reconnection cycle called by `_reconnect_ping()`. That works successfully fortunately, but the heartbeat task of the previous websocket client is still running in the background.

### Specifications

- OS platform: AWS Fargate, Linux Docker
- Python version: 3.11
- `nautilus_trader` version: develop branch

**Comment by davidsblom** [comment]
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/4b1b3229-e46e-4de0-8613-5e8328af14ab">

**Comment by davidsblom** [comment]
Looking at the rust code in the `spawn_controller_task`, there seems to be a missing implemented for an edge case where `disconnected` is `True` and `inner.is_alive()` is `false`.

https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_core/network/src/websocket.rs#L447

offtopic, but this debug message is wrong: https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_core/network/src/websocket.rs#L437

**Comment by cjdsellers** [comment]
Hi @davidsblom

Thanks for the report. This is partially fixed from dc1f18c70696b141c7102b4b6fb37952176ec075 and we'll address the ping behavior soon.

**Comment by davidsblom** [comment]
Awesome!

**Comment by twitu** [comment]
It's indeed quite an edge case. The #1981 is a fix that cleans up background tasks even if the network client is not alive. Please see if this fixes the issue for you.

**Comment by davidsblom** [comment]
Great! I'll test it later today.

**Comment by davidsblom** [comment]
Seems to work fine with the latest change. Not sure if I hit this specific edge case, but it used to be easy to break it. Now I didn't manage that :)
