### ISSUE TITLE
Multiple subscription/reconnection attempts every second by BinanceWebSocketClient

### ISSUE THREAD

**Issue by rubenmarias** [nautechsystems/nautilus_trader#1989]
# Bug Report
At some point when running an instance subscribed to Binance data (have seen it both with trades and quotes/orderbooks) there begin to appear a lot of reconnection attempts in the logs by the `BinanceWebSocketClient`.

After approximately 48 hours of normal operation with order submission, matching and cancellation without issue, this message sequence starts being logged about 4-5 times per second:

```
[2024-09-23T23:52:00.171471582Z [WARN] BINANCE_TRADING-001.BinanceWebSocketClient: Reconnected to wss://stream.binance.com:9443

[2024-09-23T23:52:00.516207484Z [DEBUG] BINANCE_TRADING-001.BinanceWebSocketClient: SENDING: {'method': 'SUBSCRIBE', 'params': ['redacted_listen_key_can_share_if_needed'], 'id': 0}

[2024-09-23T23:52:00.516650502Z [DEBUG] BINANCE_TRADING-001.BinanceWebSocketClient: Subscribed to redacted_listen_key_can_share_if_needed
```

### Expected Behavior
Reconnection occurs when Binance websocket stream expires, e.g. every 12/24 hours.

### Actual Behavior
Multiple reconnections occurring each second.

### Steps to Reproduce the Problem

1. Start a trading node subscribed to Binance market data
2. Wait ~48 hours
3.

### Specifications

- OS platform: Ubuntu 20.04
- Python version: 3.12.1
- `nautilus_trader` version: 1.201.0

**Comment by cjdsellers** [comment]
Hey @rubenmarias

Thanks for the report.

There have actually been some recent changes related to the `WebSocketClient`, including reconnect behavior. We'd really need you to be on v1.203.0 (latest release) or even v1.204.0 on `develop` branch to be able to investigate this further - as I think this has been addressed specifically already.

Closing this ticket for now, but if you can confirm the issue still exists, then I'll re-open.
