### ISSUE TITLE
Websocket panic when calling unwrap on the writer

### ISSUE THREAD

**Issue by davidsblom** [nautechsystems/nautilus_trader#1992]
# Bug Report

The reader of the websocket terminates after receiving an error message. 
When trying to reconnect, the writer is in some kind of error state too.

```
[1m2024-10-09T17:46:21.039591189Z[0m [1;33m[WARN] FIREHOSE-SPOT-001.Throttler-dydx_websocket_subscribe_throttler: Buffering {'type': 'subscribe', 'channel': 'v4_orderbook', 'id': 'SOL-USD', 'batched': True}[0m
--
[1m2024-10-09T17:47:21.040495687Z[0m [1;33m[WARN] FIREHOSE-SPOT-001.Throttler-dydx_websocket_subscribe_throttler: Buffering {'type': 'subscribe', 'channel': 'v4_orderbook', 'id': 'SOL-USD', 'batched': True}[0m
[1m2024-10-09T17:48:13.283701232Z[0m [ERROR] FIREHOSE-SPOT-001.nautilus_network::websocket: Received error message - terminating: IO error: Connection reset by peer (os error 104)[0m
thread 'tokio-runtime-worker' panicked at network/src/websocket.rs:252:34:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

This happened on the `develop` branch with commit `17411b9451f01b3d9c19139723de2e1c79806f53`

Here is a link to the source code:
https://github.com/nautechsystems/nautilus_trader/blob/17411b9451f01b3d9c19139723de2e1c79806f53/nautilus_core/network/src/websocket.rs#L252

### Expected Behavior
The writer is closed by handling the error. The connection with the websocket is reestablished as usual.

### Actual Behavior
rust panic resulting in a crash of the Python application.

### Specifications

- OS platform: AWS Fargate, Docker, Linux
- Python version: 3.11
- `nautilus_trader` version: develop branch, commit `17411b9451f01b3d9c19139723de2e1c79806f53`

**Comment by cjdsellers** [comment]
Hi @davidsblom

Thanks for the report!

This is now fixed from commit c5d2841284be3da6735ef5176fb47ee9513cd1c7. Instead of unwrapping, we just log the error for now. I also audited for any other unwraps across all of the network clients and there were only a couple of others in header parsing which we just propagate up now too.
