### ISSUE TITLE
Multiple subscription/reconnection attempts every second by BinanceWebSocketClient 

### ISSUE THREAD

**Issue by rubenmarias** [nautechsystems/nautilus_trader#2019]
Based on https://github.com/nautechsystems/nautilus_trader/issues/1989 

# Bug Report
At some point when running an instance subscribed to Binance data (have seen it both with trades and quotes/orderbooks) there begin to appear a lot of reconnection attempts in the logs by the `BinanceWebSocketClient`.

After approximately 48 hours of normal operation with order submission, matching and cancellation without issue, this message sequence starts being logged about 4-5 times per second:

```

[DEBUG] BINANCE_TRADING-001.ExecEngine: Checking in-flight orders status...

[DEBUG] BINANCE_TRADING-001.ExecEngine: Found 0 orders in-flight

[DEBUG] BINANCE_TRADING-001.ExecEngine: Checking in-flight orders status...

[DEBUG] BINANCE_TRADING-001.ExecEngine: Found 0 orders in-flight

[2024-09-23T23:52:00.171471582Z [WARN] BINANCE_TRADING-001.BinanceWebSocketClient: Reconnected to wss://stream.binance.com:9443

[2024-09-23T23:52:00.516207484Z [DEBUG] BINANCE_TRADING-001.BinanceWebSocketClient: SENDING: {'method': 'SUBSCRIBE', 'params': ['redacted_listen_key_can_share_if_needed'], 'id': 0}

[2024-09-23T23:52:00.516650502Z [DEBUG] BINANCE_TRADING-001.BinanceWebSocketClient: Subscribed to redacted_listen_key_can_share_if_needed
```

### Expected Behavior
Reconnection occurs when Binance websocket stream expires, e.g. every 12/24 hours.

### Actual Behavior
Multiple reconnections occurring each second.

### Steps to Reproduce the Problem

1. Start a trading node subscribed to Binance market data
2. Wait ~48 hours
3.

### Specifications

- OS platform: Ubuntu 20.04
- Python version: 3.12.1
- `nautilus_trader` version: 1.201.0

**Comment by cjdsellers** [comment]
Per discussion on discord, closing this for now as it doesn't seem to be a code issue which other users are encountering. Potentially rate limit or network related?

Feel free to update this issue with any further findings, and we can always reopen it if it turns out to be a bug.

**Comment by rubenmarias** [comment]
Adding some additional logs including rust logs, it seems an error is occurring in one of the handlers called during reconnection: 

> 2024-11-01T09:20:13.663209706Z [WARN] MARKET_RECORDER-001.BinanceWebSocketClient: Reconnected to wss://stream.binance.com:9443
> 2024-11-01T09:20:13.663225Z DEBUG nautilus_network::websocket: Called `post_reconnection` handler
> 2024-11-01T09:20:13.859129Z ERROR nautilus_network::websocket: Error calling handler: ValidationError: Object missing required field `stream`
> 2024-11-01T09:20:13.865264Z DEBUG nautilus_network::websocket: Closing connection
> 2024-11-01T09:20:13.865284Z DEBUG nautilus_network::websocket: Aborted heartbeat task
> 2024-11-01T09:20:13.865288Z DEBUG nautilus_network::websocket: Closing writer
> 2024-11-01T09:20:13.865331Z DEBUG nautilus_network::websocket: Closed connection
> 2024-11-01T09:20:13.888451Z DEBUG nautilus_network::websocket: Started task 'read'
> 2024-11-01T09:20:13.888470Z DEBUG nautilus_network::websocket: Started task 'heartbeat'
> 2024-11-01T09:20:13.888482Z DEBUG nautilus_network::websocket: Reconnected successfully
> 2024-11-01T09:20:13.888565384Z [WARN] MARKET_RECORDER-001.BinanceWebSocketClient: Reconnected to wss://stream.binance.com:9443
> 2024-11-01T09:20:13.888583Z DEBUG nautilus_network::websocket: Called `post_reconnection` handler
**> 2024-11-01T09:20:14.051108Z ERROR nautilus_network::websocket: Error calling handler: ValidationError: Object missing required field `stream`**
> 2024-11-01T09:20:14.091491Z DEBUG nautilus_network::websocket: Closing connection
> 2024-11-01T09:20:14.091568Z DEBUG nautilus_network::websocket: Aborted heartbeat task
> 2024-11-01T09:20:14.091573Z DEBUG nautilus_network::websocket: Closing writer
> 2024-11-01T09:20:14.091637Z DEBUG nautilus_network::websocket: Closed connection
> 2024-11-01T09:20:14.115146Z DEBUG nautilus_network::websocket: Started task 'read'
> 2024-11-01T09:20:14.115165Z DEBUG nautilus_network::websocket: Started task 'heartbeat'
> 2024-11-01T09:20:14.115399Z DEBUG nautilus_network::websocket: Reconnected successfully
> 2024-11-01T09:20:14.115564074Z [WARN] MARKET_RECORDER-001.BinanceWebSocketClient: Reconnected to wss://stream.binance.com:9443
