### ISSUE TITLE
How to apply a strategy with multiple timeframes?

### ISSUE THREAD

**Issue by shiniantianlang** [nautechsystems/nautilus_trader#204]
I wonder if nautilus_trader could support the strategy which has multiple timeframes (eg. both daily and minute data)？

**Comment by cjdsellers** [comment]
Hi @shiniantianlang 

The platform can absolutely handle this. All you need to do is specify your required `BarSpecification`s when you subscribe to bars.

For example;
`1min_bars = BarSpecification(1, BarAggregation.MINUTE, PriceType.LAST)`
`1day_bars = BarSpecification(1, BarAggregation.DAY, PriceType.LAST)`

These specs can then form `BarType` with a particular symbol.
Then pass these bar types into; 

`self.subscribe_bars(BarType(your_symbol, 1min_bars))`
`self.subscribe_bars(BarType(your_symbol, 1day_bars))`

Then the strategy will receive those bars into the `on_bar` method when they are produced. So any combination can be subscribed to and handled within the same strategy.

This also works for requesting historical data.

If you're trading live and have trouble with data not being available or supported try;
`self.subscribe_bars(BarType(your_symbol, 1day_bars, is_internal_aggregation=False))`

Which will get the data directly from the exchange instead (both for requests and subscriptions).

Note that the keyword `is_internal_aggregation` is changing to `internal_aggregation` in the next version. Default value is `True`.

Please let me know if you need any further help.

**Comment by shiniantianlang** [comment]
Got it ! Thank you so much!
