### ISSUE TITLE
dydx orderbook handling not working as expected 

### ISSUE THREAD

**Issue by omencat** [nautechsystems/nautilus_trader#2075]
# Bug Report

### Expected Behavior
Proper orderbook is maintained. bids are lower than asks

### Actual Behavior
For most of my observations comparing with the dydx webui, it looks like the bid appears to get stuck at a higher tick.

### Steps to Reproduce the Problem

1. subscribe to quote ticks, order_book_deltas with L2_MBP
2. listen on `on_quote_tick`
3. see snippet below for debugging

### Specifications

- OS platform: macos 15.1.1
- Python version: 3.12.7
- `nautilus_trader` version: `nautilus-trader[dydx]>=1.206.0`

```py
    def on_quote_tick(self, tick: QuoteTick) -> None:
        """
        Actions to be performed when a delta is received.
        """
        if tick.bid_price >= tick.ask_price:
            self.log.info(f"on_quote_tick: crossed: b={tick.bid_price} a={tick.ask_price}")

```

output. Note I used OrderBookImbalance strategy as a starting point.
```
2024-11-25T23:22:29.794935001Z [INFO] dydx-001.OrderBookStats: on_quote_tick: crossed: b=3465.3 a=3459.3
2024-11-25T23:22:30.042432001Z [INFO] dydx-001.OrderBookStats: on_quote_tick: crossed: b=3465.3 a=3459.3
2024-11-25T23:22:30.545192001Z [INFO] dydx-001.OrderBookStats: on_quote_tick: crossed: b=3465.3 a=3459.3
2024-11-25T23:22:32.325153001Z [INFO] dydx-001.OrderBookStats: on_quote_tick: crossed: b=3459.1 a=3459.0
2024-11-25T23:22:32.577644001Z [INFO] dydx-001.OrderBookStats: on_quote_tick: crossed: b=3459.1 a=3459.0
2024-11-25T23:22:33.880946001Z [INFO] dydx-001.OrderBookStats: on_quote_tick: crossed: b=3459.1 a=3459.1
2024-11-25T23:22:34.414633001Z [INFO] dydx-001.OrderBookStats: on_quote_tick: crossed: b=3459.1 a=3458.4
2024-11-25T23:22:34.664993001Z [INFO] dydx-001.OrderBookStats: on_quote_tick: crossed: b=3459.1 a=3458.3

```

**Comment by davidsblom** [comment]
I have noticed this as well. The order book snapshots are requested every minute. We could make that configurable. Another option is to only add quotes to the data engine if they are valid? 
@cjdsellers what do you think is the best approach?

**Comment by davidsblom** [comment]
There is a pull request in the dYdX v4-clients repo which "resolves" the order book by adding missing deltas when the book is crossed.

https://github.com/dydxprotocol/v4-clients/pull/265/files#diff-4ac5027057a58c15a33fddfc7f9c406a76f9235d7b7455aea9283efdbeb87b81R91

This shows that it is an issue with the messages sent by the venue.

@cjdsellers  we could implement similar logic in the dYdX adapter. What are your thoughts, or do you see any side effects?

**Comment by cjdsellers** [comment]
Hi @omencat and @davidsblom

I'll leave it to your discretion to confirm if this is indeed an issue with the venue.

In any case, there is either an issue with our current parsing logic, or with the sequence of messages being emitted by the venue.
Assuming it is a venue issue - then I think we have to add some kind of processing logic to maintain correct book state?

**Comment by omencat** [comment]
Yeah, they expect you to uncross due to there not being a global CLOB. https://docs.dydx.exchange/api_integration-guides/how_to_uncross_orderbook

> v4 doesn't guarantee that order book prices don't cross because there is no centralized order book. For that reason, the software does not include a global offset. The “correct” order book at any given time is whatever the current block proposer has in its mempool, which is not what the indexer or the front end can directly see...
...If the trader doesn’t need the order book prices uncrossed, simply listen to the updates given by the websocket and they should uncross eventually.

Note thats for grpc listening on a full node. But still needs to be done on websocket to maintain an uncrossed book.

Thanks for the update!

**Comment by cjdsellers** [comment]
Yeah, that actually makes sense then because there's no CLOB.

Thanks again for reaching out @omencat
