### ISSUE TITLE
FuturesContract - Add missing margin and fee parameters to Python

### ISSUE THREAD

**Issue by stefansimik** [nautechsystems/nautilus_trader#2112]
The Python implementation of `FuturesContract` is missing several important parameters that exist in its Rust/PyO3 counterpart. This creates an inconsistency between the two implementations that should be addressed.

Current State:
The Python `FuturesContract` class does not include the following parameters that are present in the PyO3 version:
- `margin_init`
- `margin_maint` 
- `maker_fee`
- `taker_fee`

These parameters are defined and accessible in the PyO3 implementation at `nautilus_trader/core/nautilus_pyo3/model/FuturesContract.py`, but cannot be set when constructing a FuturesContract using the Python implementation.

![CleanShot_2024-12-13_at_23 29 572x](https://github.com/user-attachments/assets/d1f208a2-1e89-4f05-b905-6b00c6bdbd16)

**Impact:**
This inconsistency means that margin and fee information cannot be properly initialized for futures contracts when using the Python implementation, which could affect margin calculations and fee modeling in trading strategies.

**Notes from Discord:**
- Similar discrepancies exist in at least 4 other instrument implementations
- This relates to the broader discussion about margin and fee modeling in the system

**Comment by cjdsellers** [comment]
Hi @stefansimik

Thanks for raising the issue.

Per the [Discord discussion](https://discord.com/channels/924497682343550976/924499913386102834/1317380848059678741), these were left off when we intended to redesign the margin and fee modeling - but for now I agree we should align the Python and Rust implementations, and add these missing params.

**Comment by cjdsellers** [comment]
Now implemented from 2a6aab08c5094e0796085d75fcf80356ee1a7adc.
