### ISSUE TITLE
Standardize Strategy configuration pattern

### ISSUE THREAD

**Issue by stefansimik** [nautechsystems/nautilus_trader#2114]
## Background
Currently, most strategy examples copy config values into strategy attributes:

```python
class TimeBasedStrategy(Strategy):
    def __init__(self, config: TimeBasedStrategyConfig):
        self.primary_bar_type = config.primary_bar_type   # HERE: Copying config data (in next 3 lines)
        self.trade_size = config.trade_size
        self.timezone = config.timezone
    
    def on_start(self):
        self.subscribe_bars(self.primary_bar_type)        # HERE: referencing copied attribute of strategy 
```

However, using the config object directly provides better separation of concerns:

```python
class TimeBasedStrategy(Strategy):
    def __init__(self, config: TimeBasedStrategyConfig):
        self.config = config

    def on_start(self):
        self.subscribe_bars(self.config.primary_bar_type)  # HERE - using `config` directly
```

While both approaches are valid, standardizing on direct config usage will improve code clarity and maintainability.

## Proposal
Standardize on using direct config usage pattern (`self.config`) in examples and documentation because it:

1. Clearly separates input configuration from other state-keeping variables `Strategy`
2. Reduces code duplication
3. Aligns with upcoming Rust implementation
4. Makes it clearer where configuration values originate
5. Results in cleaner, more maintainable code

## Implementation Tasks
- [x] Update all example strategies to use direct config pattern
- [x] Update documentation to reflect this pattern
- [x] Add note clarifying that config isn't required (attributes can still be assigned directly)

**Comment by cjdsellers** [comment]
Hi @stefansimik 

Thanks for raising the issue.

Per the [Discord discussion](https://discord.com/channels/924497682343550976/924506736927334400/1317602178919170088), I think this is a cleaner approach and will standardize with the Rust side.

One refinement is that the [config attribute](https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/common/actor.pyx#L134) from the `Actor` base class can be used through `self.config`. This is assigned from the `config` passed in during init `super().__init__(config)`.

Many thanks for your help on this :pray:.

**Comment by stefansimik** [comment]
Hi @cjdsellers 
ready to send PR. 

Doing it for the first time here (and after longer time of not sending any PR on github,
so just to make sure everything goes smoothly.... any recommendations?

- It is just 1 commit 
-    - https://github.com/nautechsystems/nautilus_trader/compare/develop...stefansimik:nautilus_trader:develop)
- right now I am on branch "develop" - is it OK or should I create separate branch for this specific issue (maybe called `issue-2214`)

This is just one-time question, next time I will know :-)

**Comment by cjdsellers** [comment]
Apologies, I should have mentioned the pre-commit. Details in the `CONTRIBUTING.md` or maybe an environment setup doc.
