### ISSUE TITLE
Decision to remove Rust

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#224]
I'm documenting the decision to remove Rust from the `nautilus_trader` codebase.

After spending weeks attempting to come up with the optimal integration solution I've decided that the increase in complexity with including another language in the tool/build chain is not worth it.

Getting Rust objects to be C ABI and FFI compatible was involving alot of raw pointer mangling which in turn required large blocks of code marked `unsafe` in Rust-land. Because of this one of the main value propositions of Rust (memory-safety) was being compromised, with a rising potential for memory leaks as data was being exchanged across the Python <-> Rust boundary.

I still believe there is huge potential in the Rust language, and will continue to work with it. However not at this stage attempting to splice it into the Python runtime. I think its far safer and simpler to utilize the language with other services across a serialized message boundary, with a greenfield codebase written entirely in Rust and no unsafe external C calls. For example to build a data aggregator, smart-order-router or centralized execution engine which can handle messages from many nautilus_trader boxes.

For the performance goals of the platform - Cython is a more than adequate tool, allowing direct access to the underlying CPython API, with plenty of potential still to be unlocked.

**Comment by jpmediadev** [comment]
just finished reading the book) 

 it is better to use rust on its own for individual applications without integration 

i wrote on Rust,  part data_producer.pyx what reads parses and iterate tardis csv.gz - performance 10x against current cython and pandas

**Comment by cjdsellers** [comment]
Good work getting through the book and up and running with Rust to this level so fast!

The problem is that `String` and especially a lot of the members of `Producer` (even `Vec`) are complex types and can't be made compatible with any C memory layout (without using indirection through raw pointers), which means this code can't share the Python runtime with NautilusTrader. 

So it would have to be a separate application and process passing its data in some way such as serialization. This is where I came to the conclusion Rust works better when it doesn't need to be compatible with C, and if it needs its own application that may as well be separate from NautilusTrader.

**Comment by jpmediadev** [comment]
in love with rust 

how expressive everything is with tests in one place 

 https://github.com/jpmediadev/nautilus_trader/blob/develop/emun_in_rust.rs

**Comment by cjdsellers** [comment]
I had a feeling you'd like it. Very nice ;)

**Comment by jpmediadev** [comment]
Thanks for encouraging me to learn it!
