### ISSUE TITLE
Interactive Brokers integration

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#234]
Scaffolding for an Interactive Brokers integration leveraging the `ib_insync` library has been added.

The vision is to initially support futures trading.

**Comment by crazy25000** [comment]
@cjdsellers I want to help with this, but the part that makes it difficult is not knowing how we expect it to work. I've been toying with the current work in progress adapters to try and learn.

**Comment by cjdsellers** [comment]
I agree, it could be much clearer how to implement an adapter. @limx0 has improved this situation with the templates PR.

As the general API becomes more stable I will improve the documentation further and write some more code examples there too. Docs is actually a larger project currently underway moving to MD over RST, how they are 'built'/deployed and where.

**Comment by cjdsellers** [comment]
This integration has been completed and tested to a basic level, closing this in favor of more specific issues. Many thanks to @limx0 for making this happen! :pray:
