### ISSUE TITLE
Commissions calculations for CryptoExchange

### ISSUE THREAD

**Issue by jpmediadev** [nautechsystems/nautilus_trader#247]
As far as I understand, the calculation of FX broker commissions differs from cryptocurrency exchanges - they are considered debited from the balance immediately after the order is executed, respectively, for a backtest close to reality, it would be nice to take this into account, or at least have access to exchange.total_commissions.values () from Strategy so that in manually subtract them from the current equity.

021-03-18T16:53:27.626636Z [INF] BacktestEngine: =================================================================
2021-03-18T16:53:27.626668Z [INF] BacktestEngine: BINANCE-001
2021-03-18T16:53:27.626717Z [INF] BacktestEngine: =================================================================
2021-03-18T16:53:27.626762Z [INF] BacktestEngine: Account balances (starting): 100,000.00000000 USDT
2021-03-18T16:53:27.626783Z [INF] BacktestEngine: Account balances (ending): 113,776.56650000 USDT
2021-03-18T16:53:27.626800Z [INF] BacktestEngine: Commissions (total): 17,808.93350000 USDT
2021-03-18T16:53:27.626816Z [INF] BacktestEngine: =================================================================

**Comment by cjdsellers** [comment]
Good pickup. This is the block of code relating to the issue;

```
        # Calculate potential PnL
        cdef Money pnl = None
        if position is not None and position.entry != order.side:
            # Calculate PnL
            pnl = position.calculate_pnl(
                avg_open=position.avg_open,
                avg_close=fill_price,
                quantity=order.quantity,
            )

        cdef Currency currency  # Settlement currency
        if self.default_currency is not None:  # Single-asset account
            currency = self.default_currency
            if pnl is None:
                pnl = Money(0, currency)

            if commission.currency != currency:
                # Calculate exchange rate to account currency
                xrate = self.get_xrate(
                    from_currency=commission.currency,
                    to_currency=currency,
                    price_type=PriceType.BID if order.side is OrderSide.SELL else PriceType.ASK,
                )

                # Convert to account currency
                commission = Money(commission * xrate, currency)
                pnl = Money(pnl * xrate, currency)

            total_commissions = self.total_commissions.get(currency, Decimal()) + commission
            self.total_commissions[currency] = Money(total_commissions, currency)

            # Final PnL
            pnl = Money(pnl - commission, self.default_currency)
        else:
            currency = instrument.settlement_currency
            if pnl is None:
                pnl = Money(0, currency)
```

The problem is where for a multi-asset account, when a position is not being reduced the commission is not being added to the `pnl` for the fill. 

So the final else block should be;

```
        else:
            currency = instrument.settlement_currency
            if pnl is None:
                pnl = commission
```

I've made that change and will be on `develop` in the next push.

**Comment by jpmediadev** [comment]
> I've made that change and will be on develop in the next push.

Thank you!
