### ISSUE TITLE
Little big questions and proposals (mix)

### ISSUE THREAD

**Issue by igorgodel** [nautechsystems/nautilus_trader#259]
1) 

       model\
        bar.pxd,bar.pyx,tick.pxd,tick.pyx,
       data\
        aggregation.pxd,aggregation.pyx ... 
       (see also (3))
       
        a) remove the member 'bar_spec' from BarBuilder class 
             cdef readonly BarSpecification bar_spec
        
        'bar_spec' is defined in BarBuilder constructor as 
            self.bar_spec = bar_type.spec
        
        There are only 2 cases to do this:
        1) self.bar_spec can be changed later (independently from value self.bar_type.spec)
        2) to speed up code execution (significant)
        
        This is not our case.
    
        similar cases:
        b) remove the members 'symbol', 'venue' from BarType class 
            cdef readonly Symbol symbol
            cdef readonly Venue venue
        c) remove the members 'symbol', 'venue' from Tick class 
            cdef readonly Symbol symbol
            cdef readonly Venue venue
        d) remove the member 'step' from TickBarAggregator class (see TimeBarAggregator) 
            cdef readonly int step
        e) remove the member 'step' from VolumeBarAggregator class (see TimeBarAggregator) 
            cdef readonly int step
        f) remove the member 'step' from ValueBarAggregator class (see TimeBarAggregator) 
            cdef readonly int step
        g) ...
  
2)

     model\bar.pxd, bar.pyx (see also (3))
        rename the member 'type' to 'bar_type' in Bar class     
        In BarBuilder class the correspondent member is ...
            cdef readonly BarType bar_type
    
3)

       model\bar.pxd,bar.pyx, data\aggregation.pxd,aggregation.pyx ...   
       More serious question, before it's too late (!!!).
       Redesign BarType, BarBuilder ... to exclude InstrumentId instrument_id
       (try to keep only BarSpecification)
       For BarAggregator InstrumentId must be passed explicitly to the constructor 
       
       In bar.pyx instrument_id is only used  in 
        - __str__ and __hash__ methods
          (instrument_id is not essential info, more important - spec )
        - serializing methods (really no need for a single bar) 
       In aggregation.pyx instrument_id (as part of bar_type) is only used:
        - for creating named timer 
          (we can build name for timer from pair instrument_id and spec)    
        - on call _handler and callback 
          (we can pass an instrument_id as arg)  
       
       The main idea - don't produce redundant/confusing/... info.   

4)

        core\uuid.pyx
        a) Remove
        assert 0 <= self.int_val < 1 << 128, "int is out of range (need a 128-bit value)"
        This statement has no effect.
        
        self.int_val was created from 16 bytes with default value of sign=False
        self.int_val = int.from_bytes(value, byteorder="big")
        Any 16 bytes will be converted to the int value in the range [0, 1 << 128)  
        
        b) Use self.int_value (not self.value) in comparison operations __eq__ and __ne__.
        It's more logical if we use self.int_value in __lt__, __gt__, ... operations    
   

to be continued

**Comment by igorgodel** [comment]
5)
 
       backtest\data_producer.pyx
       Pass arg dtype to function np.asarray (bug).  
       Example:    
       cdef str ts_dtype = 'uint64' 
       self._quote_timestamps = np.asarray([dt_to_unix_nanos(dt) for dt in quote_ticks_slice.index], dtype=ts_dtype)
       ...
   
6)

       core\datetime.pyx
       Use explicit type cast to uint64_t.
       Example:
       return <uint64_t>lround(...) 
       ...
       return NANOSECONDS_IN_SECOND * <int64_t>(delta.total_seconds())

**Comment by igorgodel** [comment]
7)

       tests/performance_tests/test_perf_decimal.py
       Provide the comparability of tests.
       1) Use everywhere 100000 runs @ 1 iteration 
       2) correct 'float_comparisons' and 'float_arithmetic' to 
          ensure the same number of operations
          (out of interest, to compare decimal and Python float arithmetic and comparisons)
          
        @staticmethod
        def float_comparisons():
            1.0 > 2.0  # noqa
            1.0 >= 2.0  # noqa
            1.0 == 2.0  # noqa
    
        @staticmethod
        def float_arithmetic():
            1.0 + 2.0  # noqa
            1.0 - 2.0  # noqa
            1.0 * 2.0  # noqa
            1.0 / 2.0  # noqa
    

to be continued

**Comment by igorgodel** [comment]
8.

        core\datetime.pyx
        item (6) is wrong (!!!)
        
        a)    
        In version 1.112.0 I found a bug related to the low-level compatibility 'long type'
        it's about Linus-Windows compatibility for lround and other functions (from libc.math)
        Example 1:
        The function secs_to_nanos:
            cpdef int64_t secs_to_nanos(double secs) except *:   
                return lround(secs * NANOSECONDS_IN_SECOND)
        
        returns 0 
        for secs = 42 or 9.999999999
        on Windows platform
        The signature lround:
            long lround(double x)
       
        (file: tests\unit_tests\core\test_core_datetime.py
         test: test_secs_to_nanos)
    
        Proposed solution (core\datetime.pyx):
            #from libc.math cimport lround
        
            cdef int _get_round_func_code() nogil:
                if sizeof(long) == 8:
                    return 0
                elif sizeof(long long) == 8:
                    return 1
                else:
                    return -1
            
            cdef int _round_func_code = _get_round_func_code()
            if _round_func_code == 0:
                from libc.math cimport lround
            elif _round_func_code == 1:
                from libc.math cimport llround as lround
            else:
                raise TypeError(f"Can't support 'C' lround function.")
    
        b)    
        The correct edition for timedelta_to_nanos.    
            original version:
            cpdef int64_t timedelta_to_nanos(timedelta delta) except *:
                return NANOSECONDS_IN_SECOND * delta.total_seconds()
            new version:
            cpdef int64_t timedelta_to_nanos(timedelta delta) except *:
                return <int64_t>(delta.total_seconds() * NANOSECONDS_IN_SECOND)
       
        c)
        No need to cast to int64 type where 
        return value is lround(...)

to be continued

**Comment by cjdsellers** [comment]
Your work is much appreciated. I'm going to attend to each item in turn.

**Comment by cjdsellers** [comment]
> ```
>    model\
>     bar.pxd,bar.pyx,tick.pxd,tick.pyx,
>    data\
>     aggregation.pxd,aggregation.pyx ... 
>    (see also (3))
>    
>     a) remove the member 'bar_spec' from BarBuilder class 
>          cdef readonly BarSpecification bar_spec
>     
>     'bar_spec' is defined in BarBuilder constructor as 
>         self.bar_spec = bar_type.spec
>     
>     There are only 2 cases to do this:
>     1) self.bar_spec can be changed later (independently from value self.bar_type.spec)
>     2) to speed up code execution (significant)
>     
>     This is not our case.
> 
>     similar cases:
>     b) remove the members 'symbol', 'venue' from BarType class 
>         cdef readonly Symbol symbol
>         cdef readonly Venue venue
>     c) remove the members 'symbol', 'venue' from Tick class 
>         cdef readonly Symbol symbol
>         cdef readonly Venue venue
>     d) remove the member 'step' from TickBarAggregator class (see TimeBarAggregator) 
>         cdef readonly int step
>     e) remove the member 'step' from VolumeBarAggregator class (see TimeBarAggregator) 
>         cdef readonly int step
>     f) remove the member 'step' from ValueBarAggregator class (see TimeBarAggregator) 
>         cdef readonly int step
>     g) ...
> ```
> 
> 
> ```
>  model\bar.pxd, bar.pyx (see also (3))
>     rename the member 'type' to 'bar_type' in Bar class     
>     In BarBuilder class the correspondent member is ...
>         cdef readonly BarType bar_type
> ```
> 
> 
> ```
>    model\bar.pxd,bar.pyx, data\aggregation.pxd,aggregation.pyx ...   
>    More serious question, before it's too late (!!!).
>    Redesign BarType, BarBuilder ... to exclude InstrumentId instrument_id
>    (try to keep only BarSpecification)
>    For BarAggregator InstrumentId must be passed explicitly to the constructor 
>    

Agreed that there is needless redundancy with no use cases in the platform currently.

The `symbol` and `venue` properties have been removed from `Tick` and `BarType` (still available through `instrument_id` anyway).

`BarBuilder` does not need the public property `bar_type` and so that has become a private member (it's needed to build the `Bar` though).

**Comment by igorgodel** [comment]
5.

       backtest\data_producer.pyx
       Need to use 'int64' (not 'uint64')
       cdef str ts_dtype = 'int64' 
       self._quote_timestamps = np.asarray([dt_to_unix_nanos(dt) for dt in quote_ticks_slice.index], dtype=ts_dtype)
       ...

**Comment by cjdsellers** [comment]
```
    similar cases:
    b) remove the members 'symbol', 'venue' from BarType class 
        cdef readonly Symbol symbol
        cdef readonly Venue venue
    c) remove the members 'symbol', 'venue' from Tick class 
        cdef readonly Symbol symbol
        cdef readonly Venue venue
    d) remove the member 'step' from TickBarAggregator class (see TimeBarAggregator) 
        cdef readonly int step
    e) remove the member 'step' from VolumeBarAggregator class (see TimeBarAggregator) 
        cdef readonly int step
    f) remove the member 'step' from ValueBarAggregator class (see TimeBarAggregator) 
        cdef readonly int step
    g) ...
```

The intent of these members is to reduce the `getattr` overhead of looking up the attribute on `bar_type.spec.step` every update.

However they don't need to be exposed 'publicly' as properties, and so have been made private.

**Comment by igorgodel** [comment]
Please pay attention (more closely, version 1.112.0) to: 
(5 - second edition):
Test tests/performance_tests/test_perf_backtest.py - failed 
(8):
compatibility problem (int64_t - long - long long) 
core/datetime.pyx is not compatible with Windows
Test tests/unit_tests/core/test_core_datetime.py - failed

Thanks

**Comment by igorgodel** [comment]
(8) 

    The run-time version to support compatibility:
    
    from libc.math cimport lround as lround_func
    from libc.math cimport llround as llround_func
    
    ctypedef int64_t (* round_func_type)(double x) nogil

    cdef round_func_type _get_round_func() nogil:
        if sizeof(long) == 8:
            return <round_func_type>lround_func
        elif sizeof(long long) == 8:
            return <round_func_type>llround_func
        else:
            return NULL
    
    cdef round_func_type lround = _get_round_func()
    if lround == NULL:
        raise TypeError(f"Can't support 'C' lround function.")

**Comment by cjdsellers** [comment]
4. 
a) Agreed - change made.
b) Agreed - change made.

**Comment by cjdsellers** [comment]
5.
`timestamp_ns` is passed an `int64_t`. So how about?;
```
            self._quote_timestamps = np.asarray(
                [dt_to_unix_nanos(dt) for dt in quote_ticks_slice.index], 
                dtype=np.int64,
            )
```

**Comment by cjdsellers** [comment]
```
ctypedef int64_t (* round_func_type)(double x) nogil

cdef round_func_type _get_round_func() nogil:
    if sizeof(long) == 8:
        return <round_func_type>lround_func
    elif sizeof(long long) == 8:
        return <round_func_type>llround_func
    else:
        return NULL

cdef round_func_type lround = _get_round_func()
if lround == NULL:
    raise TypeError(f"Can't support 'C' lround function.")
```

I have added your code to the top of `core/datetime.pyx`.

Please report if this fixes the compatibility for the functions you listed.

**Comment by cjdsellers** [comment]
Changed 

`bar.pyx`
```
timestamp_ns=long(pieces[5]),
```

`tick.pyx`
```
long(pieces[4]),
```
to
```
timestamp_ns=int(pieces[5]),
```
```
int(pieces[4]),
```

Not optimally performant - however it won't create a bottleneck, and will work for now.

**Comment by igorgodel** [comment]
(4)
core\uuid.pyx
Ok

(5)
backtest\data_producer.pyx
Ok (np.int64)

    Another idea:
    [dt_to_unix_nanos(dt) for dt in quote_ticks_slice.index]
    and 
    [dt_to_unix_nanos(dt) for dt in trade_ticks_slice.index]
    generate the creating intermediate (!!!) lists (list of int64_t) 
    to convert these lists to the numpy arrays.
    In the test example tests/performance_tests/test_perf_backtest.py 
    we have the list with ~30 000 bars but it can be 300 000, 3 000 000 ...
    
    So it'll be more optimally use the next:
    cpdef int64_t[:] _create_timestamps(ticks_slice_index) except *:
        cdef int k = 0
        cdef np.ndarray dst = np.ndarray(len(ticks_slice_index), dtype = 'int64')
        cdef int64_t[:] dst_mv = memoryview(dst)
        for dt in ticks_slice_index:
            dst_mv[k] = dt_to_unix_nanos(dt)
            k += 1
        return dst_mv
    
    # where _create_timestamps - is modul-level internal function
    and 
    ...
    self._quote_timestamps = _create_timestamps(quote_ticks_slice.index)
    ...
    self._trade_timestamps = _create_timestampstrade_ticks_slice.index)

(8) 
    core\datetime.pyx
    Ok (fixed)


(..)
    model\bar.pyx, tick.pyx
    Ok

**Comment by igorgodel** [comment]
(1) - redundantcy

Ok: a) - f)

        similar cases:
       g) remove the members 'symbol', 'venue' from Position class  (model\position.pxd)
            cdef readonly Symbol symbol
            cdef readonly Venue venue
       h) remove the members 'symbol', 'venue' from Instrument class  (model\instrument.pxd)
            cdef readonly Symbol symbol
            cdef readonly Venue venue
       i) remove the members 'symbol', 'venue' from TradingCommand class (model\commands.pxd)
            cdef readonly Symbol symbol
            cdef readonly Venue venue
       j) remove the members 'symbol', 'venue' from Order class (model\order\base.pxd)
            cdef readonly Symbol symbol
            cdef readonly Venue venue

**Comment by cjdsellers** [comment]
a) - f):

Agreed, there is still redundancy here as its inefficient to store identical memory addresses on backing fields. All of those symbol and venue C struct properties have been removed.

However,
For `Order`, `Position`, and `Instrument` I've added some convenience Python `@property`(s), as some users would find it more natural to call `order.symbol` than `order.instrument_id.symbol`, and extra microseconds with the `getattr` call won't be a concern if they're in pure Python already.

All Cython framework code however calls through the efficient C struct e.g. `order.instrument_id.venue`.

**Comment by igorgodel** [comment]
(1)
g - j):
Ok
Thanks

**Comment by cjdsellers** [comment]
I found another occurrence of `lround` in `/execution/cache.pyx`, this was easily removed by using `unix_timestamp_us` and the standard python `round` (its not called often).

**Comment by igorgodel** [comment]
### [1] \trading\account.pyx

Fixup the financial terminology:

    from multi-asset account -> to multi-currency account (MCA)

(see also examples and tests)


### [2] \analysis\performance.pyx (class PerformanceAnalyzer) 

methods:

    a) cpdef double total_pnl(self, Currency currency=None) except *
    b) cpdef double total_pnl_percentage(self, Currency currency=None) except *   
    c) cpdef object get_realized_pnls(self, Currency currency=None)

if currency is None these methods calculate target values (or series) actually
using data for a first (!!!) currency:

    1) for a) and b)
        ...
        if currency is None:
            account_balance = next(iter(self._account_balances.values()))
            account_balance_starting = next(iter(self._account_balances_starting.values()))
        ...
    2) for c)
        ...
        if currency is None:
            return next(iter(self._realized_pnls.values()))
        ...

What is the logical/financial meaning of the 'first' currency as item, for example,
in the balance of an account?
(or it is the base (default) currency in any multi-currency account ???)

Possible solutions (it's more predictable/expected behavior):

    if currency is None
        1) return None or
        2) check we have a single-currency account and
           return target value for this single currency else return None


Thanks

**Comment by cjdsellers** [comment]
```from multi-asset account -> to multi-currency account (MCA)```

This makes more sense within the codebase, and is better terminology.

Will make the change soon and also investigate **[2]**

**Comment by cjdsellers** [comment]
The terminology has now been standardized to `multi-currency` account.

The behavior of `Account` and `PerformanceAnalyzer` has been standardized.
If `None` is passed:
- For single-currency the only (first) result will be returned.
- For multi-currency a `ValueError` will be raised.

Pushed to latest `develop` branch.

**Comment by cjdsellers** [comment]
I think this completes the issues you've listed so far. 

I'll close this one and await further specific issues from you as they come up!
