### ISSUE TITLE
Computing performance

### ISSUE THREAD

**Issue by igorgodel** [nautechsystems/nautilus_trader#262]
## (1) - fast_mean, fast_std

For example, I would like to consider some simple functions (core\functions.pyx):
1) cpdef double fast_mean(list values) except *
2) cpdef double fast_std(list values) except *

You are right that:
"> 10x faster than `np.mean`"
"> 10x faster than `np.std`"
(see performance tests:  tests\performance_tests\test_perf_functions.py)
BUT ...

This is true when a list length < ~100

**Using lists to pass values for calculation,e.g., mean and std, has significant drawback: 
significant loss of speed calculation with increasing length (speed degradation).
(see tables below).**

So my proposal - use np.ndarray  

### Table 1 (comparison of 'mean' сomputation with different methods)

Annotation:

    1. np_mean       - 'mean' сomputation with numpy.mean 
    2. fast_mean     - 'mean' сomputation with fast_mean (current nautilus_trader version - 1.113)   
    3. fast_mean_new - 'mean' сomputation with fast_mean_new (new version of fast_mean)   
    4. N samples     - numbers of samples in the list/array
    5. us = microsec
       Numbers tests (TESTS) for each timing = 10000 - 1000 (dependent from N samples)
    7. Test PC - CPU Type AMD Ryzen 7 1700, 3685 MHz
    8. row "20; 11.8us (12.9); 2.5us (2.8); 0.9us (1.0)":
     
     - 20 = N samples
     - 11.8us (12.9) = average computation time with 'np_mean'       (12.9 ~= 11.8/0.9)   
     -  2.5us ( 2.8) = average computation time with 'fast_mean'     ( 2.8 ~=  2.5/0.9)   
     -  0.9us ( 1.0) = average computation time with 'fast_mean_new' ( 1.0  =  0.9/0.9) (standard=basis) 
   

<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">N samples</th>
<th title="Field #2">np_mean</th>
<th title="Field #3">fast_mean</th>
<th title="Field #4">fast_mean_new</th>
</tr></thead>
<tbody><tr>
<td align="right">5</td>
<td align="right"> 10.6us (11.9)</td>
<td align="right"> 0.7us (0.8)</td>
<td align="right"> 0.9us (1.0)</td>
</tr>
<tr>
<td align="right">10</td>
<td align="right"> 12.0us (13.3)</td>
<td align="right"> 1.4us (1.5)</td>
<td align="right"> 0.9us (1.0)</td>
</tr>
<tr>
<td align="right">20</td>
<td align="right"> 11.8us (12.9)</td>
<td align="right"> 2.5us (2.8)</td>
<td align="right"> 0.9us (1.0)</td>
</tr>
<tr>
<td align="right">50</td>
<td align="right"> 11.3us (14.4)</td>
<td align="right"> 4.7us (5.9)</td>
<td align="right"> 0.8us (1.0)</td>
</tr>
<tr>
<td align="right">100</td>
<td align="right"> 11.0us (11.0)</td>
<td align="right"> 8.7us (8.7)</td>
<td align="right"> 1.0us (1.0)</td>
</tr>
<tr>
<td align="right">200</td>
<td align="right"> 11.9us (11.7)</td>
<td align="right"> 17.7us (17.4)</td>
<td align="right"> 1.0us (1.0)</td>
</tr>
<tr>
<td align="right">500</td>
<td align="right"> 10.5us (7.6)</td>
<td align="right"> 42.0us (30.4)</td>
<td align="right"> 1.4us (1.0)</td>
</tr>
<tr>
<td align="right">1000</td>
<td align="right"> 11.4us (6.3)</td>
<td align="right"> 82.7us (45.6)</td>
<td align="right"> 1.8us (1.0)</td>
</tr>
<tr>
<td align="right">2000</td>
<td align="right"> 12.4us (4.4)</td>
<td align="right"> 162.5us (57.4)</td>
<td align="right"> 2.8us (1.0)</td>
</tr>
<tr>
<td align="right">5000</td>
<td align="right"> 13.1us (2.3)</td>
<td align="right"> 449.3us (79.3)</td>
<td align="right"> 5.7us (1.0)</td>
</tr>
<tr>
<td align="right">10000</td>
<td align="right"> 14.2us (1.4)</td>
<td align="right"> 837.3us (83.6)</td>
<td align="right"> 10.0us (1.0)</td>
</tr>
<tr>
<td align="right">20000</td>
<td align="right"> 17.2us (0.9)</td>
<td align="right"> 1675.0us (84.4)</td>
<td align="right"> 19.8us (1.0)</td>
</tr>
<tr>
<td align="right">50000</td>
<td align="right"> 28.2us (0.6)</td>
<td align="right"> 4182.1us (92.8)</td>
<td align="right"> 45.1us (1.0)</td>
</tr>
<tr>
<td align="right">100000</td>
<td align="right"> 42.7us (0.5)</td>
<td align="right"> 8287.9us (94.3)</td>
<td align="right"> 87.9us (1.0)</td>
</tr>
<tr>
<td align="right">1000000</td>
<td align="right"> 816.3us (0.9)</td>
<td align="right"> 84214.4us (93.2)</td>
<td align="right"> 903.9us (1.0)</td>
</tr>
<tr>
<td align="right">10000000</td>
<td align="right"> 10978.4us (1.2)</td>
<td align="right"> 882933.4us (96.8)</td>
<td align="right"> 9124.7us (1.0)</td>
</tr>
</tbody></table>

### Table 2 (comparison of 'std' сomputation with different methods)

Annotation:

    1. np_std       - 'std' сomputation with numpy.std 
    2. fast_std     - 'std' сomputation with fast_std (current nautilus_trader version - 1.113)   
    3. fast_std_new - 'std' сomputation with fast_std_new (new version of fast_std)   
    4. N samples     - ...
    5. us = ...
    7. Test PC = ...
    8. ...

<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">N samples</th>
<th title="Field #2">np_std</th>
<th title="Field #3">fast_std</th>
<th title="Field #4">fast_std_new</th>
</tr></thead>
<tbody><tr>
<td align="right">5</td>
<td align="right"> 33.6us (25.4)</td>
<td align="right"> 1.8us (1.3)</td>
<td align="right"> 1.3us (1.0)</td>
</tr>
<tr>
<td align="right">10</td>
<td align="right"> 37.2us (27.9)</td>
<td align="right"> 3.4us (2.5)</td>
<td align="right"> 1.3us (1.0)</td>
</tr>
<tr>
<td align="right">20</td>
<td align="right"> 34.1us (30.1)</td>
<td align="right"> 6.8us (6.0)</td>
<td align="right"> 1.1us (1.0)</td>
</tr>
<tr>
<td align="right">50</td>
<td align="right"> 34.2us (29.4)</td>
<td align="right"> 13.4us (11.5)</td>
<td align="right"> 1.2us (1.0)</td>
</tr>
<tr>
<td align="right">100</td>
<td align="right"> 33.9us (24.7)</td>
<td align="right"> 26.3us (19.1)</td>
<td align="right"> 1.4us (1.0)</td>
</tr>
<tr>
<td align="right">200</td>
<td align="right"> 37.1us (21.8)</td>
<td align="right"> 51.9us (30.6)</td>
<td align="right"> 1.7us (1.0)</td>
</tr>
<tr>
<td align="right">500</td>
<td align="right"> 34.9us (15.7)</td>
<td align="right"> 132.8us (59.9)</td>
<td align="right"> 2.2us (1.0)</td>
</tr>
<tr>
<td align="right">1000</td>
<td align="right"> 37.6us (12.7)</td>
<td align="right"> 254.9us (86.2)</td>
<td align="right"> 3.0us (1.0)</td>
</tr>
<tr>
<td align="right">2000</td>
<td align="right"> 42.5us (8.1)</td>
<td align="right"> 531.7us (102.0)</td>
<td align="right"> 5.2us (1.0)</td>
</tr>
<tr>
<td align="right">5000</td>
<td align="right"> 48.5us (4.7)</td>
<td align="right"> 1336.0us (129.5)</td>
<td align="right"> 10.3us (1.0)</td>
</tr>
<tr>
<td align="right">10000</td>
<td align="right"> 57.6us (2.8)</td>
<td align="right"> 2630.5us (126.6)</td>
<td align="right"> 20.8us (1.0)</td>
</tr>
<tr>
<td align="right">20000</td>
<td align="right"> 67.6us (1.8)</td>
<td align="right"> 5192.6us (141.0)</td>
<td align="right"> 36.8us (1.0)</td>
</tr>
<tr>
<td align="right">50000</td>
<td align="right"> 100.4us (1.1)</td>
<td align="right"> 13126.2us (147.7)</td>
<td align="right"> 88.9us (1.0)</td>
</tr>
<tr>
<td align="right">100000</td>
<td align="right"> 149.8us (0.8)</td>
<td align="right"> 27235.6us (151.4)</td>
<td align="right"> 179.8us (1.0)</td>
</tr>
<tr>
<td align="right">1000000</td>
<td align="right"> 4524.3us (2.5)</td>
<td align="right"> 267034.9us (147.7)</td>
<td align="right"> 1807.9us (1.0)</td>
</tr>
<tr>
<td align="right">10000000</td>
<td align="right"> 50570.1us (2.8)</td>
<td align="right"> 2748350.5us (151.2)</td>
<td align="right"> 18173.4us (1.0) </td>
</tr>
</tbody></table>

### Conclusion

   If we don't consider the special cases (using increased computation accuracy, alg Kahan and ... ,
   and parallel computations) I propose new fast versions for 'fast_mean',  'fast_std' and other functions 
   (Note: no problem to convert, for example, deque to nd.array ...)
   
   Send you all code today later.
   (with new version for tests\performance_tests\test_perf_functions.py)

**Comment by igorgodel** [comment]
## (1) - fast_mean, fast_std (new versions)



(A) - fast_mean

    import cython    
    from libc.math cimport sqrt
    cimport numpy as np

    @cython.boundscheck(False)
    @cython.wraparound(False)
    cpdef double fast_mean_new(np.ndarray values) except *:
        """
        Return the average value for numpy.ndarray values
    
        Parameters
        ----------
        values : numpy.ndarray
            The array to evaluate.
    
        Returns
        -------
        double
    
        Notes
        -----
        > 10x faster than `np.mean` if the array length < ~200.
    
        """
        cdef double[:] mv
        cdef int length
        cdef double total = 0.0
        cdef int i
    
        if values is None or values.ndim != 1:
            raise ValueError(f"values must be valid numpy.ndarray with ndim == 1.")
    
        mv = values
        length = len(mv)
    
        if length == 0:
            return 0.0
    
        with nogil:
            for i in range(length):
                total += mv[i]
    
        return total / length


(B) - fast_std

    import cython    
    from libc.math cimport sqrt
    cimport numpy as np

    cpdef double fast_std_new(np.ndarray values) except *:
        """
        Return the standard deviation from the given values.
    
        Parameters
        ----------
        values : numpy.ndarray
            The array for the calculation.
    
        Returns
        -------
        double
    
        Notes
        -----
        > 25x faster than `np.std` if the array length < ~200.
    
        """
        return fast_std_with_mean_new(values, fast_mean_new(values))

    @cython.boundscheck(False)
    @cython.wraparound(False)
    cpdef double fast_std_with_mean_new(np.ndarray values, double mean) except *:
        """
        Return the standard deviation from the given values and mean.
    
        Parameters
        ----------
        values : numpy.ndarray
            The array for the calculation.
        mean : double
            The pre-calculated mean of the given values.
    
        Returns
        -------
        double
    
        Notes
        -----
        > 25x faster than `np.std` if the array length < ~200.
    
        """
        cdef double[:] mv
        cdef int length
        cdef double std_dev = 0.0
        cdef double v
        cdef int i
    
        if values is None or values.ndim != 1:
            raise ValueError(f"values must be valid ndarray with ndim == 1.")
    
        mv = values
        length = len(mv)
    
        if length == 0:
            return 0.0
    
        with nogil:
            for i in range(length):
                v = mv[i] - mean
                std_dev += v * v
    
        return sqrt(std_dev / length)

Send you new version for tests\performance_tests\test_perf_functions.py later.

**Comment by cjdsellers** [comment]
Great work. This is a much better implementation.

I'll incorporate and test soon.

**Comment by cjdsellers** [comment]
The code has been incorporated as above and pushed to `develop`.

One interesting point is that the changes triggered compile time warnings:
```
warning:  "Using deprecated NumPy API, disable it by defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
```

As per the accepted answer:
_"This is a known issue, and it stems from the fact that Cython historically has supported very old numpy versions"_
https://stackoverflow.com/questions/52749662/using-deprecated-numpy-api

Apparently it will be fixed in the next Cython release and shouldn't be a problem.

This warning was silenced with:
```
define_macros = [("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")]
```
in the `build.py` script.

Another point is that several indicators now need to call `np.asarray` to convert a `list` to `ndarray`, which is only available through Numpys Python API. I tried casting to `<double[:]>` but that can only be done from a C pointer or array.

Possibly there is a more efficient way to handle this? apart from changing the type of `deque` - although probably not worth the engineering effort for the performance gain.

**Comment by cjdsellers** [comment]
Would you like me to give you credits for the implementations in the code and reference this issue? what is your preference?

**Comment by igorgodel** [comment]
I have to think a little bit and give you some proposals including indicators
Thanks

**Comment by igorgodel** [comment]
About credits ... not necessary,  thanks

**Comment by igorgodel** [comment]
### 1)
About warning:  "Using deprecated NumPy API..."
I do the same in my projects (in the build.py script):

        NPY_NO_DEPRECATED_API_MACROS = [("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")]
        if define_macros is not None:
            define_macros += NPY_NO_DEPRECATED_API_MACROS
        else:
            define_macros = NPY_NO_DEPRECATED_API_MACROS

### 2)
    Another point is that several indicators
    ...
    Possibly there is a more efficient way to handle this? ...

Good time to do some refactoring for indicator's classes.
'deque' ('deque' idea) has no an alternative (?) to support the accumulation of values.
So ... 

### 3) Changes in indicators ...

Annotation:

    CURRENT VERSION = 1.113
    NEW VERSION = new version ...
    
    Run NEW VERSION for all tests (on Windows) - status 'PASSED'':
        - tests/acceptance_tests/...
        - tests/integration_tests/redis/...
        - tests/performance_tests/...
        - tests/unit_tests/... (including /indicators)

\core\functions.pyx
We need the new version of fast_mean_iterated_new

    @cython.boundscheck(False)
    @cython.wraparound(False)
    cpdef double fast_mean_iterated_new(
        np.ndarray values,
        double next_value,
        double current_value,
        int expected_length,
        bint drop_left=True,
    ) except *:
        # ... - docs

        cdef double[:] mv
        cdef int length
    
        if values is None or values.ndim != 1:
            raise ValueError(f"values must be valid ndarray with ndim == 1.")
    
        mv = values
        length = len(mv)
    
        if length < expected_length:
            return fast_mean_new(values)
    
        assert length == expected_length
    
        cdef double value_to_drop = mv[0] if drop_left else mv[length - 1]
        return current_value + (next_value - value_to_drop) / length

indicators\base\indicator.pyx

    ...
    cdef str _params_str(self):
        # CURRENT VERSION ---------
        # return str(self._params)[1:-1].replace("'", '').strip('()') if self._params else ''
        #
        # NEW VERSION 1 ++++++++ (YOUR ATTENTION !!!) see \unit_tests\indicators\test_wma.py
        # to avoid issues to output numpy.ndarray, e.g. for wma (see test_wma.py)     
        return str(self._params)[1:-1].replace("'", '') if self._params else ''
        # NEW VERSION 2 ++++++++ (YOUR ATTENTION !!!) see \unit_tests\indicators\test_wma.py
        # or can keep parameters as list .. see wma.pyx
    ...

indicators\average\hma.pxd

    cimport numpy as np

    ...
        # CURRENT VERSION ---------
        # cdef list _w1
        # cdef list _w2
        # cdef list _w3
        #
        # NEW VERSION ++++++++
        cdef np.ndarray _w1
        cdef np.ndarray _w2
        cdef np.ndarray _w3
    ...

        # CURRENT VERSION ---------
        # cdef list _get_weights(self, int size)
        #
        # NEW VERSION ++++++++
        cdef np.ndarray _get_weights(self, int size)
    ...

indicators\average\hma.pyx

    import numpy as np
    cimport numpy as np

    ...
    cdef np.ndarray _get_weights(self, int size):
        # CURRENT VERSION ---------
        # 1. create ndarray of int w
        # 2. do div operation and create new ndarray w / sum(w)
        # 3. converting ndarray to the list
        # w = np.arange(1, size + 1)
        # return list(w / sum(w))
        #
        # NEW VERSION ++++++++
        # 1. create 'float64' array at once
        # 2. do in-place(!!!) div operation
        cdef np.ndarray w = np.arange(1, size + 1, dtype='float64')
        w /= w.sum()
        return w
    ...

indicators\average\wma.pxd

    cimport numpy as np
    
    ...
        # CURRENT VERSION ---------
        # cdef readonly object weights
        #
        # NEW VERSION ++++++++
        cdef readonly np.ndarray weights
    ...

indicators\average\wma.pyx

    import numpy as np
    cimport numpy as np

    ...
    def __init__(
        self,
        int period,
        weights=None,
        PriceType price_type=PriceType.LAST,
    ):

        # CURRENT VERSION ---------
        # Condition.positive_int(period, "period")
        # if weights is not None:
        #     Condition.equal(len(weights), period, "len(weights)", "period")
        # super().__init__(period, params=[period, weights], price_type=price_type)
        # self._inputs = deque(maxlen=period)
        # self.weights = weights
        # self.value = 0
        #
        # NEW VERSION ++++++++
        Condition.positive_int(period, "period")
        if weights is not None:
            if not isinstance(weights, np.ndarray):
                # convert weights to the np.ndarray if it's possible
                weights = np.asarray(weights, dtype='float64')
                # to avoid the case when weights = [[1.0, 2.0, 3,0], [1.0, 2.0, 3,0]] ...
                if weights.ndim != 1:
                    raise ValueError("weights must be iterable with ndim == 1.")
            else:
                if weights.ndim != 1 or weights.dtype != np.float64:
                    raise ValueError("weights must be a ndarray of 'float64' with ndim == 1.")

            Condition.equal(len(weights), period, "len(weights)", "period")
        
        # if weights is None <=> weights equal to one !!!

        # There are 2 ways (see yourself)
        # 1) we can keep weights in parameters as np.ndarray ...
        # 2) we can keep weights in parameters as list ...

        # 1) 
        super().__init__(period, params=[period, weights], price_type=price_type)
        # 2)
        # if weights is not None:
        #     super().__init__(period, params=[period, list(weights)], price_type=price_type)
        # else:
        #     super().__init__(period, params=[period, weights], price_type=price_type)

        self._inputs = deque(maxlen=period)
        # in any case keep in self.weights np.ndarray 
        self.weights = weights
        self.value = 0
    ...

indicators\bollinger_bands.pyx

    import numpy as np
    ...
        # CURRENT VERSION ---------
        #cdef double std = fast_std_with_mean(values=list(self._prices), mean=self._ma.value)
        #
        # NEW VERSION ++++++++
        cdef double std = fast_std_with_mean_new(values=np.asarray(self._prices, dtype='float64'), mean=self._ma.value)

indicators\fuzzy_candlesticks.pyx

    ...
        # CURRENT VERSION ---------
        # cdef double mean_length = fast_mean(list(self._lengths))
        # cdef double mean_body_percent = fast_mean(list(self._body_percents))
        # cdef double mean_upper_wick = fast_mean(list(self._upper_wick_percents))
        # cdef double mean_lower_wick = fast_mean(list(self._lower_wick_percents))
        #
        # cdef double sd_lengths = fast_std_with_mean(list(self._lengths), mean_length)
        # cdef double sd_body_percents = fast_std_with_mean(list(self._body_percents), mean_body_percent)
        # cdef double sd_upper_wick_percents = fast_std_with_mean(list(self._upper_wick_percents), mean_upper_wick)
        # cdef double sd_lower_wick_percents = fast_std_with_mean(list(self._lower_wick_percents), mean_lower_wick)
        #
        # NEW VERSION ++++++++
        # convert deques to ndarrays to avoid doing this twice
        cdef np.ndarray _lengths = np.asarray(self._lengths, dtype='float64')
        cdef np.ndarray _body_percents = np.asarray(self._body_percents, dtype='float64')
        cdef np.ndarray _upper_wick_percents = np.asarray(self._upper_wick_percents, dtype='float64')
        cdef np.ndarray _lower_wick_percents = np.asarray(self._lower_wick_percents, dtype='float64')

        cdef double mean_length = fast_mean_new(_lengths)
        cdef double mean_body_percent = fast_mean_new(_body_percents)
        cdef double mean_upper_wick = fast_mean_new(_upper_wick_percents)
        cdef double mean_lower_wick = fast_mean_new(_lower_wick_percents)

        cdef double sd_lengths = fast_std_with_mean_new(_lengths, mean_length)
        cdef double sd_body_percents = fast_std_with_mean_new(_body_percents, mean_body_percent)
        cdef double sd_upper_wick_percents = fast_std_with_mean_new(_upper_wick_percents, mean_upper_wick)
        cdef double sd_lower_wick_percents = fast_std_with_mean_new(_lower_wick_percents, mean_lower_wick)

    ...

indicators\spread_analyzer.pyx

    import numpy as np

    ...
        # CURRENT VERSION ---------
        # self.average = fast_mean_iterated(
        #     values=list(self._spreads),
        #     next_value=spread,
        #     current_value=self.average,
        #     expected_length=self.capacity,
        #     drop_left=False,
        # )
        #
        # NEW VERSION ++++++++
        self.average = fast_mean_iterated_new(
            values=np.asarray(self._spreads, dtype='float64'),
            next_value=spread,
            current_value=self.average,
            expected_length=self.capacity,
            drop_left=False,
        )
    ...

\unit_tests\core\test_core_functions.py

    ...
    # CURRENT VERSION ---------
    # from nautilus_trader.core.functions import fast_mean_iterated
    # from nautilus_trader.core.functions import fast_mean
    # from nautilus_trader.core.functions import fast_std
    # from nautilus_trader.core.functions import fast_std_with_mean
    #
    # NEW VERSION ++++++++
    from nautilus_trader.core.functions import fast_mean_iterated_new
    from nautilus_trader.core.functions import fast_mean_new
    from nautilus_trader.core.functions import fast_std_new
    from nautilus_trader.core.functions import fast_std_with_mean_new

    ...


        # CURRENT VERSION ---------
        # def test_fast_mean_with_empty_list_returns_zero(self):
        #     # Arrange
        #     values = []
        #
        #     # Act
        #     result = fast_mean(values)
        #
        #     # Assert
        #     assert result == 0
        #
        # NEW VERSION ++++++++
        def test_fast_mean_with_empty_list_returns_zero(self):
            # Arrange
            values = np.asarray([], dtype='float64')

            # Act
            result = fast_mean_new(values)

            # Assert
            assert result == 0
    
        # CURRENT VERSION ---------
        # def test_fast_mean_with_values(self):
        #    # Arrange
        #    values = [0.0, 1.1, 2.2, 3.3, 4.4, 5.5]
        #
        #    # Act
        #    result = fast_mean(values)
        #
        #    # Assert
        #    assert result == 2.75
        #    assert np.mean(values) == 2.75
        #
        # NEW VERSION ++++++++
        def test_fast_mean_with_values(self):
            # Arrange
            values = np.asarray([0.0, 1.1, 2.2, 3.3, 4.4, 5.5], dtype='float64')
    
            # Act
            result = fast_mean_new(values)
    
            # Assert
            assert result == 2.75
            assert np.mean(values) == 2.75
    
        # CURRENT VERSION ---------
        # def test_fast_mean_iterated_with_empty_list_returns_zero(self):
        #    # Arrange
        #    values = []
        #
        #    # Act
        #    result = fast_mean_iterated(values, 0.0, 0.0, 6)
        #
        #    # Assert
        #    assert result == 0
        #
        # NEW VERSION ++++++++
        def test_fast_mean_iterated_with_empty_list_returns_zero(self):
            # Arrange
            values = np.asarray([], dtype='float64')
    
            # Act
            result = fast_mean_iterated_new(values, 0.0, 0.0, 6)
    
            # Assert
            assert result == 0
    
        # CURRENT VERSION ---------
        # def test_fast_mean_iterated_with_values(self):
        #     # Arrange
        #     values1 = [0.0, 1.1, 2.2]
        #     values2 = [0.0, 1.1, 2.2, 3.3, 4.4]
        #  
        #     # Act
        #     result1 = fast_mean_iterated(values1, 0.0, fast_mean(values1), 5)
        #     result2 = fast_mean_iterated(values2, 5.5, np.mean(values2), 5)
        # 
        #     # Assert
        #     assert result1 == np.mean(values1)
        #     assert result2 == 3.3000000000000003
        #
        # NEW VERSION ++++++++
        def test_fast_mean_iterated_with_values(self):
            # Arrange
            values1 = np.asarray([0.0, 1.1, 2.2], dtype='float64')
            values2 = np.asarray([0.0, 1.1, 2.2, 3.3, 4.4], dtype='float64')
    
            # Act
            result1 = fast_mean_iterated_new(values1, 0.0, fast_mean_new(values1_arr), 5)
            result2 = fast_mean_iterated_new(values2, 5.5, np.mean(values2_arr), 5)
    
            # Assert
            assert result1 == np.mean(values1)
            assert result2 == 3.3000000000000003
    
        # CURRENT VERSION ---------
        # def test_std_dev_with_mean(self):
        #     # Arrange
        #     values = [0.0, 1.1, 2.2, 3.3, 4.4, 8.1, 9.9, -3.0]
        # 
        #     mean = fast_mean(values)
        #  
        #     # Act
        #     result1 = fast_std(values)
        #     result2 = fast_std_with_mean(values, mean)
        # 
        #     # Assert
        #     assert result1 == np.std(values)
        #     assert result2 == np.std(values)
        #     assert result1 == 3.943665807342199
        #     assert result2 == 3.943665807342199
        #
        # NEW VERSION ++++++++
        def test_std_dev_with_mean(self):
            # Arrange
            values = np.asarray([0.0, 1.1, 2.2, 3.3, 4.4, 8.1, 9.9, -3.0], dtype='float64')
    
            mean = fast_mean_new(values)
    
            # Act
            result1 = fast_std_new(values)
            result2 = fast_std_with_mean_new(values, mean)
    
            # Assert
            assert result1 == np.std(values)
            assert result2 == np.std(values)
            assert result1 == 3.943665807342199
            assert result2 == 3.943665807342199
    

\unit_tests\indicators\test_wma.py

    ...
    # CURRENT VERSION ---------
    # def test_str_repr_returns_expected_string(self):
    #     # Arrange
    #     # Act
    #     # Assert
    # 
    #     self.assertEqual(
    #         "WeightedMovingAverage(10, [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])",
    #         str(self.wma),
    #     )
    #     self.assertEqual(
    #         "WeightedMovingAverage(10, [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])",
    #         repr(self.wma),
    #     )
    #
    # NEW VERSION ++++++++ (YOUR ATTENTION !!! ) see indicator.pyx
    def test_str_repr_returns_expected_string(self):
        # Arrange
        # Act
        # Assert

        weights_repr = repr(self.wma.weights)
        self.assertEqual(
            f"WeightedMovingAverage(10, {weights_repr})",
            str(self.wma),
        )
        self.assertEqual(
            f"WeightedMovingAverage(10, {weights_repr})",
            repr(self.wma),
        )

    # CURRENT VERSION ---------
    # def test_weights_returns_expected_weights(self):
    #     ...
    #     self.assertEqual(self.w, self.wma.weights)
    #
    # NEW VERSION ++++++++
    def test_weights_returns_expected_weights(self):
        ...
        self.assertEqual(self.w, list(self.wma.weights))

    # CURRENT VERSION ---------
    # def test_wma_factory_update_raw(self):
    #     ...
    #     self.assertEqual(self.w, self.wma_factory.weights)
    #
    # NEW VERSION ++++++++
    def test_wma_factory_update_raw(self):
        ...
        self.assertEqual(self.w, list(self.wma_factory.weights))

**Comment by igorgodel** [comment]
Extra notes to 3) - changes:

WeightedMovingAverage class stores not normalized (!) weights in self.weights so:

    1) in wma.pyx:
        for WeightedMovingAverage.__init__(,,,)  method we have to append
        the next check after calling Condition.equal:
              Condition.equal(len(weights), period, "len(weights)", "period")
              cdef double sum = weights.sum()
              cdef double eps = np.finfo(np.float64).eps
              if not (eps < sum):
                  raise ValueError(f"sum of weights must be positive number > {eps}.")

    2) in hma.pyx:
        when we create three WeightedMovingAverage objects:
              self._w1 = self._get_weights(period_halved)
              self._w2 = self._get_weights(period)
              self._w3 = self._get_weights(period_sqrt)
              self._ma1 = WeightedMovingAverage(period_halved, weights=self._w1)
              self._ma2 = WeightedMovingAverage(period, weights=self._w2)
              self._ma3 = WeightedMovingAverage(period_sqrt, weights=self._w3)
        we don't need to normalize weights in self._get_weights
        But really members self._w1, self._w2, self._w3 are not used in code at all.
        Then we can simplify:
        a) remove data self._w1, self._w2, self._w3
        b) remove method self._get_weights
        b) create WeightedMovingAverage objects as:
              self._ma1 = WeightedMovingAverage(period_halved, weights=np.arange(1, period_halved + 1, dtype='float64'))
              self._ma2 = WeightedMovingAverage(period, weights=np.arange(1, period + 1, dtype='float64'))
              self._ma3 = WeightedMovingAverage(period_sqrt, weights=np.arange(1, period_sqrt + 1, dtype='float64'))

**Comment by igorgodel** [comment]
### 3) Changes in indicators ... 
(continue, forgot to include some changes)

indicators\average\sma.pyx

    ...
    cpdef void update_raw(self, double value) except *:
        ...
        # CURRENT VERSION ---------
        #self.value = fast_mean(list(self._inputs))
        #
        # NEW VERSION ++++++++
        self.value = fast_mean_new(np.asarray(self._inputs, dtype='float64'))

analysis\performance.pyx

    ...
    cpdef double avg_winner(self, Currency currency=None) except *:
        ...
        # CURRENT VERSION ---------
        # return fast_mean(winners)
        #
        # NEW VERSION ++++++++
        return fast_mean_new(np.asarray(winners, dtype='float64'))
    ...
    cpdef double avg_loser(self, Currency currency=None) except *:
        ...
        # CURRENT VERSION ---------
        # return fast_mean(losers)
        #
        # NEW VERSION ++++++++
        return fast_mean_new(np.asarray(losers, dtype='float64') )

**Comment by igorgodel** [comment]
### 4) Remarks to analysis\performance.pyx ... 

For this module we don't need super speed (it's not critical).
More importantly - clarity and elegance.
In any case do not use Python lists (but np.ndarray) and fast_mean_new

    cpdef double avg_winner(self, Currency currency=None) except *:
        realized_pnls = self.get_realized_pnls(currency)
        if realized_pnls is None or realized_pnls.empty:
            return 0.0

        cdef np.ndarray pnls = realized_pnls.to_numpy()
        cdef np.ndarray winners = pnls[pnls > 0.0]
        if len(winners) == 0:
            return 0.0
        else:
            return winners.mean()

    cpdef double avg_loser(self, Currency currency=None) except *:
        realized_pnls = self.get_realized_pnls(currency)
        if realized_pnls is None or realized_pnls.empty:
            return 0.0

        cdef np.ndarray pnls = realized_pnls.to_numpy()
        cdef np.ndarray losers = pnls[pnls <= 0.0]
        if len(losers) == 0:
            return 0.0
        else:
            return losers.mean()

**Comment by cjdsellers** [comment]
**1)**
We do something similar in `build.py`
```
    define_macros = [("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")]
    if PROFILING_MODE or ANNOTATION_MODE:
        define_macros.append(("CYTHON_TRACE", "1"))
```

**Comment by cjdsellers** [comment]
**2, 3)**
`core/functions.pyx`

I think using memory views is much better so this change as been made.

**Comment by cjdsellers** [comment]
All of the above were good changes. 

Only minor modifications to your condition checks in `wma.pyx` to utilize the `Condition` class.

**Q:** Is it faster to create a string for `dtype='float64'` than to just use the constant `dtype=np.float64` - I'm not sure?

**Comment by cjdsellers** [comment]
Changes have been pushed to develop for inclusion in release `1.115.0`.

**Comment by igorgodel** [comment]
Q: Is it faster to create a string for dtype='float64' than to just use the constant dtype=np.float64 - I'm not sure?

I have no exact answer.
np.float64 is the predefined class and there are a lot of such classes in Numpy 
I think the searching a string from a predefined set of string is faster than the searching a class from a predefined set of classes.
May be I am not wrong.
There is another reason (for me) to use string representation of dtype: 
I am using *.yaml, '*.json' files with description of db fields  ... in my projects
as well as scripts with signature description for different math functions and operators for NN and AI ...

**Comment by cjdsellers** [comment]
Closing this issue for now.

Performance related discussions focusing on #272
