### ISSUE TITLE
Backtest bar data with PriceType.LAST

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#269]
We need to refactor the `BacktestDataContainer.add_bar_data` method so that data added with `PriceType.LAST` will be interpreted as, and pre-processed into, trade ticks.

**Comment by brbatv** [comment]
hey 
i'm trying to pass my own bars data  to the backtester 
how could I do that ? 
I could help with the coding

**Comment by cjdsellers** [comment]
I just saw this, will respond soon.

**Comment by brbatv** [comment]
@cjdsellers  thank you
i'm ready to help if you can provide general details about the structure (it's quite heavy to understand to whole library for me now)
i will look into it today and the next week if I can do stuff on my own

Basically now my objective I just want to pass my ohlcv(+) data and run a simple backtest

**Comment by cjdsellers** [comment]
Hi @brbatv 

I understand its always challenging to fully digest how a large codebase is put together. 

Have you managed to make any progress at this stage? 

Significant amounts of work is being carried out in the area of data sourcing and loading (mainly by @limx0). We're 80% converged on making parquet/arrow DataFrames the standard data 'currency' being passed into the `BacktestEngine`. At a high level the general workflow is: 
- Source your raw data and load into memory.
- Parse the data it into the necessary format (currently `pandas.DataFrame`), objects but possibly parquet/arrow soon.
- Pass the data frame to the `BacktestEngine`. 

Custom parsers may be needed depending on the format of your raw data, with some examples/inspirations in the codebase already). I'd suggest looking into how this currently works for getting the example data at `nautilus_trader/tests/test_kit/data` into the backtest runs.

I'd also suggest reading some of the more recent issues on backtest data loading/streaming. One of the additional challenges with answering your question is that the project is undergoing some heavy development right now with design/technology decisions and the API in a state of flux. 

Will wait to hear back from you to get an update on where you're at before expanding on these initial suggestions.

**Comment by cjdsellers** [comment]
Did you manage to figure out how to load your OHLCV data?
