### ISSUE TITLE
Performance benchmarking with pytest-benchmark

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#272]
After some research it seems like a good idea if we transition the performance benchmarking over to a more established tool such as `pytest-benchmark` https://pytest-benchmark.readthedocs.io/en/latest/.

This will allow continuous benchmarking through GitHub workflows which publishes on a page to track and analyze the benchmarks https://github.com/marketplace/actions/continuous-benchmark.

This will then allow the removal of the bespoke `PerformanceHarness` which is really reinventing the wheel which pytest is already rolling with.

Development on this branch:
https://github.com/nautechsystems/nautilus_trader/tree/performance

Thoughts and comments welcome!

**Comment by ian-wazowski** [comment]
Nice, Great work @cjdsellers, I seems very useful.

**Comment by igorgodel** [comment]
pytest-benchmark
Good plan.
(In the tests results - output some machine info, e.g., 'system', 'cpu-info' ... )

Send you later some recommendations about using in tests relative (and absolute) errors due to rounding in floating point arithmetic.

**Comment by igorgodel** [comment]
**@cjdsellers** 

Walking down the version 1.116.1 with your new performance benchmarking with pytest-benchmark.
**Nice, great and useful.**

I have some recommendations

## Some definitions
(pytest-benchmark site)

**Iteration** is a single run of a benchmarked function.
**Round** is a set of iterations. 
(If we don't set 'iterations' parameter the size of a round is computed in the calibration phase.)

**Statistics are computed with 'rounds', not with 'iterations'.**
**The duration for a round is an average of all the iterations in that round.**

**For getting durations and statistics:** 
    a test function will be called 'rounds' * 'iterations' times.

**For getting warmup:** 
    a test function will be called 'warmup_rounds' * 'iterations' times.

## Сritical values for 'rounds' and 'iterations' to avoid

1)  If we set 'rounds' to 1 then we will not be able to get statistics (See bm-1-10000.png).
    
    In this case we get a result of the single measurement which will be an average of all iterations in that round.
    
    In this case and for any (!!!) test function we will get:
    
        1) Min = Max = Mean = Median
        2) StdDev = 0.0
        3) IRQ = 0.0
        4) Outliers = 0;0
    
    bm-1-10000.png
    ![bm-1-10000](https://user-images.githubusercontent.com/81437543/115318757-0f0b7c80-a187-11eb-8c54-e6d9173774a1.png)


2)  If we set 'iterations' to 1, 2, ... 10 ...(??) then we will get 'bad' statistics (See bm-10000-1.png).
    
    In terms of probability theory:
    - the probability of getting smaller values (minimums) is decreased
    - the probability of getting larger values (maximums) is increased (extremely)
      (for Max we will have extremely large values)
      
    Another issue: timer calibration issues for fast test functions. 
    
    bm-10000-1.png
    ![bm-10000-1](https://user-images.githubusercontent.com/81437543/115318537-986e7f00-a186-11eb-9d5d-35f72cfb4921.png)
    

## Preferable values for 'rounds' and 'iterations' (See bm-1000-100.png)

   There is no a total rule but for tests with duration ~100 ns - ~  100 microsec
   we can accept next preferable values:

   'rounds' = ~1000   
   'iterations' = ~100

   bm-1000-100.png
   ![bm-1000-100](https://user-images.githubusercontent.com/81437543/115318818-34988600-a187-11eb-8271-17521047c101.png)

## Recommendations
 
1) Preferable values for 'rounds' and 'iterations' (see above)
2) Preferable value for 'warmup_rounds' = ~5
3) For each test one can define consts:

        _ROUNDS = 1000
        _ITERATIONS = 100
        _WARMUP_ROUNDS = 5

   to use the same values for all tests in same file, for example:

        def test_foo(self):
            self.benchmark.pedantic(
                target=foo,
                args=...,
                rounds=_ROUNDS,
                iterations=_ITERATIONS,
                warmup_rounds=_WARMUP_ROUNDS
            )

4) For special cases - special  values.

**Comment by cjdsellers** [comment]
The above is a good suggestion, lets implement this moving forward as we get into more performance profiling. 

Also on the agenda is persisting the benchmarks somewhere to track trends and produce visualizations.

https://github.com/gaogaotiantian/viztracer

https://perfetto.dev/docs/quickstart/trace-analysis

https://github.com/quasiben/dask-scheduler-performance

**Comment by cjdsellers** [comment]
We could incorporate the following into the `test` workflow which triggers on every PR.

https://github.com/marketplace/actions/comment-with-pytest-benchmark-result

**Comment by cjdsellers** [comment]
Performance bench-marking is now being persisted, tracked and displayed on a GH pages dev page.

https://nautechsystems.github.io/nautilus_trader/dev/bench/index.html

This gets updated with each push or PR to the `develop` branch.

Next up on this issue is to go through the tests incorporating @igorgodel s comments above and generally tidying up along with adding some canonical backtest benches.

**Comment by cjdsellers** [comment]
Closing in favour of #370
