### ISSUE TITLE
Backtest realism

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#286]
I'd like to open a discussion about things that could be improved on the backtest / simulation side. A handful of things I'd like to see in the near term: 
- Full order books in the Simulated Exchange (#287)
- Improved quoting logic (probabilistic fills based on a full order book) 
  - Also maintaining a strategies order position in the orderbook (if someone is on the orderbook level, then your strategy joins, then someone joins behind you, we should simulate getting a fill if the level trades (as far as our order)) 
- An (optional) latency added to insert/delete/updates that a strategy sends
- Latency for strategy calculations (if a strategy goes off and computes something for 3s, we should walk the backtest clock forward by that amount of time before resuming).

**Comment by cjdsellers** [comment]
All valid and good features.

Potentially probabilistic fills can be replaced with proper time vs price priority logic?

The strategy calculations one is interesting. I'd propose that there isn't any logic to define that within the actual strategy script as it should be reusable live. Probably some sort of means of registering a strategy method for a relay with the engine...

**Comment by cjdsellers** [comment]
Currently the `L1OrderBook` is not correctly modelling fills running with a `TradeTick` stream only. If the order book is left in cross after a trade then the bid.price = ask.price.

There's also a temporary hack to assign a fixed size to the top of the book for `QuoteTicks` if volume data is not provided.

The `FillModel` functionality likely needs to be expanded to cover some of the above.

**Comment by limx0** [comment]
Closing this issue in favour of discussion #379, will raise more specific issues when they arise.
