### ISSUE TITLE
The documentation link is broken

### ISSUE THREAD

**Issue by jeremie-martin** [nautechsystems/nautilus_trader#289]
Generating it with poetry and sphinx works fine, but https://docs.nautilus-trader.io seems to be down.

**Comment by cjdsellers** [comment]
Thanks Jeremie,

We had an issue with read the docs and are currently in a transition to GitHub pages to host at that url - however the move hasn't been completed yet. It shouldn't be too much longer.

**Comment by cjdsellers** [comment]
The documentation link is repaired and available at https://docs.nautilustrader.io

Although there is currently a dependency conflict on the RTD build server I'm not able to solve yet.

Apologies for the inconvenience!

**Comment by cjdsellers** [comment]
Documentation is now back up.
