### ISSUE TITLE
Commission is not applied when executing a trade in the same dir as the position

### ISSUE THREAD

**Issue by scoriiu** [nautechsystems/nautilus_trader#29]
Right now the commission is calculated only when the position is reduced. I think this is wrong, because the commission should be applied also when a fill happens in the same dir as the position. I can also submit a fix to this if you agree.

On a separate note, it would be nice to have different commissions applied for maker/taker, where in case of maker commission bp can be negative (rebates).

**Comment by cjdsellers** [comment]
I agree with you on when commission should be applied. You're most welcome to open a PR on the develop branch to support the above.

**Comment by scoriiu** [comment]
Ok, will do.

**Comment by scoriiu** [comment]
See https://github.com/nautechsystems/nautilus_trader/pull/32#partial-pull-merging

**Comment by cjdsellers** [comment]
Your changes were merged. Thank you
