### ISSUE TITLE
Building/installing pitfalls/bugs

### ISSUE THREAD

**Issue by igorgodel** [nautechsystems/nautilus_trader#303]
## Building/installing pitfalls/bugs and Cython version control

    For Linux and Windows.
    Terminal commands - for Windows, as example

At this moment (version 1.117.0 and commits on May 2, 2021) there is one 
grave pitfall. But this pitfall is 'mysterious', so we all fall into it.

You can read only D) and E)

#### A) Let's be
test_dir\ - some local directory for our experiment
test_dir\nautilus_trader\ - the root directory of the project  

Load the project from github:
 - using 'git clone https://github.com/nautechsystems/nautilus_trader.git' ...
 - or downloading zip file ...  

#### B) Do some changes in the ..nautilus_trader\build.py:

These changes need only to output Cython version on building to the file and terminal. 
```python
# ...

# APPEND THIS: import Cython version 
from Cython.Compiler.Version import version as cython_build_version
# END APPEND

# ...

if __name__ == "__main__":
    
    # ...
    
    print("Starting build...")
    bits = "64-bit" if sys.maxsize > 2 ** 32 else "32-bit"
    print(f"System: {platform.system()} {bits}")

    # APPEND THIS: output Cython version on building (to the file and terminal)
    with open("build_dependencies_view.log", 'w') as cbv:
        cbv.write(f"Build dependencies: Cython version = {cython_build_version}")
    print(f"Build dependencies: Cython version = {cython_build_version}")
    # END APPEND

    build({})
```

#### C.1) Building the project using 'poetry'
```
# install all dependency, build the the project and install the project
#
test_dir\nautilus_trader>poetry install
```
Installation completed. Ok, fine, don't you think?
Very interesting question:
Q: Is this installation correct?
A: YES 

      - The file "build_dependencies_view.log" will contain: 
        "Build dependencies: Cython version = 3.0a6"
      - We also can open any *.c file, generated by Cython, 
        for example, build\optimized\nautilus_trader\core\functions.c:
        the first row will be:
        /\* Generated by Cython 3.0a6 */
  

#### C.2) Building the project using 'pip install'
```
# do cleanup
#
test_dir\nautilus_trader>python scripts\cleanup.py

# create virtual env: nt_env (right here)
# activate nt_env
# do some uprade and install cython==3.0a6
# installing cython has no effect really (see below)
#
test_dir\nautilus_trader>python -m venv nt_env
test_dir\nautilus_trader>nt_env\Scripts\activate.bat
(nt_env) test_dir\nautilus_trader>python -m pip install -U pip setuptools cython==3.0a6

# Run 'pip install'
# To create build\ directory and view building results (*.c, *.pyd (*.so), ...)
# we use option --use-feature
#
(nt_env) test_dir\nautilus_trader>python -m pip install . -v --use-feature=in-tree-build
```

Installation completed. Ok, fine, don't you think?
Very interesting question:
Q: Is this installation correct?
A: NO 

      - The file "build_dependencies_view.log" will contain: 
        "Build dependencies: Cython version = 0.29.23"
      - We also can open any *.c file, generated by Cython, 
        for example, build\optimized\nautilus_trader\core\functions.c:
        the first row will be:
        /\* Generated by Cython 0.29.23 */

#### C.3) Building the project using 'pip install' from PYPI from sdist(!!!)
We will get **the same incorrect results as C.2** if PYPI does not contain appropriate *.whl file.
```
Sorry, this experiment is more complex: 
we need to download nautilus_trader-1.117.0.tar.gz (source distribution) from PYPI
then edit the build.py (see above, to view the Cython version),
create virt env and run
python -m pip install nautilus_trader-1.117.0.tar.gz -v
```

#### D) Pitfall description

Now pyproject.toml does not contain any version for Cython in 'build-system' section,
there is only the version for run-time dependency:

```toml
[build-system]
requires = ["poetry-core>=1.0.2", "cython", "numpy", "setuptools"]
build-backend = "poetry.core.masonry.api"

# ...

[tool.poetry.build]
#...
cython = "^3.0a6"
#...

```

[1] For 'pip install' case:

During regular installation, 'pip' will copy the entire project directory to a temporary location
and install from there.
There is no version information for Cython in 'build-system' section.
So 'pip install' will try to load the latest stable version and
now(!!!) the latest stable version for Cython is 0.29.23.
   
[2] For 'poetry' case:

When we run 'poetry install' 'poetry' resolves dependencies in 
'tool.poetry.dependencies' and 'tool.poetry.dev-dependencies' sections and
installs these dependencies, including, Cython (3.0a6) in some virt env and 
then uses this Cython (3.0a6) version to build the project.
   

This was a real reason of installation problem (for Linux and Windows) from source (!!!) - see,
for example, message from @eicnix (see Windows support #257) and may be from @RKMaynard -
NumPy-Cython compatibility issue.
(See my notes in Windows support #257 "NumPy-Cython compatibility issue description")

#### E) Proposals

1) Specify versions for Cython and NumPy in the 'build-system' section of pyproject.toml.
   (there are also another ways to control build dependencies)
   
    For example:
    ```toml
    [build-system]
    requires = ["poetry-core>=1.0.2", "cython>=3.0a6", "numpy>=1.20.2", "setuptools"]
    build-backend = "poetry.core.masonry.api"
    
    # ...
    
    [tool.poetry.build]
    #...
    cython = "^3.0a6"
    numpy = "^1.20.2"
    #...
    
    ```
    
    Build dependency and runtime dependency control allow to test the project with
    min requirements in the future.
    
    It's really necessary when we talk about the possibility to install the package in the environment
    with other packages, for example, trading/brokerage platforms and systems, quantitative trading systems,
    Pytorch, Tensorflow, sklearn, ... . 
    
    These allow users to prepare specific 'home' building.
    For example:
    ```toml
    [build-system]
    requires = [
        "poetry-core>=1.0.2",
        "Cython>=0.29.18,<3.0",
        "numpy>=1.19.3", 
        "setuptools<=51.0.0"
   ]
    build-backend = "poetry.core.masonry.api"
    
    # ...
    
    ```

2) Provide some build dependencies version control at least for some time (see B)      

3) Provide the correct usage of 'NPY_NO_DEPRECATED_API', for example,
   in the ..nautilus_trader\build.py:
   
    ```python
    
    # ...
    
    from Cython.Compiler.Version import version as cython_build_version
    from distutils.version import LooseVersion
    
    # ...
    
    def _build_extensions() -> List[Extension]:
    
        define_macros = []
        
        # ...
        
        # see notes "NumPy-Cython compatibility issue description" in Windows support #257:
        # 1) if LooseVersion("3.0") > LooseVersion(cython_build_version) we can't
        # avoid deprecated messages from NumPy 
        # 2) if LooseVersion("3.0") <= LooseVersion(cython_build_version) we can
        # avoid deprecated messages from NumPy if we want
        if LooseVersion("3.0") <= LooseVersion(cython_build_version):
            # if we want we can avoid deprecated messages from NumPy
            define_macros.append(("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION"))
     
        # ...
    
    ```

**Comment by cjdsellers** [comment]
Thank you for this detailed analysis.

For the proposals, I agree we should specify versions for Cython and Numpy in the build-system requirements.

I'm not sure it's a good idea to maintain backwards compatibility for Cython versions < 3.0, as we can't guarantee the behavior of the package unless we regularly compile with older Cython versions and run the test suite.

Cython >= 3.0 includes various bug fixes and features.
https://cython.readthedocs.io/en/latest/src/changes.html#alpha-6-2020-07-31

In the `build.py` I'm still prepared to include the `LooseVersion` condition, which determines if the NumPy deprecated API macro is appended - for those users compiling with older versions of Cython.

Also worth noting is that installation from source requires the correct version of Cython as the first step.
```
Installation from source requires Cython to compile the Python C extensions.

1. To install Cython, run:

        pip install -U Cython==3.0a6
```

And also the use of pre-compiled binary wheels should be encouraged. 

Windows wheels will be included hopefully in the next release as there's just one remaining task, which involves reading the name of the built `.whl` in the `dist` directory using Powershell commands.


**Maybe you could assist with this?**

See `.github/workflows/test-tag-publish.yml` - the below only works for Linux and MacOS:
```
      # Set release output variables
      - name: Set output
        id: vars
        run: |
          echo "::set-output name=asset_path::$(find ./dist -mindepth 1 -print -quit)"
          cd dist
          echo "::set-output name=asset_name::$(printf '%s\0' * | awk 'BEGIN{RS="\0"} {print;  exit}')"
```

Lastly, logging the Cython compiler version from `Cython.Compiler.Version.version` is a great addition to the script.

I'll include the changes in the next push to `develop`.

**Comment by cjdsellers** [comment]
To clarify, did you mean we can avoid the NumPy deprecation warning for versions of Cython prior to 3.0?
```
    if LooseVersion(cython_compiler_version) < LooseVersion("3.0"):
        # https://github.com/nautechsystems/nautilus_trader/issues/303
        define_macros.append(("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION"))
```

**Comment by igorgodel** [comment]
> 
> 
> To clarify, did you mean we can avoid the NumPy deprecation warning for versions of Cython prior to 3.0?
> 
> ```
>     if LooseVersion(cython_compiler_version) < LooseVersion("3.0"):
>         # https://github.com/nautechsystems/nautilus_trader/issues/303
>         define_macros.append(("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION"))
> ```

NO (we will get definetly a compilation error with the current source) !!!
See my notes in Windows support #257 "NumPy-Cython compatibility issue description" and
E)-3) in this issue "Building/installing pitfalls/bugs and Cython version control"

New edition for build.py :

```python

# ...

from setuptools import Extension

# APPEND THIS 
from distutils.version import LooseVersion as Version
from Cython.Compiler.Version import version as cython_build_version
# Min Cython 3 version is "3.0a6" (to exclude 3.0a1, ...). Later - "3.1...", ...
CYTHON_3_MIN_VERSION = "3.0a6"

# ...

# APPEND THIS 
def _append_numpy_macros(define_macros: List[Any]) -> None:
    # See notes:
    #
    # 1) note 1:
    #    https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html
    #    section "NumPy C-API".
    #    Even here the description is not correct. 
    #    For example, for version Cython 3.0a1, 3.0a2, ... 3.0a4 it's wrong.
    # 2) note 2:
    #    "NumPy-Cython compatibility issue description" in Windows support #257.
    # 3) note 3:
    #    "Building/installing pitfalls/bugs"  #303.
    #
    # Logic description:
    #
    # A) if Version(cython_build_version) < Version("3.0")
    #    We can't avoid deprecated messages from NumPy if we use NumPy C-API.
    #    Moreover,
    #    if we use NumPy C-API (cython does it, when we call array.ndim, ...)
    #    and try to define macros ("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")    
    #    we will get errors (see note 2).
    #    In this case we don't define the macros.    
    #
    # B) if Version("3.0") <= Version(cython_build_version) < Version("3.0a5")
    #    Even in this case we can't define this macros with a guarantee.
    #    In this case we don't define the macros.    
    #
    # C) if Version("3.0a6") <= Version(cython_build_version) 
    #    (I skip version "3.0a5" - no need such details)
    #    We can avoid deprecated messages from NumPy if we use NumPy C-API and if we want
    #    In this case we can define the macros.    
    #    We don't use here CYTHON_3_MIN_VERSION but - "3.0a6" 
    if Version("3.0a6") <= Version(cython_build_version):
        # we can do the next:
        # 1) avoid deprecated messages from NumPy if we use NumPy C-API or 
        # 2) pass 
        define_macros.append(("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION"))

# CURRENT VERSION
def _build_extensions() -> List[Extension]:
    define_macros = []

    # ...    

# NEW VERSION
def _build_extensions() -> List[Extension]:
    define_macros = []

    _append_numpy_macros(define_macros)

    # ...    

# ...    

# APPEND THIS 
def _check_cython_version():
    # Here we check only acceptable Cython versions
    #
    if Version("3.0") <= Version(cython_build_version):
        if Version(cython_build_version) < Version(CYTHON_3_MIN_VERSION):
            raise ValueError(f"nautilus_trader supports minimum Cython 3 version {CYTHON_3_MIN_VERSION}\n"
                             f"got Cython {cython_build_version}"
            )
    else:
        # if Version(cython_build_version) < Version("3.0")
        # we can do the next:
        # 1) raise exception that nautilus_trader does not accept
        #    versions < Version("3.0") or
        # 2) we can inroduce CYTHON_0_MIN_VERSION  ... or
        # 3) pass (to give users the opportunity to build the package with older versions)
        #    we can also ouput the warning message 
        pass 
        

# APPEND THIS 
def _get_build_dependency_versions():
    return (
        f"Using build dependencies:\n"
        f"    Cython = {cython_build_version}\n"
        f"    NumPy  = {np.__version__}"
    )


# CURRENT VERSION
if __name__ == "__main__":

    # ...  

    print("Starting build...")
    # ...  
    bits = "64-bit" if sys.maxsize > 2 ** 32 else "32-bit"
    print(f"System: {platform.system()} {bits}")
    build({})


# NEW VERSION
if __name__ == "__main__":

    # ...  

    _check_cython_version()
    print("Starting build...")
    # ...  
    bits = "64-bit" if sys.maxsize > 2 ** 32 else "32-bit"
    print(f"System: {platform.system()} {bits}")
    print(_get_build_dependency_versions())
    # we can remove this tmp log
    with open("build_dependencies_tmp.log", 'w') as cbv:
        cbv.write(_get_build_dependency_versions())
    
    build({})

**Comment by igorgodel** [comment]
**@cjdsellers** 
> Also worth noting is that installation from source requires the correct version of Cython as the first step.
> 
> Installation from source requires Cython to compile the Python C extensions.
> 
> 1. To install Cython, run:
> 
>         pip install -U Cython==3.0a6

Agreed, Installation from source requires Cython to compile the Python C extensions.

But:
For 'pip install',  'pip' will read 'pyproject.toml' (PEP 518). 'pyproject.toml' does not contain information
about cython version (only requirement). In this case 'pip' will try to get the latest stable version. ("3.0a6" - prerelease). 

If we set for Cython version "0.29.23" in 'pyproject.toml'
```toml
[build-system]
requires = ["poetry-core>=1.0.2", "cython==0.29.23", "numpy>=1.20.2", "setuptools"]

# ...
```
and run 'pip install',  'pip' will load version "0.29.23".

**Comment by igorgodel** [comment]
### sdist (source distribution) file contains a bug

We need to exclude from "nautilus_trader-*.tar.gz" files any *.so (and *.pyd) files

**Comment by cjdsellers** [comment]
I ran an experiment, with the following inserted into the `build.py` 

```
if cython_compiler_version != "3.0a6":
    raise RuntimeError("Incompatible Cython version")
```
and build-dependencies in the `pyproject.toml`
```
[build-system]
requires = [
    "poetry-core>=1.0.2",
    "cython",
    "numpy>=1.20.2",
    "setuptools",
]
```
and running the following command from the root directory
```
pip install .`
```
The installation exits with a non-zero code after raising the `RuntimeError`.

If we set the build-dependencies as per your suggestion (and as per the latest `develop` branch):

```
[build-system]
requires = [
    "poetry-core>=1.0.2",
    "Cython>=3.0a6",
    "numpy>=1.20.2",
    "setuptools",
]
```
and running the following command from the root directory
```
pip install .
```
The installation completes successfully.

And so I think we have solved the issue of Cython compatibility when installing from source?

I don't think its necessary to leave the runtime exception in place though, just to make it possible to compile with older Cython versions if a user wishes?

**Comment by cjdsellers** [comment]
> ### sdist (source distribution) file contains a bug
> 
> We need to exclude from "nautilus_trader-*.tar.gz" files any *.so (and *.pyd) files

Agreed, these shouldn't be required in an `sdist` distribution.

**Comment by igorgodel** [comment]
> So I think we have solved the issue of Cython compatibility when installing from source either via PyPI sdist or from the cloned > source?
>  
> However, I don't think its necessary to leave the runtime exception in place though, just to make it possible to compile with   older Cython versions if a user wishes?
> 

Yes, we can fix the pyproject.toml version at this moment:
```toml
[build-system]
requires = [
    "poetry-core>=1.0.2",
    "Cython>=3.0a6",
    "numpy>=1.20.2",
    "setuptools",
]

# ...
 ```
See also detail corrections to the build.py above "New edition for build.py".

**Comment by cjdsellers** [comment]
With reference to the options you listed:
```
        # if Version(cython_build_version) < Version("3.0")
        # we can do the next:
        # 1) raise exception that nautilus_trader does not accept
        #    versions < Version("3.0") or
        # 2) we can inroduce CYTHON_0_MIN_VERSION  ... or
        # 3) pass (to give users the opportunity to build the package with older versions)
        #    we can also ouput the warning message 
```
I think we should take option 3.

I've modified the `build.py` to the follow - is this logic correct?

```
def _build_extensions() -> List[Extension]:
    # Build Extensions to feed into cythonize()
    # Profiling requires special macro directives
    define_macros = []
    if PROFILING_MODE or ANNOTATION_MODE:
        define_macros.append(("CYTHON_TRACE", "1"))

    if LooseVersion("3.0a6") <= LooseVersion(cython_compiler_version):
        # https://github.com/nautechsystems/nautilus_trader/issues/303
        define_macros.append(("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION"))
```

Hopefully Cython releases the next version soon!

**Comment by cjdsellers** [comment]
What do we gain from generating a `build_dependencies_view.log` in your view ?

**Comment by igorgodel** [comment]
> I think we should take option 3.

Yes. (and I think in the future we'll return to this question)

> I've modified the build.py to the follow - is this logic correct?

There is no doubt.

> What do we gain from generating a build_dependencies_view.log in your view ?

It's comfortably for 'home' experiments (to avoid looking for the cython build version on the screen).
You can remove that.

**Comment by cjdsellers** [comment]
Ok great!

I'll close this issue now and await any more that you may kindly raise :+1:

**Comment by cjdsellers** [comment]
I think we may be getting close to a deterministically successful build for all the OS's.

@ian-wazowski could you please report the current version builds OK for your 32-bit environment?

**Comment by cjdsellers** [comment]
@igorgodel we finally achieved a flawless CI and release for the full OS/Python matrix. I'd like to express my appreciation once again for all of your efforts to help make this happen! :clap:

**Comment by cjdsellers** [comment]
@igorgodel 
We fixed the copying of `.so` files into the `sdist` source tree.

```
      # Install / Build (No need to copy built *.so files back into the source tree)
      - name: Install / Build
        run: |
          export SKIP_BUILD_COPY=true
          poetry install
          poetry build --format sdist
```
