### ISSUE TITLE
ccxt-coinbasepro authentication

### ISSUE THREAD

**Issue by BlackWingedKing** [nautechsystems/nautilus_trader#309]
@cjdsellers 

[This](https://github.com/nautechsystems/nautilus_trader/commit/615e065675cc6cadb905fa1462aa05bbc41845d2) commit added the `password` field to `internal_config` of `CCXTDataClientFactory`. I think it should also be added to `internal_config` of `CCXTExecutionClientFactory` after [this](https://github.com/nautechsystems/nautilus_trader/blob/733b8d9a8cdede938f2c6412d3da6ae6f0788cd2/nautilus_trader/adapters/ccxt/factories.pyx#L149) line

**Comment by cjdsellers** [comment]
Added and pushed :+1:

**Comment by BlackWingedKing** [comment]
Thank you
