### ISSUE TITLE
Order Fill event has no knowledge about the execution state

### ISSUE THREAD

**Issue by scoriiu** [nautechsystems/nautilus_trader#31]
Placing a Limit Order below the market price, should execute the order at the market price. In this case the order fill structure should capture this as `fill_event.order_type` = `OrderType.Limit` and `fill_event.execution.order_type` = `OrderType.Market`.

A quick solution would be to convert the order type to `Market` when placing the `Limit` below/equal the market price, and let it be executed as MARKET. This doesn't imply changing the `OrderFillEvent`.

Please let me know your thoughts.

**Comment by cjdsellers** [comment]
Assuming you're referring to the behavior in the `BacktestExecClient` (which we should probably rename). My initial impression is that the behavior of a limit order is broker dependent. Most APIs I've worked with will simply reject the order if the price is invalid, what has your experience been here?

A couple of solutions could be;
- Capture the `OrderRejected` event relating to this, and then submit a new `MarketOrder`.
- Refactor `LimitOrder` to include a market if rejected type flag. The re-submission as a MarketOrder type could then be handled by the `ExecutionEngine`. 

Changing the type of an initialized order which has already been ID'd would cause problems with the current setup.

Some brokers may also provide some kind of Limit-To-Market order type (in which case we just add an implementation for that) but I'm not aware off the top of my head...

Many thanks for your interest and feeback!

**Comment by scoriiu** [comment]
Yes, I'm referring to the `BacktestExecClient`, forgot to mention.

From my experience most of/if not all the brokers accept and execute orders as Market, without specifying an option about this. However, my experience is limited mainly to crypto brokers.

Some brokers have an explicit option called "post-only" in which case the limit order will be rejected (e.g. www.bitmex.com)

My preference is having a feature that handles this automatically instead of handling it via a reject. Right now the Limit order is not rejected if submitted at a market price, but executed. I propose adding a state in the `OrderFillEvent.execution_type` which is set to Market/Limit and a flag in the order called `post_only` which will decide wether to accept/reject the order in this case (we will have to decide the default value). If the flag is set to `False` and the price of the limit order is bellow the market price, the order will be executed in `_process_order` and the `OrderFillEvent.execution_type = Market`.

Please let me know your thoughts.

**Comment by cjdsellers** [comment]
I'm currently reviewing the documentation on BitMEX and having a think about how to proceed. BitMEX is actually the first exchange I want to integrate with, I'll be writing a refactored and more solid/efficient version of the official WebSockets client soon.

**Comment by cjdsellers** [comment]
Ok, so I agree all that's needed on the `LimitOrder` is an additional optional param `post_only`. This object can then carry that option along to any `ExecutionClient` which is submitting orders to BitMEX so the "box is/isn't checked". To communicate what actually occurred on fill I agree that there should be another field in the order fill events. 

I propose a better name for this may be `.liquidity_side` with a new enum `LiquiditySide` with .MAKER and .TAKER. Every order no matter what type (obviously market and stop orders are always TAKER), will have the liquidity side applied on fill which will as a result pick up that information you need for your limit order market making.

I'll have to have a think about how to handle things with the `OrderInitialized` event and persisting orders to Redis. Probably the easiest thing to do here is introduce an `options` `{str, str}` dictionary which contains simple mappings of order options which may not apply to every order or every exchange. Then this becomes infinitely extendable without continuously adding new fields into the immutable events.

From here we can alter the behavior of the `BacktestEngine` to recognize the `LiquiditySide` and introduce the extended commission model for the rebates etc.

Thoughts?

**Comment by scoriiu** [comment]
I think `liquidity_side` is an excellent concept. I also like the idea of having an extensible dict of params, because this will handle nicely the differences between exchange APIs. And they are so different from one exchange to another.

**Comment by scoriiu** [comment]
Regarding the websocket implementation will it be python with asyncio?

**Comment by cjdsellers** [comment]
I've pushed some upgrades to the order API. We now have `is_post_only` and `is_hidden` options on the `LimitOrder`. Will add icebergs and some of the other BitMEX options in due course.

I've also integrated the extensible options `dict` which solves the persistence issue - nice and simple solution. The fields which any order needs are there on the immutable class with anything else going into the options dictionary. Since that mutable dictionary never gets passed around the system, with the contents being parsed out to domain objects, I feel that's still safe usage. With that I can now bring back `MarketIfTouched` and `StopLimit` type orders as they needed an additional trigger price.

I've also upgraded the `BacktestExecClient` to recognize the option and execute the `LimitOrder` at the current market if placed beyond a price it can work at. I believe the implementation is correct. I intend on pushing a few more refactorings tonight to clean up all of that logic, some methods need to be extracted there.

**Comment by cjdsellers** [comment]
I wasn't aware of hummingbot, quite an impressive body of work indeed. There is an argument to not reinvent the wheel and simply integrate with existing clients. The code on BitMEX isn't too extensive and I've already received some refactoring examples - I'm still open to anything though.

I understand you are attempting to integrate this platform onto BitMEX yourself. We can definitely work together on this to help things move faster, with the benefit that code can come under the umbrella of this repo with its test suite and CI.

**Comment by scoriiu** [comment]
Excellent work.

I think the implementation is mainly correct. The only remark is about the decision of when to execute at market price, it should be if the price is grater than **or equal** the best ask for BUY and lower than **or equal** the best bid for SELL. Right now the "or equal" part is missing.

**Comment by scoriiu** [comment]
Oh, please ignore the above, I see that you add/subtract the ticker size when you compare. So it is correct.

**Comment by scoriiu** [comment]
What is your strategy for interacting with the exchanges (e.g. REST calls)? I recommend using CCXT as a singular client, since it integrates with all the crypto exchanges. This has the big advantage of not having to implement exchange specific REST APIs and also that it gives a uniform interface across exchanges.

**Comment by scoriiu** [comment]
From my experience, the disadvantage of using the official client approach is that not every exchange have clients that are reliable. Even big exchanges like Binance. In this cases you will still have to rely on your own implementation to stay solid. 

In this case another con is that Bitmex client is not build on asyncio.

**Comment by cjdsellers** [comment]
I did a refactoring of the backtest order processing. You were right it needed to pickup the case where the limit order equals the applicable market price too. The comparison when subtracting the tick is to capture the case where some brokers require a one tick buffer on certain instruments. The refactoring has made things much clearer and easier to work with too.

Integration with CCXT could be valuable although I agree the lack of asyncio when using REST would hurt performance. Given the performance of the platform is so good because of Cython, this should be preserved as much as possible. I'd lean towards going down the road of adding individual exchanges one at a time. Utilizing asyncio is a big ++

**Comment by scoriiu** [comment]
CCXT supports asyncio. I meant that the BITMEX official websockets client is not built on top of asyncio. I also fancy the idea of having both REST and websockets in asyncio if possible.

**Comment by cjdsellers** [comment]
In your opinion which is the best way to proceed? Work with a refactored asyncio version of the official BitMEX client, or integrate CCXT?

**Comment by scoriiu** [comment]
There are 2 separate components here, CCXT doesn't support websocket sreams yet, it is only used for REST calls. And for this, I strongly recommend using it because it is solid and it integrates with all the crypto exchanges out there.

For the websocket streams, I recommend using our own implemenation in async io.

**Comment by cjdsellers** [comment]
I'm going to review the CCXT library more closely, however I feel it could be a good option. Its nice and efficient that they've already figured out how to cater to all of the different exchange APIs.

I was reviewing the BitMEX documentation earlier today, and I believe you can receive streaming market data via the websockets API, however all trading is done via the REST API?

So we need both really, as you're indicating.

**Comment by scoriiu** [comment]
Yes, there are 2 separate channels, and this applies to all the exchanges AFAIK. Some of them have support for FIX, in which case is possible to use the same streaming channel for trading and market data.

I agree, CCXT is a pretty nice library that saves a lot of integration work. I use it for quite some time now and I'm satisfied with it. They're working on a PRO version which will include streams, order tracking, uniform interface for derivatives, but at this point it is far from being production ready -> https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual.

**Comment by cjdsellers** [comment]
I saw the pro option which looks interesting for down the track. That's good that you have experience working with CCXT already, this could mean we could work quite quickly - as I'm familiar with this platform already, and you're familiar with CCXT.

**Comment by cjdsellers** [comment]
I'm currently hustling to convert all docstrings to numpydoc spec https://numpydoc.readthedocs.io/en/latest/format.html
and then get a readthedocs site up.

Will be making periodic pushes.

**Comment by scoriiu** [comment]
Cool. I think we will work nicely together.

**Comment by cjdsellers** [comment]
I'm opening a new issue regarding the CCXT integration.
