### ISSUE TITLE
[Doubt] How to get ticker data for a symbol (latest and 24hr price change)

### ISSUE THREAD

**Issue by BlackWingedKing** [nautechsystems/nautilus_trader#310]
@cjdsellers 

I would like to write a strategy (for `CCXT-BINANCE` ) for which I require ticker data for a symbol (`fetchTicker` in `ccxt`).

From the examples, I understand for bar data I could add subscriptions and handle them in the `on_bar` callback function. How can I get the latest ticker data in the strategy class?

Thank you.

**Comment by cjdsellers** [comment]
That's actually an endpoint I haven't wired up yet. It shouldn't be too difficult, I can have a look tomorrow AM.

**Comment by BlackWingedKing** [comment]
I don't actually need entire ticks for last 24 hrs

I think just an endpoint to this [`fetchTicker`](https://github.com/ccxt/ccxt/blob/master/examples/py/async-fetch-ticker.py) in ccxt is enough which would return [This](https://ccxt.readthedocs.io/en/latest/manual.html#ticker-structure) ticker structure

**Comment by cjdsellers** [comment]
Out of interest, what specific information did you need from that ticker structure?

The same could be received through a `QuoteTick` request also, which we could hookup by requesting an order book snapshot.

**Comment by cjdsellers** [comment]
It looks like the `request_quote_ticks` endpoint isn't implemented for CCXT as yet. It could probably be parsed from a request for order book history if this is possible as quote ticks are top of book changes.

However as a work around for the moment - while we look into this more closely is:
Use `subscribe_quote_ticks(instrument_id)` to recover the current price.

And request daily bars through `request_bars(bar_type). Depending on the timestamp of the open/close this could give you a longer period price change in the order of 24hrs. If period is < 24hrs then try the prior daily bar close.

**Comment by cjdsellers** [comment]
Or even request one hour or even higher resolution bars and then count back depending on the current time.

**Comment by cjdsellers** [comment]
How did you go with this?

Just a thought - it may make sense to start implementing some `Binance` specific objects in the `binance` adapter, possibly a `BinanceCCXTDataClient` inheriting/overriding the `CCXTDataClient`. 
https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_trader/adapters/ccxt/data.pyx

For example we could create an appropriate object for the 24hr Ticker Price Change Statistics endpoint:
https://binance-docs.github.io/apidocs/spot/en/#24hr-ticker-price-change-statistics

Eventually we could do a complete integration, fully supporting all endpoints and functionality.
Thoughts? If you wanted to take the lead on starting some of this work then you're most welcome!

**Comment by BlackWingedKing** [comment]
Hello, @cjdsellers 
I planned to go with this solution suggested by you
> Or even request one hour or even higher resolution bars and then count back depending on the current time.

I think creating a `BinanceCCXTDataClient` inheriting the `CCXTDataClient` is a good idea, I'll start with that

I will create an issue once I have it working with some binance specific endpoints.
