### ISSUE TITLE
How do I check account balances free?

### ISSUE THREAD

**Issue by thematz1** [nautechsystems/nautilus_trader#323]
I'm trying to but an account balances check in my strategy. I'm having difficulties retrieving the Account(event).balances_free() function or tapping into the CCXT-Binance _watch_balances... 

Essentially I would like to update the balance and ensure I am not sending trades that result in insufficient funds.

Thanks for any help in advance.

Apologies in advance, I'm not so great with github and have no idea how to label as a question.

**Comment by thematz1** [comment]
Thank you for your super fast answer. 

This project is amazing, the more I dig into it over the past few months, the more I see its glory. For this reason, I hope to slowly but surely contribute to the repo. It has been about two months working through the code (for me) and I am still discovering more about it.

I will be keeping an eye out for the future of the RiskEngine :)

**Comment by cjdsellers** [comment]
Many thanks for your kind feedback! :pray: 

Don't hesitate to ask more questions, and looking forward to any potential contributions from you :+1:

**Comment by thematz1** [comment]
I ended up using this in my strategy (it's a rough draft). It required some imports but seems to run.

`       cdef str asset_buy = self.instrument_id.symbol.value.split("/")[1]
        currency_buy = Currency(asset_buy, precision=8, iso4217=0, name=asset_buy, currency_type=CurrencyType.CRYPTO)
        cdef str asset_sell = self.instrument_id.symbol.value.split("/")[0]
        currency_sell = Currency(asset_sell, precision=8, iso4217=0, name=asset_sell, currency_type=CurrencyType.CRYPTO)
        wallet_amount = self.portfolio.account(self.instrument_id.venue).balance_free(currency_buy)

        if wallet_amount >= Money(self.trade_size, currency_sell):
            self.submit_order(order)`

Should leave it live on my wallet today to see what happens.
