### ISSUE TITLE
Any rebalancing strategy example?

### ISSUE THREAD

**Issue by yohplala** [nautechsystems/nautilus_trader#324]
Hi there,
I would like to know from your experience if setting up a rebalance strategy with Nautilus would be possible?
I am refering to the type of portofolio management [Shrimpy](https://www.shrimpy.io/) is featuring:
Basically:
- a set of crypto (yes, applied to crypto :)) is defined (for instance USDT, BTC, ETH & BNB)
- for each crypto, a target amount in the portfolio is defined (for instance USDT: 20%, BTC: 40%, ETH: 30% & BNB: 10% - the total is 100%)
- and according a condition defined by the strategy author, a rebalancing is triggered:
    - for instance at fixed time interval, like every hour,
    - or when the unbalance with respect to target allocation grows above a limit threshold

I had a look in the `examples/strategies` folder, and did not identify this type of strategy?

I am sure implementing the condition for triggering the rebalance is no worries.
But is Nautilus able to handle:
 - several cryptos in a same strategy?
 - manage size of positions defined as % of a total portfolio?
 - (not compulsory, but desired) implement 'live' limit order, i.e. limit orders that are updated every x seconds to follow the best price till they are filled (best price = ask for limit sell order, bid for buy order). Indeed, with this type of strategy, transaction price is not 'critical (so to say) and over the long run, this price optimization is preferable.

Thanks in advance for your advices,

**Comment by ian-wazowski** [comment]
1. several cryptos in a same strategy?
Yes(multi exchange, multi asset).

2. manage size of positions defined as % of a total portfolio?
Yes.

3. (not compulsory, but desired) implement 'live' limit order, i.e. limit orders that are updated every x seconds to follow the best price till they are filled (best price = ask for limit sell order, bid for buy order). Indeed, with this type of strategy, transaction price is not 'critical (so to say) and over the long run, this price optimization is preferable.
Yes. look closer strategy.pyx.

**Comment by yohplala** [comment]
Thanks a lot for your feedbacks, I appreciate them very much!
Ok, I will have a look, lot of thanks!
