### ISSUE TITLE
Data Streaming for backtest

### ISSUE THREAD

**Issue by thematz1** [nautechsystems/nautilus_trader#333]
I recently tried using trade history to backtest and the size of DataFrame is unmanageable. I was wondering if there were plans to create a backtest data container that streams data from a server or batches trade history from smaller files?

I have found using dask to join dataframes works pretty well. Streaming data from redis or a db could help memory management for things like grid searches.

Thanks in advance for the response.

**Comment by ian-wazowski** [comment]
I'm going to make the exactly same logic you mentioned using [Arctic](https://github.com/man-group/arctic)(developed by Man Group). At a very close point(may be 1~2 weeks later).

At various point of view, Dask might be a good option, but in terms of scalability and maintenance, it seems better to use arctic or parquet(file system) with s3.

**Comment by yohplala** [comment]
Hi @ian-wazowski 
I am sorry, I am a newbie on this topic. Please, what are the pros and cons of the 3 solutions you mention for this use case? 
Or more exactly,
- what difference do you make between Dask (which store and access data to parquet file through fastparquet) and what you call 'parquet (file system)' ?
- how does compare Arctic to above solution? (I know about it by name, but I have never tried)
I am building a 'crypto data management system' based on fastparquet, but it is purely local, and at some point, I may need to make available data from it to a trading engine (which may probably be Nautilus Trader)
In this context, I was starting to think that maybe using Git LFS as buffer might be an option.
Hence my curiosity in this topic :)

**Comment by thematz1** [comment]
@ian-wazowski Arctic is an amazing tip. What I am looking to accomplish seems similar to the offering of that project from my quick glance.

I'm looking in the live trading node to see if i could parallel its functions that builds a queue from rows returned by a database in sequential batches. This way one memory store could be access from multiple backtest engines. I hope to keep overhead for something such as grid searching strategy parameters low by it reading from hard drive  into ram in batches. Each concurrent backtest process should be able to call tits next batch of data it needs until the completion of the backtest. 

Sidenote - with the time index being the keeper of time, I see no need for realism in the time with which the data is delivered but there is always a huge need to manage hardware costs so this seems like an acceptable compromise to me. 

@cjdsellers So far I'm left with the assumption that I need to import the LiveDataEngine to build up the queue for the backtest engine to read from. How would use a loop like the event loop passed into the live trading node as the self._order_book_data, self._trade_ticks....? It expects a pandas dataframe, which would likely be the result of using pandas to make the server call anyways. The further I read into the modules the more I learn about this amazing project but ultimately end up lost.  

Any ideas or guidance would be greatly appreciated.

**Comment by limx0** [comment]
Hey @thematz1 this is definitely on our radar. There's a couple of things we'd like to improve on the backtest data loading side - I'm going to open another issue to try and summarise my thoughts on things we can improve, I'll link to it here when I get around to finishing it.

**Comment by limx0** [comment]
See https://github.com/nautechsystems/nautilus_trader/issues/337

**Comment by ian-wazowski** [comment]
@limx0 Thanks!

**Comment by ian-wazowski** [comment]
> Hi @ian-wazowski
> I am sorry, I am a newbie on this topic. Please, what are the pros and cons of the 3 solutions you mention for this use case?
> Or more exactly,
> 
> * what difference do you make between Dask (which stores and access data to parquet file through fastparquet) and what you call 'parquet (file system)' ?
> * how does compare Arctic to above solution? (I know about it by name, but I have never tried)
> 
> I am building a 'crypto data management system' based on fastparquet, but it is purely local, and at some point, I may need to make available data from it to a trading engine (which may probably be Nautilus Trader)
> In this context, I was starting to think that maybe using Git LFS as buffer might be an option.
> Hence my curiosity in this topic :)

what difference do you make between Dask (which stores and access data to parquet file through fastparquet) and what you call 'parquet (file system)' ?
1. There is no distinguishable difference. I just wanted to point out that dask is not necessary to load tick data. we just can load directly via pandas(fastparquet, arrow lib)(Assuming we already have a well-defined tick data)

2. One of the biggest reasons to use Arctic is, man group(author of arctic) already has been solved many problems that we have deal with. e.g. (creating directory scheme to save tick data(orderbook, trade, bars), compression, chunking, datetime indexing)

**Comment by limx0** [comment]
Hi @thematz1 and @yohplala - I've added the start of a PR (https://github.com/nautechsystems/nautilus_trader/pull/343/) to address some of the issues mentioned above - could you please give it a try and provide any feedback you have?

**Comment by yohplala** [comment]
> Hi @thematz1 and @yohplala - I've added the start of a PR (#343) to address some of the issues mentioned above - could you please give it a try and provide any feedback you have?

Hi @limx0 , thanks for letting us know you are working on this. I have not started yet 'playing' with Nautilus trader yet, so I will not be able to test in the short term (doing this during my spare time :)) But still I browsed the source files in your branch. I think I understand the logic and it seems good to me!

There is maybe this logic I am wondering about:
```python
                ).sort_values("timestamp_ns")
```
[link](https://github.com/nautechsystems/nautilus_trader/blob/0cf34d80e4e6c4c971c276c5dd40b876be798954/nautilus_trader/backtest/data_loader.py#L294)

I am following your discussions 'from far', but I understand you are sorting by timestamps of receipt by Nautilus trader.
May there be a case when Nautilus trader receives data in wrong order and then this timestamp is not appropriate to sort data?
Would not be `timestamp_origin_ns` more appropriate? Just an open question.

Have a good day,
Bests,

**Comment by limx0** [comment]
> Would not be `timestamp_origin_ns` more appropriate? Just an open question.

Yes it would be. I'll fix it up in my next push.

**Comment by cjdsellers** [comment]
One small point worth mentioning on the topic of timestamps is a renaming which just occurred on the latest `develop`. For data objects only `timestamp_origin_ns` and `timestamp_ns` have been renamed to `ts_event_ns` and `ts_recv_ns` respectively.

From the release notes;
In the interests of explicitness there is now a convention that timestamps are named either `timestamp_ns`, or prepended with `ts`. Timestamps which are represented with an int64 are always in nanosecond resolution, and appended with _ns accordingly.

Any thoughts or opinions here are welcome.

**Comment by yohplala** [comment]
> One small point worth mentioning on the topic of timestamps is a renaming which just occurred on the latest `develop`. For data objects only `timestamp_origin_ns` and `timestamp_ns` have been renamed to `ts_event_ns` and `ts_recv_ns` respectively.
> Any thoughts or opinions here are welcome.

Hi Christophe, no specific thoughts about this.
I am myself using `ts_event` as both timestamp of event, and timestamp of opening (k-line) in my own code.
I am not using a timestamp of receiving. In Cryptofeed, Bryant is using wording `ts_receipt`.
Bests,

**Comment by cjdsellers** [comment]
Ok sounds good. Thanks for the heads up on Bryant's terminology too!

**Comment by Hyeokreal** [comment]
Hi, @limx0 - I'm really looking forward to use data streaming(chunking) feature. I'm trying to backtest with whole instruments of 1m binance furture data but i found it consumes about 30gb ram for 30days.

I'm wondering if you keep tracking of this issue or concentrate on other issues.

Thank you always!

**Comment by limx0** [comment]
Hey @Hyeokreal, yep I will keep this issue updated. The latest work is being done in #361, but streaming data is still a little way away.

Basically we need to implement an `iter` method on the BacktestEngine, and then I could modify my code in #361 to build a graph that loads chunks and passes to this method.

Between @cjdsellers and I we will try and take a look over the next few days (hopefully it should be an easy fix)

**Comment by cjdsellers** [comment]
Hi @Hyeokreal!
So @limx0 has done a huge amount of work on the backtest experience lately, particularly around sourcing and loading data. We have a few ideas around running a `BacktestEngine` in a batch style where data is cleared and replaced with the next chunk in the stream, with the run continuing from the last state. This would overcome the problem of running into memory limitations having to hold all data for the backtest in memory at once.

How that will actually look will be determined soon as we both devote some cycles to this, either an `iter` type method option as @limx0 suggests, or some kind of `BatchRunner` type class which takes the loader and an engine and manages the run.

We'll keep everyone updated with our thoughts on this issue.

**Comment by Hyeokreal** [comment]
Thank you so much for the comments @limx0 @cjdsellers !
I'll also try to figure out the best way to achieve this feature.

**Comment by crazy25000** [comment]
> Good point.
> 
> I'm going to make the exactly same logic you mentioned using [Arctic](https://github.com/man-group/arctic)(developed by Man Group). At a very close point(may be 1~2 weeks later).
> 
> With various point of view, Dask might be a good option, but in terms of scalability and maintenance, it seems better to use arctic or parquet(file system) with s3.

+1 for Arctic. This is what I use now and plan on sticking with it.

**Comment by cjdsellers** [comment]
@limx0 and I are currently looking at this.

**Comment by OnlyC** [comment]
In term of timeseries DB,  there is one really good solution that I found & used before, https://questdb.io/.
Maybe you guys wanna take a look at it.

**Comment by cjdsellers** [comment]
So @limx0 and I have made some progress on this. 

There is now a `BacktestNode` which can execute batches of configurable runs synchronously, or built into a lazily evaluated graph for execution by a dask executor https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/backtest/node.py.

The next step will be setting up the data streaming to allow batched running. This is a goal for the new sprint starting tomorrow.

**Comment by limx0** [comment]
Hey guys - we just merged https://github.com/nautechsystems/nautilus_trader/pull/442 which gets us a little closer to streaming backtests. All that's left now is some work on the BacktestNode. 

For anyone following along with the `DataCatalog` work also - if you happen to be using a backend other than parquet (questdb, arctic etc), it should be trivial for you to subclass the `DataCatalog` and get streaming backtests working there also.

**Comment by cjdsellers** [comment]
There's also a great example notebook in `examples/backtest/notebooks`.

**Comment by limx0** [comment]
Another update here - https://github.com/nautechsystems/nautilus_trader/pull/443 has just been merged which implements this functionality. Tests are a little light on right now but I would encourage anyone interested to try it out.

If using the `BacktestNode`, simply set `batch_size_bytes` on the  `BacktestRunConfig`. 

```diff 
 venue_config = BacktestVenueConfig(
    name="SIM",
    venue_type="ECN",
    oms_type="HEDGING",
    account_type="MARGIN",
    base_currency="USD",
    starting_balances=["1000000 USD"],
)
data_config = BacktestDataConfig(
    catalog_path="/root",
    catalog_fs_protocol="memory",
    data_type=QuoteTick,
    instrument_id="AUD/USD.SIM",
    start_time=1580398089820000000,
    end_time=1580504394501000000,
)
run_config = BacktestRunConfig(
    engine=BacktestEngineConfig(),
    venues=[venue_config],
    data=[data_config],
+    batch_size_bytes=parse_bytes("100mb")
)

node = BacktestNode()
node.run_sync([run_config])

```

**Comment by cjdsellers** [comment]
We're currently refining and testing the streaming operation.

Closing this in favor of more specific issues or upgrades as they arise.
