### ISSUE TITLE
Tradestation Integration

### ISSUE THREAD

**Issue by TheRealBecks** [nautechsystems/nautilus_trader#341]
I would like to use your backtesting and live trading engine for stock trading with Tradestation. Tradestation offers an API for integration:
- https://www.tradestation.com/platforms-and-tools/web-api/
- https://developer.tradestation.com/webapi/

Tradestation has different account types for stock (and option?) trading and coin trading, but stock trading accounts and coin trading accounts belong to different legal entities. There are also test and live accounts.

**Comment by cjdsellers** [comment]
Hi and thanks for your interest in NautilusTrader!

We could support a Tradestation integration - if you were able to take the lead on the bulk of the initial development. Is this something you might be able to manage?
