### ISSUE TITLE
Error In Backtesting.

### ISSUE THREAD

**Issue by thematz1** [nautechsystems/nautilus_trader#353]
I came across this when backtesting on the develop branch (I will check master). I changed the Stop Market to Stop Limit orders in the examples/strategies/ema_cross_trail.py file. I am using trade data from the Binance API from the past 89 days. 

The error happens at different bar specifications and with different strategy parameters.  It also happens with different assets and starting currencies in the wallet.

The backtest doesn't stop. Im wondering why this error happens and if it is important or should be expected?

`2021-06-08T00:00:00.700000Z [ERR] BACKTESTER-000.ExecEngine: InvalidStateTrigger(ACCEPTED -> REJECTED)
 Traceback (most recent call last):
  File "nautilus_trader/execution/engine.pyx", line 688, in nautilus_trader.execution.engine.ExecutionEngine._handle_order_event
  File "nautilus_trader/model/orders/base.pyx", line 516, in nautilus_trader.model.orders.base.Order.apply
  File "nautilus_trader/core/fsm.pyx", line 117, in nautilus_trader.core.fsm.FiniteStateMachine.trigger`

<img width="981" alt="Screen Shot 2021-06-20 at 8 33 32 PM" src="https://user-images.githubusercontent.com/52376235/122693238-00812600-d207-11eb-9d7e-1c6550181bb1.png">

Btw, I'm really excited to see all the work in development. So much going on all the time. I try to read the code to learn because the coding level is well above mine. Thanks

**Comment by cjdsellers** [comment]
Great find!

You have indeed uncovered a bug, and also prompted some deeper thinking into whether a `LIMIT` order should be `post-only` by default.

Firstly, to cover the case of a `StopLimit` order being valid as a stop, and then rejected as a limit, we just need the addition of `ACCEPTED` -> `REJECTED` added to the state transition table. This seems reasonable, thoughts here?

Secondly, on the topic of the default value for the `post-only` execution instruction (currently `True`). I think most traders who send a `LIMIT` order probably have the intention of trading, and would rather have the order filled as marketable and incur the potential extra trading costs as a liquidity taker, than suffer an order rejection and potentially miss a trade. If a trader is market making or sensitive to costs then they could explicitly set `post-only` to true.

**Does anyone have thoughts around the default param value for `post-only`?**

**Comment by limx0** [comment]
Agreed - I would prefer `post-only` be opt-in (`False` by default), and think we should err on the side of defaults reflecting basic functionality rather than specific order types.

**Comment by cjdsellers** [comment]
Yep, good point there on basic functionality as default.

**Comment by cjdsellers** [comment]
The latest `develop` branch now includes a fix for the above. Added the state transition, and default argument for `post_only` now `False`.
