### ISSUE TITLE
Backtest Results Bug

### ISSUE THREAD

**Issue by thematz1** [nautechsystems/nautilus_trader#359]
I am currently trying to backtest using ADA/BTC trade ticks. Unfortunately, the results keep bugging in such a fashion. I keep trying to see if it is something I am doing wrong, but when reviewing the orders, positions, and account I keep seeing the issue from the get go. Could anyone help identify where I may be going wrong? Or perhaps if it is something in the program when handing suchs low values. 

`  engine.add_venue(
      venue=BINANCE,
      venue_type=VenueType.EXCHANGE,
      oms_type=OMSType.NETTING,
      account_type=AccountType.CASH,  # Spot cash account
      base_currency=None,  # Multi-currency account
      starting_balances=[Money(0.006, BTC), Money(60, ADA)],
      fill_model=fill_model,
  )`

`    strategy = EMACross(
        instrument_id=ADABTC_BINANCE.id,
        bar_spec=BarSpecification(1, BarAggregation.DAY, PriceType.LAST),
        fast_ema_period=1,
        slow_ema_period=2,
        trade_size=Decimal("20"),
        order_id_tag="001",
    )
`

<img width="1157" alt="Screen Shot 2021-06-26 at 2 11 33 PM" src="https://user-images.githubusercontent.com/52376235/123548256-08265a80-d732-11eb-8aa6-4c941e12adbb.png">

 When looking at the trade orders everything seems fine. I'm wondering if the floating point with so many zeros is to blame though.
[order_fills_1.csv](https://github.com/nautechsystems/nautilus_trader/files/6721732/order_fills_1.csv)
[positions_1.csv](https://github.com/nautechsystems/nautilus_trader/files/6721733/positions_1.csv)

The account report is where the problem can be seen in the BTC columns. The end row somehow becomes reasonable. The ADA columns moves reasonably also. The BTC in this case is sometimes ~3e-5.
[account_report_1.csv](https://github.com/nautechsystems/nautilus_trader/files/6721734/account_report_1.csv)

I am also getting this log message in each variation I tried. I have varied bar specification, I changed the base currency from None to each the base and quote currencies, and I have varied trade size and parameters. I am using the develop branch.
<img width="1357" alt="Screen Shot 2021-06-27 at 4 51 14 PM" src="https://user-images.githubusercontent.com/52376235/123559092-fd86b800-d767-11eb-8ddb-a8ec06b155e1.png">

Here is what my data table looks like.
<img width="657" alt="Screen Shot 2021-06-27 at 4 52 20 PM" src="https://user-images.githubusercontent.com/52376235/123559106-11321e80-d768-11eb-976f-098d5ece403e.png">

**Comment by cjdsellers** [comment]
I will have to look into this more closely, however it could relate to the mechanics of how we're handling trade ticks in the exchanges order book...

**Comment by cjdsellers** [comment]
Something else worth noting is that the commission modeling is still fairly generic, and so for instance does not exactly match Binance. For Binance the commission currency is base for BUY side and quote for SELL side (from memory), also there is the BNB commission discount scheme which would make the commission currency BNB.

Commission models are on the near term roadmap to address the above and above issue will be created soon.

**Comment by cjdsellers** [comment]
So for this backtest bug, if you wanted to get involved in the investigation then I would suggest a good place to start would be to read through `nautilus_trader/exectuion/client.pyx` line 662 `generate_order_filled` where you can see for a `BacktestExecutionClient` it will take the path of calculating account state which leads into `_calculate_balances` line 761. Binance should be a multi-currency CASH account.

**Comment by thematz1** [comment]
@cjdsellers thanks for the answers. I will look into proactively investigating this further after work. I will check the generate_order_fill and _calculate_balances to see if I notice a way to solve this. I will set to get ADA/USDT data so I can test with that also. 

Ill keep you posted!

**Comment by thematz1** [comment]
On ADA/USDT I see an error log of no cached balance for ADA. I haven't exported the reports but they seem normal. The account balance starting and account balance ending are the same although the commissions are 12.70979250 USDT. The backtest this time took 40 positions. I will look into the _calculate_balances and execution client when I get a chance.

**Comment by thematz1** [comment]
The balance that gets appended to balances in _calculate_multi_currency is what is shooting up from what I can tell on the logs. The currency being printed is the correct quote currency, btc is the correct commission. The PnL is the correct trade size. Somehow the balance before appending to balances makes a crazy leap in value. I only see a subtraction. Line 878 of execution/client.pyx
`                balance.total = Money(balance.total - commission, currency)
                balance.free = Money(balance.free - commission, currency)
`
Where balance is that of  the commission currency, the commission the fill.commission, and the currency is the quote currency.

**Comment by cjdsellers** [comment]
Looks like you may have narrowed it down to that commission calculation then.

You could try looking at where commission is calculated at the `SimulatedExchange`. `nautilus_trader/backtest/exchange.pyx` at line 1144.

The actual value is calculated inside `Instrument` at `nautilus_trader/model/instruments/base.pyx` from line 554.

**Comment by thematz1** [comment]
I logged the calculate commission in the instrument base and got a normal looking commission (for example 3.8930E-8). I also tried to type cast string in the Money object. Neither had a corrective change.

**Comment by thematz1** [comment]
In `nautilus_trader/execution/client.pyx` the pnl is what gets the crazy number of BTC. I have found this conclusively by logging it after line 872.

**Comment by thematz1** [comment]
`    cdef list _calculate_pnls_cash_account(
        self,
        Instrument instrument,
        OrderFilled fill,
    ):
        # Assumption that a cash account never deals
        # with inverse or quanto instruments.
        cdef list pnls = []

        cdef Currency quote_currency = instrument.quote_currency
        cdef Currency base_currency = instrument.get_base_currency()

        cdef int scale_value = 100000000

        fill.last_px = Price(fill.last_px.as_decimal() * Decimal(scale_value), 8)

        if fill.order_side == OrderSide.BUY:
            if base_currency:
                pnls.append(Money(fill.last_qty, base_currency))
            pnls.append(Money(-((fill.last_qty * (1 / fill.last_px))/scale_value), quote_currency))
        else:  # OrderSide.SELL
            if base_currency:
                pnls.append(Money(-fill.last_qty, base_currency))
            pnls.append(Money((fill.last_qty * (1 / fill.last_px))/scale_value, quote_currency))

        return pnls
`

This code solves the problem, I am just unsure it is the best approach because of additional calculations and rounding error. What do you think?

**Comment by cjdsellers** [comment]
Many thanks for being so tenacious looking into this!

I think the issue is the original calculation was assuming an inverse instrument for some reason and so recalculating the fill price as 1 / last_px. Your `scale_value` simply counteracts this for BTC.

Instead I'm about to push a fix to `develop` as such:
```
        cdef Currency quote_currency = instrument.quote_currency
        cdef Currency base_currency = instrument.get_base_currency()

        if instrument.is_inverse:
            fill_px = 1 / fill.last_px
        else:
            fill_px = fill.last_px.as_decimal()

        if fill.order_side == OrderSide.BUY:
            if base_currency:
                pnls.append(Money(fill.last_qty, base_currency))
            pnls.append(Money(-(fill.last_qty * fill_px), quote_currency))
        else:  # OrderSide.SELL
            if base_currency:
                pnls.append(Money(-fill.last_qty, base_currency))
            pnls.append(Money(fill.last_qty * fill_px, quote_currency))

        return pnls
```

Please let me know if this fixes the issue! :chart_with_upwards_trend:

**Comment by cjdsellers** [comment]
I've had another look at this, my code above is in error so looking at another fix.

**Comment by cjdsellers** [comment]
```
    cdef list _calculate_pnls_cash_account(
        self,
        Instrument instrument,
        OrderFilled fill,
    ):
        # Assumption that a cash account never deals
        # with inverse or quanto instruments.
        cdef list pnls = []

        cdef Currency quote_currency = instrument.quote_currency
        cdef Currency base_currency = instrument.get_base_currency()

        # Scale fill price to ensure correct calculations
        # for instruments with higher precision
        scaler = Decimal(1 * (10 ** instrument.price_precision))
        fill_qty: Decimal = fill.last_qty.as_decimal()
        fill_px: Decimal = fill.last_px.as_decimal() * scaler
        pnl_quote: Decimal = (fill_qty * (1 / fill_px)) / scaler

        if fill.order_side == OrderSide.BUY:
            if base_currency:
                pnls.append(Money(fill_qty, base_currency))
            pnls.append(Money(-pnl_quote, quote_currency))
        else:  # OrderSide.SELL
            if base_currency:
                pnls.append(Money(-fill_qty, base_currency))
            pnls.append(Money(pnl_quote, quote_currency))

        return pnls
```

I've come up with this, so scaler is determined by the price precision (if `price_precision` == 0 then it will be 1). e.g.
```
>>> from decimal import Decimal
>>> Decimal(1 * (10 ** 0))
Decimal('1')

>>> from decimal import Decimal
>>> Decimal(1 * (10 ** 8))
Decimal('100000000')
```

I'm at a loss as to why a scaler is necessary, however going by the above logic from your fix this _should_ work. Possibly there is something going on with the type casting during the arithmetic, possibly getting all of the underlying decimal values out "into the open" also fixes the problem without the need for a scaler - however lacking the data you are using to run the backtest, I can't check this myself.

Pushing to the `develop` branch now - please let me know if this works.

**Comment by thematz1** [comment]
> I've come up with the following fix:
> 
> ```
>     cdef list _calculate_pnls_cash_account(
>         self,
>         Instrument instrument,
>         OrderFilled fill,
>     ):
>         # Assumption that a cash account never deals
>         # with inverse or quanto instruments.
>         cdef list pnls = []
> 
>         cdef Currency quote_currency = instrument.quote_currency
>         cdef Currency base_currency = instrument.get_base_currency()
> 
>         # Scale fill price to ensure correct calculations
>         # for instruments with higher precision
>         scaler = Decimal(1 * (10 ** instrument.price_precision))
>         fill_qty: Decimal = fill.last_qty.as_decimal()
>         fill_px: Decimal = fill.last_px.as_decimal() * scaler
>         pnl_quote: Decimal = (fill_qty * (1 / fill_px)) / scaler
> 
>         if fill.order_side == OrderSide.BUY:
>             if base_currency:
>                 pnls.append(Money(fill_qty, base_currency))
>             pnls.append(Money(-pnl_quote, quote_currency))
>         else:  # OrderSide.SELL
>             if base_currency:
>                 pnls.append(Money(-fill_qty, base_currency))
>             pnls.append(Money(pnl_quote, quote_currency))
> 
>         return pnls
> ```
> 
> So scaler is determined by the price precision (if `price_precision` == 0 then it will be 1). e.g.
> 
> ```
> >>> from decimal import Decimal
> >>> Decimal(1 * (10 ** 0))
> Decimal('1')
> 
> >>> from decimal import Decimal
> >>> Decimal(1 * (10 ** 8))
> Decimal('100000000')
> ```
> 
> I'm at a loss as to why a scaler is necessary, however going by the above logic from your fix this _should_ work. Possibly there is something going on with the type casting during the arithmetic, possibly getting all of the underlying decimal values out "into the open" also fixes the problem without the need for a scaler - however lacking the data you are using to run the backtest, I can't check this myself.
> 
> Pushing to the `develop` branch now - please let me know if this works.
> 
> I'll also be writing some tests to cover this in the next few days.

If I fill these values on a calculator, fill.last_qty * (1 / fill.last_px))/scale_value, quote_currency), the division denominator being less that one seems to give large numbers. For example, 1 ADA * 1/0.00003 BTC results in 33333.3333333 although the quantity is 1 ADA which buys 0.00003 BTC the value 3333.333 comes out. A number 1 or greater will result in a number 1 or smaller when doing the division.

The abstract method is nicer, but would it also scale numbers with a precision greater than 1? I will test the push soon. I'm just waiting for this ray tune search to finish.

**Comment by cjdsellers** [comment]
Great find on this.

Now that I've put pen to paper I can see exactly whats going on, the multiplicative inverse of `fill_px` is always going to result in larger numbers when `fill_px` is fractional. In this example of ADA/BTC, the current bid price is around 0.00004100 (`price_precision` is 8). The purpose of the calculation in the BUY case is to determine how much of the quote currency (BTC) was needed to gain the base currency of ADA (we'd be buying ADA at the `ASK` and selling BTC at the `BID`).

I think this is actually just a straight forward multiplication. It costs 100 * 0.00004100 BTC to buy 100 ADA (0.0041 BTC.)
I was probably thrown a little with all the work on inverse instruments which use 1 / price to determine the base quantity.

And so I just think we need
```
        cdef Currency quote_currency = instrument.quote_currency
        cdef Currency base_currency = instrument.get_base_currency()

        fill_qty: Decimal = fill.last_qty.as_decimal()
        fill_px: Decimal = fill.last_px.as_decimal()

        if fill.order_side == OrderSide.BUY:
            if base_currency:
                pnls.append(Money(fill_qty, base_currency))
            pnls.append(Money(-(fill_px * fill_qty), quote_currency))
        else:  # OrderSide.SELL
            if base_currency:
                pnls.append(Money(-fill_qty, base_currency))
            pnls.append(Money(fill_px * fill_qty, quote_currency))

        return pnls
```

I'll push the above to `develop` and please let me know how this works for you.

**Comment by thematz1** [comment]
I just tested, pulled a few minutes ago. Seems to work fine :)

**Comment by cjdsellers** [comment]
I've just added the ADA/BTC.BINANCE instrument to the `TestInstrumentProvider` as its a good test example, and also added some tests for this calculation.

**Comment by cjdsellers** [comment]
Just pushed again - I think the 'old fix' probably worked for this case, however wasn't the most correct.
