### ISSUE TITLE
Redis int64 loss of precision after 17 digits

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#363]
It has recently come to our attention that Redis can only persist `int64` types with up to 17 significant digits of precision (it uses ASCII default stringification which outputs in scientific notation with limited precision).

Since the nanosecond timestamps have 19 digits, then there will be a loss of precision. The following warning has been added to the `RedisCacheDatabase` class docs.

```
    Warnings
    --------
    Redis can only accurately store int64 types to 17 digits of precision.
    Therefore nanosecond timestamp int64's with 19 digits will lose 2 digits of
    precision when persisted. If precision to this level is important, then you
    could additionally persist events in another medium/database which can
    properly handle int64 types.
```

Further notes:
https://github.com/redis/redis/issues/1118

**Comment by crazy25000** [comment]
Sounds like this is blocked until fixed in Redis. Or do we want to to look for alternatives?

**Comment by cjdsellers** [comment]
I looked at KeyDB however their implementation of this was the same. 

I'm perusing potential fixes or database alternatives however nothing obvious is popping up. I'm surprised there isn't more about it as the `int64` type is clearly very common and can represent many different things (not just Unix nanoseconds).

As per above, I'm accepting the current situation as is, and will eventually raise the issue with Redis - however it will have to be very well articulated to gain traction, so I've been putting it off.

**Comment by cjdsellers** [comment]
This issue has now been solved with the addition of an option flag `timestamps_as_str` for the `MsgPackSerializer`. Default is false, if set to true then will convert the `ts_event` and `ts_init` timestamps to strings on the way into Redis, and convert back to `int64_t` on the way out.

By default the Redis cache database takes an instance of this serializer. So as to avoid the precision loss this option flag as been hardcoded to true as per the below:

```
        elif config.cache_database.type == "redis":
            cache_db = RedisCacheDatabase(
                trader_id=self.trader_id,
                logger=self._logger,
                serializer=MsgPackSerializer(timestamps_as_str=True),
                config=config.cache_database,
            )
```

Granted there is some performance overhead, however this will likely be remedied in a future iteration where we look at performance optimization overall again, likely accessing the msgpack C library directly with the option of implementing a similar solution in C land.

**Comment by cjdsellers** [comment]
Updated docs:
```
cdef class RedisCacheDatabase(CacheDatabase):
    """
    Provides a cache database backed by Redis.

    Warnings
    --------
    Redis can only accurately store int64 types to 17 digits of precision.
    Therefore nanosecond timestamp int64's with 19 digits will lose 2 digits of
    precision when persisted. One way to solve this is to ensure the serializer
    converts timestamp int64's to strings on the way into Redis, and converts 
    timestamp strings back to int64's on the way out. One way to achieve this is 
    to set the `timestamps_as_str` flag to true for the `MsgPackSerializer`, as 
    per the default implementations for both `TradingNode` and `BacktestEngine`.
    """
```
