### ISSUE TITLE
Benchmarking tweaks

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#370]
Following on from #272, there are a couple of remaining minor tweaks we should do to the [newly persisted benchmarking](https://nautechsystems.github.io/nautilus_trader/dev/bench/index.html):
- Tune the rounds/iterations for each of the performance benchmark tests. I think this is mostly correct, but it needs another set of eyes over it. See https://github.com/nautechsystems/nautilus_trader/issues/272#issuecomment-822893851
- Change the generated charts (see index.html above) from reporting iterations/second to ns/iteration. This is more intuitive I believe. 
- Determine what number is actually being reported by this workflow, and potentially swap it out for the min / a low percentile (10th?)
- Add a couple more specific tests for our critical paths (data/exec engines, backtest) 

Any other thoughts would be appreciated!

**Comment by cjdsellers** [comment]
I feel benchmarking and performance optimizations is more of an epic now.

I won't close this for now in favour of granular tasks. However marking this as `epic` and moving it back to roadmap so we don't keep rolling it.

All great suggestions by @limx0 above. 

We could just create one clearly defined performance related task per sprint with an associated issue?

**Comment by cjdsellers** [comment]
As per the discussion above, now closing this epic in favor of more specific performance optimizations as issues. Performance optimization will be a goal for the project for years to come (particularly with greater amounts of Rust being introduced).
