### ISSUE TITLE
Generating incorrect account state timestamp in backtest

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#388]
It appears as though we're emitting an account state with the current timestamp in a backtest (rather than the start time of the backtest).

The below screenshot is from `examples/fx_ema_cross_audusd_bars_from_ticks.py` and pulling out ` engine.trader.generate_account_report(SIM)` after the backtest

![Screen Shot 2021-07-14 at 8 49 15 am](https://user-images.githubusercontent.com/4816153/125535022-7f1dd454-b8b5-4509-94da-48b2d7f46c3c.png)

Looking through the code (and stepping back each level):
- in `backtest/exchange.pyx` we generate the first account state on L380 using `self._clock.timestamp_ns()`
- in `backtest/engine.pyx` we instantiate the BacktestExchange on L707 with the self._test_clock`
- on L150 we initialise the `_test_clock` with the timestamp from the `LiveClock()` presumably for logging of the header

**Comment by cjdsellers** [comment]
Another great find, and many thanks for the PR with a failing test!

We managed to fix this through a solid cleanup of the backtest start-up sequence, which also uncovered some inconsistencies in log timestamps - which were also corrected. A duplicate initial account state event was also uncovered and cleaned up.

Closing as fixed from #389
