### ISSUE TITLE
Bar count + indicator value count mismatch

### ISSUE THREAD

**Issue by crazy25000** [nautechsystems/nautilus_trader#398]
I'm running into a strange miscount issue and tried to troubleshoot it, but couldn't make progress/not sure where it's coming from. When I add bars to the engine and run a backtest, the number of values generated for an indicator far exceed the number of bars.

#### To reproduce:
1. Using this example https://github.com/nautechsystems/nautilus_trader/blob/11c83f4a7bc4f05ce8655c1eb008af81ba03e090/examples/backtest/fx_ema_cross_gbpusd_bars.py#L64-L71 
2. Test data shape
    `TestDataProvider.gbpusd_1min_bid().shape = (30117, 4)`
    `TestDataProvider.gbpusd_1min_ask().shape = (30117, 4)`
3. Updated bar step from 5 to 1 https://github.com/nautechsystems/nautilus_trader/blob/11c83f4a7bc4f05ce8655c1eb008af81ba03e090/examples/backtest/fx_ema_cross_gbpusd_bars.py#L108
4. Modified the strategy to store all the calculated values for fast ema by adding `self.all_fast_ema_values.append(self.fast_ema.value)` to line 177 https://github.com/nautechsystems/nautilus_trader/blob/11c83f4a7bc4f05ce8655c1eb008af81ba03e090/examples/strategies/ema_cross_simple.py#L176-L177
5. Number of indicator values `len(strategy.all_fast_ema_values) = 41761`

I was expecting the length of values for the indicator to be less than or equal to (account for warmup) the number of 1 minute bars passed to the strategy. Are we supposed to pass data differently if we want to run the timeframe as is, like 1 minute in this case?

**Comment by cjdsellers** [comment]
For the backtest run, could you please confirm that `start` and `stop` args weren't sent in? It was a straight `run()` over all data?

**Comment by crazy25000** [comment]
Yup, I can confirm it. Aside from the modifications mentioned in the description, there weren't any other. This line was run: https://github.com/nautechsystems/nautilus_trader/blob/11c83f4a7bc4f05ce8655c1eb008af81ba03e090/examples/backtest/fx_ema_cross_gbpusd_bars.py#L118

Even if there was a start/end date, the number of indicator values should still be less than or equal to the number of bars:
`41,761 indicator vs. 30,117 bars`

**Comment by cjdsellers** [comment]
Ok good point. I'll investigate this more closely tomorrow.

I suspect it's not the indicator itself - as the counter is fairly simple and tested. So I suspect something could be up with the data processing or backtest engine.

**Comment by cjdsellers** [comment]
Ok, I can reproduce the behavior above.

There are 30117 rows in that bar data CSV.

So the `DataProducer` generates 4 ticks per bar row - to simulate an OHLC in that order.
The logs report the correct number of ticks are prepared 4 * 30117 = 120468.
```
BACKTESTER-000.BacktestDataProducer: Prepared 120,468 total data elements in 0.397s.
```

I've confirmed that the number of bars received by the strategy is the same number as the count of values produced by the indicators, which is the surprising value of 41761.

I can confirm that the timestamp of every bar being passed to `on_bar` is unique (no duplicates).

So I think we have narrowed this down to an issue upstream of when the strategy and indicator receive a bar, and downstream of where the data producer converts the bar data into ticks. I was surprised there are no duplicate timestamps although I used a set so I didn't check monotonically increasing.

I will continue the investigation. Probably looking into the bar aggregation.

**Comment by cjdsellers** [comment]
Potentially one improvement is to only print bars for known market hours for that instrument being aggregated.

Also, the lower the data resolution the less you would expect missing rows. We would never expect missing daily bars, however in thin market hours we often see missing minute bars and second bars.

**Comment by crazy25000** [comment]
> Another improvement: if a user subscribes to external_aggregation bars, then only the bars contained in the data will be emitted.
I thought this would be the default behavior, did not expect gaps to be automatically filled or extra data generated. Since there are markets that won't have 24 hour data, it would be a good idea to only emit data that's passed as the default.

I spent a few days troubleshooting this (unsuccessfully) and didn't see your new comments until now. Is this something easy/doable to figure out/refactor or would it be better for someone with more knowledge/experience like you or @limx0?

**Comment by crazy25000** [comment]
Side note/context: I ran the simple crossover strategy live in production (used fraction of a penny when trading) and when I tried to replicate the results in back-testing, there was a major discrepancy with the trades open/close dates. Than I started reviewing everything from the strategy to data to figure out what could be causing it.

**Comment by cjdsellers** [comment]
I agree that the default behavior should just be to emit them as per the data passed in. Most exchanges/brokers do aggregate time bars and provide API endpoints to query or stream them, so the platform should be able to simulate subscribing to such an endpoint rather than internally aggregating as a default.

I've been thinking about this and have a good idea for a solution for the backtest data stream handling. Basically the bars need to be held as per the data, in a list away from the main data stream, and only emitted to the `DataEngine` if a strategy subscribes to them - and at the corresponding timestamps.

**Comment by cjdsellers** [comment]
Just an update for those watching this issue.

The current plan is to wait for some imminent changes to the backtest API / implementations which will see the addition of distributed and batched running. 

At that stage it will be clearer how to proceed with a fix to achieve consistent externally aggregated bars as per the input data.

**Comment by cjdsellers** [comment]
I've come up with a fix for this issue.

Basically for `BacktestEngine` there will be a method to add `Bar` data for a particular `BarType` which be generated as per the data, and simply merged with the main backtest data stream.

You'll then just have to subscribe to the bars as you normally would, making sure to set `internal_aggregation=False`.

I'll implement this before the end of the week.

**Comment by cjdsellers** [comment]
With the latest push to the `develop` branch this has now been solved with the addition of two methods to `BacktestEngine` and the renaming of one for clarity. There are now three options for adding bar data to an engine depending on what you want to achieve:

- `add_bars` (add bars from raw data to be subscribed to for external aggregation).
- `add_bar_objects` (add built nautilus object bars to be subscribed to for external aggregation).
- `add_bars_as_ticks` (add bar data as tick rows which can then be used to subscribe to any type of bar aggregation).

@crazy25000 what you probably want is the `add_bars` method which does the obvious thing of adding bars as per the data to the main data stream (and also generating quote ticks which will be used for execution). 

I ran some tests on the test data and 30117 bars were correctly generated. The important thing to remember is when subscribing ensure `is_internal_aggregation=False` as we are simulating a subscription to an external publisher which has aggregated the bars from their own source.

Examples from the unit tests:
```
    def test_add_bars_adds_to_engine(self, capsys):
        # Arrange
        engine = BacktestEngine()
        engine.add_instrument(USDJPY_SIM)

        bar_spec = BarSpecification(
            step=1,
            aggregation=BarAggregation.MINUTE,
            price_type=PriceType.BID,
        )

        bar_type = BarType(
            instrument_id=USDJPY_SIM.id,
            bar_spec=bar_spec,
            internal_aggregation=False,  # <-- important
        )

        # Act
        engine.add_bars(
            instrument=USDJPY_SIM,
            bar_type=bar_type,
            data=TestDataProvider.usdjpy_1min_bid()[:2000],
        )

        # Assert
        log = "".join(capsys.readouterr())
        assert "Added USD/JPY.SIM Instrument." in log
        assert "Added 2000 USD/JPY.SIM MINUTE-BID tick rows." in log
        assert "Added 2000 USD/JPY.SIM-1-MINUTE-BID bar elements." in log
```

```
    def test_add_bar_objects_adds_to_engine(self, capsys):
        # Arrange
        engine = BacktestEngine()
        engine.add_instrument(USDJPY_SIM)

        bar_spec = BarSpecification(
            step=1,
            aggregation=BarAggregation.MINUTE,
            price_type=PriceType.BID,
        )

        bar_type = BarType(
            instrument_id=USDJPY_SIM.id,
            bar_spec=bar_spec,
            internal_aggregation=False,  # <-- important
        )

        bars = BarDataWrangler(
            bar_type=bar_type,
            price_precision=USDJPY_SIM.price_precision,
            size_precision=USDJPY_SIM.size_precision,
            data=TestDataProvider.usdjpy_1min_bid()[:2000],
        ).build_bars_all()

        # Act
        engine.add_bar_objects(
            bar_type=bar_type,
            bars=bars,
        )

        # Assert
        log = "".join(capsys.readouterr())
        assert "Added USD/JPY.SIM Instrument." in log
        assert "Added 2000 USD/JPY.SIM-1-MINUTE-BID bar elements." in log
```

```
    def test_add_bars_as_ticks_adds_to_engine(self, capsys):
        # Arrange
        engine = BacktestEngine()
        engine.add_instrument(USDJPY_SIM)

        # Act
        engine.add_bars_as_ticks(
            USDJPY_SIM.id,
            BarAggregation.MINUTE,
            PriceType.BID,
            TestDataProvider.usdjpy_1min_bid()[:2000],
        )

        engine.add_bars_as_ticks(
            USDJPY_SIM.id,
            BarAggregation.MINUTE,
            PriceType.ASK,
            TestDataProvider.usdjpy_1min_ask()[:2000],
        )

        # Assert
        log = "".join(capsys.readouterr())
        assert "Added 2000 USD/JPY.SIM MINUTE-BID tick rows." in log
        assert "Added 2000 USD/JPY.SIM MINUTE-ASK tick rows." in log
```
