### ISSUE TITLE
Adding a "plugin" component

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#402]
Now that the message bus is in place, it would be great to allow adding extra components to be run alongside nautilus for the purposes of computations that aren't necessarily a strategy or may be shared by multiple strategies. This could all be done in the trading strategy - but sometimes you might want to share computations between strategies or keep strategy code lean. 

A motivating example:

You wanted to compute the total volume (or similar) for a a client that doesn't implement it. You could do something like this (psuedo-ish code):

```
class TotalVolume(Plugin):

    def __init__(self, instruments):
        self.instruments = instruments
        self.total_volumes = {instrument: 0 for instrument in instruments}

    def on_startup(self):
        for instrument in self.instruments:
            self.subscribe_instruments(instrument)
            self.subscribe_trade_ticks(instrument)

    def on_trade_tick(self, tick):
        self.total_volumes[tick.instrument_id] = tick.volume
        self.publish("data.total_volume", self.total_volumes[tick.instrument_id])

# Build some backtest engine
# engine = ...

engine.add_plugin(TotalVolume)
```

I am imagining a very similar API to `TradingStrategy`. I think this would encourage cleaning up trading strategy code and also allow publishing shared messages to a wider audience (all trading strategies or whoever is subscribed).

Many trading strategies also have "calculations" they may want to run in a separate process pool or call out to other APIs to compute - this would potentially make the abstraction of these thing a littler cleaner.

**Comment by cjdsellers** [comment]
Pushed some initial code for this to `develop`.

```
class TotalVolume(Actor):
    # implementation
```

```
engine.trader.add_plugin(TotalVolume)
```

**Comment by cjdsellers** [comment]
Custom components can now be registered with a `Trader` which implement the `Actor` base class. These components will be started and stopped along with the strategies.

A `TradingStrategy` now inherits from `Actor` which has helped to break up that huge god class.

```
trader.add_component(my_component)

# and

trader.add_components([my_component1, my_component2])
```

**Comment by OnlyC** [comment]
I am able to add plugin and running it along with a trategy but how can we access plugin's calculation from strategies?

**Comment by limx0** [comment]
@OnlyC you can publish messages from the component using the `publish_data` method, which requires a `Data` subclass, and then you can listen to those messages from the trading strategy by subscribing to the channel of your subclass name on the message bus. Following on from the example above:

First, create a subclass of `Data` to wrap your values:

```
class MyCustomData(Data):
    def __init__(self, value: float):
        self.value = value
```

Next, instantiate a instance and call `publish_data`

```
class TotalVolume(Plugin):
  
    def on_trade_tick(self, tick):
        self.total_volumes[tick.instrument_id] = tick.volume
        data = MyCustomData(value=self.total_volumes[tick.instrument_id])
        self.publish_data(data)
```

Now, inside your trading strategy, you can subscribe to `data.MyCustomData`

```
class MyStrategy(TradingStrategy):

    def on_start(self):
        # Messages will be sent to `self._on_data`
        self.subscribe(topic=f"data.{MyCustomData.__name__}.*", handler=self.on_data)
```

**Comment by OnlyC** [comment]
TradingStrategy doesn't have subscribe method. 
self.msgbus.subscribe does the job.
btw, thank you so much for your detailed instructions !

**Comment by cjdsellers** [comment]
These methods are also available:
```
subscribe_data(self, ClientId client_id, DataType data_type)
subscribe_strategy_data(self, type data_type=*, StrategyId strategy_id=*)
```
