### ISSUE TITLE
Account/margin improvements

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#410]
I'd like to propose we move the current margin calculations from the instruments themselves onto the Account object. Currently the instruments themselves calculate the margin inside the portfolio, simply setting the values on the account. However the same instrument could have multiple margin calculations depending on account (cash vs margin account for example). 

I'd like to move some of this logic from the instrument onto the account, and allow a little more flexibility for customising the account for individual exchanges/brokers. Specifically I'd like a some hook (registration or subclass?) to override these calcs in an adapter or possibly even per instance. 

My immediate motivation for this is the Betfair adapter - Betfair reduces account margin on both long and short positions. But I can also imagine some more advanced users who may trade derivative products (or similar) wanting to override the margin calculations for their specific trading strategy (if they have a better understanding of how their broker calculates margin for example). I believe this is one of the final little pieces to make the platform a truly flexibly trading stack capable of tackling any instruments or exchanges.

Another little check/safety we should probably also implement is some tracking of the internal nautilus margin calculations vs the broker reported margins (where available), reporting to/warning the user where the numbers deviate by some %. This would be an adapter specific implementation. 

I believe this is a requirement for #407

**Comment by cjdsellers** [comment]
There has been recent enhancements to the account classes inspired by the above suggestions/feedback. This iteration has seen the following:

- `Account` has now been subclassed with the additions of `CashAccount` and `MarginAccount`.
- Margin calculation logic has been moved out of `Instrument` and into `MarginAccount`.
- Hooks for adding custom account classes per client/adapter have been added to `ExecutionEngine` which handles instantiation and registration of accounts based on `AccountState` events.

**Comment by limx0** [comment]
Thank you!
