### ISSUE TITLE
How to set breakpoints within cython code.

### ISSUE THREAD

**Issue by Hyeokreal** [nautechsystems/nautilus_trader#413]
Hi, always thanks for your commitment for this great repository.

I'm having hard time debugging the cython code.
I'm using the vscode with built-in debugger for the python now but i cannot set the breakpoints for the cython code part. 

I'm wondering how can I set breakpoints within cython code.
If it's not available, I'm also wondering how you guys debug the cython code (just printing the logs?).

Thank you.

**Comment by cjdsellers** [comment]
Hi @Hyeokreal 

We've made efforts to get a debugger working with Cython. I'm personally using PyCharm with a plug-in, you definitely need to build with `PROFILING_MODE=1` (this is what allows codecov to track code coverage of Cython code). 

However at this point I still haven't seen it working. We rely on writing good tests and using good old print statements :smile: 

Was there something in particular you were debugging which I could help with?

**Comment by Hyeokreal** [comment]
Thank you so much for your reply !
The problem that I was debugging has been resolved with old print statements : )
