### ISSUE TITLE
Order object should have 2 ids, a client id and an exchange/broker id

### ISSUE THREAD

**Issue by scoriiu** [nautechsystems/nautilus_trader#43]
Currently the Order is identified through the `id` member. However, when tracking the order in real live executions, the brokers usually let's the client identify the order through a `client_id` which is a unique id set by the client, as opposed to the `exchange_id` which is set upon accepting the order by the exchange. I recommend  implementing `client_id` the Order, and be passed as optional when creating an order.

The order flow I envision is as follows for tracking an order:
1) Start the webscoket stream for listening to order updates
2) Submit and order with client_id='123'. Save the order in store as submitted.
3) Order updates are received on the stream. Based on the client id, update the order state in the store.

**Comment by cjdsellers** [comment]
This is similar logic to what already occurs. Currently there is `.id` which is the identifier set by the user/client, and there is `order_id_broker` which is determined once accepted by the broker. On reflection this may be slightly confusing as it looks like its the identifier FOR the broker.

I accept the naming here could be better, `clOrderID` is already established in FIX protocols and I believe BitMEX for example use client_id and their own order_id?

I like the idea of two separate classes though so there is no chance of mixing up a `ClientOrderId` with the brokers `OrderId`... not certain of the best naming convention though.

**Comment by cjdsellers** [comment]
Also bear in mind I would like to continue having the platform general for as many trading domains as possible including more traditional brokers such as IB, FXCM etc. So it's not always an exchange we're dealing with directly.

**Comment by scoriiu** [comment]
Yes, Bitmex and many more use this notation Order.id and Order.client_id. So I think having `client_id` or `id_client` instead of `id_broker` is more clear and generic as well.

**Comment by cjdsellers** [comment]
Ok, let me have a ponder and I'll make a change.

**Comment by cjdsellers** [comment]
I've had a read of a couple of the other APIs plus FIX. `client_id` it is. I'll change the class name to `ClientOrderId` and `OrderId` will now be that which is assigned by the broker/exchange.

What are your thoughts on the position ids now? There's a similar issue.

**Comment by scoriiu** [comment]
I'm not sure I follow regarding the id-ing the position. As far as I know the position is identified by the account_id and the instrument.

**Comment by cjdsellers** [comment]
Sure. Well the platform currently allows the user to specify a `client_id` for positions ahead of time (to associate with an order), this may be redundant though. It should only be necessary to wait for the broker/exchange assigned ticket/position_id or whatever they may call it.

The refactoring for the client order ids should be complete shortly. On `Order` the property is `client_id` on the events its `cl_ord_id` just following the conventions I'm seeing in API docs.

Those broker_ids just become `id` on the Order, and `order_id` on the events.

**Comment by scoriiu** [comment]
Sounds good. Will have a look on it when finished.

**Comment by cjdsellers** [comment]
Ok I managed to get that one through. Quite a large commit.

I may need to tidy up some documentation in due course.

I'll keep investigating the usage of the position ids too.

**Comment by scoriiu** [comment]
Wow, quite a large of changes. Great work!

**Comment by cjdsellers** [comment]
I decided for clarity to standardize on `cl_ord_id` for the order property as well.

I did another refactoring sweep and picked up a lot of documentation too.

I'm investigating whether this `cl_pos_id` client position identifiers are event necessary. For simplicity it would be better just to use whatever the broker/exchange assigns (if anything).
