### ISSUE TITLE
`DataCatalog` has no `bars` method

### ISSUE THREAD

**Issue by yohplala** [nautechsystems/nautilus_trader#506]
### Expected Behavior
`myCatalog.bars(start=start, end=end)` to return requested bars, similar to what return existing methods like `myCatalog.trade_ticks(start=start, end=end)` for instance.

Not a big deal, I could see I could use `generic_data` instead.
```python
import pandas as pd
from nautilus_trader.core.datetime import dt_to_unix_nanos
from nautilus_trader.model.data.bar import Bar
start = dt_to_unix_nanos(pd.Timestamp('2021-01-01', tz='UTC'))
end =  dt_to_unix_nanos(pd.Timestamp('2021-01-02', tz='UTC'))
myCatalog.generic_data(Bar, start=start, end=end)
```
This works.
I think, still, for newbies like me, starting with not too much data first, handling bars is nice.

### Specifications
- OS Platform: Ubuntu 20.04
- NautilusTrader Version: 1.134.0

**Comment by cjdsellers** [comment]
I agree the data catalog definitely needs a bars method. We'll be sure to add this, leaving the issue open until it is.

**Comment by limx0** [comment]
Thanks for raising @yohplala! This is a simple fix - I'll add it in as soon as we have some test bar data (via #501)

**Comment by cjdsellers** [comment]
Now added from #507
