### ISSUE TITLE
TA-Lib wrapper

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#515]
It has been suggested we should include a wrapper for the excellent TA-Lib project:
https://mrjbq7.github.io/ta-lib/index.html
https://github.com/mrjbq7/ta-lib

I'd imagine this would be as simple as adding a `TALibIndicator` class, and using some kind of `indicator_name` param as a hook to then wrap the corresponding TA-Lib indicator.

I'm not completely across TA-Lib and so there could be some additional complications.

**Comment by graceyangfan** [comment]
nautilus is very powerful to write indicators，maybe more basic functions is needed，I really like the iterative update style，just wrap talib cannot perform well，because talib functions compute the indicator values just for arrays every time when a new data is coming，maybe a deep couple can solve this problem，but why not we rewrite it in cython？

**Comment by cjdsellers** [comment]
Hi @graceyangfan

So an update on this is, I've seen an implementation now however unsure how performant it is, I believe the attributes to call into TALib have to be matched using strings which is quite slow in Python.

I find most users of Nautilus are implementing their own proprietary indicators, or building models with some kind of numerical output such as a probability, or an array of values.

Can you suggest any basic functions which would assist you in writing indicators?

**Comment by graceyangfan** [comment]
@cjdsellers I think alpha101 basic operator  and some basic operator in Neural Network such as sigmod function would help a lot. In Fact,qlib(https://github.com/microsoft/qlib/blob/main/qlib/data/ops.py) provide some basic operators,with these operators,users can make their indicators simply

**Comment by graceyangfan** [comment]
@cjdsellers  I make a wrap of the patterns recognition indicators from talib,this is a independent part different from continue indicators.

**Comment by cjdsellers** [comment]
My assessment of TA-Lib is that the packaging structure is quite unwieldy, and has presented a challenge for me to install. It also doesn't seem possible to add it to the `pyproject.toml` as it can't work with conda-forge. So with a manual pip-install, the dependency is then unresolved with all other dependencies in the `poetry.lock`, and so testing becomes more difficult which reduces the reliability.

I think a better approach will be to port or create one indicator at a time rather than wrapping this external library. Users are also welcome to suggest a complete solution to the above.

Closing this for now.
