### ISSUE TITLE
API integration rate limits

### ISSUE THREAD

**Issue by happysammy** [nautechsystems/nautilus_trader#547]
Exchanges usually impose what is called a rate limit. Exchanges will remember and track your user credentials and your IP address and will not allow you to query the API too frequently. So I was wondering how you process ratelimits for these Exchanges(such as Binance or Ftx)?  As far as i know, token bucket algorithm often be used to solve the rate limit problem.

**Comment by cjdsellers** [comment]
Hi @happysammy apologies for the delayed response!

The short answer is no, the current adapters don't do a good job of handling any rate limits.

However, there is some indirect rate limiting available via the `RiskEngines` order throttler, which is configurable (100/s by default). See the `RiskEngineConfig` docs:
```
class RiskEngineConfig(pydantic.BaseModel):
    """
    Configuration for ``RiskEngine`` instances.

    Parameters
    ----------
    bypass : bool
        If True then all risk checks are bypassed (will still check for duplicate IDs).
    max_order_rate : str, default=100/00:00:01
        The maximum order rate per timedelta.
    max_notional_per_order : Dict[str, str]
        The maximum notional value of an order per instrument ID.
        The value should be a valid decimal format.
    """

    bypass: bool = False
    max_order_rate: ConstrainedStr = ConstrainedStr("100/00:00:01")
    max_notional_per_order: Dict[str, str] = {}
```

If rate limiting is extremely important, you could probably adapt the generic `Throttler` into any adapter you may be writing.

Going forward my ideas on how to handle this are:
- Leverage a library such a [ratelimit](https://github.com/tomasbasham/ratelimit) and decorate the HTTP client methods accordingly.
- Write some efficient Cython for a token bucket algo, and utilize this into the `HttpClient` base class for flexible/configurable applications of rate limiting for certain endpoint paths.
- Add functionality into adapter HTTP clients for monitoring rate limit status.

Do you have any thoughts or ideas?
