### ISSUE TITLE
Why MsgBus not use pyzmq?

### ISSUE THREAD

**Issue by hongguangguo** [nautechsystems/nautilus_trader#555]

**Comment by cjdsellers** [comment]
Hi @hongguangguo 

Thanks for your interest on this. So the purpose of the current MessageBus implementation is for messaging between components in the same process, within a single system instance (backtest or live).

You mention `pyzmq` which is a brilliant library, however its main use case is to handle IPC or messaging across a network.

**Comment by hongguangguo** [comment]
Got it, thanks!
