### ISSUE TITLE
CSVReader parser should have a separator argument

### ISSUE THREAD

**Issue by amitsinghpgs** [nautechsystems/nautilus_trader#556]
### Expected Behavior
I was working with csv zipped files which had '|' as separator. CSVReader only accepts ',' as separator currently. CSVReader should support separators other than ','

### Actual Behavior
CSVReader only accepts ',' as separator currently.

**Comment by cjdsellers** [comment]
That's a good suggestion. We'll be sure to offer a parameterized separator soon.

We'll keep this issue open until that feature is complete.

**Comment by cjdsellers** [comment]
I'm keeping an eye on it, CI seems to be failing on me following my last dependencies update (passed locally on Ubuntu).

If your run also fails on this I'll be sure to merge in the fixes before accepting your PR.

**Comment by limx0** [comment]
@cjdsellers can we close this after #557?
