### ISSUE TITLE
Some confusion when configuring Venues in BacktestVenueConfig 

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#559]
As per https://github.com/nautechsystems/nautilus_trader/issues/532#issuecomment-1026296255, there are currently not any checks in place to ensure a user doesn't add data/instruments from one `Venue` and try and configure another via `BacktestVenueConfig` or `engine.add_venue`. I think at the moment, a `ValueError("The \'instruments\' collection was empty")` error will actually be raised, which can also be confusing.

In addition, we should probably add some more detail about the `Venue` to the docs.

**Comment by cjdsellers** [comment]
This has now been improved with an additional layer of validation at the `BacktestNode`.

The check verifies that there is a matching venue for all data configs which have an `instrument_id`. If the venue is not found then a clear error message is given.
