### ISSUE TITLE
Simulate margin and leverage

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#57]
Currently there are some properties for margin reported in the `AccountState` event. The `Account` also tracks some margin information, however margin and leverage is not being entirely simulated.

Proposing we introduce some leverage configuration options and accurately simulate margin inside `SimulatedMarket`. Orders should be rejected, and positions liquidated if margin requirements are not met - as appropriate for a generic exchange at this stage.

**Comment by scoriiu** [comment]
Great. Personally I use `leverage` when simulating quite a lot. I'm not sure what is the simplest model to start with here. Tracking the margin and the liquidation price is not trivial AFAIK.

Will have to think about this.

**Comment by scoriiu** [comment]
FYI so far I'm not aware of another open source project that offers accurate margin tracking and liquidation, so this would be a big advantage if we could pull this through.

**Comment by cjdsellers** [comment]
It would be a valuable feature. I think it would just require a solid separation of concerns.

Today I've been a little bogged down reimplementing the way position ids are generated and handled. It doesn't make sense to assign them at submission, there are `PositionEvent`s generated anyway which will report what position id was assigned for an order which opened a position for example. I may just retain the option for hedging or netting type order management which can be declared at order submission.

More details soon, it'll be a fairly large diff so hold on any PRs.

**Comment by cjdsellers** [comment]
Lets revisit this once the new `Account` and `Portfolio` classes are in place.

**Comment by cjdsellers** [comment]
`Portfolio` and `Account` are getting there...

`Instrument` now has all properties necessary to simulate margin on an account.

We just need to decide where `leverage` will go, and if this can be set dynamically.

**Comment by scoriiu** [comment]
I think going with a fixed leverage non-mutable leverage in the first phase would make more sense. Later we can think to dynamically adjusting the leverage so it can work in "cross" mode, but this would be more like a nice to have feature.

**Comment by cjdsellers** [comment]
Ok, so `leverage` has been implemented as an `Instrument` property. If the leverage is set/updated then an updated `Instrument` will be sent through the system with the new leverage. The instrument loaders now accept an optional leverage argument to help with testing.

`position_margin` and `order_margin` has an initial implementation now from `Portfolio`.

`open_value` is currently based on total open position quantities (without leverage), is that the behavior we want? or should it also include leverage.

**Comment by cjdsellers** [comment]
Closing this as order and position margin is now implemented, leverage available as a property on `Instrument`.

**Comment by cjdsellers** [comment]
> I think going with a fixed non-mutable leverage in the first phase would make more sense. Later we can think to dynamically adjusting the leverage so it can work in "cross" mode, but this would be more of a nice to have feature.

Agreed that we can expand the leverage feature somewhat, probably once live trading is implemented and being tested.
