### ISSUE TITLE
Rust introduction

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#573]
We're excited to announce that the [Rust](https://www.rust-lang.org/) programming language will be reintroduced to the trunk codebase following the next release (`1.139.0`), first hitting the `develop` branch in around two weeks.

There will be no immediate effects for users who are simply installing the binary wheels from PyPI, as any Rust has already been compiled into the binaries before they are shipped.

However, developers who are working with the source code directly will need to have the latest **stable** Rust installed to be able to build the project from that point. This is quite straight forward - being achieved in a few lines of code, as per the [installing from source](https://github.com/nautechsystems/nautilus_trader/tree/develop#from-source) section of the README.

Much thought and deliberation has gone into this decision, and whilst there will be challenges, the benefits far outweigh the development cost of overcoming them. A short spiel on the thinking behind this decision, how the correctness which the project strives for will be maintained, and the beginnings of a Safety Policy around the use of Rusts `unsafe` facility can be found [here](https://docs.nautilustrader.io/developer_guide/rust.html) in the docs.

A lot of the finer details are yet to be worked out, however the general roadmap will first see Rust being increasingly used for core function and model code, then progressing into the order book and simulated exchange (matching engine).

Please let me know if you have any questions, concerns or general thoughts. I'll be sure to make myself available to assist any users who run into trouble with installing Rust, and the new build. :crab: :black_heart:

**Comment by OnlyC** [comment]
In the future, we will make indicator & strategy in Rust language? Will you drop Cython after Rust version is done?
I have plan to learn Rust, happy to hear that.

**Comment by cjdsellers** [comment]
@OnlyC The vision is that eventually a critical mass of components will be oxidized into Rust, allowing the platform to be run without using the Python run-time, especially appealing for live trading. This is probably going to take a significant amount of time to get to though, over a year minimum I would predict but who knows what may happen in terms of contributors. Python will always be a first-class citizen for the project though, and I can't see some of the data and backtesting functionality being replaced by Rust on any short to medium timeline (Python is just so suitable for alot of that, i.e. the right tool for the job).

**Comment by cjdsellers** [comment]
A user in the [discord](https://discord.gg/AUWVs3XaCS) asked the following question, which I think is important to relay here.

Q: _I'm a Python developer: Am I able to use Python only in the future? E.g. writing strategies and integrating nautilus_trader in my Python Software?_

A: Yes, there will always be a Python API for the platform. A lot of users who just `pip install nautilus_trader` might not even know some of the core is written in Rust. For users/developers who are working with the source code, if you install rustup and then install Rust stable as per the installation guide, and update it every 4-6 weeks with `rustup update` you'll be fine. It won't be necessary to know Rust, or write any Rust to use the platform. Good question, thanks for asking that :-)

Another way of looking at this is, currently we leverage Cython to create C extension modules, which is what provides the faster performance over pure Python. We're moving towards Rust for this instead of Cython.

**Comment by cjdsellers** [comment]
**Update**

The `rust-experimental` branch is likely to run for at least another release cycle before merging while the Rust -> Python bindings for core objects are bedded down, and more automated testing is written. Present benchmarks show instantiation of core objects is between 2-3x faster even when wrapped in a Python class using Cython, with arithmetic comparisons achieving an order of magnitude improvement.

**Comment by walter211** [comment]
Could you provide a rust backtest example?

**Comment by cjdsellers** [comment]
Hi @walter211 
Thanks for your interest here. The Rust language will only be used to implement core objects and components initially, and so the system will remain wrapped in a Python API for the foreseeable future. Currently I'm making sure there are absolutely no issues before merging the `rust-experimental` branch for Rust core objects.

**Comment by cjdsellers** [comment]
There is currently an open PR #606 

One challenge remaining is handling the static linking on Windows, working on it!

**Comment by cjdsellers** [comment]
The `rust-experimental` branch has now been merged into `develop`.

Closing this issue in favor of more specific tasks and bug reports!
