### ISSUE TITLE
Genetic programming optimization for backtest params 

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#589]
# Feature Request

Please provide a detailed description of your proposal, with some examples.
I just read the document,it seems that the params of strategy can only be  optimized by Grid search.genetic agorithm optimization is very popular in many quant project,polpular library such as gplearn and deap could help

**Comment by cjdsellers** [comment]
Hi @graceyangfan thanks for your interest

So one goal for this project is to stay focused on its core competency as a trading platform and framework, while remaining less opinionated over how people should trade or conduct ML (while supporting both of these as much as possible). So we like to add hooks and functionality where possible to provide generality, and leave the rest to the user.

So absolutely, I think genetic methods are great, and I believe its not too hard to adapt the way a `BacktestNode` is used for this use case. However, as it stands there aren't libraries for this wired in 'out of the box' such as `hyperopt` which is more of an experimental feature right now, and I feel building out more optimization options is something which we'll tackle longer term.
