### ISSUE TITLE
Hyperopt  optimize  require conflict

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#653]
(1)https://github.com/nautechsystems/nautilus_trader/blob/15fca3babf99c9796f19191d18ef4e25d81f6be0/nautilus_trader/backtest/hyperopt.py#L144

`hyper_research` require` self.strategy_config` be callable,
`ImportableStrategyConfig` require `self.strategy_config` be dict,dict is not callable 
(2)https://github.com/nautechsystems/nautilus_trader/blob/15fca3babf99c9796f19191d18ef4e25d81f6be0/nautilus_trader/backtest/hyperopt.py#L154
`BacktestRunConfig` has no `strategies` attribute

Version:latest develop version

**Comment by cjdsellers** [comment]
This has been repaired from 81a1f6ff3f06eb6cf9fd4377de09f433b97cebd6 and the node is now more generalized in the parameters it takes.

Whilst the API for this node could still be improved, closing this for now.
