### ISSUE TITLE
Add more indicators

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#662]
As disscussed in #515 I decided to moving more indicators to nautilus_trader with the inside functions, the main reference libaries are:
(1) [pandas-ta](https://github.com/twopirllc/pandas-ta)
(2) [finta](https://github.com/peerchemist/finta)
(3) https://github.com/mrjbq7/ta-lib
now,I am working on pandas-ta.In fact,I have rewrite some pandas-ta indicators with nautilus_trader's inside functions,I will gradually pull them.

**Comment by cjdsellers** [comment]
Many thanks for your efforts!

I haven't looked too closely at libraries 1 or 2 yet, however we do want to be mindful of bloating the project dependencies. I think more indicators are valuable, at worse we can make them optional.

**Comment by graceyangfan** [comment]
@cjdsellers Yes,using those libraries as a reference.So it is not always to repetition these indicators 100%.Now,the two added indicators give the same results with pandas-ta during my test,but I am not sure if I should include this test in unit-test code, because this introduce a new library.

**Comment by cjdsellers** [comment]
I think your current approach is good. Just using the other library is a reference to aid development, and inform the test cases - without having to take a dependency.
