### ISSUE TITLE
Defining an ABC for the DataCatalog

### ISSUE THREAD

**Issue by jordanparker6** [nautechsystems/nautilus_trader#673]
# Feature Request

Looking to define an Abstract Base Class ('ABC') for the DataCatalog to enhance the modularity and extendability of the DataCatalog. This includes refactoring the existing DataCatalog to leverage the ABC definition. This would include the renaming the current implementation of the DataCatalog to ParquetDataCatalog 

Further ambitions would be to provide an implementation of the DataCatalog ABC (BaseDataCatalog) for persistence in a SQL-like data store as an alternative to the ParquetDataStore.

**Comment by cjdsellers** [comment]
This technical direction is quite sound I think - with reference to your comments in the PR #674  feel free to push more functionality down into `BaseDataCatalog` where it makes sense. Also, if we could keep test coverage up or even increase it a little that would be idea, if you can.

With the understanding that this abstraction layer could handle basically any SQL database, out of interest were you targeting TimescaleDB in particular for your own use case?

**Comment by cjdsellers** [comment]
Well done on getting this in! 

Now that we've merged #674 closing this in favor of a more focused issue, for example implementing a `SQLDataCatalog` which could accomodate `TimescaleDB`.
