### ISSUE TITLE
Adding historic download feature to Binance adapter

### ISSUE THREAD

**Issue by jordanparker6** [nautechsystems/nautilus_trader#675]
# Feature Request

Unlike the IB adapter, the Binance adapter does not include the ability to back fill historic data. 

Please see `from nautilus_trader.adapters.interactive_brokers.historic` for the IB implementation. 

This PR will look to achieve the following:

- add a` historic.py` to the Binance adapter to reflect the `historic.py` feature offered in the IB adapter
- add tests for the new feature
- add a `historic.py` file to the adapter template. Any shared code defined between the adapters will be defined in the template file.

**Comment by cjdsellers** [comment]
This sounds like a good direction to me if we're able to consolidate some common code. I'll be interested to see how you structure this.

**Comment by graceyangfan** [comment]
would you like to improve the require_bar function at the same time to get more history bars for live trading

**Comment by OnlyC** [comment]
Binance even expose their historic trades & other data aswell here (csv zipped format): https://data.binance.vision/
