### ISSUE TITLE
Improve for request_bars function 

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#693]
# Feature Request

I am trying to using strategy with 10-SECOND-LAST-INTERNAL with binance,but the strategy need several  bars to initialize, with EXTERNAL bars, this can be realized by request_bars function,however for INTERNAL bars,I have to wait for live data to aggregate.So we need to improve request_bars functions:
(1)request EXTERNAL history bars several times to exceed the 1000 limit bars
(2)request INTERNAL history bars. first request  histrory trade_tick or quote_tick  and then auto aggregate them to get  INTERNAL history bars,of course there still need to deal with  several requests to exceed 1000 limit ticks

**Comment by cjdsellers** [comment]
I believe @jordanparker6 has a PR in the works to address pagination of historical bar requests?

**Comment by jordanparker6** [comment]
@cjdsellers yeah a while loop is resolving the pagination issues

**Comment by graceyangfan** [comment]
@jordanparker6  any process on this,I have get binance future to request EXTERNAL history bars several times to exceed the 1000 limit bars,still need some time to test it

**Comment by graceyangfan** [comment]
@cjdsellers Accurately,I have made improve to request_bars with several request to get external bars more than 1000,but binance did not provide more data for tick data,so it's difficult to make request_ticks work as I expect,maybe in the future we need to reuqest from a database or stream from other data provider,but that's a another topic,maybe close this?

**Comment by cjdsellers** [comment]
Hi @graceyangfan 

We could, although we haven't properly handled pagination yet to request > 1000 bars from Binance. We never managed to merge the work by @jordanparker6 and I've noticed a couple of users have mentioned this issue, and implemented their own workarounds.

You're right that Binance doesn't make historical ticks available through the public API.
