### ISSUE TITLE
Utility to convert streamed feather format into parquet

### ISSUE THREAD

**Issue by niks199** [nautechsystems/nautilus_trader#697]
# Feature Request

It would be nice to have a utility to convert streamed data saved in feather format into parquet format. So, stream recorded data can be used in backtest scenarios.

**Comment by cjdsellers** [comment]
Hi @niks199 

As per the Discord answer provided by @limx0 :

Theres a `read_feather_file` method in `nautilus_trader.persistence.catalog.parquet.read_feather_file`
which will return you a dataframe, which you can then call `df.to_parquet(...)` on.
