### ISSUE TITLE
Not authorized to access jupyter lab in docker container

### ISSUE THREAD

**Issue by OAuthBringer** [nautechsystems/nautilus_trader#704]
# Bug Report

### Expected Behavior
Executing the steps in the readme for running the example jupyter notebooks in the nautilus docker container should allow the user to access the notebook server.

### Actual Behavior
The user gets asked for a password or token that is never set, and appears to be explicitly overridden in the relevant dockerfile.

See: https://github.com/nautechsystems/nautilus_trader/blob/master/.docker/jupyterlab.dockerfile#L6

The logs indicate that there may be an underlying change in the jupyterlab module that may have broken the authentication bypass.

See logs:
```
[W 2022-07-21 16:32:43.953 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-07-21 16:32:43.954 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
/usr/local/lib/python3.10/site-packages/traitlets/traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '' instead of "''" if you require traitlets >=5.
  warn(
[I 2022-07-21 16:32:43.964 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-07-21 16:32:43.980 ServerApp] nbclassic | extension was successfully linked.
[I 2022-07-21 16:32:43.981 ServerApp] Writing Jupyter server cookie secret to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-07-21 16:32:44.307 ServerApp] notebook_shim | extension was successfully linked.
/usr/local/lib/python3.10/site-packages/traitlets/traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '' instead of "''" if you require traitlets >=5.
  warn(
[W 2022-07-21 16:32:44.328 ServerApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 2022-07-21 16:32:44.332 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-07-21 16:32:44.334 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/site-packages/jupyterlab
[I 2022-07-21 16:32:44.334 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2022-07-21 16:32:44.338 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-07-21 16:32:44.343 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-07-21 16:32:44.343 ServerApp] Serving notebooks from local directory: /opt/pysetup/examples/notebooks
[I 2022-07-21 16:32:44.343 ServerApp] Jupyter Server 1.18.0 is running at:
[I 2022-07-21 16:32:44.343 ServerApp] http://bedff5ba68f7:8888/lab
[I 2022-07-21 16:32:44.343 ServerApp]  or http://127.0.0.1:8888/lab
```

### Steps to Reproduce the Problem

1. `docker run -p 8888:8888 ghcr.io/nautechsystems/jupyterlab:develop` or `docker run -p 8888:8888 ghcr.io/nautechsystems/jupyterlab:latest`
2. Access the labs server via the url.
3. Note the locked state.
<img width="1046" alt="Screen Shot 2022-07-21 at 12 50 44 PM" src="https://user-images.githubusercontent.com/8813557/180269872-02e98fda-87df-423e-ac20-946260e72afe.png">

### Specifications

- OS platform: Osx Monterrey 12.01, Arch86
- Python version: n/a - Docker Desktop 4.3.1 (72247)
- `nautilus_trader` version: develop/latest containers

I'll probably just clone the repo and try to rebuild directly but I may be missing some state.

**Comment by cjdsellers** [comment]
Hi @OAuthBringer 

Thanks for your interest in the project and for trying it out! 

Both Brad @limx0 and I have tried the example out and it works fine. There shouldn't be any additional setup necessary other than what's in the README. 

Could you check you don't have another jupyter-lab server running which is overlapping with port 8888?

**Comment by OAuthBringer** [comment]
@cjdsellers 🤦 

Closing.
