### ISSUE TITLE
IB: instrumentId does not exist in a map

### ISSUE THREAD

**Issue by niks199** [nautechsystems/nautilus_trader#706]
# Bug Report
IB adapter gets instrument:
Adding instrument=Equity(id=AAPL.NASDAQ, native_symbol=AAPL, asset_class=EQUITY, asset_type=SPOT, quote_currency=USD, is_inverse=False, price_precision=2, price_increment=0.01, size_precision=0, size_increment=1, multiplier=100, lot_size=1, margin_init=0, margin_maint=0, maker_fee=0, taker_fee=0, info={}) from IB instrument provider

Subscribe(TradeTick{'instrument_id': InstrumentId('AAPL.NASDAQ')}).

but later exception happens:
File "nautilus_trader/adapters/interactive_brokers/data.py", line 170, in subscribe_trade_ticks
    contract_details: ContractDetails = self._instrument_provider.contract_details[
KeyError: InstrumentId('AAPL.NASDAQ')

instrumentId does not exist in a map.

**Comment by niks199** [comment]
figured out the issue

**Comment by limx0** [comment]
Closed by #709
