### ISSUE TITLE
IB: AssertionError on trade ticks and quoteticks

### ISSUE THREAD

**Issue by niks199** [nautechsystems/nautilus_trader#710]
# Bug Report
Value (Ticker(contract=Contract(secType='STK', conId=265598, symbol='AAPL', exchange='SMART', primaryExchange='NASDAQ', currency='USD', localSymbol='AAPL', tradingClass='NMS'), time=datetime.datetime(2022, 7, 22, 14, 30, 8, 516342, tzinfo=datetime.timezone.utc), bid=155.52, bidSize=4.0, ask=155.53, askSize=25.0, last=155.52, lastSize=1.0, prevBid=155.53, prevBidSize=15.0, prevAsk=155.54, prevAskSize=33.0, prevLast=155.53, prevLastSize=2.0, volume=158572.0, open=155.38, high=156.28, low=154.92, close=155.35, ticks=[TickData(time=datetime.datetime(2022, 7, 22, 14, 30, 8, 516342, tzinfo=datetime.timezone.utc), tickType=4, price=155.52, size=1.0), TickData(time=datetime.datetime(2022, 7, 22, 14, 30, 8, 516342, tzinfo=datetime.timezone.utc), tickType=8, price=-1.0, size=158572.0), TickData(time=datetime.datetime(2022, 7, 22, 14, 30, 8, 516342, tzinfo=datetime.timezone.utc), tickType=2, price=155.53, size=25.0), TickData(time=datetime.datetime(2022, 7, 22, 14, 30, 8, 516342, tzinfo=datetime.timezone.utc), tickType=0, price=155.52, size=4.0)]),) caused exception for event Event<updateEvent, [[None, <weakref at 0x1255adee0; to 'InteractiveBrokersDataClient' at 0x1253db040>, <function InteractiveBrokersDataClient._on_trade_ticker_update at 0x124ed0940>]]>
Traceback (most recent call last):
  File "[...]site-packages/eventkit/event.py", line 189, in emit
    result = func(obj, *args)
  File "[...]/nautilus_trader/adapters/interactive_brokers/data.py", line 311, in _on_trade_ticker_update
    update = TradeTick(
  File "nautilus_trader/model/data/tick.pyx", line 424, in nautilus_trader.model.data.tick.TradeTick.__init__
  File "nautilus_trader/core/data.pyx", line 40, in nautilus_trader.core.data.Data.__init__
AssertionError

### Expected Behavior
Add here...

### Actual Behavior
Add here...

### Steps to Reproduce the Problem

1.
2.
3.

### Specifications

- OS platform:
- Python version:
- `nautilus_trader` version:

**Comment by niks199** [comment]
@limx0 which assert could trigger this?

**Comment by cjdsellers** [comment]
Thanks for the report @niks199 

The assert which was triggering is this one on the `Data` base class L40 (with an improved error message I just added):
```
    def __init__(self, uint64_t ts_event, uint64_t ts_init):
        # Design-time invariant: correct ordering of timestamps
        assert ts_event <= ts_init, "failed invariant: `ts_event` is greater than `ts_init`"
```

Just pushed a fix for this to `develop` 217c077f01f6e83ff54ab0571156b9ef6df09b79.
 
Its a common issue if the data source `ts_event` is running ahead of the Nautilus clock. 

The options to handle this are:
1- Reduce the `ts_event` in line with `ts_init`
2- Increase the `ts_init` in line with `ts_event`
3- Fix the issue upstream (clock sync etc)

Without knowing more, if we assume the Nautilus clock is correct, and to preserve logically monotonic timestamps, then option 1 is better - which is what the fix applies.

Please reopen this issue if it persists!

**Comment by niks199** [comment]
@cjdsellers ts_init - is local time and ts_event  is event time? I think this is a legitimate scenario when event time is ahead of local time. Also event time is more precise than local time. The invariant is that next event should not have time less than the previous event. What do you think?

**Comment by cjdsellers** [comment]
The intention is that all Nautilus timestamps are UNIX nanos (UTC). `ts_event` is the timestamp the data event occurred, and `ts_init` is the timestamp the data object is initialized.

So it depends on the implementation what timestamps are actually assigned to the data object, so it's not actually a difference between data event time and local time (all timestamps are UTC), however it does matter if the clock assigning the timestamps which become `ts_event` is running ahead or behind relative to the clock Nautilus is using to produce  the `ts_init` timestamps.

So the time the data event occurred should never be greater than the time the data object was initialized, unless the clocks are significantly different, and accounting for latency.
