### ISSUE TITLE
 Lift currency precision constraint and add venue to currency map hash (code, venue)

### ISSUE THREAD

**Issue by miller-moore** [nautechsystems/nautilus_trader#715]
# Bug Report
There is currently a constraint on currency precision, which is hard coded to a maximum of 9 [in currency.pyx](https://github.com/nautechsystems/nautilus_trader/blob/8ce5b90d0fce07e7aced6f3fe4d9d5d104250352/nautilus_trader/model/currency.pyx#L72). Many cryptocurrencies have up to 18 decimal places (e.g., ETH). There is a comment recognizing this fact to the right of ETH's definition [in currencies.pyx](https://github.com/nautechsystems/nautilus_trader/blob/8ce5b90d0fce07e7aced6f3fe4d9d5d104250352/nautilus_trader/model/currencies.pyx#L69). Additionally, a currency's precision may vary from venue to venue. Would it be possible to index currencies by `code` & `venue` (still allowing `venue` to be `None`) so that exchange rates are calculated correctly?

### Expected Behavior
Add here...

### Actual Behavior
Add here...

### Steps to Reproduce the Problem

1.
2.
3.

### Specifications

- OS platform:
- Python version:
- `nautilus_trader` version:

**Comment by cjdsellers** [comment]
Hi @roon , thanks for your interest and questions!

I just changed the label from bug to question, as its more a question of why certain design choices were made.

Is there a trading venue you're aware of which supports/requires greater than 8 digits of precision?

We get some large performance optimizations using this fixed precision integer strategy which normalizes all prices, as prices can be directly compared as integers. Its actually a common approach within some larger trading firms, and some exchanges such as CME.

Having to go to a hashmap to lookup precisions based on venue every time we wanted to bring one back from the integer memory representation would be some serious overhead. Out of interest what would you expect the behaviour to be with a None venue? a certain default?

The precision is for that currency as typically represented on most trading venues (for crypto typically 8, so 9 allows mid prices). However, with the way we store prices and sizes (as fractional units), the maximum supported precision is 9, as per the above.

**Comment by cjdsellers** [comment]
Just a quick note also, that price and size precisions for certain products (i.e. spot currency pairs, perpetual futures etc) can vary from venue to venue, even for the same currencies. Nautilus supports this, see also the `Instrument` classes where currencies and their precision can be specified independently of price and size precisions.

**Comment by miller-moore** [comment]
This makes good sense. When raising this issue, I was thinking about moving money on-chain from nautilus venues and back off-chain to nautilus venues. I have not found a currency's precision to be greater than 8 on any venue that nautilus-trader supports. Considering that there is significant overhead in making this change, that the hypothetical problem seems to be outside nautilus-trader's scope to boot, and that instrument-level precisions are unaffected, I do not believe the issue is worth further consideration. Thanks for the extra insight provided in your comments!
