### ISSUE TITLE
tdameritrade version

### ISSUE THREAD

**Issue by regholl** [nautechsystems/nautilus_trader#729]
# Feature Request

is there a tdameritrade version in the near future

**Comment by cjdsellers** [comment]
Hi @regholl 

Thanks for your interest in the project!

I wouldn't say this brokerage is on our radar near term, we already have an Interactive Brokers integration which covers equities and traditional asset classes for the moment. Granted the TD Ameritrade fees are lower in many cases, however overall its not a brokerage which fits the goals for the project right now (as you've seen focusing on Crypto mostly).
