### ISSUE TITLE
[Proposal] AssetClass + AssetType

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#73]
Open for comments;

My thoughts here are that these days not every tradable asset is necessarily a Security in the traditional sense. 

So this name could be more general?

**Comment by scoriiu** [comment]
Agreed, AssetType or AssetClass makes more sense. I prefer the former.

**Comment by bohblue2** [comment]
AssetType.

**Comment by cjdsellers** [comment]
Change was made https://github.com/nautechsystems/nautilus_trader/commit/892999c0dae213b93d7ea58d0db66cb970e80c7c

**Comment by cjdsellers** [comment]
I've been considering this.

Introduced `AssetClass` and `AssetType` as there's a distinction and it can affect certain mechanics such whether to include quotes in any exchange rate calculation.

For `AssetClass` we have
`CRYPTO`
`FX`
`EQUITY`
`COMMODITY`
`BOND`

For `AssetType` we have
`SPOT`
`SWAP` aka PERPETUAL
`FUTURE`
`FORWARD`
`CFD`
`OPTION`

Some combinations aren't valid, however the value here is the enum combination can capture some important distinctions.

Are there any others we can think of?

**Comment by bohblue2** [comment]
It looks like there is not any logical flaw.

We can represent all issued instrument with this.

**Comment by cjdsellers** [comment]
This has now been actioned https://github.com/nautechsystems/nautilus_trader/commit/33d372b60f4f09277563d766e8985b7f653000d7
