### ISSUE TITLE
Open position's duration is not calculated

### ISSUE THREAD

**Issue by seongs1024** [nautechsystems/nautilus_trader#741]
# Bug Report

### Expected Behavior
`position.duration_ns` has some value.

### Actual Behavior
It is always `0`

### Steps to Reproduce the Problem

1. Backtest a strategy that is based on the position holding duration
```
position_open = self.cache.positions_open(instrument_id=self.instrument_id, strategy_id=self.id)
print(position_open[0].duration_ns)
```
2. Got `0`
```
0
```

### Specifications

- OS platform: `Windows 11 WSL Ubuntu`
- Python version: `3.10`
- `nautilus_trader` version: `1.151`

**Comment by cjdsellers** [comment]
Thanks for the report,

Just so you know, that `duration_ns` value is only updated once the position is closed (it represents the total duration the position was open). 

Does this change your expectation of the behavior at all?

**Comment by seongs1024** [comment]
Aha I should be better to go on a different approach to get the duration of the position.
Thank you!
