### ISSUE TITLE
LiveClock in live trading get thread timer

### ISSUE THREAD

**Issue by sidnvy** [nautechsystems/nautilus_trader#743]
# Bug Report

### Expected Behavior
NautilusTrader designed to be single thread in live trading mode, while whenever a strategy schedule a timer through `self.clock.set_timer(...)`, trading instance become a multi-threaded process immediately.

### Actual Behavior
<img width="877" alt="image" src="https://user-images.githubusercontent.com/3996515/186564687-53985dc9-ae2a-404b-9e9f-812ee0db572f.png">
As new timer added, a new thread spawned.

### Steps to Reproduce the Problem

1. call `self.clock.set_timer(...)` in any TradingStrategy `on_start` section.
2. run trader, check thread count via py-spy.

### Specifications

- OS platform: MacOS 12.5
- Python version: python v3.10.6
- `nautilus_trader` version: 1.151.0

**Comment by sidnvy** [comment]
https://github.com/nautechsystems/nautilus_trader/blob/9a6f74d570884aa0a30c695bd37356bc74cf34dc/nautilus_trader/trading/trader.pyx#L251

After some code diving. Found clock init problem.
Clock initialized here doesn't have the loop argument, which make them all generate `ThreadTimer`. Only LiveClock in live mode affected.
https://github.com/nautechsystems/nautilus_trader/blob/9a6f74d570884aa0a30c695bd37356bc74cf34dc/nautilus_trader/common/clock.pyx#L708-L734

**Comment by cjdsellers** [comment]
Great catch on this.

I've had a look at your PR, and I think given every strategy that is wired in needs a clock, and that we need to pass the `loop` into those `LiveClock` instances for the `LoopTimer`(s) to be able to work. Then we can't get away with needing the option for passing the kernels `loop` down into the `Trader`.

So I'll accept and merge your PR too, many thanks for your work!
