### ISSUE TITLE
ParquetDataCatalog is very slow when backtest 18G trade_tick

### ISSUE THREAD

**Issue by jandykwan** [nautechsystems/nautilus_trader#745]
# Feature Request

ParquetDataCatalog loads all the data into memory, so if the data is very big, like couple years of trade tick, it won't work. 
if it is possible that when backtest , ParquetDataCatalog will load the data month by month? thanks.

**Comment by limx0** [comment]
Hey @jandykwan - the backtest engine has a `batch_size_bytes` config option that allows streaming the data in chunks

**Comment by cjdsellers** [comment]
The Rust parquet integration will see a huge increase in performance for loading data from the Data Catalog. The Rust side is basically complete, we're just working on integrating it from the Python side at the moment.

It'll also be a breaking change though when it does land, as all the schemas have had to change to more efficient fixed width versions to take full advantage of the fixed precision integers for price and size etc

**Comment by jandykwan** [comment]
Realy thanks for your quick reply. 
Nautilus is a great project. It's much better than any other quant framework, good coding,  excellent high level design. Any plan to realease the Hybrid Cloud version? I want to buy it. Thanks again.

**Comment by cjdsellers** [comment]
Thanks so much for your kind feedback there!

I don't want to set the wrong expectations, but we're currently working towards a goal of getting an MVP going for this year.
