### ISSUE TITLE
Got segmentation fault when running the backtest example

### ISSUE THREAD

**Issue by linmingren** [nautechsystems/nautilus_trader#756]
# Bug Report

When I run the crypto_ema_cross_ethusdt_trade_ticks.py example, I got segmentation fault error.

### Expected Behavior

Finished with the performance report of backtest.

### Actual Behavior

Python crashed with segmentation fault error.

### Steps to Reproduce the Problem

1. Run "poetry install" under source code root folder, everything goes well in this step
2. Go to folder examples/backtest
3.  Run command "poetry run python -q -X faulthandler crypto_ema_cross_ethusdt_trade_ticks.py"

Then I got the following output:

Fatal Python error: Segmentation fault

Current thread 0x0000000109700600 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1176 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "xxx/nautilus_trader/nautilus_trader/backtest/data/providers.py", line 30 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "xxx/nautilus_trader/examples/backtest/crypto_ema_cross_ethusdt_trade_ticks.py", line 21 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.strptime, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pyarrow.lib, pyarrow._hdfsio, pandas._libs.ops, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pyarrow._compute, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json (total: 57)
[1]    88150 segmentation fault  poetry run python -q -X faulthandler crypto_ema_cross_ethusdt_trade_ticks.py

### Specifications

- OS platform: MacOS 12.4 Darwin x86_64 
- Python version: 3.10.6
- `nautilus_trader` version: v.151.0
- Rust: 1.63.0 (4b91a6ea7 2022-08-08)
- Cython: 3.0.0a9

**Comment by linmingren** [comment]
I found the following command will run into the same segmentation fault error, so it looks like something went wrong then python load module from a .so file.

poetry run python -c 'from nautilus_trader.model.objects import Price'

**Comment by cjdsellers** [comment]
There's a chance the last release botched the wheels, as you can see here the wheel which was uploaded for macOS x86_64 Python 3.10 was actually built on an ARM64 machine
https://github.com/nautechsystems/nautilus_trader/actions/runs/2969350061

Currently investigating how to properly built wheels on ARM64 prior to the next release (likely tomorrow).

**Comment by linmingren** [comment]
The crypto_ema_cross_ethusdt_trade_ticks.py example goes well if I install nautilus using pip.

**Comment by linmingren** [comment]
Here is the tail output when I run "objdump -tT" on the objects.cpython-310-darwin.so file.
0000000000000000         *UND* _strstr
0000000000000000         *UND* _strtol
0000000000000000         *UND* _strtoul
0000000000000000         *UND* _symlink
0000000000000000         *UND* _symlinkat
0000000000000000         *UND* _sync
0000000000000000         *UND* _sysconf
0000000000000000         *UND* _system
0000000000000000         *UND* _tcgetpgrp
0000000000000000         *UND* _tcsetpgrp
0000000000000000         *UND* _time
0000000000000000         *UND* _times
0000000000000000         *UND* _truncate
0000000000000000         *UND* _ttyname_r
0000000000000000         *UND* _tzset
0000000000000000         *UND* _umask
0000000000000000         *UND* _uname
0000000000000000         *UND* _ungetc
0000000000000000         *UND* _unlink
0000000000000000         *UND* _unlinkat
0000000000000000         *UND* _unsetenv
0000000000000000         *UND* _utimensat
0000000000000000         *UND* _vfprintf
0000000000000000         *UND* _vsnprintf
0000000000000000         *UND* _wait
0000000000000000         *UND* _wait3
0000000000000000         *UND* _wait4
0000000000000000         *UND* _waitpid
0000000000000000         *UND* _wcscat
0000000000000000         *UND* _wcschr
0000000000000000         *UND* _wcscmp
0000000000000000         *UND* _wcscoll
0000000000000000         *UND* _wcscpy
0000000000000000         *UND* _wcsftime
0000000000000000         *UND* _wcslen
0000000000000000         *UND* _wcsncat
0000000000000000         *UND* _wcsncmp
0000000000000000         *UND* _wcsncpy
0000000000000000         *UND* _wcsrchr
0000000000000000         *UND* _wcstok
0000000000000000         *UND* _wcstol
0000000000000000         *UND* _wcstombs
0000000000000000         *UND* _wcsxfrm
0000000000000000         *UND* _wmemcmp
0000000000000000         *UND* _write
0000000000000000         *UND* _writev
DYNAMIC SYMBOL TABLE:

**Comment by cjdsellers** [comment]
Just out of interest, could you please confirm the Cython version for the runs where it segfaults?

They changed the implementation of finalizers from Cython 3.0.0a10+ which can cause this. Therefore, we are currently pinned on Cython 3.0.0a9 until this is figured out.

**Comment by linmingren** [comment]
I just confirmed that my Cython version is 3.0.0a9 both from 'cython -V' and the output from "poetry install."

**Comment by cjdsellers** [comment]
Are you able to try with version 1.152.0, or is this the version after pip installing which you've tried successfully already?

**Comment by linmingren** [comment]
I tried pip installing first and everything went well, then I want to learn more so I tried to build it from source code (I run 'pip uninstall nautilus_trader' before that).

**Comment by cjdsellers** [comment]
If you're on a MacBook Pro M1, this is also something I encounter if you don't do a completely clean build with something like:
```
make clean insteall
```

Installation seems to be solid for Linux, and as far as I know Windows too.

**Comment by linmingren** [comment]
I have tried version 1.152.0 and I got the same error. I didn't touch any code before doing 'poetry install'.  I also tried 'make clean install', it doesn't help.

**Comment by linmingren** [comment]
I copies the same source code to a Ubuntu 20.04 machine and the example runs successfully without errors.

**Comment by linmingren** [comment]
I noticed that the size of file objects.cpython-310-darwin.so which I compiled from source code is 6.4M while the one installed from pip is 2.4M.

**Comment by cjdsellers** [comment]
Thanks for the info, given I don't own an x86_64 macOS machine myself, its difficult to debug. We can keep talking about it here though if you find anything further (maybe gdb or similar could help?)

We have have tests running in CI for Python 3.8, 3.9 and 3.10 for macOS x86_64 ~3500 unit and integration tests which exercises all of the code paths from that example well and truly, and haven't seen any segfaults there

At this stage, my best guess is it could be something about your local environment, compiler version, flag settings, etc... It's quite a complex beast of a codebase right now as we move towards eliminating Cython (where things will then become much simpler)

**Comment by linmingren** [comment]
Yes, I agree with you, it should be my local environment issue, I will do more investigation and will let you know if I find something interesting :)

**Comment by linmingren** [comment]
I don't know why, but if I comment out "extra_link_args=extra_link_args," in the build.py file and then run "make clean install" again,  I can  run the backtest example successfully.

**Comment by linmingren** [comment]
Don't known, but if I added features to the  pyo3 crate like this: 

`pyo3 = { version = "0.16.5" ,features = ["extension-module"]}`

 in the Cargo.toml and run peotry install again, the problem resolved on my machine.

**Comment by cjdsellers** [comment]
Ah yes, exactly. Depending on the architecture the `extension-module` feature is needed to successfully compile
