### ISSUE TITLE
[Proposal] Express commission and funding rates as percentage

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#77]
Currently commission and funding rates are expressed in basis points. For simplicity and standardization I'm proposing this be changed to a decimal percentage e.g. 

 1% = `Decimal("1")`
-0.0250% =  `Decimal("-0.0250")`

This seems to align with most fee schedules.

Thoughts/comments?

**Comment by scoriiu** [comment]
Sounds good to me.

**Comment by cjdsellers** [comment]
I think what I'll do is use decimal value as per this calculator
https://www.omnicalculator.com/finance/basis-point

So 1% = `Decimal("0.01")`

So `/ 100` doesn't need to be involved in arithmetic constantly, plus it also aligns with CCXT.

**Comment by cjdsellers** [comment]
This has now been actioned https://github.com/nautechsystems/nautilus_trader/commit/25f3c89f89caddb5556fa7f7305eeb16ed2cf763
