### ISSUE TITLE
Unable to access the bar_type on BinanceBar object

### ISSUE THREAD

**Issue by gaugau3000** [nautechsystems/nautilus_trader#784]
# Bug Report

Unable to access the bar_type on BinanceBar object.

### Expected Behavior
Access bar_type on BinanceBar object should return a BarType object

### Actual Behavior
Access bar_type on BinanceBar return missing property (but work using "type" property).

### Steps to Reproduce the Problem
`self.log.info(repr(bar), LogColor.CYAN)` print

> BinanceBar(bar_type=ETHUSDT-PERP.BINANCE-1-MINUTE-LAST-EXTERNAL, open=1338.34, high=1339.20, low=1337.48, close=1338.92, volume=140.256, quote_volume=187716.10917, count=41, taker_buy_base_volume=87.160, taker_buy_quote_volume=116664.80454, taker_sell_base_volume=53.096, taker_sell_quote_volume=71051.30463, ts_event=1663754279999000064,ts_init=1663754280554110018)

-> we see the bar_type.

when 
`self.log.info(str(dir(bar)), LogColor.CYAN) print  `

> ['__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__pyx_vtable__', '__reduce__', '__reduce_cython__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__setstate_cython__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'close', 'count', 'from_dict', 'fully_qualified_name', 'high', 'is_single_price', 'low', 'open', 'quote_volume', 'taker_buy_base_volume', 'taker_buy_quote_volume', 'taker_sell_base_volume', 'taker_sell_quote_volume', 'to_dict', 'ts_event', 'ts_init', '**type**', 'volume']

-> we don't see the bar_type but type.

### Specifications

- `nautilus_trader` version: 1.155.0

**Comment by cjdsellers** [comment]
After some consideration I think a rename of all properties which are currently named `.type` makes sense:
- Avoids conflicts with the `type` keyword (Rust) and the `type` object / class (Python)
- Keeps names aligned between Rust and Python
- Reduces any ambiguity as to what is returned by a `.*_type` property (not a `type` in these cases)

So the implications of this are:
- `Bar.type` renames to `Bar.bar_type`
- `Order.type` renames to `Order.order_type`

This breaking change will be included on my next push to `develop` and will be included in the next release.

Many thanks for your feedback here!
