### ISSUE TITLE
Add support for 1s bars timeframe for binance exchange.

### ISSUE THREAD

**Issue by gaugau3000** [nautechsystems/nautilus_trader#787]
# Feature Request

Binance now support 1s candlestick.

https://binance-docs.github.io/apidocs/spot/en/#trade-streams

It can be use full to have it ?

Many tks for this nice project !

**Comment by cjdsellers** [comment]
Looks like second bars are only available for Binance Spot currently

This had been added ec1ba4a70693f1f5eff3197a141375a448e0fbea
