### ISSUE TITLE
pylint and no-name-in-module 

### ISSUE THREAD

**Issue by gaugau3000** [nautechsystems/nautilus_trader#793]
# Feature Request
Pylint seems not happy with class that use cyphon.
`No name 'LogColor' in module 'nautilus_trader.common.logging'pylint(no-name-in-module)`

I don't know if it can be fixed (or just ignore as false positive).

Have a nice day.

**Comment by cjdsellers** [comment]
This is one of the issues with Cython and why we're moving away from it. There's a general lack of compatibility and first class support for many things.

Very soon I plan on single sourcing all enums in Rust and providing the Python bindings using PyO3. I believe this issue would be resolved then.

**Comment by cjdsellers** [comment]
Closing this one as there isn't much we can do about it while Cython is in codebase :smile:

Things will be gradually solved with more pure Python + Rust, and less Cython. 

I'm currently using nvim with the `pyright` LSP, and it just thinks Cython files are pyrex (Cython was forked from pyrex) and doesn't have much idea how to interpret them.
