### ISSUE TITLE
ImportableClientConfig factory_path doesn't work

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#815]
# Bug Report
When using ImportableClientConfig, it works perfectly except the factory_path. It does validates the path syntax as expected behavior however it has no further effect.
```python
data_clients = {
                "IB": dict(
                    factory_path="path.to.module:class",
                    config_path="nautilus_trader.adapters.interactive_brokers.config:InteractiveBrokersDataClientConfig",
                    config=dict(
                        account_id=account_id,
                        gateway_host=gateway_host,
                        trading_mode=trading_mode,
                        gateway_port=gateway_port,
                        client_id=client_id,
                        start_gateway=False,
                    ),
                ),
}
config = TradingNodeConfig(
    data_clients=data_clients,
)
node = TradingNode(config=config)
from nautilus_trader.adapters.interactive_brokers.factories import InteractiveBrokersLiveDataClientFactory
node.add_data_client_factory("IB", InteractiveBrokersLiveDataClientFactory)
```

### Expected Behavior
Node should add the client factor from the config and without the need of seperately adding. I left the factory_path to `path.to.module:class` intentionally because it has no impact. However once it works as expected it would raise error of class non-availability just like if you use generic path for config_path it throw exception. As per my debug this doesn't look adapter specific issue.

### Actual Behavior
Currently no use of it.

### Steps to Reproduce the Problem

1. Use Importable config just like above. Above is for IB but I believe it will not work for any as the issue is at core level.

### Specifications

- OS platform: 20.04.5 LTS
- Python version: 3.9
- `nautilus_trader` version: 1.155.0

**Comment by limx0** [comment]
Thanks for the report @rsmb7z - this should be closed by #860. Let us know if you have any other issues.
