### ISSUE TITLE
Keep record of an indicator's previous values

### ISSUE THREAD

**Issue by SeverinJB** [nautechsystems/nautilus_trader#817]
# Feature Request

Currently, the indicators (e.g. moving average) always only keep a record of the last value, which can be accessed through self.indicator_instance.value. I think it would be great and create consistency within the platform if the indicators' previous values could also be accessed. 

Similar to accessing a previous bar with "self.cache.bar(bar.type, index)", it would then be possible to access previous indicator values with "self.indicator_instance.value(index)".

This feature would allow using the indicator's previous values without the need to store them within the strategy.

**Comment by cjdsellers** [comment]
Hi @SeverinJB 

I think it would make more sense to store the indicator values with the strategy/actor on a case by case basis. Many indicators have output which isn't just a `value`, but may be several values, so this logic would need to be added for each indicator where its desired to cache the previous values.

Your API above actually suggests this by calling `.value(index)` on the indicator instance itself

**Comment by SeverinJB** [comment]
Hi @cjdsellers 

Thank you! I appreciate your point of view on this one. I am still familiarising myself with Nautlius and trust your judgment. 

I will go ahead and close this issue. After all, it’s easily stored case by case as you said.
