### ISSUE TITLE
catalog.list_partitions path error

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#829]
# Bug Report
Hi,
The `catalog.list_partitions` gives path error. I think it should look into data sub-folder if I am not making the wrong use of it.

### Expected Behavior
```python
    def list_partitions(self, cls_type: type):
        assert isinstance(cls_type, type), "`cls_type` should be type, i.e. TradeTick"
        name = class_to_filename(cls_type)
        dataset = pq.ParquetDataset(
            resolve_path(self.path / "data" / f"{name}.parquet", fs=self.fs), filesystem=self.fs
        )
        partitions = {}
        for level in dataset.partitions.levels:
            partitions[level.name] = level.keys
        return partitions
```

### Actual Behavior
```python
    def list_partitions(self, cls_type: type):
        assert isinstance(cls_type, type), "`cls_type` should be type, i.e. TradeTick"
        name = class_to_filename(cls_type)
        dataset = pq.ParquetDataset(
            resolve_path(self.path / f"{name}.parquet", fs=self.fs), filesystem=self.fs
        )
        partitions = {}
        for level in dataset.partitions.levels:
            partitions[level.name] = level.keys
        return partitions
```
### Steps to Reproduce the Problem

1. Store the data to catalog using `write_objects(catalog, bars)`
2. Access `catalog.list_partitions(Bar)` - its fails trying to look in CATALOG_PATH whereas the object was saved in CATALOG_PATH\data

### Specifications

- OS platform: Windows
- Python version: 3.10.6
- `nautilus_trader` version: 1.156.0

**Comment by limx0** [comment]
Thanks for the report @rsmb7z! You are correct, I have made this change in #858
