### ISSUE TITLE
TimeEvents should update backtest clock

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#831]
# Bug Report

### Expected Behavior
When creating a time event, the backtest clock should be updated to the current time when the event triggers.

### Actual Behavior
The clock is stepped forward to the next data tick.

### Steps to Reproduce the Problem
- Create two ticks days apart
  - `QuoteTick(2020-01-01)` and `QuoteTick(2020-01-03)`
- Create a time event in the middle
  - `TimeEvent(2020-01-02)`
- When the time event is triggered, the clock time will be `2020-01-03` but it should be 2020-01-02

**Comment by cjdsellers** [comment]
The accuracy of clocks used with the `BacktestEngine` has now been improved 8f560a772596ddac8f124c7273e472303a66834e:

All clocks will now match the `ts_init` (same as `ts_event`) of any triggered time events.

Say for `Data` with a `ts_init` of 2, events will be processed in the following way:
- All `TimeEvent`s **_up to_** 2 (not inclusive)
- The `Data` **_at_** 2
- All `TimeEvent`s **_at_** 2

Unfortunately the current implementation has cost us a 10% performance overhead, however in this case we'll favor accuracy and realism over performance - and optimize in Rust later.
