### ISSUE TITLE
Catalog keeps adding multiple instruments with same ID

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#833]
# Bug Report
Ideally the unique field for Instruments Catalog should be Instrument Id, and ts_event/ts_init supposed to hold the timestamp when record added. The current workaround is to set es_event/ts_init to 0 so the behavior is as expected.

### Expected Behavior
If already present it should overwrite the Instrument.

### Actual Behavior
Duplicate Instrument is added.

### Steps to Reproduce the Problem

1. Create an instrument and write to Catalog
2. Modify or Create instrument with different ts_event and ts_init
3. Add it again to the Catalog
4. It will show two instruments with same instrument_id

### Specifications

- OS platform: Windows
- Python version: 3.10.6
- `nautilus_trader` version: 1.157.0

**Comment by rsmb7zhx** [comment]
Hi,
Adding more info for the weired behavior. Even though in below example, instrument remains same, when accessing `catalog.instruments(as_nautilus=True)` it shows multiple records, although when accessing as dataframe `catalog.instruments()` it shows single record. I have done some investigation and duplicates adds upto 3 records. The quantity of records in Parquet file using Tad viewer are same as_nautilus.

To reproduce write the same instrument multiple time.
```python
from nautilus_trader.backtest.data.providers import TestInstrumentProvider
instrument = TestInstrumentProvider.default_fx_ccy('EUR.USD')
write_objects(self._catalog, [instrument])
```

**Comment by cjdsellers** [comment]
We thought checking equality after the `ts_event` and `ts_init` fields are deleted would be a good way to get around this. We'll make sure the new catalog impl handles this in a better way.

**Comment by rsmb7z** [comment]
After couple of months digging into the system and working with Parquet, actually I found it is due to the Parquet behavior `write_or_ignore` hence closed this. Let's see how things go in v2.

**Comment by cjdsellers** [comment]
We lower level libraries can handle this, then event better again.
