### ISSUE TITLE
Raise exception if `.` in Symbol or fix catalog bar_type suffix

### ISSUE THREAD

**Issue by rsmb7zhx** [nautechsystems/nautilus_trader#836]
# Feature Request

Not sure if this should come under bug however I would suggest to raise exception if '.' is present when creating Symbol and Venue.
If there is dot and you write parquet catalog using 'write_objects' it will and then write again with different bar_type, it will eventually overwrite the file on disk because suffix will never return proper bar_type in that case `suffix = df.iloc[0]["bar_type"].split(".")[1]`.

**Comment by limx0** [comment]
Nice find @rsmb7zhx - this is definitely a bug.

Could you give us an example of a symbol/venue you're trying to write? This will help with us debugging/testing.

**Comment by rsmb7zhx** [comment]
Because IB adapter is not complete yet and EUR/USD was causing issues, so I though quick fix is using IB localSymbol which is EUR.USD format for currency pairs (because the benefit is you don't need reverse conversion when dealing with IB objects). So I was download BID and ASK historical data and to my surprise files were being written on data receipt but file numbers were not increasing in folder :-D
I just noticed that because `InstrumentId.from_str('EUR.USD.IDEALPRO')` works without any issue and still allowing localSymbol fix could be `df.iloc[0]["bar_type"].split(".")[-1]`.

**Comment by cjdsellers** [comment]
Now fixed from #840, many thanks!
