### ISSUE TITLE
Creating QuoteTick object leads to "segmentation violation" error

### ISSUE THREAD

**Issue by SeverinJB** [nautechsystems/nautilus_trader#842]
# Bug Report

Hey everybody, 

I run into an error with QuoteTick. Whenever I try to use it, the program immediately fails. 

Have a great weekend, and let me know if you need anything to reproduce the error. 

### Expected Behavior
QuoteTick object created without the program failing. 

### Actual Behavior
Creating QuoteTick object results in immediate shutdown of the program with the error "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)".

### Steps to Reproduce the Problem

Please run the below minimal example for recreating the error.

```
from nautilus_trader.model.data.tick import QuoteTick
from nautilus_trader.model.identifiers import InstrumentId
from nautilus_trader.model.identifiers import Symbol
from nautilus_trader.model.identifiers import Venue
from nautilus_trader.model.instruments.equity import Equity
from nautilus_trader.model.objects import Quantity, Price
from nautilus_trader.model.currencies import USD


instrument = Equity(
                instrument_id=InstrumentId(Symbol('Test-Symbol'), Venue('Test-Venue')),
                native_symbol=Symbol('Test-Symbol'),
                currency=USD,
                price_precision=1,
                price_increment=Price(1, 1),
                multiplier=Quantity.from_int(1),
                lot_size=Quantity.from_int(1),
                ts_event=1665671425397803283,
                ts_init=1665671425397803283,
                isin=None,
                margin_init=None,
                margin_maint=None,
                maker_fee=None,
                taker_fee=None,
            )

data = QuoteTick(
            instrument_id=instrument.id,
            ask_price=instrument.make_price('1'),
            bid_price=instrument.make_price('1'),
            ask_size=instrument.make_qty('1'),
            bid_size=instrument.make_qty('1'),
            ts_event=1665671425397803283,
            ts_init=1665671425397803283,
        )

print(data)
```

### Specifications

- OS platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.10.6
- `nautilus_trader` version: nautilus-trader latest (master 1.158.0)

**Comment by cjdsellers** [comment]
So the issue here is you're passing the incorrect kwargs for prices.

They param names should be `bid` and `ask`.

I'm currently looking at why this leads to a segfault though, and not Python immediately complaining.

**Comment by cjdsellers** [comment]
Looks like this is new behaviour for the latest Cython... I recompiled with `Cython==3.0.0a9` and you should have been something like this (not a segfault):

```
def __init__(
E   TypeError: __init__() takes exactly 7 positional arguments (1 given)

nautilus_trader/model/data/tick.pyx:74: TypeError

```

**Comment by cjdsellers** [comment]
It looks like its not honoring the `not None` check on params for some reason

If I can't get to the bottom of it I'll likely roll back Cython, because this is really unhelpful behavior for users...

**Comment by cjdsellers** [comment]
I figured it out, its not Cython, its the fact we're actually calling `free` for the backing structs, and because Python raises a `TypeError` for the argument being `None`, we're never actually initializing the memory before calling free on it.

I'll fix this objects because the segfault gives no information about what the problem actually was.

**Comment by SeverinJB** [comment]
Thank you, @cjdsellers. I am glad that me overlooking something obvious did shine a light on this.

**Comment by cjdsellers** [comment]
I just pushed a change to `develop` which ensures we never segfault when a Python exception is raised during initialization (such as passing an unknown kwarg).

Please let me know if you run into this again anywhere else! :pray:
