### ISSUE TITLE
Add Data Recorder for data analysis and backtesing 

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#843]
# Feature Request

Hello,recently I am doing some research with Orderbook and Liquidation, I find it is difficult to find free data from Internet,and different data provider's data has different format, can nautilus_trader develop data record functions to record data living and save them to catalog?

**Comment by cjdsellers** [comment]
Hi @graceyangfan 

Thanks for the question. You could probably implement this, however due to certain obligations I can't give you any direction here or support it in the project. Hope you understand :pray:
