### ISSUE TITLE
Access the cache between two indexes

### ISSUE THREAD

**Issue by DownBadCapital** [nautechsystems/nautilus_trader#845]
# Feature Request

Currently, if you want to get a selection of (for example) bars from the cache you either need to loop using cache.bar which is slow.

Or, you can use cache.bars and grab the entire cache and then filter, which is wasteful, especially if you scale up the cache to 10,000+ bars.

It would be good to have a start and end index parameter's for cache.bars (plural) which instead of grabbing the entire cache would return all of the bars between the two indexes (inclusive).

**Comment by cjdsellers** [comment]
It would be fairly easy to add some kind of `start` and `end` index parameter to `cpdef list bars(self, BarType bar_type)`.

What would you expect the behavior to be if either index was out of range though?

**Comment by DownBadCapital** [comment]
If the user requests a timestamp that is not in the index, just return nothing I suppose.

**Comment by cjdsellers** [comment]
I think we'd prefer simplicity, here and keep the cache component nice and simple. Adding params for range queries would have to be applied to many of the methods for symmetry, and is something which could easily be setup in an actor or strategy?

It's also not just the overhead of the production code, but also adding all the supporting test code, and then maintaining that.

We're also happy to accept any further proposals on this, or a PR :smile:
