### ISSUE TITLE
ib_instruments.ipynb raises ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by femtotrader** [nautechsystems/nautilus_trader#854]
# Bug Report

### Expected Behavior
ib_instruments.ipynb shouldn't raises error

### Actual Behavior
ib_instruments.ipynb raises ModuleNotFoundError: No module named 'lxml'

### Steps to Reproduce the Problem

1. docker run -p 8888:8888 ghcr.io/nautechsystems/jupyterlab:develop
2. browse http://127.0.0.1:8888/lab/tree/ib_instruments.ipynb
3. CTRL + enter

### Specifications

- OS platform:
- Python version:
- `nautilus_trader` version:

**Comment by limx0** [comment]
Hi @femtotrader - this notebook should not have been commited to the repo, I am removing it in #859.

The same functionality exists here - https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_trader/adapters/interactive_brokers/web.py

So you can: 

```python
from nautilus_trader.adapters.interactive_brokers.web import ProductClass, Exchange, load_instrument_list

products = load_product_list(exchange=Exchange.NYSE, product_class=ProductClass.STOCKS)
```
