### ISSUE TITLE
Doc Error - Bar

### ISSUE THREAD

**Issue by DownBadCapital** [nautechsystems/nautilus_trader#856]
# Bug Report

### Expected Behavior
Bar still has parameter and method "bar_type" in the docs, when it should have "type".

Apologies, not sure how to make request to change docs, they seem to be autopopulated.

**Comment by cjdsellers** [comment]
Thanks for checking in on it.

So we actually decided to move towards being explicit and renamed this to `.bar_type` rather than the generic `.type` which is illegal syntax in Rust too.
