### ISSUE TITLE
Different function arguments type in _request_bars 

### ISSUE THREAD

**Issue by Tzumx** [nautechsystems/nautilus_trader#879]
# Bug Report

In nautilus_trader.adapters.binance.futures.data.BinanceFuturesDataClient._request_bars we are waiting "Timestamp":

```
from_datetime: Optional[pd.Timestamp],
 to_datetime: Optional[pd.Timestamp],
```

but below in code we have

```
if from_datetime is not None:
            start_time_ms = secs_to_millis(from_datetime)
```

we are waiting for a double?

`(cpdef uint64_t secs_to_millis(double secs))`

### Expected Behavior
Should convert pd.Timestamp into timestamp at first.

        start_time_ms = None
        if from_datetime is not None:
            from_datetime = from_datetime.timestamp()
            start_time_ms = secs_to_millis(from_datetime)

        end_time_ms = None
        if to_datetime is not None:
            to_datetime = to_datetime.timestamp()
            end_time_ms = secs_to_millis(to_datetime)

### Actual Behavior
 Produce exemption when request_bars in strategy:

### Steps to Reproduce the Problem

1. Create a strategy
2. Add in it requesting bars with period arguments
3. Get exemption

### Specifications

- OS platform: Ubuntu 20.04 LTS
- Python version: 3.10.8
- `nautilus_trader` version: 1.160

**Comment by cjdsellers** [comment]
Hi @Tzumx 

Thanks so much for the report. This is now fixed on `develop` from 609a63425a8199a0bd1a0808283573a8eb202e65 and will make it into the next release!
