### ISSUE TITLE
Documentation Table of Contents

### ISSUE THREAD

**Issue by DownBadCapital** [nautechsystems/nautilus_trader#887]
# Bug Report
https://docs.nautilustrader.io/api_reference/config.html
![image](https://user-images.githubusercontent.com/109688391/205419389-61098b3d-1ca5-4210-93d7-9ec48f5dc2f2.png)

3rd level of the TOC is hard to read. Color is too dark.

My suggestion would be to remove the 3rd level entirely, or hide it behind a dropdown. I don't recall this being here a couple of months back, and its addition makes the docs harder to scroll. But also CTRL+F becomes more challenging, hence my preference is to remove it entirely rather than hiding behind a dropdown.

**Comment by cjdsellers** [comment]
So the behavior of this is controlled by the `sphinx-external-toc` extension. We recently (26th Nov) upgraded the version of it - which may have produced this behavior. 

It actually looks like it has more potential use and picks up all the methods, however its not fitting into the formatting and styling of the docs so I've reverted it for now.

I'll keep an eye on it, and if we get back to the original TOC menu then I'll close this.

**Comment by cjdsellers** [comment]
I've now fixed both the color, and toc collapse of the right sidebar.

Showing the inheritance seems to truncate the namespace with the longer ones, so will work on improving that too.

Closing this for now.
