### ISSUE TITLE
More indicators

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#89]
Whilst many quant traders are using bespoke machine learning models / proprietary indicators, it would still be valuable to add some more "standard" indicators for the more traditional algo traders.

Putting out an open invitation for anyone to add an indicator including unit tests.

Alternatively I'm "taking requests" and suggestions for indicators!

**Comment by ian-wazowski** [comment]
cusum filter and related trading strategy [here](http://momentum.technicalanalysis.org.uk/LaYa97.pdf)

I am working on this, I'II let you know when done.
