### ISSUE TITLE
Improve filters for InstrumentProvider config 

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#904]
# Feature Request

We currently have `filters: Optional[dict[str, Any]] = None` on the `InstrumentProviderConfig` for passing an optional filter to the adapters InstrumentProvider, which can be tricky for users to implement and use. The dict does not allow validation until nautilus starts up, which can cause frustration and slow iteration when trying to get something working.  

I propose we remove the loose dicts in favour of each adapter implementing their own msgspec class for configuration. 

An example can be found [here](https://github.com/nautechsystems/nautilus_trader/blob/54df7d9400995460cf125d32051587ea8e7e7ed0/nautilus_trader/adapters/interactive_brokers/config.py#L25)

**Comment by cjdsellers** [comment]
Closed as completed.
