### ISSUE TITLE
Wrangler process_bar_data creates malformed ticks if either of BID/ASK bar missing

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#923]
# Bug Report

### Expected Behavior
Wrangler should ignore / drop NaN if either of BID/ASK bars missing for same ts_event.

### Actual Behavior
Wrangler currently processes without error or ignoring by creating malformed QuoteTick.

### Steps to Reproduce the Problem

1. Use QuoteTickDataWrangler.process_bar_data to generate ticks with some bars missing in either BID or ASK from input data
2. Wrangler shall produce malformed tick similar to below
`QuoteTick(AAPL.NASDAQ,14.26,-9223372036.85,1000000,9223372037,1320696059700000000)`

### Specifications

- OS platform: Windows 10
- Python version: 3.10.6
- `nautilus_trader` version: 1.163.0 (master)

**Comment by cjdsellers** [comment]
Many thanks for the report, and I believe you have kindly fixed this from #924 :pray:
