### ISSUE TITLE
Potential memory leak in backtesting (v2)

### ISSUE THREAD

**Issue by Tzumx** [nautechsystems/nautilus_trader#930]
# Bug Report

First of all, thanks for the efforts in solving this problem ( #880 ). The behaviour has improve heavily. You can compare those two screens with 1.160 and 1.163 version. It takes much more time to get the same size of memory:
![memory_leak_nautilus_1 160](https://user-images.githubusercontent.com/91601062/209662159-d10d7a28-5de3-4920-b5ee-34a2ec925293.png)

![memory_leak_nautilus_1 163](https://user-images.githubusercontent.com/91601062/209686899-87dc8a74-0bb6-4147-b222-401392df2609.png)

But the problem with memory leak is still present.

In backtesting (using batches per day) in case we use a lot of data (like millions of QuoteTicks), we get continuous rising of allocated memory.

### Expected Behavior
Used instances of data should be properly delete / collected by garbage collector.

### Actual Behavior
Looks like some instances of data remains alive and consume memory

### Steps to Reproduce the Problem

Example:
[memory_leak](https://github.com/limitless-galaxy/memory_leak)

    Take any strategy (signal_strategy from nautilus examples)
    Generate about 9 million QuoteTicks per day
    Send it to the backtesting

### Specifications

- OS platform: Ubuntu 20.04 LTS, Mac
- Python version: 3.10.9
- `nautilus_trader` version:  version: 1.163
- Tested on AMD Ryzen 9 5950X, 4*32GB and local PCs

**Comment by cjdsellers** [comment]
Thanks for continuing to investigate.

So the plan is to finish off the single sourcing of enums on the Rust side in the next day or so.

Then merge the new C string over pointers implementation from @ghill2.

Then we'll see where we're at in terms of leaks.

**Comment by cjdsellers** [comment]
So we've now completed points 1 and 2 above, and we seem to again have a huge improvement in memory management. Below is a screenshot from a test I just ran with over 1100 samples of running `crypo_ema_cross_ethusdt_trade_ticks.py` in a loop. Memory grew from ~150 MB to ~218 MB.

That script does need modifying a little, adding a `while True`, and commenting out the `input`. Having said that it'll be a good idea to have a standard test setup for checking memory performance, so I'll add one including instructions on how to run with `memray` to the `performance` tests.

Please let me know how testing goes at your end.

![image](https://user-images.githubusercontent.com/22510164/210158048-4df1aad0-57a2-4a2d-a761-56f097506407.png)

**Comment by cjdsellers** [comment]
I'll close this for now, and we can open a v3 if we want to get to the next level in terms of leak plugging. I feel we're at an acceptable point now though.

@twitu and I have plans to carry out more targeted leak testing, because we'd like to further refine the C string conversions - potentially reducing copying. We'll see how far we get there.
