### ISSUE TITLE
ParquetDataCatalog Bars reading

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#939]
# Sharing my experience for improvement in ParquetDataCatalog

Hi,
I know you guys are working to improve parquet reader and porting to Rust. Not sure if you have tried through pandas using below example which have significant improvement. Following is the comparison using both methods.

- `bar.parquet` having 912k+ files in total
- Each partition having 1,875 files with weekly data
- Both results being returned are same and in DataFrame

## Data loads in < 2 seconds
```
import time
import pandas as pd
from nautilus_trader.serialization.arrow.util import clean_key
instrument_id = 'EUR/USD.IDEALPRO'
bar_type = f"{instrument_id}-1-MINUTE-MID-EXTERNAL"
full_path = f"{CATALOG_PATH}/data/bar.parquet/instrument_id={clean_key(instrument_id)}"
perf_start = time.perf_counter()
df = pd.read_parquet(path=full_path, filters=[("bar_type", "=", bar_type)])
print(f"Bars loaded in {time.perf_counter() - perf_start:0.4f} seconds for {instrument_id}")
```

## Data loads in approx 27 mintues (on SSD)
```
import time
import pyarrow as pa
from nautilus_trader.persistence.catalog import ParquetDataCatalog
instrument_id = 'EUR/USD.IDEALPRO'
bar_type = f"{instrument_id}-1-MINUTE-MID-EXTERNAL"
catalog = ParquetDataCatalog(CATALOG_PATH)
perf_start = time.perf_counter()
df = catalog.bars(as_nautilus=False, instrument_id=[instrument_id], filter_expr=(pa.dataset.field("bar_type").isin([bar_type])))
print(f"Bars loaded in {time.perf_counter() - perf_start:0.4f} seconds for {instrument_id}")
```

If this is something dropped for some issue, this can be closed.

**Comment by cjdsellers** [comment]
Lets keep this open, there's a new pyo3 based implementation on a branch. We're just working on integration the build right now, then we can re-asses this performance once thats merged.

**Comment by rsmb7z** [comment]
Closing this as subject resolution planned in #991.
