### ISSUE TITLE
GTD expiration of partially filled order blocks backtest

### ISSUE THREAD

**Issue by bb01100100** [nautechsystems/nautilus_trader#943]
# Bug Report

Hello, I think I've run into a bug in the backtester, details below. If you have any suggestions on how to work around this, that would be great. I suppose I could reduce my backtest equity value, or reload the data with more volume on the bid/ask.

### Expected Behavior
Partially filled limit orders that expire due to a GTD condition should not cause the backtester to get into a state whereby it retains the order but will not cancel it.

### Actual Behavior
When the backtester attempts to cancel the partially filled order, it logs an invalid state warning: `[WRN] BACKTESTER-001.ExecEngine: InvalidStateTrigger: PARTIALLY_FILLED -> EXPIRED, did not apply OrderExpired(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059, account_id=SIM-001, ts_event=1641859200000000000)`

### Steps to Reproduce the Problem
1. Backtest data is loaded into the catalogue, with bid and ask quantities set to 100,000.
2. A 1-minute timeframe strategy places a limit order with a GTD expiry, with a size that exceeds 100,000 (e.g. in my bug it is 131,000)
3. The order is partially filled (100k fill): `[EVT] OrderFilled(instrument_id=EUR/JPY.SIM, 
client_order_id=O-20220110-001-000-61, 
venue_order_id=SIM-1-061, 
account_id=SIM-001, 
trade_id=SIM-1-044, position_id=EUR/JPY.SIM-H3Strategy-000, 
order_side=BUY, order_type=LIMIT, last_qty=100_000, last_px=131.052 JPY, commission=262 JPY, liquidity_side=MAKER, ts_event=1641807900000000000)`
4. Price never drops below the limit price so the order remains partially filled during the trading session
5. The backtester expires the order, which causes a warning about invalid state: `[WRN] BACKTESTER-001.ExecEngine: InvalidStateTrigger: PARTIALLY_FILLED -> EXPIRED, did not apply OrderExpired(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059, account_id=SIM-001, ts_event=1641859200000000000)`
6. While the 100k position can be closed, the partially filled order cannot be cancelled: 
6.1 `2022-01-11T05:00:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: [CMD]--> CancelOrder(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059).`
6.2 `2022-01-11T05:00:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: No open positions to close.`
6.3 `2022-01-11T05:01:00.000000000Z [WRN] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderCancelRejected(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059, account_id=SIM-001, reason=ClientOrderId('O-20220110-001-000-59') not found, ts_event=1641877260000000000).`

#### Sequence of events from the logs

Backet order initialised and submitted:
Entry `2022-01-10T08:02:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderInitialized(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, side=SELL, type=LIMIT, quantity=131_500, time_in_force=GTD, post_only=False, reduce_only=False, options={'price': '131.166', 'display_qty': None, 'expire_time_ns': 1641859199000000000}, emulation_trigger=NONE, contingency_type=OTO, order_list_id=20, linked_order_ids=['O-20220110-001-000-60', 'O-20220110-001-000-61'], parent_order_id=None, tags=ENTRY).`

Stop loss `2022-01-10T08:02:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderInitialized(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-60, side=BUY, type=STOP_MARKET, quantity=131_500, time_in_force=GTC, post_only=False, reduce_only=True, options={'trigger_price': '131.280', 'trigger_type': 'DEFAULT', 'expire_time_ns': 0}, emulation_trigger=NONE, contingency_type=OUO, order_list_id=20, linked_order_ids=['O-20220110-001-000-61'], parent_order_id=O-20220110-001-000-59, tags=STOP_LOSS).`

Take profit `2022-01-10T08:02:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderInitialized(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-61, side=BUY, type=LIMIT, quantity=131_500, time_in_force=GTC, post_only=True, reduce_only=True, options={'price': '131.052', 'display_qty': None, 'expire_time_ns': 0}, emulation_trigger=NONE, contingency_type=OUO, order_list_id=20, linked_order_ids=['O-20220110-001-000-60'], parent_order_id=O-20220110-001-000-59, tags=TAKE_PROFIT). `

Everything accepted:
`2022-01-10T08:02:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderAccepted(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059, account_id=SIM-001, ts_event=1641801720000000000).`
`2022-01-10T08:02:00.000000000Z [INF] BACKTESTER-001.OrderMatchingEngine(SIM): Pending OTO O-20220110-001-000-60 triggers from O-20220110-001-000-59`
`2022-01-10T08:02:00.000000000Z [INF] BACKTESTER-001.OrderMatchingEngine(SIM): Pending OTO O-20220110-001-000-61 triggers from O-20220110-001-000-59`

Entry order partially filled:
`2022-01-10T09:17:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderFilled(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059, account_id=SIM-001, trade_id=SIM-1-043, position_id=EUR/JPY.SIM-H3Strategy-000, order_side=SELL, order_type=LIMIT, last_qty=100_000, last_px=131.166 JPY, commission=262 JPY, liquidity_side=MAKER, ts_event=1641806220000000000).`
`2022-01-10T09:17:00.000000000Z [INF] BACKTESTER-001.Portfolio: EUR/JPY.SIM net_position=-100000.0  `

100k position opened:
`2022-01-10T09:17:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] PositionOpened(instrument_id=EUR/JPY.SIM, position_id=EUR/JPY.SIM-H3Strategy-000, account_id=SIM-001, opening_order_id=O-20220110-001-000-59, closing_order_id=None, entry=SELL, side=SHORT, net_qty=-100000.0, quantity=100_000, peak_qty=133_900, currency=JPY, avg_px_open=131.166, avg_px_close=0.0, realized_return=0.00000, realized_pnl=-47_151 JPY, unrealized_pnl=0 JPY, ts_opened=1641806220000000000, ts_last=1641806220000000000, ts_closed=0, duration_ns=0).`

TP & Stop loss orders accepted:
`2022-01-10T09:17:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderAccepted(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-60, venue_order_id=SIM-1-060, account_id=SIM-001, ts_event=1641806220000000000).`

`2022-01-10T09:17:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderAccepted(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-61, venue_order_id=SIM-1-061, account_id=SIM-001, ts_event=1641806220000000000).`

Trade stopped out for a loss:
`2022-01-10T09:45:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderFilled(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-61, venue_order_id=SIM-1-061, account_id=SIM-001, trade_id=SIM-1-044, position_id=EUR/JPY.SIM-H3Strategy-000, order_side=BUY, order_type=LIMIT, last_qty=100_000, last_px=131.052 JPY, commission=262 JPY, liquidity_side=MAKER, ts_event=1641807900000000000).`
`2022-01-10T09:45:00.000000000Z [INF] BACKTESTER-001.Portfolio: EUR/JPY.SIM net_position=0.0`

100k Position closed:
`2022-01-10T09:45:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] PositionClosed(instrument_id=EUR/JPY.SIM, position_id=EUR/JPY.SIM-H3Strategy-000, account_id=SIM-001, opening_order_id=O-20220110-001-000-59, closing_order_id=O-20220110-001-000-61, entry=SELL, side=FLAT, net_qty=0.0, quantity=0, peak_qty=133_900, currency=JPY, avg_px_open=131.166, avg_px_close=131.052, realized_return=0.00087, realized_pnl=-36_013 JPY, unrealized_pnl=0 JPY, ts_opened=1641806220000000000, ts_last=1641807900000000000, ts_closed=1641807900000000000, duration_ns=1680000000000).`

Stop loss & TP orders cancelled:
`2022-01-10T09:45:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderCanceled(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-61, venue_order_id=SIM-1-061, account_id=SIM-001, ts_event=1641807900000000000).`

`2022-01-10T09:45:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderCanceled(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-60, venue_order_id=SIM-1-060, account_id=SIM-001, ts_event=1641807900000000000).`

At midnight (next bar after GTD of 23:59:59) the backtest engine tries to cancel the entry order and fails:
`2022-01-11T00:00:00.000000000Z [WRN] BACKTESTER-001.ExecEngine: InvalidStateTrigger: PARTIALLY_FILLED -> EXPIRED, did not apply OrderExpired(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059, account_id=SIM-001, ts_event=1641859200000000000)`

I log out the order via `self.cache.orders_open()`:

`1970-01-01T00:00:00.000000000Z [INF] TRADER-000.BACKTEST_LOGGER: LimitOrder(SELL 131_500 EUR/JPY.SIM LIMIT @ 131.166 GTD 2022-01-10T23:59:59.000Z, status=PARTIALLY_FILLED, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059, contingency_type=OTO, linked_order_ids=[O-20220110-001-000-60, O-20220110-001-000-61], tags=ENTRY)`

`2022-01-11T05:00:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: [CMD]--> CancelOrder(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059).`

I also call `self.close_all_positions(self.instrument_id)`:
`2022-01-11T05:00:00.000000000Z [INF] BACKTESTER-001.H3Strategy-000: No open positions to close.`

On the next bar we get the warning about the entry order cancellation being rejected, yet it's there in the cache:

`2022-01-11T05:01:00.000000000Z [WRN] BACKTESTER-001.H3Strategy-000: <--[EVT] OrderCancelRejected(instrument_id=EUR/JPY.SIM, client_order_id=O-20220110-001-000-59, venue_order_id=SIM-1-059, account_id=SIM-001, reason=ClientOrderId('O-20220110-001-000-59') not found, ts_event=1641877260000000000).`

### Specifications

- OS platform: macos
- Python version: 3.10.7
- `nautilus_trader` version: 1.164.0

**Comment by cjdsellers** [comment]
Hi @bb01100100 

You've indeed uncovered a bug in the order state transition table. The state `PARTIALLY_FILLED` -> trigger `EXPIRED` didn't previously exist. So I've added that and should now work on `develop`.

```python
...
    (OrderStatus.PARTIALLY_FILLED, OrderStatus.PENDING_UPDATE): OrderStatus.PENDING_UPDATE,
    (OrderStatus.PARTIALLY_FILLED, OrderStatus.PENDING_CANCEL): OrderStatus.PENDING_CANCEL,
    (OrderStatus.PARTIALLY_FILLED, OrderStatus.CANCELED): OrderStatus.CANCELED,
    (OrderStatus.PARTIALLY_FILLED, OrderStatus.EXPIRED): OrderStatus.EXPIRED,  # <------------ added this
    (OrderStatus.PARTIALLY_FILLED, OrderStatus.PARTIALLY_FILLED): OrderStatus.PARTIALLY_FILLED,
    (OrderStatus.PARTIALLY_FILLED, OrderStatus.FILLED): OrderStatus.FILLED,
}
```
