### ISSUE TITLE
Bar with OHLC having Decimal

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#970]
# Feature Request

Hi @cjdsellers 
There is a scenario for BarType where all Bar charactristics are same except:

- Instead of Price_Type, its Data_Type such as `HISTORICAL_VOLATILITY`, or `OPTION_IMPLIED_VOLATILITY`
- OHLC hold Decimal instead of Price

For example `MSFT.NASDAQ-1-HOUR-HISTORICAL_VOLATILITY-EXTERNAL` and `MSFT.NASDAQ-1-HOUR-OPTION_IMPLIED_VOLATILITY-EXTERNAL`.

Do you think this is something can be integrated in existing Bar, or will make it complicated and seperate/clone object should be used?

**Comment by cjdsellers** [comment]
So there's two parts to this:
- 1: How do we represent these aggregations as a `BarSpecification`?
- 2: What should the type of `Bar` be? what should the field types be?

For 1, we need to keep the parsed bar specification to three hyphen separated tokens:
```
{step}-{aggregation}-{price_type}
```

Unless we change that, I don't think a volatility really qualified as a price type. Because of that, they probably need to look more like this `MSFT.NASDAQ-1-HOUR_HISTORICAL_VOLATILITY-EXTERNAL`. Which is more or less what you have above, just one additional underscore.

For 2, we have three options:
- Just use the existing `Bar` and make the OHLC of type `Price`
- Create a new data type like `VolatilityBar`, which probably can't subclass `Bar` because its using the `Price` type
- Generalize `Bar` so that the `open`, `high`, `low`, `close` fields are any type of Python object, and/or create `PriceBar`

I think right now options 1 and 2 are the least invasive and don't involve breaking changes to the API. So we could experiment with those. I'm open to reviewing any PR along those lines.

**Comment by rsmb7z** [comment]
> For 1, we need to keep the parsed bar specification to three hyphen separated tokens:

For this I have just added the `HistoricalVolatility` and `ImpliedVolatility` in the rust enum. Surprisingly it took care of underscore as in python and shows like `HISTORICAL_VOLATILITY` and `IMPLIED_VOLATILITY`. Although its weird to be in PriceType but this will keep the usage simpler and without created another BarSpec and BarType classes.

> For 2, we have three options:

For this I have inhered the original Bar and changed and inputs to accept `Decimal` and `double` whereas returns `Decimal` for OHLC. I have attempted to do as seperate class but in Rust hash didn't worked for float, hence required another data type class similar to Price/Quantity.

**Comment by cjdsellers** [comment]
Commented on #988

**Comment by cjdsellers** [comment]
Hi @rsmb7z

Following on from the conversation in the PR.

To move forward on this, all things considered I don't think a volatility is a price type, but can be based on a price type (so should be separate).

How many different time frames for volatility would be appropriate? we could just make them different bar aggregations, e.g.

    MINUTE_HISTORICAL_VOLATILITY
    HOUR_IMPLIED_VOLATILITY

Having said that, the combination of the step and the BarAggregation becomes the rule for bar formation. So in the case of the current time based bars, the bar is closed at the end of the time interval and represents a data event at ts_event.

In this way, aren't implied volatility bars also an aggregation sampled across time? This leads me back to a previous suggestionABC-IMPLIED-VOLATILITY.NYSE-1-MINUTE-LAST-EXTERNAL

So a bar type is {INPUT}-{STEP}-{AGGREGATION/RULE}-{EXTERNAL/INTERNAL}. The input in the above cases is the bid, ask, mid, last implied volatility across step * time intervals?

**Comment by rsmb7z** [comment]
> How many different time frames for volatility would be appropriate? we could just make them different bar aggregations, e.g.

Same `BarAggregation` as of current `Bar`. Step could be any, IB supports as follows:
![image](https://user-images.githubusercontent.com/105105941/218337297-22614957-d69e-4a19-aacf-ebdc288b4509.png)



> In this way, aren't implied volatility bars also an aggregation sampled across time? This leads me back to a previous suggestion, we could use something like `ABC-IMPLIED-VOLATILITY.NYSE-1-MINUTE-LAST-EXTERNAL`?

`IMPLIED_VOLATILITY` or `HISTORICAL_VOLATILITY` doesn't have any Bid/Ask/Last etc except single type values for OHLC so above naming convension wouldn't be valid.

```
{InstrumentId}-{step}-{aggregation}-{HISTORICAL_VOLATILITY}-{aggregation_source}
{InstrumentId}-{step}-{aggregation}-{IMPLIED_VOLATILITY}-{aggregation_source}
{InstrumentId}-{step}-{aggregation}-{YIELD_BID}-{aggregation_source}
{InstrumentId}-{step}-{aggregation}-{YIELD_ASK}-{aggregation_source}
{InstrumentId}-{step}-{aggregation}-{YIELD_LAST}-{aggregation_source}
```

On the chart below you can see closing value of IV/HV. So you can see the chart can be any timeframe, so does these values.
![image](https://user-images.githubusercontent.com/105105941/218339730-320942ba-2d5e-406d-9bf8-4760b1a4c00f.png)



> So a bar type is `{INPUT}-{STEP}-{AGGREGATION/RULE}-{EXTERNAL/INTERNAL}`. The input in the above cases is the bid, ask, mid, last implied volatility across `step * time` intervals?

_Actually let me try to explain in a different way to make clear understanding of the use case and how HV/IV is supposed to work._
Assume I have to use Nautilus as-is, without this PR gone through, I will simply do this and boom. I get all the functional requirements.
![image](https://user-images.githubusercontent.com/105105941/218337727-1f5cda12-c380-403b-a4bd-697117ce7f13.png)

Only annoying part here is
- I have to call and refer these both types as `PriceType` [this is not that much annoying though]
- I have to call OHLC values as `Price` [functionally okay as at the it its number just annoying, hence the concept of `GenericBar`]

_Being a layman user how I would prefer to make a Bar?_ [On this project my actual role is `User` as not working for any third-party]

**Of course if it doesn't impact the existing performance, simply same class accepts two data types and/or the same case can apply with the BarSpecification.**
```
    price_bar = Bar(
        open=Price(1,2),
        high=Price(1,2),
        low=Price(1,2),
        close=Price(1,2),
        volume=Quantity(0,0),
        ts_event=0,
        ts_init=0,
    )
    iv_bar = Bar(
        open=Decimal(1,8),
        high=Decimal(1,8),
        low=Decimal(1,8),
        close=Decimal(1,8),
        volume=Quantity(0,0),
        ts_event=0,
        ts_init=0,
    )
```

**Comment by limx0** [comment]
Just jumping in here, I've read most of the conversation above (albeit quite quickly). 

The main issue I see here is including these volatility measures into the core of nautilus, giving the impression to users that they may be implemented for any Adapter. I think the types we include in nautilus itself should only be things we reasonable expect to be implemented in _almost_ all Adapters. I can't say this is the case for IV/HV.

My thoughts here are creating an `IBBar` and `IBPrice` subclass would be a better route (at least in the meantime, until we find more use cases). Being a subclass should mean they operate within the system as essentially a `Bar`, could likely even be passed through the data engine and arrive at the strategy in the same way, but without causing confusion for other users.

@rsmb7z how does that sound?

**Comment by rsmb7z** [comment]
Sounds great. Thanks for clicking the idea, yes lets move this to adapter itself. Let me test the scenario and get back to you.
