### ISSUE TITLE
Refactor IB adapter

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#987]
# Feature Request

I think it would be good to refactor IB adapter based on `ibapi` directly. While `ib_insync` is handy when working seperately but within this system many things become redundant and when done directly will be more clean. This will improve the performance, and will make it easier to approach what is compatibility between NT and IB.

Let me know if this is something of interest and fits into system. I would be happy to contribute and share the initial plan/PR.

**Comment by limx0** [comment]
Hey @rsmb7z - this was certainly always the plan; with ib_insync offering a quicker path to getting a working adapter, the long term plan was to move pieces over to ibapi as we had capacity / necessity. 

We would very happy accept any contributions for the above, and will do our best to facilitate and contribute to the direction. 

Feel free to jump into the discord (there's an interactive-brokers channel) if you'd like to discuss things more in depth.

**Comment by cjdsellers** [comment]
Seconded what @limx0 is saying, the `ib_insync` approach was something to help get the adapter going quickly. I think integrating directly without going via the `ib_insync` will be a much better outcome in the end.

This is definitely something we'll support.

**Comment by cjdsellers** [comment]
Now landed from #1036 many thanks again @rsmb7z :pray:
